### ISSUE TITLE
How to install h264 for media playback on the web

### ISSUE THREAD

**Issue by fwilhe** [fedora-silverblue/issue-tracker#1]
Hi,

I'm using silverblue for a few days now, and I love it so far. Great work, thanks.

What I could not figure out yet is how to enable media playback on youtube, spotify etc. Youtube works for some videos, but for others it throws an error, both in Firefox and Chromium.

![screenshot from 2018-12-30 16-25-06](https://user-images.githubusercontent.com/2292245/50548565-897b0000-0c4f-11e9-86fb-39e3215f2b55.png)

Also, I'm not sure how I can install Google Chrome, if I need to. I could not find a flatpak for it, and, and I'm not sure if `rpm-ostree` can be used for third part rpms such as the one provided by google. Also, I tried to setup rpm fusion as described [here](https://medium.com/@alex285/how-to-enable-h-264-on-chromium-on-silverblue-6ca8058a6a27), but no luck. I don't recall the exact error message, but it was something along the lines that gpg could not verify.

Any pointers are appreciated,
thanks a lot for your work

Florian

**Comment by fwilhe** [comment]
What I found so far

* Youtube seems to work sometimes, I'm not sure what it depends on
* Browsers installed via flatpak (found only [Eolie](https://flathub.org/apps/details/org.gnome.Eolie) so far) seems to work for most things, except for netflix and spotify

**Comment by biswasab** [comment]
https://rpmfusion.org/Configuration

**Comment by ferrettim** [comment]
The instructions you want are [in the forums](https://discussion.fedoraproject.org/t/adding-h-264-support-to-firefox/1005). Works fine here.

**Comment by fwilhe** [comment]
Thanks
