### ISSUE TITLE
Missing icons when installing from fedora flatpak repository

### ISSUE THREAD

**Issue by mykytosyk** [fedora-silverblue/issue-tracker#10]
I installed flatpak File Roller and Evince from registry.fedoraproject.org repository using GNOME Software and have 2 icons missing. One is the icon of File Roller and another is in upper-left corner of Evince. 
![image](https://user-images.githubusercontent.com/54434175/63577237-a5446500-c596-11e9-975e-bbd9f38836bd.png)
![image](https://user-images.githubusercontent.com/54434175/63577275-ba20f880-c596-11e9-96f9-02969fb4bf48.png)
![image](https://user-images.githubusercontent.com/54434175/63577319-cad16e80-c596-11e9-81c2-1c7c4160e9cc.png)

Temporary fix working **for me**: I installed Evince from flathub.org and there is no this bug. And there is no real need to install File Roller because Nautilus can extract different types of archives.

**Comment by tpopela** [comment]
> Fix: I installed Evince from flathub.org and there is no this bug.
 
That's not a solution. The Fedora Flatpaks needs to be fixes as well.

> And there is no real need to install File Roller because Nautilus can extract different types of archives.

That's not entirely true as some people could not use file manager at all and they want to extract the archives as well.

**Comment by mykytosyk** [comment]
> That's not a solution. The Fedora Flatpaks needs to be fixes as well.
Right. That's why I reported the issue.
> That's not entirely true as some people could not use file manager at all and they want to extract the archives as well.
Right. That's a fix working for me, but the developers should improve Fedora Flatpaks as well.

**Comment by Honza0297** [comment]
As for File Roller, icons were not exported properly, I'll look at it and fix it in next few days. 
Thanks for bug report! :)

**Comment by Honza0297** [comment]
It took a little bit longer than I wanted, but bugfix is in testing and should be in stable version within a week.

**Comment by tpopela** [comment]
This was fixed by the update that @Honza0297 mentioned.

**Comment by akarshanbiswas** [comment]
Facing the exact same problem, this time with only flathub apps on a friend's freshly installed silverblue.

Booted image version is : 35.20220105.0 (2022-01-05T01:31:51Z)

![Screenshot from 2022-01-05 15-48-48](https://user-images.githubusercontent.com/17230826/148202025-d31aee8c-d181-4dd3-bded-f6d32fc63793.png)

**Comment by peacememories** [comment]
Got the same problems. As far as I can tell flatpak correctly installs the icons in `/var/lib/flatpak/exports/share`, although the icons from fedoras own repository don't seem to be there. The aforementioned folder is also correctly added to `XDG_DATA_DIRS` so I have no idea why Gnome won't source them

**Comment by jelwid** [comment]
Today I had the same problem after fresh install. 
I did:
- Installed Silverblue;
- Set 125% scalling in system and gdm, installed some drivers.
- Installed apps from flathub using the terminal.
-
Nothing worked until I read the last post and tried to set scaling to 100%. Icons appeared immediately, after that icons work as expected even with scaling 125%.

**Comment by 22p** [comment]
icon-theme.cache was created in the future.
Just delete it

rm -rf /var/lib/flatpak/exports/share/icons/hicolor/icon-theme.cache
