### ISSUE TITLE
Enterprise login during install not possible

### ISSUE THREAD

**Issue by dschier-wtd** [fedora-silverblue/issue-tracker#100]
Hi,
during the installation, it is not possible to join an Active Directory domain, since some packages are missing in the base image. I dont know how the Fedora Workstation installer handles this, but maybe the silverblue base image needs the oddjob/sssd/realm packages for a proper AD join/Enterprise Login.

**Comment by tpopela** [comment]
Did it worked for you on Workstation? According to https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/issues/80 (linked from https://pagure.io/fedora-workstation/issue/200 and from https://github.com/fedora-silverblue/issue-tracker/issues/93) it doesn't work for quite some time..

**Comment by daniel-wtd** [comment]
We have tested it just some minutes ago with the following images:

- everything ISO -> anaconda -> new user (Enterprise Login) -> not tested
- everything ISO -> anaconda -> new user (local) -> gnome-settings -> user -> new user (enterprise login) -> works

for silverblue, bot are not working without overlaying new packages.

**Comment by tpopela** [comment]
Thank you @daniel-wtd ! Can you share the exact names and version of packages that you override to get this working?

**Comment by daniel-wtd** [comment]
Status Update for today:

The following packages were needed to make at least the join work, these packages were needed:

```
oddjob
oddjob-mkhomedir
samba-common-tools
```

After a reboot, I was able to join. Now another issue occured after a reboot. The below services either crashed or were not startable:

```
avahi-daemon.service
rtkit-daemon.service
polkit.service
cups.service
```
There were som other (network?) Services, but I am not able to read them properly :p

Afterwards the system is stale with "Failed to start CUPS scheduler. :/

**Comment by tpopela** [comment]
Looking at Fedora 33 Workstation in a VM, I see oddjob* packages installed, but not a samba-common-tools (but samba-common and samba-common-libs). Looking in the fedora-comps, I don't have an idea why are oddjob* packages pulled it. And using 

```
[liveuser@localhost-live ~]$ dnf repoquery --recursive --whatrequires oddjob-mkhomedir
Last metadata expiration check: 0:02:20 ago on Thu 12 Nov 2020 08:22:04 AM EST.
freeipa-client-0:4.8.10-6.fc33.x86_64
freeipa-client-epn-0:4.8.10-6.fc33.x86_64
freeipa-client-samba-0:4.8.10-6.fc33.x86_64
freeipa-fas-0:0.0.4-1.fc33.noarch
freeipa-healthcheck-0:0.6-4.fc33.noarch
freeipa-healthcheck-0:0.7-1.fc33.noarch
freeipa-server-0:4.8.10-6.fc33.x86_64
freeipa-server-dns-0:4.8.10-6.fc33.noarch
freeipa-server-trust-ad-0:4.8.10-6.fc33.x86_64
ipsilon-tools-ipa-0:2.1.0-15.git20200618.c90a76b.fc33.noarch
python3-nest-0:2.20.0-5.fc33.x86_64
```
nothing from these are installed on Workstation. Why this has to be that hard :/

**Comment by tpopela** [comment]
I see oddjob-mkhomedir in system-tools group and that one is included in the base-system group.. Looking at the base-system group I can't say whether it's included in Workstation by default (probably it is).

**Comment by daniel-wtd** [comment]
Let me check the behaviors a little bit more detailed on Monday/Tuesday. I will spin up some stuff and see where I can help to identify the situation. Since realmd pulls additional packages during domain join, there may be some situation here.

**Comment by daniel-wtd** [comment]
unfortunately no real progress. I think realmd is used to join the domain and therefore in WS it will just install some dependencies. Since doing these steps manual at least leads to the situation that I can join a domain, but a reboot is not possible, I assume it may not be really package related.

Are there some "twists" when coming to config file manipulation in /etc/ in silverblue, maybe some immutable paths which are required for samba/polkit, etc?

**Comment by travier** [comment]
This is still an issue but we'll keep https://github.com/fedora-silverblue/issue-tracker/issues/320 to track it.
