### ISSUE TITLE
[Little issue]: Evince icon inside thumbnails view is not visible

### ISSUE THREAD

**Issue by lalincedeldeserto** [fedora-silverblue/issue-tracker#103]
Related to this version:
Evince	org.gnome.Evince	3.38.0	stable	fedora	system
I noticed that the same version on flathub doesn't have this issue.

On the upper left corner, the icon to show thumbnails of the pages isn't visible. 
![thumbnail-pages](https://user-images.githubusercontent.com/33136381/99367077-c723b900-28b9-11eb-92ba-0e64a56c76f2.png)

**Comment by tpopela** [comment]
@kalev any idea? Could we miss some icons package in Evince Flatpak or Fedora runtime?

**Comment by kalev** [comment]
Hm, I think we are missing gdk pixbuf cache regeneration for icons that evince installs. Investigating.

**Comment by kalev** [comment]
This should be now fixed in https://src.fedoraproject.org/flatpaks/evince/c/3ce4e5ad231ddd6dce08bde0ec08eab71a1d2bdf?branch=master . Still waiting on the build to finish.

**Comment by kalev** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2020-ffc9849ee2

**Comment by lalincedeldeserto** [comment]
I've just received your update. Thanks!! :heart: 
Good job!!  :+1:
