### ISSUE TITLE
Roadmap for graphical applications not packaged as flatpaks

### ISSUE THREAD

**Issue by cjao** [fedora-silverblue/issue-tracker#107]
Silverblue is intended to run most user-facing graphical applications as flatpaks. Yet, many applications for Linux have not yet been packaged as flatpaks. There are several reasons for this:

* Some simply have not yet been converted to flatpak. This includes many packages in the Fedora repositories. There was a "Fedora Flatpaks" program from a few years ago which seems to have stalled, leaving the Fedora [Container Registry](https://registry.fedoraproject.org/) with a very small fraction of the desktop applications in the RPM repositories. Some third party graphical software, such as [Anaconda](https://www.anaconda.com/), continue to be distributed using custom install scripts.

* Others are technically incompatible with flatpak. For instance, they may implement their own sandbox (Google Chrome), require extra privileges be fully functional (Wireshark), or install system services, such as a license manager for professional software.

Where on Silverblue systems do such applications belong?

* Are they to be layered on the base system using `rpm-ostree`? Gnome-software on Silverblue supported layering RPMs at one point, but that feature seems to have been reverted. Since rpm-ostree requires special handling of postinstall scripts and certain file paths, this solution would not be robust when applied to general third-party RPMs. 

* Do they belong in a Toolbox container? Such containers aren't currently designed to keep too much valuable state or run complex, multi-process applications. Also, by design they cannot grant programs privileges beyond what the user has.

**Comment by tpopela** [comment]
Hi @cjao !

> * Some simply have not yet been converted to flatpak. This includes many packages in the Fedora repositories. There was a "Fedora Flatpaks" program from a few years ago which seems to have stalled, leaving the Fedora [Container Registry](https://registry.fedoraproject.org/) with a very small fraction of the desktop applications in the RPM repositories.

This is not true. The Fedora Flatpaks are definitely not stalled and definitely it didn't started few years ago. We converted the most favorite applications and those that are preinstalled in Fedora Workstation. We are adding new Flatpaks from time to time, but it waits on community involvement as well. Also @kalev is doing a great job by keeping the Flatpaks up to date and constantly improving them.

> Some third party graphical software, such as [Anaconda](https://www.anaconda.com/), continue to be distributed using custom install scripts.

Is it packaged in Fedora? If so, then please contribute by creating a Fedora Flatpak for it. Or create a Flathub Flatpak for it.

> * Others are technically incompatible with flatpak. For instance, they may implement their own sandbox (Google Chrome),

That's not entirely true - please see https://github.com/flathub/com.google.Chrome (it's in Flathub Beta channel).

> require extra privileges be fully functional (Wireshark), or install system services, such as a license manager for professional software.

Are there upstream issues (on Flatpak or on portals side) opened for these problems? 

> 
> Where on Silverblue systems do such applications belong?
> 
> * Are they to be layered on the base system using `rpm-ostree`? Gnome-software on Silverblue supported layering RPMs at one point, but that feature seems to have been reverted. Since rpm-ostree requires special handling of postinstall scripts and certain file paths, this solution would not be robust when applied to general third-party RPMs.
> * Do they belong in a Toolbox container? Such containers aren't currently designed to keep too much valuable state or run complex, multi-process applications. Also, by design they cannot grant programs privileges beyond what the user has.

I don't have a strong opinion there as I see both solutions used by the users. I would say (from my POV) that it depends on the origin of these applications. If they're coming from Fedora repositories I wouldn't mind overlaying them and if they're some 3rd party ones I would rather use Toolbox.

**Comment by travier** [comment]
A lot of applications are now available as Flatpak on Flathub and we're tracking the default applications installed in https://github.com/fedora-silverblue/issue-tracker/issues/289 so I'm going to close this one.
