### ISSUE TITLE
[Issue]: Evince doesn't save the page to continue reading where you left off

### ISSUE THREAD

**Issue by lalincedeldeserto** [fedora-silverblue/issue-tracker#108]
Evince from the fedora repository doesn't save the page to continue reading where you left off. This doesn't happen in the flathub version.

The right behavior of the program should be:

1) open a document
2) go to page number n
3) close the document
4) reopen the document from page n

**Comment by tpopela** [comment]
@felipeborges @kalev any idea what might be wrong?

**Comment by felipeborges** [comment]
Evince stores this information as GVFS metadata.

In Evince from Flathub I can see the "metadata::evince::*" entries with `gio info <some-pdf>`, but the same doesn't get stored for the Fedora Flatpak.

Both containers have the same permissions, so I wonder if this is an issue with some gvfs bit missing in the Fedora runtime.

**Comment by kalev** [comment]
What's going on here is that we are installing the gvfs-client bits into /app as part of the evince flatpak, but there is nothing to tell gio to find its loadable gvfs modules under /app/lib64/gio/modules.

I think the solution here is to just install gvfs-client in the flatpak runtime instead, similar to what's done in the GNOME flatpak runtime.

**Comment by kalev** [comment]
https://src.fedoraproject.org/modules/flatpak-runtime/c/eeb319b3bb9e477f39a8cf81848cf671e0302369?branch=f34 adds gvfs-client to the runtime. I've tested that it fixes the evince issue and also makes 'flatpak run org.gnome.gedit http://google.com' work that oholy mentioned on IRC.

**Comment by kalev** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2021-07aed72837 is the runtime update that adds gvfs-client and should fix this.
