### ISSUE TITLE
Cannot use hunspell-el

### ISSUE THREAD

**Issue by alex-theoto** [fedora-silverblue/issue-tracker#109]
Hello,
I use Fedora Silverblue 33 and I installed the package hunspell-el for dictation on Greek language but I cannot use it. I checked it on gedit and libreoffice and the only available dictation is the English one.
Both English and Greek dictations are on folder /usr/share/myspell/ .

Any idea how to enable this dictation?

**Comment by tpopela** [comment]
Hi @alex-theoto,

Are you using the gedit and libreoffice from RPM (you've overlayed it) or as flatpak from Fedora or from Flathub ?

**Comment by alex-theoto** [comment]
The gedit from rpm-ostree works fine, but both flatpak versions doesn't work.
I installed the package glibc-langpack-el form rpm with no success on the problem.

**Comment by tpopela** [comment]
Yeah, the problem will be that we don't include the dictionaries in Fedora Flatpak apps or runtimes. We recently added the localization packages there and maybe we should do the same for hunspell packages? @kalev any idea? I will also ping Owen.

**Comment by owtaylor** [comment]
Mostly defer to @kalev on this one - will note that we have 82 hunspell-* packages in the libreoffice container, so we could just move those to the runtime without impacting the installed size of anybody who has libreoffice installed.

Obviously language extensions would be nice, but it's hard in the OSBS framework to figure out how to make one build spit out multiple artifacts.

**Comment by kalev** [comment]
> Mostly defer to @kalev on this one - will note that we have 82 hunspell-* packages in the libreoffice container, so we could just move those to the runtime without impacting the installed size of anybody who has libreoffice installed.

Let me try a local build and see how much it affects the size.

> Obviously language extensions would be nice, but it's hard in the OSBS framework to figure out how to make one build spit out multiple artifacts.

Oh, but I don't think it has to necessarily spit out multiple artifacts: We could just do multiple builds/containers, similar to how we do separate builds for the runtime and SDK right now. Not 82 builds, but if it's 6 builds to do instead of 2, that should still be fine:

runtime, runtime langpacks, runtime debuginfo
SDK, SDK langpacks, SDK debuginfo

**Comment by kalev** [comment]
> > Mostly defer to @kalev on this one - will note that we have 82 hunspell-* packages in the libreoffice container, so we could just move those to the runtime without impacting the installed size of anybody who has libreoffice installed.
> 
> Let me try a local build and see how much it affects the size.

OK, I tried this now and all 148 hunspell-* packages that we have available in koji would add 72 MB to the runtime (so it goes from 585 MB to 657 MB).

**Comment by tpopela** [comment]
As we do have the support for the delta updates, then I would say that it's fine.

**Comment by tpopela** [comment]
@kalev we've talked about this on yesterday's meeting and we agreed that the bump is worth it. Can you please proceed with the changes (feel free to decide whether you will target the next major version i.e. runtime based on F35 or do the changes in the current one - F34)? Will you sync with Stephan or will you adapt the LibreOffice later on?

**Comment by kalev** [comment]
OK, great! Thanks. I'll be gone for two weeks but I'll get this merged when I get back.

**Comment by fabriciojardim** [comment]
I'm on Silverblue 36 and Text Editor spell check only have access to English dictionary despite my system language (Portuguese from Brazil).

Is this the same issue?

**Comment by hellpe** [comment]
Same question as above, using Silverblue 37 in French and gnome-text-editor only allows "English (United States)" for spell checking.

**Comment by tpopela** [comment]
It should be fixed once you get the https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2023-e69c75a57e
