### ISSUE TITLE
Caldav in Gnome

### ISSUE THREAD

**Issue by ams-123** [fedora-silverblue/issue-tracker#11]
Gnome calendar does not authenticate Caldav correctly. When adding Caldav calendars in Gnome Calendar, it prompts for an account password, lists the calendars, and they can be added. yes when trying to sync:

source_credentials_required_cb: Failed to authenticate 'Calendar': Bad Request

Deleting the Caldav calendars then recreating in Evolution allows Evolution to show the calendar content, but Gnome Calendar, which can reference the calendars in Evolution still gives the same authentication error.

**Comment by tpopela** [comment]
Hi @ams-123 what Evolution are you using? Evolution from Flathub's Flatpak or Evolution from Fedora Flatpak or overlayed Evolution?

**Comment by ams-123** [comment]
Hi @tpopela 

I installed through Gnome software center - the source is Flathub.

**Comment by tpopela** [comment]
Thank you @ams-123, can you please open the issue on https://github.com/flathub/org.gnome.Evolution/issues so the Flathub maintainers are aware of it (and close this issue?).

**Comment by ams-123** [comment]
@tpopela Thanks. Will do.
