### ISSUE TITLE
Could `totem-thumbnailer` and `evince-thumbnailer` be integrated as flatpaks?

### ISSUE THREAD

**Issue by nickavem** [fedora-silverblue/issue-tracker#110]
Working with a lot of files can get kind of overwhelming without thumbnails, especially if their names are pretty ambiguous. I know a temporary fix is `rpm-ostree install totem evince-thumbnailer` but that pulls in quite a few dependencies that I'd rather not have overlaid. Could something similar be done, as was done with the `sushi` flatpak (#56 )?

**Comment by tpopela** [comment]
Hi @nickavem, for evince-thumbnailer see https://github.com/fedora-silverblue/issue-tracker/issues/98 (it's fixed in F33+). For totem I don't know how to proceed there. I will ask the Totem maintainer on his opinion.

**Comment by hadess** [comment]
I don't think that it's useful to split off totem's thumbnailer from the package, when we don't have a good way to install codec packages. In fact, we don't have a working way to install codec packages in the traditional Fedora distribution either, as that workflow has been broken for years.

**Comment by nickavem** [comment]
> I don't think that it's useful to split off totem's thumbnailer from the package, when we don't have a good way to install codec packages. In fact, we don't have a working way to install codec packages in the traditional Fedora distribution either, as that workflow has been broken for years.

totem-thumbnailer works pretty dang well without encumbered codecs. Matroska should be fine, MPEG-4 seems to work well enough, and QuickTime seems to work pretty well as well. (All tested with totem and nautilus in a vanilla toolbox). You would need some pretty nasty files to break it, at least in my experience.

**Comment by hadess** [comment]
If you have MPEG-4 support, then you don't have a "stock" image. AFAIK, there's no support for the Cisco OpenH264 codec in stock Silverblue without using an RPM overlay. This discussion seems relevant:
https://discussion.fedoraproject.org/t/codecs-and-other-functional-overlays/22738

Also, Matroska and QuickTime are "container" types, not codecs. Those are usually supported in GStreamer plugins that aren't patent encumbered, and shipped by default in Fedora. What's important is the codecs used. You can use `gst-discoverer-1.0` to check the contents of the file (or totem or vlc's properties pages).

**Comment by nickavem** [comment]
I do have H.264 in the container, whoops. That could be funky... Thanks for pointing that out!

**Comment by nickavem** [comment]
I see `totem-thumbnailer` has been implemented in 34, but still no support for H.264. Is there no way around this? What would be the cleanest way to get H.264 support on Silverblue using the Cisco repo?

**Comment by nickavem** [comment]
`gstreamer1-plugin-openh264` is the package required. Could a note about this be written in the docs somewhere? I would be wiling to PR it at some point today.

**Comment by patriziobruno** [comment]
This issue has been closed, but I still see the problem in Fedora Silverblue 34. Has anyone made any progress? Is there any plan to fix it? Thanks
