### ISSUE TITLE
Consider shortening timeout for ostree-finalized-staged.service

### ISSUE THREAD

**Issue by cjao** [fedora-silverblue/issue-tracker#111]
As of Silverblue 33, this service is currently allotted up to 5 minutes to complete. That seems far too long. Users shouldn't have to unexpectedly wait 5 extra minutes when they are packing up for the day and decide to shut down their computer. That experience would be no less aggravating than Windows deciding "Aha! Now is the perfect time to apply a major update!" when you're rushing out the door.

If I understand correctly, the service simply merges the current /etc with the pending /etc and points the bootloader to the new system image. It should be a bug if this process takes longer than, say, 30 seconds.

**Comment by tpopela** [comment]
Hi @cjao . I never saw this on any of my machines (the power off is instant here). Maybe there's something weird going on on your machine? @cgwalters @dustymabe

**Comment by cjao** [comment]
Thanks for your response. Here is the result of `systemctl show ostree-finalize-staged` (truncated for brevity):

```Type=oneshot
Restart=no
NotifyAccess=none
RestartUSec=100ms
TimeoutStartUSec=infinity
TimeoutStopUSec=5min
TimeoutAbortUSec=5min
TimeoutStartFailureMode=terminate
TimeoutStopFailureMode=terminate
...
ExecStop={ path=/usr/bin/ostree ; argv[]=/usr/bin/ostree admin finalize-staged ; ignore_errors=no ; start_time=[n/>
ExecStopEx={ path=/usr/bin/ostree ; argv[]=/usr/bin/ostree admin finalize-staged ; flags= ; start_time=[n/a] ; sto>
```

**Comment by cjao** [comment]
I should add that while this service usually takes a few seconds, on a handful of occasions it has taken over a minute, in which case I just hard-shutdown my system as the service has clearly failed.

**Comment by cgwalters** [comment]
This is probably a dup of https://github.com/ostreedev/ostree/issues/1924
Do you have `os-prober` enabled?

**Comment by cjao** [comment]
`os-prober` has been disabled for a while. It's possible that I had not yet disabled it when I encountered the long delays.

**Comment by tpopela** [comment]
@cjao is this still a problem?

**Comment by cjao** [comment]
Thanks for following up. I have not experienced this issue in a while.
