### ISSUE TITLE
Rawhide ostree composes failing with "error: Packages not found: libproxy-mozjs"

### ISSUE THREAD

**Issue by AdamWill** [fedora-silverblue/issue-tracker#112]
Rawhide Silverblue ostree composes are failing with "error: Packages not found: libproxy-mozjs". E.g. [today's x86_64 attempt](https://koji.fedoraproject.org/koji/taskinfo?taskID=56573613). Looks like this has been broken since 2020-11-23 or so, since today's Rawhide Silverblue installer deploys an ostree versioned 20201123.n.0.

**Comment by AdamWill** [comment]
Hum, it seems libproxy-mozjs was removed in libproxy-0.4.15-27.fc34 , but that was tagged back on 2020-10-07, so not sure how this only showed up as an issue last month. Curious. Anyway, that seems to be the problem now.

**Comment by AdamWill** [comment]
https://pagure.io/fedora-comps/pull-request/557 should fix it.

**Comment by AdamWill** [comment]
Well, no, because we also need to [sync workstation-ostree-config](https://pagure.io/workstation-ostree-config/pull-request/186).

**Comment by travier** [comment]
Looks like this should be good now?

**Comment by tpopela** [comment]
True @travier ! Looking at https://openqa.fedoraproject.org/nightlies.html there's a compose from yesterday (it failed some tests, but these's a compose)

**Comment by AdamWill** [comment]
A Silverblue installer image existing in a Rawhide compose doesn't sufficiently indicate that an ostree compose issue is fixed. If the ostree compose fails for a given Rawhide compose, we still build a Silverblue installer image - it just contains/deploys an older ostree.

In the openQA results, you can check the [release identification test result](https://openqa.fedoraproject.org/tests/740178) for an indication of this; if it's complaining about `VERSION` and `PRETTY_NAME` being wrong, as it [is today](https://openqa.fedoraproject.org/tests/740178#step/os_release/310), that's an indication we've got an old ostree. Note how it's expecting 20201214.n.0 (same as the compose itself) but seeing 20201209.n.0 (indicating that was the last Rawhide compose in which we got a successful Silverblue ostree compose).

Another good place to check is [the releng failed-composes tracker](https://pagure.io/releng/failed-composes/issues). This gets a ticket for all composes (not just failed ones, actually) and lists all failed tasks within each compose. So you can see [in the ticket for 20201214.n.0](https://pagure.io/releng/failed-composes/issue/2126) some notes recording failed Silverblue ostree compose tasks. We can look at the logs from those tasks to see why the ostree compose is failing now, e.g. [the x86_64 task here](https://koji.fedoraproject.org/koji/taskinfo?taskID=57412984), where in [`root.log` we see](https://kojipkgs.fedoraproject.org//work/tasks/2984/57412984/root.log):

    DEBUG util.py:446:  COMMAND: rpm-ostree compose tree --repo=/mnt/koji/compose/ostree/repo/ --write-commitid-to=/mnt/koji/compose/rawhide/Fedora-Rawhide-20201214.n.0/logs/x86_64/Silverblue/ostree-1/commitid.log --touch-if-changed=/mnt/koji/compose/rawhide/Fedora-Rawhide-20201214.n.0/logs/x86_64/Silverblue/ostree-1/commitid.log.stamp --add-metadata-string=version=Rawhide.20201214.n.0 --force-nocache /mnt/koji/compose/rawhide/Fedora-Rawhide-20201214.n.0/work/ostree-1/config_repo/fedora-silverblue.json
    DEBUG util.py:446:  -------------------------------------------------------------------------------
    DEBUG util.py:446:  bwrap: Failed to make / slave: Invalid argument
    DEBUG util.py:446:  error: bwrap test failed, see <https://github.com/projectatomic/rpm-ostree/pull/429>: Executing bwrap(true): Child process killed by signal 1
    DEBUG util.py:446:  Traceback (most recent call last):
    DEBUG util.py:446:    File "/usr/bin/pungi-make-ostree", line 33, in <module>
    DEBUG util.py:446:      sys.exit(load_entry_point('pungi==4.2.7', 'console_scripts', 'pungi-make-ostree')())
    DEBUG util.py:446:    File "/usr/lib/python3.9/site-packages/pungi/ostree/__init__.py", line 159, in main
    DEBUG util.py:446:      func()
    DEBUG util.py:446:    File "/usr/lib/python3.9/site-packages/pungi/ostree/tree.py", line 151, in run
    DEBUG util.py:446:      self._make_tree()
    DEBUG util.py:446:    File "/usr/lib/python3.9/site-packages/pungi/ostree/tree.py", line 59, in _make_tree
    DEBUG util.py:446:      shortcuts.run(
    DEBUG util.py:446:    File "/usr/lib/python3.9/site-packages/kobo/shortcuts.py", line 409, in run
    DEBUG util.py:446:      raise exc
    DEBUG util.py:446:  RuntimeError: ERROR running command: rpm-ostree compose tree --repo=/mnt/koji/compose/ostree/repo/ --write-commitid-to=/mnt/koji/compose/rawhide/Fedora-Rawhide-20201214.n.0/logs/x86_64/Silverblue/ostree-1/commitid.log --touch-if-changed=/mnt/koji/compose/rawhide/Fedora-Rawhide-20201214.n.0/logs/x86_64/Silverblue/ostree-1/commitid.log.stamp --add-metadata-string=version=Rawhide.20201214.n.0 --force-nocache /mnt/koji/compose/rawhide/Fedora-Rawhide-20201214.n.0/work/ostree-1/config_repo/fedora-silverblue.json

so, I'll file a new bug for that.

**Comment by AdamWill** [comment]
Filed https://github.com/fedora-silverblue/issue-tracker/issues/116 .
