### ISSUE TITLE
[documentation] Installation -> partition customizations

### ISSUE THREAD

**Issue by daniel-wtd** [fedora-silverblue/issue-tracker#113]
According to the docs, customizations during the installation in /var should be possible. But this seems not well maintained since:

- /var/containers is nothing facilitated with a default Fedora/SB installation
- the screenshot description states the screenshot shows a customized /var/home, but it does not

I would appreciate to help with the documentation. 

- Is this the valid docs to contribute to SB docs? https://docs.fedoraproject.org/en-US/fedora-docs/contributing/contributing-to-existing-docs/

**Comment by tpopela** [comment]
Hi @daniel-wtd! The workflow is described in a readme on https://github.com/fedora-silverblue/silverblue-docs.

**Comment by daniel-wtd** [comment]
Thanks, I will have look :)
