### ISSUE TITLE
Silverblue ostree composes fail since Fedora-Rawhide-20201210.n.0 with `bwrap: Failed to make / slave: Invalid argument`

### ISSUE THREAD

**Issue by AdamWill** [fedora-silverblue/issue-tracker#116]
Since Fedora-Rawhide-20201210.n.0, all Silverblue ostree composes fail like this:

    DEBUG util.py:446:  COMMAND: rpm-ostree compose tree --repo=/mnt/koji/compose/ostree/repo/ --write-commitid-to=/mnt/koji/compose/rawhide/Fedora-Rawhide-20201210.n.0/logs/x86_64/Silverblue/ostree-1/commitid.log --touch-if-changed=/mnt/koji/compose/rawhide/Fedora-Rawhide-20201210.n.0/logs/x86_64/Silverblue/ostree-1/commitid.log.stamp --add-metadata-string=version=Rawhide.20201210.n.0 --force-nocache /mnt/koji/compose/rawhide/Fedora-Rawhide-20201210.n.0/work/ostree-1/config_repo/fedora-silverblue.json
    DEBUG util.py:446:  -------------------------------------------------------------------------------
    DEBUG util.py:446:  bwrap: Failed to make / slave: Invalid argument
    DEBUG util.py:446:  error: bwrap test failed, see <https://github.com/projectatomic/rpm-ostree/pull/429>: Executing bwrap(true): Child process killed by signal 1
    DEBUG util.py:446:  Traceback (most recent call last):
    DEBUG util.py:446:    File "/usr/bin/pungi-make-ostree", line 33, in <module>
    DEBUG util.py:446:      sys.exit(load_entry_point('pungi==4.2.7', 'console_scripts', 'pungi-make-ostree')())
    DEBUG util.py:446:    File "/usr/lib/python3.9/site-packages/pungi/ostree/__init__.py", line 159, in main
    DEBUG util.py:446:      func()
    DEBUG util.py:446:    File "/usr/lib/python3.9/site-packages/pungi/ostree/tree.py", line 151, in run
    DEBUG util.py:446:      self._make_tree()
    DEBUG util.py:446:    File "/usr/lib/python3.9/site-packages/pungi/ostree/tree.py", line 59, in _make_tree
    DEBUG util.py:446:      shortcuts.run(
    DEBUG util.py:446:    File "/usr/lib/python3.9/site-packages/kobo/shortcuts.py", line 409, in run
    DEBUG util.py:446:      raise exc
    DEBUG util.py:446:  RuntimeError: ERROR running command: rpm-ostree compose tree --repo=/mnt/koji/compose/ostree/repo/ --write-commitid-to=/mnt/koji/compose/rawhide/Fedora-Rawhide-20201210.n.0/logs/x86_64/Silverblue/ostree-1/commitid.log --touch-if-changed=/mnt/koji/compose/rawhide/Fedora-Rawhide-20201210.n.0/logs/x86_64/Silverblue/ostree-1/commitid.log.stamp --add-metadata-string=version=Rawhide.20201210.n.0 --force-nocache /mnt/koji/compose/rawhide/Fedora-Rawhide-20201210.n.0/work/ostree-1/config_repo/fedora-silverblue.json
    DEBUG util.py:446:  For more details see /mnt/koji/compose/rawhide/Fedora-Rawhide-20201210.n.0/logs/x86_64/Silverblue/ostree-1/create-ostree-repo.log

They seem to have been succeeding up to 20201209.n.1.

**Comment by AdamWill** [comment]
@cgwalters

**Comment by cgwalters** [comment]
Hmm I commented in https://pagure.io/releng/failed-composes/issue/2126#comment-706236 - feels like releng is a better place as this affects IoT too?

**Comment by AdamWill** [comment]
ah thanks, didn't see that. I thought it was silverblue-specific as we only had failures for silverblue, I thought we had some non-silverblue ostree composes in Rawhide still but do we not?
