### ISSUE TITLE
[RFE] Install `mozilla-openh264` on first boot

### ISSUE THREAD

**Issue by cjuniorfox** [fedora-silverblue/issue-tracker#119]
I was unable to decode h-264 videos from facebook with silverblue's firefox.
The message appears on Firefox's consol:
Unable to reproduce the media. There's no decoders: video/mp4; codecs="avc1.4D4028", audio/mp4; codecs="mp4a.40.5", video/mp4; codecs="avc1.42E01E mp4a.40.2", video/mp4; codecs="avc1.4D401E mp4a.40.2", video/mp4; codecs="avc1.4D401F mp4a.40.2", video/mp4; codecs="avc1.640032 mp4a.40.2", video/mp4; codecs="avc1.640033 mp4a.40.2"

**Comment by cjuniorfox** [comment]
Also Youtube for certain videos.

**Comment by tpopela** [comment]
What's your Firefox version? Is it the one from the base image or some that was additionally installed?

**Comment by cjuniorfox** [comment]
From base image.

Em qui, 7 de jan de 2021 10:04, Tomáš Popela <notifications@github.com>
escreveu:

**Comment by tpopela** [comment]
Can you please use rpm -q firefox and paste the exact version of the rpm?

Dne čt 7. 1. 2021 21:42 uživatel Carlos Junior <notifications@github.com>
napsal:

**Comment by cjuniorfox** [comment]
firefox-84.0.1-2.fc33.x86_64

**Comment by cjuniorfox** [comment]
I also having the same issues with some Youtube videos. An example follows: https://www.youtube.com/watch?v=GAbxBvi7ZUo

**Comment by tpopela** [comment]
> I also having the same issues with some Youtube videos. An example follows: https://www.youtube.com/watch?v=GAbxBvi7ZUo

I tested the link with the latest stable FIrefox package (firefox-84.0.2-1.fc33.x86_64) and it works here, can you please try it yourself and let me know?

**Comment by cjuniorfox** [comment]
I updated to the latest image and the same issue persists.

[junior@localhost ~]$ rpm -q firefox
aviso: Found bdb Packages database while attempting sqlite backend: using bdb backend.
firefox-84.0.2-1.fc33.x86_64

[junior@localhost ~]$ rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/33/x86_64/silverblue
                   Version: 33.20210111.0 (2021-01-11T00:51:49Z)
                BaseCommit: 280b5cf09ac43340eada28ff0be2d005b8abbde6540cafa04a80bb542ea21940
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31
           LayeredPackages: bcache-tools fedora-workstation-repositories
             LocalPackages: dcpt500wcupswrapper-3.0.2-0.i386 dcpt500wlpr-3.0.2-0.i386

  ostree://fedora:fedora/33/x86_64/silverblue
                   Version: 33.20210108.0 (2021-01-08T02:25:39Z)
                BaseCommit: 29c3ecc12e44a1da2348fea231987b3837c3f7c886e94e1867402b0f0ec8548a
              GPGSignature: Valid signature by 963A2BEB02009608FE67EA4249FD77499570FF31
           LayeredPackages: bcache-tools fedora-workstation-repositories
             LocalPackages: dcpt500wcupswrapper-3.0.2-0.i386 dcpt500wlpr-3.0.2-0.i386

Follows the Firefox error:

Media resource blob:https://www.youtube.com/a36ab463-8ab1-477d-83db-2941514126d7 could not be decoded. watch
This error message will be blank when privacy.resistFingerprinting = true.  If it is really necessary, please add it to the whitelist in MediaError::GetMessage: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)

I'll wipe my Firefox folder (~/.mozilla/firefox, ~/.cache/firefox) to check if the issue has something related with some installed extension, plugin or something like that.

**Comment by cjuniorfox** [comment]
I Wiped-out Firefox all local settings and no success. Issue still persists.

**Comment by cjuniorfox** [comment]
I managed to fix the issue installing mozilla-openh264 package (rpm-ostree install mozilla-openh264). So, to achieve this, I believe is just matter of add the mozilla-openh264 package to the base image.

**Comment by tpopela** [comment]
Good that you managed to figure it out @cjuniorfox ! But mozilla-openh264 can't be part of the base image (due to legal reasons) - please see https://pagure.io/fedora-workstation/issue/84 (warning - long read). Once this will be implemented for Workstation, we will do the Silverblue part.

**Comment by cjuniorfox** [comment]
Understanded @tpopela. Many thanks for your attention. So, until the Silverblue team figure some alternative to mozilla-openh264, the Fedora Silverblue will keep unable to decode, out of the box, online h264 content. My conclusion is correct?

**Comment by tpopela** [comment]
Hi @cjuniorfox sorry for getting back to you this late. I actually removed all my overlays and I can confirm that Firefox doesn't decode the content out of the box, unless you install the mozilla-openh264 package. To your question. This isn't entirely accurate as we (Silverblue team) won't be looking for the alternative for mozilla-openh264, but for a way how to install it after the user installs the Silverblue as due to licensing issues it can't be part of any installation media, but have to be installed afterwards. Once we have solution for regular Workstation, we will adapt the same solution for Silverblue as well. @kalev please take into account the Silverblue as well when working on something for Workstation.

**Comment by cjuniorfox** [comment]
@tpopela, I very appreciate your answer.

I followed as described and my browser is capable of correctly decode h-264 content. It's fully understandable the licencing issue about packaging mozilla-openh264 into Silverblue's base installation image.

**Comment by jkonecny12** [comment]
If SilverBlue has a knows issues somewhere it should be written there. If I understand it correctly the only thing is that you have to manually layer that package to avoid really annoying problems.

Probably add it here: https://fedoraproject.org/wiki/Common_F35_bugs -- with info that it's SilverBlue specific.

**Comment by juhp** [comment]
But this is not Silverblue specific.

The workaround is to install either the third party `mozilla-openh264` or `ffmpeg-libs` package.

**Comment by jkonecny12** [comment]
If it is not SB specific it really should be mentioned there or somewhere else visible.

**Comment by Kugelschieber** [comment]
Installing `mozilla-openh264` fixed this for me (Fedora 36, Firefox 100).

**Comment by travier** [comment]
This is also tracked in https://pagure.io/fedora-workstation/issue/84 as it also affects Workstation.
