### ISSUE TITLE
Gnome Contacts Cardav

### ISSUE THREAD

**Issue by ams-123** [fedora-silverblue/issue-tracker#12]
After adding Cardav contacts in Evolution, though they are displayed in Evolution, they are not shown in Gnome Contacts.

**Comment by tpopela** [comment]
Hi @ams-123 what Evolution are you using? Evolution from Flathub's Flatpak or Evolution from Fedora Flatpak or overlayed Evolution?

**Comment by ams-123** [comment]
Hi @tpopela 

I installed through Gnome software center - the source is Flathub.

**Comment by tpopela** [comment]
Thank you @ams-123, can you please open the issue on https://github.com/flathub/org.gnome.Evolution/issues so the Flathub maintainers are aware of it (and close this issue?).

**Comment by ams-123** [comment]
@tpopela Thanks. Will do.

**Comment by Sesivany** [comment]
Evolution in Flatpak is not using the host evolution-data-server, it has its own. The compability of Evo and host e-d-s can't be ensured.
I recommend you use some Cardav server for syncing the data between Flatpak and host (and any other client).
