### ISSUE TITLE
Print preview is broken out of the box

### ISSUE THREAD

**Issue by cjao** [fedora-silverblue/issue-tracker#122]
In the GTK printing dialog, the "Print Preview" button launches `evince-previewer`. This action doesn't work on a default install, however, since Evince is installed as a flatpak.

**Comment by felipeborges** [comment]
Thanks for the report!

I think `evince-previewer` won't be used in GTK4, so for now we could go with a similar solution to https://github.com/fedora-silverblue/issue-tracker/issues?q=evince-thumbnailer+is%3Aclosed and just ship `evince-preview` (as a separate package).

Thoughts?

**Comment by cjao** [comment]
My workaround is to drop a wrapper script called `evince-previewer` in `/usr/local/bin` that calls `flatpak run --command=evince-previewer org.gnome.Evince $@`.  Perhaps flatpak could automatically export similar wrappers to commands that each application wants to expose, similar to [what snap does](https://snapcraft.io/docs/defining-a-command)

**Comment by felipeborges** [comment]
I posted https://src.fedoraproject.org/rpms/evince/pull-request/10

**Comment by kalev** [comment]
Thanks Felipe -- I went ahead and merged it and submitted to Bodhi as https://bodhi.fedoraproject.org/updates/FEDORA-2021-c671eb23a0

**Comment by tpopela** [comment]
And I added it to the Silverblue config - it should get to users tomorrow - https://pagure.io/workstation-ostree-config/c/4a00bfa3f29e91a6c6e62ff21f902acf2ef33761?branch=f34

**Comment by cjao** [comment]
Thanks. Is it possible to backport the fix to F33?

**Comment by travier** [comment]
This is now likely fixed.
