### ISSUE TITLE
Sanity-checking final rpmdb: Didn't find package 'annobin-9.49-1.fc33.x86_64'

### ISSUE THREAD

**Issue by monterrr** [fedora-silverblue/issue-tracker#124]
Doing a rpm-ostree upgrade on fedora silverblue 33 gives me an error today after yesterday updates:

2 metadata, 0 content objects fetched; 788 B transferred in 5 seconds; 0 bytes content written
Inactive base removals:
  firefox
Checking out tree 635d8c6... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora rpmfusion-nonfree-nvidia-driver updates-archive
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-08-25T19:10:34Z
rpm-md repo 'updates' (cached); generated: 2021-02-04T02:07:54Z
rpm-md repo 'fedora' (cached); generated: 2020-10-19T23:27:19Z
rpm-md repo 'rpmfusion-nonfree-nvidia-driver' (cached); generated: 2021-02-01T09:48:31Z
rpm-md repo 'updates-archive' (cached); generated: 2021-02-05T06:27:48Z
Importing rpm-md... done
Resolving dependencies... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
error: Sanity-checking final rpmdb: Didn't find package 'annobin-9.49-1.fc33.x86_64'

**Comment by tpopela** [comment]
That's https://github.com/coreos/fedora-coreos-tracker/issues/723, please install https://bodhi.fedoraproject.org/updates/FEDORA-2021-937b45bf55 manually to get it fixed.

**Comment by nickavem** [comment]
> That's [coreos/fedora-coreos-tracker#723](https://github.com/coreos/fedora-coreos-tracker/issues/723), please install https://bodhi.fedoraproject.org/updates/FEDORA-2021-937b45bf55 manually to get it fixed.

How would you recommend installing this build? Normally, I would just download the .rpms and `override replace`, however I am receiving the same error when trying to do that (even after running `rpm-ostree reset`:
```sh
[andythurman@rockhopper Downloads]$ rpm-ostree override replace rpm-ostree-2021.1-3.fc33.x86_64.rpm rpm-ostree-libs-2021.1-3.fc33.x86_64.rpm
Checking out tree 39ac11c... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora updates-archive
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-08-25T19:10:34Z
rpm-md repo 'updates' (cached); generated: 2021-02-05T01:01:46Z
rpm-md repo 'fedora' (cached); generated: 2020-10-19T23:27:19Z
rpm-md repo 'updates-archive' (cached); generated: 2021-02-05T06:27:48Z
Importing rpm-md... done
Resolving dependencies... done
Applying 2 overrides
Processing packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
error: Sanity-checking final rpmdb: Didn't find package 'rpm-ostree-2021.1-3.fc33.x86_64'
```

**Comment by jlebon** [comment]
See https://bodhi.fedoraproject.org/updates/FEDORA-2021-937b45bf55#comment-1873116.

**Comment by nickavem** [comment]
> See https://bodhi.fedoraproject.org/updates/FEDORA-2021-937b45bf55#comment-1873116.

Just got cc'd on that. Thanks!

**Comment by monterrr** [comment]
Now I have this problem when doing an upgrade:

error: Running %post for akmod-nvidia: Executing bwrap(/bin/sh): Child process killed by signal 1; run `journalctl -t 'rpm-ostree(akmod-nvidia.post)'` for more information
