### ISSUE TITLE
Systemd timer located in /usr/local fails to start on start-up

### ISSUE THREAD

**Issue by jackmonty** [fedora-silverblue/issue-tracker#125]
I use a systemd timer to start an associated service; simply a rsync backup of certain (e.g. `/home`) directories. A copy of the timer content is below, and the file is located in the `/usr/local/lib/systemd/system/` directory. FYI, the rsync systemd unit and script are both tested and work well.

```bash
# cat /usr/local/lib/systemd/system/rsync-backup.timer

[Unit]
Description=Run backup via rsync script each morning.

[Timer]
OnCalendar=*-*-* 3:00:00

[Install]
WantedBy=timers.target
```

My problem is that the above timer shows the following status after each boot, the key part being inactive (dead).

```bash
● rsync-backup.timer - Run backup via rsync script each morning.
     Loaded: loaded (/usr/local/lib/systemd/system/rsync-backup.timer; enabled; vendor preset: disabled)
     Active: inactive (dead)
    Trigger: n/a
   Triggers: ● rsync-backup.service
```

I can simply solve this by entering the following command and everything comes up as expected. So long as I do not restart before the next backup, the backup runs at the expected time and goes smoothly.

```bash
# systemctl enable --now rsync-backup.timer
# systemctl status rsync-backup.timer
● rsync-backup.timer - Run backup via rsync script each morning.
     Loaded: loaded (/usr/local/lib/systemd/system/rsync-backup.timer; enabled; vendor preset: disabled)
     Active: active (waiting) since Sat 2021-01-30 22:19:15 EST; 3s ago
    Trigger: Sun 2021-01-31 03:00:00 EST; 4h 40min left
   Triggers: ● rsync-backup.service
```

Not wanting to have to complete the above manual steps each boot, I have checked/tried the following:

- confirmed the SELinux contexts are correct.
- confirmed the permissions are correct.
- attempted adding a systemd.preset file (changes vendor preset: from disabled to enabled however, does not solve the original problem).
- confirmed that systemd checks the correct path via systemd-analyze unit-paths
- confirmed that btrfs subvolumes are mounted prior to timer.targets is run (by using systemd-analyze plot).

Some additional details that I think might have an affect:

- `/usr/local` (i.e. `/var/usrlocal`) is a separate subvolume (i.e. usrlocal) on a single btrfs volume (fedora).

I have moved both the service timer and unit files to `/etc/systemd/system` and both work flawlessly … but I am attempting to keep any local configurations to `/usr/local` so that I can back them up. This avoids having to back up the entire `/etc` directory. Plus, using those files within the `/usr/local/lib/systemd/system` is acceptable according to `man systemd.unit`.

To further my experimentation, I decided to try testing timer and service files in a Silverblue VM. The only difference is that I did not create a separate partition for `/usr/local` (i.e. `/var/usrlocal`). This resulted in the same end-result; the timer file was loaded but inactive on reboot. This presumably eliminates the possibility that using a brfs subvolume for `/var/usrlocal` creates an issue.

I took this one step further and did the same but on a Fedora 33 VM (i.e. not SIlverblue), with the same timer and service located in `/usr/local`. Success! The timer loaded and was active on boot and the service ran correctly. In other words, I did not need to take the manual step of using `systemctl start`.

Therefore my conclusion is that this is an issue specifically related to Silverblue that falls out of the expected behavior of a non ostree-based distribution. This is based on `man systemd.unit` documentation relating to local configuration and above experimentation. I also hazard a guess it is likely related to the use of `/var/usrlocal`, as the path falls outside of what is stated within systemd documentation.

**Comment by owtaylor** [comment]
Might suggest trying to reproduce this with a Fedora CoreOS VM ... it sounds like some rpm-ostree vs. systemd interaction where systemd doesn't correctly handle the mount changes that happen when moving from the initrd to the deployed system.

**Comment by jlebon** [comment]
Ahh yeah, this is probably due to `/var` getting mounted later in the boot and so the symlink is broken at the time systemd prepares the transaction. I suspect a traditional Fedora 33 with a separate `/usr/local` would exhibit the same issue.

Not sure if there's an easy way to fix this. We could ship a systemd unit that runs after `var.mount`, but I don't know if there's an elegant way to tell systemd "try to reload and activate those units which you couldn't find before, but don't change anything else". Probably easier to stick with `/etc` for now and just add `/etc/systemd` to your backed up paths.

I also have a similar backup timer+service unit setup, though they're user units (`$HOME/.config/systemd/...`) which works out fine because I really just back up `$HOME`.

**Comment by travier** [comment]
Is this still an issue or should we consider that using `/etc` is the recommended approach here.

**Comment by jackmonty** [comment]
Practically, `/etc` does work. I used the advice above to copy my `/usr/local/etc` scripts into `/etc` and they operate as expected.

Conceptually, my expectation is Silverblue mimics the behavior of Workstation where the unit files under `/usr/local/etc` work as expected, e.g.:

> I took this one step further and did the same but on a Fedora 33 VM (i.e. not SIlverblue), with the same timer and service located in /usr/local. Success! The timer loaded and was active on boot and the service ran correctly.

I might be the only one with this expectation. It would be a shame if Silverblue did not operate as per the Workstation variant, as it is cleaner and easier to back up.

**Comment by travier** [comment]
have you tested on classic Fedora with a separated partition?

**Comment by wolfgangrupprecht** [comment]
I'm seeing the same thing.   The issue is that the timers that don't start are located in /usr/local/lib/systemd/system and /usr/local/ is a separate filesystem that is mounted at boot time.   I suspect that the mount happens after systemd gathers info about all the *.timers files in its search path.   

I'm not using silverblue but a google search showed a bug for the problem I'm seeing so I figured I'd help out with this note.

**Comment by travier** [comment]
So then it's not a Silverblue specific issue and it should be reported upstream to systemd.

**Comment by wolfgangrupprecht** [comment]
Agree, not a Silverblue issue.   Sadly the systemd folks don't intend to fix the issue other than documenting that it doesn't work.
https://github.com/systemd/systemd/issues/33563

**Comment by travier** [comment]
According to https://github.com/systemd/systemd/pull/33233 & https://github.com/systemd/systemd/issues/33563, this is not supported.

Please write your units to `/etc` instead.
