### ISSUE TITLE
gnome-software does not show any flatpak updates.

### ISSUE THREAD

**Issue by box-dev** [fedora-silverblue/issue-tracker#129]
In vanilla installs of F33 Silverblue (then updated with rpm-ostree update), gnome-software fails to show any flatpak updates. So the Fedora flatpaks installed by default remain at their old versions despite **flatpak update** listing the upgrades.

Checking for updates in gnome-software makes no difference, and the only way I have found to update the flatpaks is in the terminal. I've tried deleting ~/.cache/gnome-software and that has no effect.

This is easily reproducible both on real hardware and in VMs. I've tried opening gnome-software immediately after install, and I've tried letting it start off rpm-ostree first before opening (and of course have tried after updating to the latest ostree deployment). Nothing works.

Note - in case it is related - in almost every instance of me doing a clean install of F33, gnome-software has frozen on the first run; either in the background (in which case trying to open it in GUI just does nothing), or while it says it is loading the package information. After killing it or restarting the machine, it works fine - but flatpak updates never show.

edit: Note the reason fedora runtime is not in need of an update in the screenshot below is that I installed something else from the repo which apparently triggered it to update - but none of the others updated.

![rpm-ostree_status](https://user-images.githubusercontent.com/54814323/108422358-6005ff80-722e-11eb-979f-cbb8d1cee0bf.png)
![flatpak_update](https://user-images.githubusercontent.com/54814323/108422367-61372c80-722e-11eb-8f80-91c1443450ce.png)
![gnome-software](https://user-images.githubusercontent.com/54814323/108422373-62685980-722e-11eb-90c9-9c94113d8a35.png)

**Comment by tpopela** [comment]
Hi @box-dev, can you please try to run the following and attach the output here?

`gnome-software --quit && gnome-software --verbose`

**Comment by tpopela** [comment]
I got in touch with Software developer and he managed to reproduce on opened https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1151 .

**Comment by box-dev** [comment]
Output attached. 

[output.txt](https://github.com/fedora-silverblue/issue-tracker/files/6013537/output.txt)
