### ISSUE TITLE
Silverblue fails on GDM in Fedora 31.

### ISSUE THREAD

**Issue by lruzicka** [fedora-silverblue/issue-tracker#13]
I have installed Silverblue using the 20190828 compose of Silverblue 31. The installation went normally. I rebooted the computer, it started the plymouth screen and it ended upon entering the GDM and only provided a white screen of death suggesting I would contact a system administrator.

I checked the messages emitted during system start up and I did not see any failure. Also, I switched to a different console trying ctrl-alt-f3 and I was able to see a login screen, but I was not able to log into the system, because no accounts were created at that time, not even the root account. I am unable to provide any logs because I do not have access to that installed system.

If you have suggestions, how I could collect some data for you, please tell me.

**Comment by tpopela** [comment]
I hit that too. adamw is tracking it in https://bugzilla.redhat.com/show_bug.cgi?id=1746563.

**Comment by tpopela** [comment]
As mentioned in the bug, it was already fixed with gnome-initial-setup-3.33.92-2.fc31.
