### ISSUE TITLE
F34 x86_64 silverblue fingerprint login issue

### ISSUE THREAD

**Issue by EchoUrandom404** [fedora-silverblue/issue-tracker#134]
Hi, I am using a Thinkpad T440 which has a fingerprint scanner. I do not use this, however, upon using the `fedora:fedora/34/x86_64/silverblue`, I cannot get past the login screen at all as it will say "Sorry, fingerprint authentication didn't work. Please try again." and it will continuously kick me out from trying to type in my password after a few seconds. I am not even touching the fingerprint scanner at all during this event.

The specific version I am on is Fedora 34.20210307 .n.0 (Silverblue Prerelease)

After battling with it a few times, it will let me in. I am not sure what the issue is. I am also not sure what log files you would need to debug this unusual behaviour.

**Comment by tpopela** [comment]
Could this be https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/XA3TQMHT5RFUQE6M5IS3PDUTAFWZSQOW/ ?

**Comment by EchoUrandom404** [comment]
> Could this be [lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/XA3TQMHT5RFUQE6M5IS3PDUTAFWZSQOW](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/XA3TQMHT5RFUQE6M5IS3PDUTAFWZSQOW/) ?

Oh yes, it's this exact same issue.
