### ISSUE TITLE
Weird package downgrades and removal in 33.20210328.0

### ISSUE THREAD

**Issue by 0rzech** [fedora-silverblue/issue-tracker#138]
Ostree upgrade to 33.20210328.0 made the following changes:

```
Upgraded:
  (...)
  gjs 1.66.2-3.fc33 -> 1.66.2-4.fc33
  (...)
  mozjs78 78.8.0-2.fc33 -> 78.9.0-1.fc33
  nss-softokn-freebl 3.62.0-1.fc33 -> 3.63.0-1.fc33
  (...)
Downgraded:
  firefox 87.0-2.fc33 -> 81.0.1-1.fc33
  nss 3.62.0-1.fc33 -> 3.57.0-1.fc33
  nss-softokn 3.62.0-1.fc33 -> 3.57.0-1.fc33
  nss-sysinit 3.62.0-1.fc33 -> 3.57.0-1.fc33
  nss-util 3.62.0-1.fc33 -> 3.57.0-1.fc33
Removed:
  libva-2.9.0-1.fc33.x86_64
```

What I find surprising is that `firefox` was downgraded to such an old version and that `nss*` packages have such version mismatch now. I'm not sure whether `libva` removal was intended too.

**Comment by cgwalters** [comment]
Ugh, that is bad indeed.  We're debating a related issue on this for FCOS here https://github.com/coreos/fedora-coreos-config/pull/892

**Comment by cgwalters** [comment]
(And this whole thing really gets into the topic of https://pagure.io/fedora-qa/os-autoinst-distri-fedora/issue/217 and having tests that run before the ostree commit ships to users, like we have for FCOS)

**Comment by cgwalters** [comment]
OK it looks like there's a nss fix in https://bodhi.fedoraproject.org/updates/FEDORA-2021-d42d8643e4 but now we're in "wait for the once-a-day bodhi run" phase.

**Comment by cgwalters** [comment]
Honestly, I would recommend anyone hit by this to do:
`rpm-ostree override remove firefox`
today and install and use a flatpak version of firefox (whether from Fedora or flathub).

**Comment by cgwalters** [comment]
A new Fedora updates compose should pull in https://bodhi.fedoraproject.org/updates/FEDORA-2021-cd68a3f8ce and fix this.

**Comment by cgwalters** [comment]
Confirmed fixed
```
[root@quicksilver ~]# ostree pull fedora:fedora/33/x86_64/silverblue
...
[root@quicksilver ~]# ostree show fedora:fedora/33/x86_64/silverblue |grep -Ee '(Date|Version)'
Date:  2021-03-28 17:04:22 +0000
Version: 33.20210328.1
[root@quicksilver ~]# rpm-ostree db list fedora:fedora/33/x86_64/silverblue firefox
ostree commit: fedora:fedora/33/x86_64/silverblue (374414782adf57a422b7d9b985ade5d85493ff4a8474f19ce3098aa84048f2a2)
warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
 firefox-87.0-2.fc33.x86_64
[root@quicksilver ~]# 
```

**Comment by rugk** [comment]
Was also in the issue in the forum https://discussion.fedoraproject.org/t/silverblue-wants-to-downgrade-firefox-87-to-v81-with-silverblue-v33-20210328-0/28410?u=rugk and Fedora Firefox bug tracker https://discussion.fedoraproject.org/t/silverblue-wants-to-downgrade-firefox-87-to-v81-with-silverblue-v33-20210328-0/28410?u=rugk BTW.

**Comment by rugk** [comment]
I hope you do a post-mortem or so or really try to do something to avoid this in the future.

**Comment by tpopela** [comment]
> I hope you do a post-mortem or so or really try to do something to avoid this in the future.

See https://github.com/fedora-silverblue/issue-tracker/issues/138#issuecomment-808899199
