### ISSUE TITLE
selinux user contexts

### ISSUE THREAD

**Issue by millerthegorilla** [fedora-silverblue/issue-tracker#139]
Hi, many of the files on my system are labeled with the system_u user context.   However, if I run semanage login -l there is no system_u context defined.
Despite the selinux being in enforcing mode, root has a default context of unconfined, where I think I would expect system_u.
output of semanage login -l
```
Login Name           SELinux User         MLS/MCS Range        Service

__default__          unconfined_u         s0-s0:c0.c1023                *
root                unconfined_u         s0-s0:c0.c1023                 *
```
Is this correct, or should I be concerned?

**Comment by travier** [comment]
In the targeted SELinux policy, interactive users are unconfined by default so this is as expected. `system_u` means that those are system files, not files owned by a specific SELinux user.

**Comment by millerthegorilla** [comment]
Thanks for letting me know.
