### ISSUE TITLE
Fedora 31 Silverblue Test Day

### ISSUE THREAD

**Issue by sumantro93** [fedora-silverblue/issue-tracker#14]
Hey All,

We are closer to beta and we would love to run Fedora Silverblue Test Day. 
I have created a test day tracker for fedora-qa team [here](https://pagure.io/fedora-qa/issue/590)
Please let me know when we can have it also what are the new features which we can test this cycle.

**Comment by returntrip** [comment]
Not part of the fedora-qa team, but currently testing Silverblue 31 and could do some testing for you guys.

**Comment by mikemorrell2** [comment]
I am willing to help with testing too. Let me know when test day for beta is scheduled.

**Comment by tpopela** [comment]
Closing this as the Fedora Silverblue 31 Test day already happened.
