### ISSUE TITLE
What about Nix???

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [fedora-silverblue/issue-tracker#143]
I am NixOS user and I have not tried fedora silverblue yet but it made me wonder why Nix package manager got rejected as something to base silverblue on? (I am sure that at some point Nix was considered and shot down for one reason or another,  I am just interested in the reason why)

For those that don't know - Nix is a package manager which strongly focuses on immutability and reproducibility. Some funky info about it: /bin /usr /lib are pretty much empty the whole system aside /home /var folders and few more random files throughout the system are symlinked to read-only mount /nix/store which contains whole system configuration and packages. 

Some useful out of the box features that come up with such an approach:
1. /nix/store can be shared between servers/VM's/etc
2. it is immutable (read-only) - which means that neither you nor some application will screw it up 
3. All files in /nix/store have a very high reproducibility rate - which means that there is no need to back it up or to snapshot it (https://r13y.com/)
4. It does not collide with FHS package managers
5. You can have multiple versions of the same package, or even something like ffmpeg fully opensource version and ffmpeg with proprietary codecs patches at the same time
6. Since it is immutable and very reproducible - packages caching is easy

**Comment by shimmark** [comment]
There are a few pages about this:

https://ostreedev.github.io/ostree/related-projects/#nixos--nix

https://blog.verbum.org/2013/08/26/ostree-v2013-6-released/

https://wiki.gnome.org/Projects/OSTree/NixOSComparison

**Comment by legendofmiracles** [comment]
Can nix be used at all on silverblue :thinking:?

**Comment by tpopela** [comment]
> I am NixOS user and I have not tried fedora silverblue yet but it made me wonder why Nix package manager got rejected as something to base silverblue on? (I am sure that at some point Nix was considered and shot down for one reason or another, I am just interested in the reason why)

I will leave the answer on @cgwalters .

**Comment by cgwalters** [comment]
Basically:

- Nix is a package manager; the goal of ostree is to make the default more to update from a "base image", where the client doesn't do any dependency resolution at all.  For Fedora CoreOS for example, we test the ostree commit (base image) across multiple clouds and what you get is a bit-for-bit reproduction of what we've tested.
- Nix completely takes over everything, from the build system to configuration.  That has a lot of advantages, but also huge disadvantages.  While there's a lot I dislike about RPM...we can't just toss out everything that exists there now on the build system side.  And for example on an ostree based system, `/etc` is writable in a traditional fashion with whatever tools you want to use from `vi` to Ansible.  

That said, https://github.com/coreos/rpm-ostree/issues/2326 is proposing some Nix-like declarative config for rpm-ostree.  So there will be crossover.

Also, it can make complete sense to use Silverblue as a host but use Nix inside a container image as a toolbox, for example.

**Comment by gytis-ivaskevicius** [comment]
Some thoughts on points you guys noted:
- Url's posted above - I hear what they say, it's only that it is difficult for me to understand the case that "it is an overhead at scale" or something along those lines since even if you patch glibc - you only need to rebuild (unfortunately pretty much everything) only once (this means only a few hundred of packages for normal servers) and of course propagating new version of the package would be achieved by shared /nix/store between machines (at least at scale) or submitting updated packages to all of them. I can't really see a reason why /nix/store would need to be snapshotted. Maybe it's just me, but yeah, I don't quite get it. From my point of view, it is only a pain for individual users who wish to __globally__ patch glibc and have do not have access to other build machines and/or https://nixbuild.net/
- "bit-for-bit reproduction" - from what I understand is everything comes from a centralized build system thus bit-for-bit reputability is achieved by just downloading the same binaries/files, from the same binary cache. Where Nix even tho has shared a binary - but reproducibility does not rely on it since most builds are highly reproducible https://r13y.com/ (I heard by 21.05 release 100% minimal image reproducibility is expected)
- Just to clarify `/etc` is writable on NixOS too, it just that most files are symlinked to read-only mount, and it should not be that big of a deal to change the implementation of it (assuming that's the problem)
- I can see use cases like Silverblue container for deploying some application stacks like Kubernetes, that actually sounds like a pretty cool idea to me! (no worries, cgroups2 support nested containers :D )

Alright, I see the reasoning behind both projects and I am very excited what the future brings both of them.

**Comment by tpopela** [comment]
@gytis-ivaskevicius can I close this? I don't think there is anything actionable and if so, then it should be opened against https://github.com/coreos/rpm-ostree/

**Comment by gytis-ivaskevicius** [comment]
Oh yeah, we can definitely close it. It was more of a question/discussion to begin with.

But may I add some very recent news from Nix side of things:
https://discourse.nixos.org/t/content-addressed-nix-call-for-testers/12881
https://github.com/NixOS/rfcs/pull/62
Long story short "content addressing" solves the issue of rebuilding the world when updating one of the core dependencies.
In other words, patching Glibc will cause only a few packages to get recompiled instead of everything :partying_face:

**Comment by ebkalderon** [comment]
@gytis-ivaskevicius Just a random passersby, but I don't believe that content addressable paths will universally solve the issue of rebuilding the world when one of the core dependencies changes. If I understand the linked RFC and the original Nix thesis chapter on the intensional store correctly, content addressable paths will allow multiple realized derivations with the same on-disk contents (sans self-references) to be easily substituted for each other, eliminating the need for rebuilding.

However, the key words here are _same on-disk contents_. If the `glibc` derivation is updated with some change that doesn't ultimately affect the final output, no rebuild of the world occurs. This is a great improvement from the status quo! But if `glibc` gets patched with something more significant, e.g. a security update or minor bugfix or feature addition, then the final output of the derivation will change (the `libc.so` will be materially different on disk, thereby creating a new CA path in the store) and will still cause a cascading rebuild of the world (downstream packages cannot substitute the old `glibc` with the new `glibc` because the CA hash is different). This _must_ happen by definition because Nix hardcodes absolute paths to dependencies (which include the hash) inside all build artifacts.

Granted, this won't be a huge deal for users with access to other build machines or public binary caches, but that's basically the same place we are today with the current extensional Nix store model, so the concern regarding cascading builds from [this URL](https://ostreedev.github.io/ostree/related-projects/#nixos--nix) still stands.

**Comment by gytis-ivaskevicius** [comment]
At the time I did not understand it well and it was explained poorly to me. So yes, the issue still stands. I guess that's the price of reproducibility :pensive: 

> Granted, this won't be a huge deal for users with access to other build machines or public binary caches, but that's basically the same place we are today with the current extensional Nix store model

May I note that sharing build artifacts and adding build machines is simple? And I guess there are impure options too. But yes, more or less the same place.

**Comment by ebkalderon** [comment]
Yup, it is quite simple! I'm a casual user of both Nix and Silverblue, by the way. I'm enthusiastic about both projects' future; but I just wanted to be transparent about the legitimate tradeoffs of both for the sake of future readers.

**Comment by juhp** [comment]
I have a nix copr repo, but don't really use nix...
If anyone has experience with nix in toolbox or Silverblue I would be interested in hearing about it.

**Comment by thrix** [comment]
@juhp quite late to the game, but nevertheless: https://thrix.github.io/nix-toolbox/
