### ISSUE TITLE
Update All button in Software doesn't work

### ISSUE THREAD

**Issue by daquinons** [fedora-silverblue/issue-tracker#145]
![Screenshot from 2021-04-03 10-50-43](https://user-images.githubusercontent.com/2612426/113473553-77115180-946a-11eb-8fc8-9749f1117e61.png)

18 updates appeared, but when clicking on "Update All" this message appears

Silverblue 34
gnome-software 40.0

**Comment by daquinons** [comment]
I think this might be related to the update to f34 platform.

`flatpak update` works.

**Comment by tpopela** [comment]
I was talking to the upstream GNOME Software maintainer and he suggested to open an issue in https://gitlab.gnome.org/GNOME/gnome-software/-/issues. Can you please do so? Thank you!

**Comment by daquinons** [comment]
Done https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1204

**Comment by tpopela** [comment]
Tahnk you @daquinons ! Closing this issue in favor of the upstream one.
