### ISSUE TITLE
Unable to get list of updates: Daemon disappeared

### ISSUE THREAD

**Issue by daquinons** [fedora-silverblue/issue-tracker#146]
![Screenshot from 2021-04-03 11-31-52](https://user-images.githubusercontent.com/2612426/113474445-4d5b2900-9470-11eb-932a-63ca0c9f89cb.png)

Fedora 34.20210401.n.0 (Silverblue Prerelease)

Seems like it actually checks properly for updates, but the message keeps appearing.

**Comment by felipehw** [comment]
I see this message a lot ...

**Comment by box-dev** [comment]
No surprise as this was reported in the prerelease, but this is still present in the released version - after rebasing to F34 this is an obvious bug.

**Comment by tpopela** [comment]
Can you please report it to https://gitlab.gnome.org/GNOME/gnome-software/-/issues ? Tried to look there and it wasn't reported. If you are able to reproduce it, then please try to run `gnome-software --verbose` from command line to get the logs.

**Comment by box-dev** [comment]
> Can you please report it to https://gitlab.gnome.org/GNOME/gnome-software/-/issues ? Tried to look there and it wasn't reported. If you are able to reproduce it, then please try to run `gnome-software --verbose` from command line to get the logs.

I have reported it at https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1224 - thanks.

**Comment by tpopela** [comment]
Thank you! Let me close this one then.

**Comment by box-dev** [comment]
I think this means no ostree updates without using the commandline until GS 40.1 is released and updated in Silverblue? I have a VM which is a few ostree updates back now (34.20210423.n.0) and Gnome Software does not see anything to update. I suppose at least Silverblue is not the primary way desktop users are using Fedora and will have generally tech savvy users at this point!
