### ISSUE TITLE
Polkit Auth modal prompts for install, with no details of packages

### ISSUE THREAD

**Issue by millerthegorilla** [fedora-silverblue/issue-tracker#147]
Hi,  I am using  a standard user account in silverblue, and when I start I get prompted by a pam auth modal to enter my sudo user password to check for upgrades.
I generally dismiss this modal and use the commandline to check for updates.  However, at seemingly random moments, a gnome auth pam modal appears asking me to enter my sudo user password with the title 'install software'.  The modal gives no details as to what software is to be installed, or updated.  It seems to be base image software that is updated, when I do enter my password rather than flathub software, unless it is dependencies of flat hub installed software.

It would be nice to know why I am entering my password, and what actions are to be taken by the process that spawned the pam modal.

**Comment by tpopela** [comment]
I was talking to the upstream GNOME Software maintainer and he suggested to open an issue in https://gitlab.gnome.org/GNOME/gnome-software/-/issues. Can you please do so? Thank you!

**Comment by millerthegorilla** [comment]
Sure, will do.  Thanks.

**Comment by tpopela** [comment]
I will just add the issues you opened as a reference - https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1203
