### ISSUE TITLE
F34: power-profiles-daemon missing

### ISSUE THREAD

**Issue by daniel-wtd** [fedora-silverblue/issue-tracker#148]
With the recent update of gnome-control-center F34 Workstation also introduced https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/816. This feature is only available, if power-profiles-daemon is installed. This is the case in F34 Workstation, but not in Silverblue.

![Screenshot from 2021-04-05 13-45-20](https://user-images.githubusercontent.com/6490538/113570821-65b87880-9615-11eb-8d66-8e4df446f6a4.png)

**Comment by tpopela** [comment]
It got to Fedora Workstation 34 by mistake - it will be only enabled for F35 - see https://src.fedoraproject.org/rpms/gnome-control-center/c/21b72320a5b49e69dad6ba444583dacb0c2a5827?branch=f34
