### ISSUE TITLE
F34: podman-docker in silverblue, but not in workstation

### ISSUE THREAD

**Issue by daniel-wtd** [fedora-silverblue/issue-tracker#149]
Hi all,

in Silverblue the package "podman-docker" is in the base layer. If moby-engine will be installed as an overlay, this may conflict (/usr/bin/docker coming from 2 different packages), therefore podman-docker will be removed as conflicting.

Since it is not pre-installed in F34 Workstation, I recommend not having it in Silverblue, too.

```
$ rpm-ostree install moby-engine
[...]
Removed:
  podman-docker-2:3.1.0-1.fc34.noarch
Added:
  containerd-1.5.0~beta.3-1.fc34.x86_64
  moby-engine-20.10.5-1.fc34.x86_64
  runc-2:1.0.0-364.dev.gite7bd1fb.fc34.x86_64
```

**Comment by tpopela** [comment]
This was caused by some of your changes. On my SB34 machine the podman-docker is not preinstalled. See :

```
tpopela  ~  >  08:09
0 $ rpm -qa | grep podman
podman-plugins-3.1.0-1.fc34.x86_64
podman-3.1.0-1.fc34.x86_64
tpopela  ~  >  08:09
0 $ rpm -qa | grep podman-docker
tpopela  ~  >  08:09
1 $ echo $?
1
```

**Comment by daniel-wtd** [comment]
Interesting, not sure where this may come from:

```
           LayeredPackages: NetworkManager-fortisslvpn-gnome ffmpeg-libs power-profiles-daemon vagrant virt-manager
```

**Comment by tpopela** [comment]
Try to use ` rpm -q --whatrequires podman-docker` to find out.

**Comment by daniel-wtd** [comment]
```
[dschier@nb01 gerri-server]$ rpm -q --whatrequires podman-docker
no package requires podman-docker
```

let me try a reset.

**Comment by daniel-wtd** [comment]
```
[dschier@nb01 gerri-server]$ rpm -q --whatrequires podman-docker
no package requires podman-docker
```
After `rpm-ostree reset` its gone.

**Comment by daniel-wtd** [comment]
Vagrant seems to be the culprit, which makes sense somehow, since it has a docker provider. Thanks for the support :)

**Comment by tpopela** [comment]
No problem @daniel-wtd ! Thank you for stepping by!
