### ISSUE TITLE
gstreamer1-plugin-openh264 by default? 

### ISSUE THREAD

**Issue by FastOSlinux** [fedora-silverblue/issue-tracker#152]
I wonder if this package followed by its necessary dependencies can be included in the base OS for the Firefox browser to work with screen sharing on SB? 

If not, is there a reason/issue? 

installing:
gstreamer1-plugin-openh264
mozilla-openh264
openh264

allows screen sharing in default Firefox 
![Captura de tela de 2021-04-17 17-38-01](https://user-images.githubusercontent.com/17401812/115126194-b16b0a80-9fa3-11eb-819f-ac8f443c6326.png)

thanks for everything, amazing system!

**Comment by felipehw** [comment]
Firefox from Flathub doesn't resolve this problem?

**Comment by FastOSlinux** [comment]
> Firefox from Flathub doesn't resolve this problem?

no, upstream Firefox doesn't share screen in wayland, yet..

**Comment by tpopela** [comment]
> I wonder if this package followed by its necessary dependencies can be included in the base OS for the Firefox browser to work with screen sharing on SB?

Screen sharing on Wayland (through Firefox or Chrome/Chromium) does work out of the box on Silverblue. The openh264 packages shouldn't be needed for Firefox.

> If not, is there a reason/issue?

Any openh264 package that you mentioned below can't be part of base OS in Silverblue or default installation of Fedora Workstation - see. https://github.com/fedora-silverblue/issue-tracker/issues/119#issuecomment-757953599
