### ISSUE TITLE
cannot upgrade to fedora 34 using gnome-software

### ISSUE THREAD

**Issue by hferreiro** [fedora-silverblue/issue-tracker#154]
I'm getting this error message when pressing the download button in gnome-software:

> Unable to upgrade to Fedora 34:
Updating rpm-md repo 'fedora-cisco-openh264': cannot update repo 'fedora-cisco-openh264': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for https://codecs.fedoraproject.org/openh264/34/x86_64/repodata/repomd.xml (IP: ..)

**Comment by tpopela** [comment]
Can you please paste here the content of `/etc/yum.repos.d/fedora-cisco-openh264.repo` and also output of `ls /etc/yum.repos.d`

**Comment by tpopela** [comment]
And also the output of `rpm -V fedora-repos-34-1.noarch`

**Comment by tpopela** [comment]
The right link in the /etc/yum.repos.d/fedora-cisco-openh264.repo should be:

`https://codecs.fedoraproject.org/openh264/34/x86_64/os/repodata/repomd.xml`

or

`metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-$releasever&arch=$basearch`

but we would like to know why you have some old link there..

**Comment by hferreiro** [comment]
Copying the file from /usr/etc worked. The weird thing is that I never changed that file.

This were the contents that weren't working:
> [fedora-cisco-openh264]
name=Fedora $releasever openh264 (From Cisco) - $basearch
baseurl=https://codecs.fedoraproject.org/openh264/$releasever/$basearch/
type=rpm
enabled=1
enabled_metadata=1
metadata_expire=14d
repo_gpgcheck=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=True
>
> [fedora-cisco-openh264-debuginfo]
name=Fedora $releasever openh264 (From Cisco) - $basearch - Debug
baseurl=https://codecs.fedoraproject.org/openh264/$releasever/$basearch/debug/
type=rpm
enabled=0
metadata_expire=28d
repo_gpgcheck=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=True

**Comment by sinaflan** [comment]
fresh install 34, Gnome Software not work - **Daemon disappeared**

**Comment by tpopela** [comment]
> fresh install 34, Gnome Software not work - **Daemon disappeared**

That's a different issue. See https://github.com/fedora-silverblue/issue-tracker/issues/146. Please use search next time.

**Comment by tpopela** [comment]
> Copying the file from /usr/etc worked. The weird thing is that I never changed that file.

We would know that (if the file was touched) with the output of `rpm -V` without that it's just the speculations. Also can you please share the output of `ls /etc/yum.repos.d` as I've asked (to see whether .rpmnew file was created there)

**Comment by hferreiro** [comment]
> $ rpm -V
rpm: no arguments given for verify

> $  ls /etc/yum.repos.d/                                                        
_copr_phracek-PyCharm.repo   fedora-updates.repo
fedora-cisco-openh264.repo   fedora-updates-testing-modular.repo
fedora-modular.repo          fedora-updates-testing.repo
fedora.repo                  google-chrome.repo
fedora-updates-archive.repo  rpmfusion-nonfree-nvidia-driver.repo
fedora-updates-modular.repo  rpmfusion-nonfree-steam.repo

**Comment by tpopela** [comment]
> > $ rpm -V
> > rpm: no arguments given for verify

See https://github.com/fedora-silverblue/issue-tracker/issues/154#issuecomment-828484927 . But it doesn't matter anyway as you already replaced the file.

> 
> > $  ls /etc/yum.repos.d/
> > _copr_phracek-PyCharm.repo   fedora-updates.repo
> > fedora-cisco-openh264.repo   fedora-updates-testing-modular.repo
> > fedora-modular.repo          fedora-updates-testing.repo
> > fedora.repo                  google-chrome.repo
> > fedora-updates-archive.repo  rpmfusion-nonfree-nvidia-driver.repo
> > fedora-updates-modular.repo  rpmfusion-nonfree-steam.repo

Ok, thanks! @dustymabe @cgwalters is rpm-ostree creating .rpmnew files when there are new updates to the configuration files or how it's handled?

**Comment by jlebon** [comment]
No, `/etc` is managed by OSTree. I added some docs in https://github.com/ostreedev/ostree/pull/2355 describing it.

**Comment by tpopela** [comment]
@jlebon thanks for the docs! After looking at the docs it would really mean that @hferreiro edited the file in the past (we obviously can't find it out now)?

**Comment by travier** [comment]
This is likely fixed now.
