### ISSUE TITLE
After rebase 33 -> 34, Strange Updates in gnome-software

### ISSUE THREAD

**Issue by richard-gravy** [fedora-silverblue/issue-tracker#155]
Hello

This afternoon I rebased to f34 (34.20210424.n.0 (2021-04-24T08:00:52Z), using the following command line:-
`rpm-ostree rebase fedora:fedora/34/x86_64/silverblue --uninstall rpmfusion-free-release-33-1.noarch --install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-branched.noarch.rpm --uninstall rpmfusion-nonfree-release-33-1.noarch --install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-branched.noarch.rpm`

After restarting, I can see the new GNOME 40 desktop, but looking in Software, I seem to be required to manually update packages that I thought were part of the base image, e.g. Calculator 3.38 -> 40, Eye of GNOME 3.38 -> 40 and File Roller "stable".

There is also a 636.7 MB update called "Fedora Platform f33 -> 33".  I'm avoiding installing that one for now.

Is there something else I need to do to ensure that updates are only sought for f34 packages?

**Comment by tpopela** [comment]
Can you please report it to https://gitlab.gnome.org/GNOME/gnome-software/-/issues ? If you are able to reproduce it, then please try to run gnome-software --verbose from command line to get the logs. Please paste the link for the issue here as well.

**Comment by kalev** [comment]
My reply on irc:

09:22 < tpopela> kalev: Hi Kalev, any idea about https://github.com/fedora-silverblue/issue-tracker/issues/155 ?
10:55 < hadess> tpopela: aren't those flatpaks now?
10:55 < hadess> and the "platform" update is the flatpak runtime for them
11:31 < tpopela> hadess: yes, on SB those are flatpaks and platform is a runtime, but I don't know why it misbehaves like this.. it should just update for f34 runtime and f34 applications..
11:34 < kalev> tpopela: ok, there are two issues there:
11:34 < kalev> issue one is that there is an update to F33 platform. This is expected as we install F33 and F34 flatpak runtimes in parallel
11:35 < kalev> the F33 runtime is going to go away when we EOL it. I just managed to EOL the F32 runtime yesterday after libreoffice switched to a newer runtime
11:36 < kalev> F33 runtime is up next, waiting on https://pagure.io/fedora-infrastructure/issue/9840#comment-730036 before we can EOL it
11:36 < kalev> issue two is that some of the flatpaks needed manual updating in gnome-software
11:37 < kalev> I think that's just how gnome-software handles changed flatpak permissions: it just asks for confirmation to update and doesn't auto update things
11:37 < kalev> so some of the things, those where flatpak permissions haven't changed get auto-updated, and others, those where permissions changed need manual updating

**Comment by richard-gravy** [comment]
OK, I was able to look at the log for gnome-software (after `killall gnome-software; gnome-software --verbose`) and every package that I am having a problem with is showing as coming from the flatpak plugin.

The IRC conversation explains the position and I am now wiser, although I do try to limit the disk space used for the system and being required to hold onto large f33 packages makes me wish I just re-installed instead of rebased ;)

**Comment by kalev** [comment]
You should be able to install all updates and then remove the F33 runtime after that with 'flatpak remove org.fedoraproject.Platform//f33'. We only have one remaining flatpak that requires the F33 runtime (the 0ad flatpak) and if you don't have that one installed, you should be able to just remove the old runtime. Everything else is on F34 runtime already.

Or if you want to wait a bit, it should get automatically removed once we can EOL it (after the 0ad update issue I linked above is resolved).

**Comment by tpopela** [comment]
I see that the f33 runtime is EOL. @richard-gravy is there anything else what we can do for you?

**Comment by richard-gravy** [comment]
No, I think that's all on this one.  Thanks for your time
