### ISSUE TITLE
Fail to rebase from F34 to F33: Failed to update rpmdb (rpmtsRun code -1)

### ISSUE THREAD

**Issue by gdesmott** [fedora-silverblue/issue-tracker#158]
I'd like to rollback from F34 to F33. As I did various update/install from the F33->F34 update, I'm no longer able to use `rpm-ostree rollback` or to switch using Grub, so I tried rebasing on F33:

```
$ rpm-ostree rebase fedora:fedora/33/x86_64/silverblue 
2 metadata, 0 content objects fetched; 788 B transferred in 2 seconds; 0 bytes content written
Checking out tree aa351a9... done
Enabled rpm-md repositories: updates fedora-cisco-openh264 fedora
rpm-md repo 'updates' (cached); generated: 2021-05-02T01:55:36Z
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-08-25T19:10:34Z
rpm-md repo 'fedora' (cached); generated: 2020-10-19T23:27:19Z
Importing rpm-md... done
Resolving dependencies... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
error: Failed to update rpmdb (rpmtsRun code -1)
```

**Comment by tpopela** [comment]
The f34 and f33 uses a different RPM database format, so I don't know whether it's actually possible to do the rebase. @jlebon any idea?

**Comment by tpopela** [comment]
@cgwalters @dustymabe any idea? It's preventing the users to roll back for F33.

**Comment by jlebon** [comment]
This is due to the rpmdb move. Fedora 34 `rpm` no longer knows how to write bdb, which is what's used in FSB 33, so it errors out.

The workaround for this is to drop all overrides (`rpm-ostree reset -lo`) and then rebase. Then it's a pure OSTree operation which does not involve RPM at all. Once rebooted into f33, you can add back your overlays.

**Comment by travier** [comment]
Both F34 & F33 are now EOL
