### ISSUE TITLE
Screensharing in Firefox flatpak stopped working after update to Fedora Silverblue 34

### ISSUE THREAD

**Issue by andreasn** [fedora-silverblue/issue-tracker#159]
I recently updated to Fedora Silverblue 34.
After the upgrade, it seems screensharing from the Firefox flatpak no longer works.

I get the little popup in Firefox, giving me the single option of "Use operating system settings"
![image](https://user-images.githubusercontent.com/209895/116871533-b15e4200-ac14-11eb-8a23-555826b47a9c.png)

After that I get presented with a window from the OS. When I press allow, nothing happens.
![image](https://user-images.githubusercontent.com/209895/116871639-dd79c300-ac14-11eb-9ea3-06de6a8bfba2.png)

Trying to figure out what component isn't working properly. Is this happening to anyone else? 
It does work in the non-flatpaked Firefox.

**Comment by grulja** [comment]
It works for me in FF flatpak from Fedora.

**Comment by travier** [comment]
Likely fixed now.
