### ISSUE TITLE
Silverblue 31 - issue installing `solaar`

### ISSUE THREAD

**Issue by returntrip** [fedora-silverblue/issue-tracker#16]
When installing `solaar` on Silverblue 31 I get the following error:

```
rpm-ostree install solaar
error: Running %posttrans for solaar-udev: Executing bwrap(/bin/sh): Child process killed by signal 1; run `journalctl -t 'rpm-ostree(solaar-udev.posttrans)'` for more information
```

Output of `journalctl --full -t 'rpm-ostree(solaar-udev.posttrans)'`:

```
Sep 13 21:04:23 rauros.figura.io rpm-ostree(solaar-udev.posttrans)[3166]: Failed to write 'add' to '/sys/devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-11/1-11.1/1-11.1:1.2/0003:046D:C52B.0004/0003:046D:101A.0008/hidraw/hidraw3/uevent': Read-only file system
Sep 13 21:04:23 rauros.figura.io rpm-ostree(solaar-udev.posttrans)[3166]: Failed to write 'add' to '/sys/devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-11/1-11.1/1-11.1:1.2/0003:046D:C52B.0004/0003:046D:2010.0007/hidraw/hidraw2/uevent': Read-only file system
Sep 13 21:04:23 rauros.figura.io rpm-ostree(solaar-udev.posttrans)[3166]: Failed to write 'add' to '/sys/devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-11/1-11.1/1-11.1:1.2/0003:046D:C52B.0004/hidraw/hidraw1/uevent': Read-only file system
Sep 13 21:04:23 rauros.figura.io rpm-ostree(solaar-udev.posttrans)[3166]: Failed to write 'add' to '/sys/devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-8/1-8:1.0/0003:1B1C:1C05.0001/hidraw/hidraw0/uevent': Read-only file system
```

**Comment by grdryn** [comment]
I just commented on the [corresponding RHBZ](https://bugzilla.redhat.com/show_bug.cgi?id=1764565), so I'll copy here for good measure:

> I think I'm hitting the same issue now that I've installed SB31. It worked fine in SB30. I've got a little more info:
>
> I _can_ install solaar, as long as I've disconnected the receiver before I try to install with rpm-ostree. That's not enough though, because Once it's installed, even though I can see my mouse in solaar (after rebooting and reconnecting the receiver), I can't change any settings for it, because of seemingly similar issues (can't write those changes). I also see issues if I now try an `rpm-ostree upgrade` with solaar installed and my receiver connected.

**Comment by dustymabe** [comment]
What scriptlets is solarr trying to run? What does `rpm -q solarr` show?

**Comment by returntrip** [comment]
@dustymabe Thanks for answering my call for help! :)

I could not run the command directly on Silveblue but I downloaded the RPM file manually then:

```
rpm -qp --scripts solaar-udev-1.0.1-1.fc31.noarch.rpm 
posttrans scriptlet (using /bin/sh):
# This is needed to apply permissions to existing devices when the package is
# installed.
/usr/bin/udevadm trigger --subsystem-match=hidraw --action=add
``

**Comment by jlebon** [comment]
See https://src.fedoraproject.org/rpms/udisks2/pull-request/3. A similar patch for this would probably work. (Though as discussed there, a more general approach is to just get `udevadm` to handle this gracefully.)

**Comment by returntrip** [comment]
@jlebon I think that makes sense. Would you know why this issue was not triggering on Silverblue 30? I see there is the same scriplet in `fc30` RPMs

**Comment by dustymabe** [comment]
> Though as discussed there, a more general approach is to just get `udevadm` to handle this gracefully.

can we open a request somewhere (or maybe there is already an open request?) for that to happen?

**Comment by returntrip** [comment]
In the meanwhile I will ask the solaar's package maintainer to use a similar solution to: https://src.fedoraproject.org/rpms/udisks2/pull-request/3

Thanks much for the quick help!

**Comment by tpopela** [comment]
Closing as it works:

```
[tpopela@localhost ~]$ rpm-ostree install solaar
Checking out tree 825786a... done
Enabled rpm-md repositories: updates-testing fedora updates fedora-cisco-openh264
rpm-md repo 'updates-testing' (cached); generated: 2020-03-26T01:32:06Z
rpm-md repo 'fedora' (cached); generated: 2020-03-26T11:17:22Z
rpm-md repo 'updates' (cached); generated: 2018-02-20T19:18:14Z
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-03-17T20:10:45Z
Importing rpm-md... done
Resolving dependencies... done
Will download: 3 packages (310.1 kB)
Downloading from 'fedora'... done
Downloading from 'updates-testing'... done
Importing packages... done
Applying 1 override and 8 overlays
Processing packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
Writing OSTree commit... done
Staging deployment... done
Added:
  python3-pyudev-0.22.0-1.fc32.noarch
  solaar-1.0.2-0.1.rc1.20200322git563ef0d.fc32.noarch
  solaar-udev-1.0.2-0.1.rc1.20200322git5
```
