### ISSUE TITLE
Insufficient Contrast between the Background and Text in GNOME Tour and Greeter when using Adwaita-dark

### ISSUE THREAD

**Issue by 0verk1ll** [fedora-silverblue/issue-tracker#161]
On Fedora 34.20210505.0 (Silverblue), with GNOME Tour and Greeter 40.0, the contrast between the background and text when the shell theme is set to "Adwaita-dark" using GNOME Tweaks is insufficient. This presents an accessibility problem.

If I should report this issue further upstream, please tell me. I submitted it here because I saw the Fedora-specific branding.

![FedoraTourThemingIssue0](https://user-images.githubusercontent.com/22098433/117220427-31cba100-add5-11eb-8c2a-01769abef58a.png)
![FedoraTourThemingIssue1](https://user-images.githubusercontent.com/22098433/117220429-32643780-add5-11eb-8ed8-ed07327c7b3e.png)

**Comment by juhp** [comment]
See https://gitlab.gnome.org/GNOME/gnome-tour/-/issues/36
