### ISSUE TITLE
Fedora Silverblue initial setup cannot connect to WPA2 Enterprise networks

### ISSUE THREAD

**Issue by strugee** [fedora-silverblue/issue-tracker#162]
STR:

1. Install Fedora Silverblue
2. Reboot into the new installation
3. Wait for the setup screen to load
4. Click the "Start Setup" button to get to the WiFi selection screen
5. Click on a WPA2 Enterprise network

Expected result: I'm prompted for my credentials and can authenticate to the network.

Actual result: nothing happens. The list entry briefly shows as clicked and then it returns to the same state it was in before.

I'm on a just-downloaded Silverblue 34 image.

**Comment by tpopela** [comment]
Hi @strugee , can you please also test the Fedora Workstation 34 image? And if it's reproducible there, can you please report the bug against NetworkManager in Red Hat Bugzilla?

**Comment by travier** [comment]
This would need to be reproduced on a more recent released. Closing until then. Feel free to comment if you can reproduce.
