### ISSUE TITLE
GNONE Software incorrectly thinks several Flatpaks are proprietary

### ISSUE THREAD

**Issue by strugee** [fedora-silverblue/issue-tracker#163]
On my Fedora Silverblue 34 installation, GNOME Software displays both SuperTux and Endless Sky (in the Games section) as proprietary applications, even though they're not - both of them are under the GPL. Presumably there are other applications with the same problem as well (it did not take me long to find these mislabeled licenses).

**Comment by tpopela** [comment]
I think that this might be a thing similar to https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1200 . Can you please add a comment into that issue?

**Comment by strugee** [comment]
Done: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1200#note_1104731

Do we want to close this since it seems the problem is already known upstream?

**Comment by tpopela** [comment]
Thank you @strugee ! Yes, let me close this one.

**Comment by strugee** [comment]
Thanks!
