### ISSUE TITLE
[RFE] Steam repository in Software

### ISSUE THREAD

**Issue by bluebluesilver** [fedora-silverblue/issue-tracker#164]
**Is your feature request related to a problem? Please describe.**
In Silverblue 33 GNOME Software had the ability to enable the Steam repository, for overlaying Steam. This is gone now, and I can't find the repository again.

**Describe the solution you'd like**
I would like for there to be a clear and easy way to install Steam as an overlaid package, without setting up RPM fusion.

**Describe alternatives you've considered**
- Steam is available on flathub, but doesn't play nice with GNOME's apps. I.e. after installing a game I need to open it in steam; the steam overlay allowed direct launch from GNOME.
- Steam is available through RPM fusion, but I don't want the entirety of RPM fusion as a mirror when I only want Steam.

**Additional context**
Running on a fresh re-install of Fedora Silverblue 34, `Version: 34.20210423.n.0 (2021-04-23T08:10:25Z)`

**Comment by bluebluesilver** [comment]
The ability to add 3rd party software repositories finally appeared (a day after initial install). From there I could find the steam repo: GNOME Software -> 3 dots (upper right hand corner) -> Software Repositories -> RPM Fusion for Fedora 34 - Nonfree - Steam.

**Comment by bluebluesilver** [comment]
I'm curious why it took so long for 3rd party repos to appear (several reboots after initail setup).

**Comment by tpopela** [comment]
@kalev any idea what might happen here?

**Comment by bluebluesilver** [comment]
So... After another setup on another computer I'm having the same problem, but many days later now. Is there some way I can trigger the "Enable 3rd party repositories" manually?

**Comment by travier** [comment]
This is now handled by the third party integrations or installed via Flathub.
