### ISSUE TITLE
[BUG] rebase 34 -> rawhide fails

### ISSUE THREAD

**Issue by bluebluesilver** [fedora-silverblue/issue-tracker#169]
**Describe the bug**
I get an error when trying to rebase from stable `34` to `rawhide`.
Error:
```
error: Updating rpm-md repo 'updates-archive': cannot update repo 'updates-archive': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 403 for https://fedoraproject-updates-archive.fedoraproject.org/fedora/rawhide/x86_64/repodata/repomd.xml (IP: 13.227.211.9)
```

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. `$ rpm-ostree rebase fedora/rawhide/x86_64/silverblue`
2. Error

**Expected behavior**
Rebased

**OS version:**
```
$ rpm-ostree status -b
State: idle
BootedDeployment:
● ostree://fedora:fedora/34/x86_64/testing/silverblue
                   Version: 34.20210508.0 (2021-05-08T02:04:12Z)
                BaseCommit: 7b460da9c2ccd2519aa6756435eaf8bb6fb1c1253f29e870ded830419e37d3c6
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: kitty kitty-terminfo
```

**Comment by tpopela** [comment]
I asked on #fedora-releng on FreeNode, but got no response so far.

**Comment by dustymabe** [comment]
@nirik yeah I can do that. It's an interesting problem, because the updates-archive repo is disabled on rawhide (in the rawhide RPM that delivers the yum repo), but because the user is rebasing from F34 the version of the repo file they are using has it enabled.

@bluebluesilver - you can just edit the yum repo file:

```
sudo sed -i s/enabled=1/enabled=0/ /etc/yum.repos.d/fedora-updates-archive.repo
```

**Comment by dustymabe** [comment]
this should be fixed now. I've populated the updates-archive with a rawhide yum repo that's empty. Should prevent people from hitting this problem in the future.
