### ISSUE TITLE
Rebase to 31 causes selinux errors and systemd-logind fails to start

### ISSUE THREAD

**Issue by boydkelly** [fedora-silverblue/issue-tracker#17]
I filed this bug [1763449](https://bugzilla.redhat.com/show_bug.cgi?id=1763449) but it is still new and probably not the right place.   When I rebase from F30 to F31 I get selinux errors with modprobe writing to /var/lib/systemd/linger.   In can only start by setting kernel parameter selinux=0.   Please see the [bootlog](https://bugzilla.redhat.com/attachment.cgi?id=1627420)

**Comment by tpopela** [comment]
Closing as it was fixed - per https://bugzilla.redhat.com/show_bug.cgi?id=1763449#c21.
