### ISSUE TITLE
[BUG] `apropos`/`man -k` do not function

### ISSUE THREAD

**Issue by strugee** [fedora-silverblue/issue-tracker#170]
**Describe the bug**

The `apropos` utility used to search manpages does not work because its database has not been built on Silverblue systems.

**To Reproduce**

1. Run e.g. `apropos list` on the host system and notice there's no results ("list: nothing appropriate.")
2. Run the same command in a Toolbox container and observe the same result
3. Run `sudo mandb` in the Toolbox container and notice how `apropos` suddenly starts returning results

**Expected behavior**

Manpage search should work out of the box.

**OS version:**
```
â— ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210423.n.0 (2021-04-23T08:10:25Z)
                BaseCommit: 7b99463136830fd9b18f8daf5f7973f3e15eaa3532f8dbcbb4f7eb9673170461
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: gnome-tweaks

```

**Comment by tpopela** [comment]
Thank you @strugee for reporting this. I didn't know about apropos until now. I looked at the RHBZ and it is already reported as https://bugzilla.redhat.com/show_bug.cgi?id=1473402 . I'm closing this in favor of that one (you might want to add to CC for that bug).
