### ISSUE TITLE
[BUG] Automatic screen blanking causes system hang (amdgpu)

### ISSUE THREAD

**Issue by nuuhku** [fedora-silverblue/issue-tracker#172]
**Describe the bug**
I have two freshly installed Silverblue 34 systems with Radeon GPUs (Core i5 6500 + RX560 & Ryzen 1700 + RX5700) and both machines hang when the automatic screen blanking activates. As far as I can tell this happens every time. The screen never wakes up, system becomes completely unresponsive and is no longer accessible from the network.

I've also tested Fedora Workstation 34 on both systems and screen blanking works fine there.

**To Reproduce**
Just wait 5 minutes for the default automatic screen blanking to activate.

**Expected behavior**
The system should not hang and the screen should wake up when the mouse is moved or a key is pressed.

**OS version:**
```
● ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210513.0 (2021-05-13T00:46:10Z)
                    Commit: 0a791a0478306d9462880703af5c235b8142371e09e9ec079e04fb29845748c6
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
```

**Additional context**
This appears to be a log message related to the problem: 
```
kernel: amdgpu: last message was failed ret is 0
kernel: amdgpu: failed to send message 254 ret is 0 
kernel: amdgpu: SMU load firmware failed
kernel: amdgpu: fw load failed
kernel: amdgpu: smu firmware loading failed
kernel: amdgpu 0000:01:00.0: amdgpu: amdgpu_device_ip_resume failed (-22).
kernel: amdgpu: Move buffer fallback to memcpy unavailable
kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to process the buffer list -19!
gnome-shell[5157]: amdgpu: The CS has been rejected, see dmesg for more information (-19).
kernel: snd_hda_intel 0000:01:00.1: CORB reset timeout#1, CORBRP = 0
kernel: amdgpu: last message was failed ret is 0
kernel: amdgpu: failed to send message 281 ret is 0 
```

**Comment by tpopela** [comment]
It's strange that the default (and updated) installation of Fedora Workstation 34 works, but the Silverblue doesn't. Looking at you Silverblue image version 34.20210513.0 - there was a kernel update - can you please try to update to kernel-5.11.20-300.fc34? Can you please also check that the kernel packages are the same when you are testing in Workstation and in Silverblue?

**Comment by nuuhku** [comment]
I installed all updates on Silverblue and Workstation, but unfortunately that didn't resolve the problem. Everything is now running kernel 5.11.20-300.fc34.x86_64 and only Silverblue hangs with screen blanking (automatic and manual with Super + L). I tested with another monitor and two different cables, but that didn't help either. I also checked with gsettings that org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type is set to 'nothing'.

The PCs I'm testing are very different and the only thing in common is an AMD GPU. So I would say the problem is somehow related to the amdgpu driver... but why is it only happening in Fedora Silverblue and not in Fedora Workstation? The kernel, driver and firmware should be exactly the same. Maybe it's due to some other difference between Silverblue and Workstation?

This might be a widespread issue, so it would be interesting to hear from other AMD GPU users. Let me know if there's anything else I could try in the meantime.

**Comment by nuuhku** [comment]
Just did a new round of tests with the new 5.12.5-300.fc34.x86_64 kernel and there is no change. Silverblue 34 is still hanging on both the Intel and AMD machine. On Fedora 34 Workstation screen blanking is still working great.

**Comment by tpopela** [comment]
> The PCs I'm testing are very different and the only thing in common is an AMD GPU. So I would say the problem is somehow related to the amdgpu driver... but why is it only happening in Fedora Silverblue and not in Fedora Workstation? The kernel, driver and firmware should be exactly the same. Maybe it's due to some other difference between Silverblue and Workstation?

But on this level the differences should be nearly zero :/ . Do you have any packages overlayed?

**Comment by nuuhku** [comment]
> But on this level the differences should be nearly zero :/ . Do you have any packages overlayed?

Nope, I don't have any overlayed packages.

Both installations are as basic as they can get - single nvme ssd, automatic partitioning, no overlayed packages or Gnome extensions. Only flatpaks from Fedora and Flathub. But just to test things out, I reinstalled Silverblue on the Ryzen machine, only did flatpak update & rpm-ostree upgrade and rebooted. It still happens. :(

**Comment by nuuhku** [comment]
Don't know how useful this information is, but I decided to test the older Silverblue 33 and initially screen blanking was working fine. Once I did an ostree-rpm upgrade, the kernel got updated to 5.12.7 and screen blanking started to hang the whole system also on Silverblue 33.

**Comment by nuuhku** [comment]
I just reinstalled Silverblue 34 and noticed something really interesting. If I log out and log back in, then screen blanking will work fine on Silverblue 34 too! And it keeps on working until the next reboot. The "Switch user" function is not enough, it has to be a full repeated login to the same or another user. So maybe this bug has something to do with GDM or Gnome?

Anyway, this bug is probably too complicated for me to figure out on my own. Guess I'll just add a log in / out / in to my daily routine until someone with better debugging skills can take a look at it. :)

**Comment by nuuhku** [comment]
Finally came up with an automatic (but totally silly) way to deal with this issue. I assumed that if logging out and back in helps, then restarting GDM should help too. So I created a oneshot-type systemd service that restarts gdm.service a few seconds after gdm.service has started.

And yes, it works! No more system freezes with screen blanking. :D

**Comment by nuuhku** [comment]
Silverblue 34 kernel got recently upgraded to 5.12.9-300.fc34.x86_64, but unfortunately that did not resolve this bug. I did notice that if you disable graphical boot (plymouth / rhgb), then screen blanking will work perfectly and the system will no longer freeze.

**Comment by nuuhku** [comment]
This has been resolved with latest updates and screen blanking is working fine again.
