### ISSUE TITLE
[BUG] rpm repo shown in gnome software

### ISSUE THREAD

**Issue by daniel-wtd** [fedora-silverblue/issue-tracker#175]
**Describe the bug**

Gnome Software is listing updates-archive (RPM) as installation source

**To Reproduce**

Please describe the steps needed to reproduce the bug:
1. Install Fedora Silverblue 34
2. Update the system
3. Enable Flathub
3. Open Gnome Software
4. choose an application (Gnome notes in my case)
5. First install option for the application is "updates-archive (RPM)" (top right corner)

**Expected behavior**

RPM respositories should be invisible in gnome software. This seems not to be true for updates-archive, which was added recently.

**Screenshots**

![Screenshot from 2021-06-24 07-58-48](https://user-images.githubusercontent.com/6490538/123210331-2128d480-d4c2-11eb-82fb-3031c988d6f2.png)

**OS version:**
```
State: idle
BootedDeployment:
● ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210622.0 (2021-06-22T00:42:51Z)
                BaseCommit: b4908886e62efb07d6a5965ced44f01b24f4ece525eb72bc3c62e94a2223fea7
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: NetworkManager-fortisslvpn-gnome arm-image-installer ffmpeg-libs libvirt-client vagrant
                            virt-manager
             LocalPackages: rpmfusion-free-release-34-1.noarch

```

**Comment by mcrha** [comment]
Why not to show it? I know this is Silverblue and rpm-ostree and so on, but as long as the repo is configured and it offers the application, then why to hide it?

**Comment by felipeborges** [comment]
It should be shown, but not made the default option. The preferable way of consuming apps in Silverblue should be Flatpak.

**Comment by mcrha** [comment]
I see. Repo priorities are discussed within the repos dialog redesign (https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1166) at https://gitlab.gnome.org/Teams/Design/software-mockups/-/issues/5 ; a related upstream bug: https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1005

**Comment by daniel-wtd** [comment]
If we want to show rpm repos, all of them should be shown. But showing the archives repo only is a bug in my opinion.

**Comment by mcrha** [comment]
Partly related upstream issue:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1218

**Comment by daniel-wtd** [comment]
@mcrha if the fedora-updates-archive should be shown, why not showing all enabled rpm repos gnome software? I dont see what is special with updates archive compared to fedora-updates or fedora.repo.

**Comment by mcrha** [comment]
There was a bug, which prevented to show all repos, not only in rpm-ostree.

**Comment by daniel-wtd** [comment]
So, the desired design is to show all available repos for these packages and install them via rpm-ostree if chosen?
If yes, that would solve this issue for me, too.
Is there a related bug for silverblue where the "absence" of other repos in gnome software is addressed?

**Comment by mcrha** [comment]
It's not fixed by silveblue, (and it fact has nothing to do with it), it's fixed by upstream. One such bug (I'm afraid there are more related) is:
https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/710

**Comment by daniel-wtd** [comment]
So, the expected behavior (in silverblue) is, that fedora.repo, fedora-updates.repo and fedora-updates-archive.repo should be shown to install software (example gnome-notes/bijiben) from? Just asking because it was not the case since silverblue release.

**Comment by daniel-wtd** [comment]
Since the Fedora (rpm) repo is also shown as software source in F34, I assume it is intended design to have rpm repositories (and therefore overlays) as regular behavior. My assumption was that overlays should be avoided as much as possible.

Closing this as "not a bug"

![Screenshot from 2021-07-09 23-56-14](https://user-images.githubusercontent.com/6490538/125139820-87903280-e111-11eb-912d-bec7f834cea5.png)
