### ISSUE TITLE
Gnome ABRT package does not install its dependencies

### ISSUE THREAD

**Issue by vchernin** [fedora-silverblue/issue-tracker#176]
**Describe the bug**
`gnome-abrt` seemingly depends on `abrt`, but rpm-ostree is not aware of that dependency.

**To Reproduce**
1. `rpm-ostree install gnome-abrt` & reboot
2. `gnome-abrt`
You will get an error:
```
$ gnome-abrt
WARNING:root:Can't connect to D-Bus system bus 'org.freedesktop.problems' path '/org/freedesktop/problems': org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ERROR:root:No available problem source.
Traceback (most recent call last):
  File "/usr/bin/gnome-abrt", line 176, in do_activate
    raise UnavailableSource(None, None,
gnome_abrt.errors.UnavailableSource: No available problem source.
```

`rpm-ostree install abrt` and restart fixes the issue.

**Expected behavior**
1. `rpm-ostree install gnome-abrt` & reboot
2. `gnome-abrt`
Runs without issues.

**OS version:**
```
State: idle
BootedDeployment:
● ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210628.0 (2021-06-28T01:11:35Z)
                BaseCommit: 4656a0db3d931b4eb79e8c423593e858e1038aaaf7dc5a518fc13b76c914434a
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: abrt gnome-abrt
             LocalPackages: rpmfusion-nonfree-release-34-1.noarch rpmfusion-free-release-34-1.noarch
```

**Additional context**
Fedora 34 Workstation does not have this issue. Explictly only installing gnome-abrt with dnf works.
Original issue: https://github.com/abrt/gnome-abrt/issues/306

**Comment by vchernin** [comment]
Apparently my testing wasn't correct. Fedora 34 Workstation does have this issue.

**Comment by Jmennius** [comment]
I believe the correct way to install abrt on Fedora is by using packages `abrt-desktop` or `abrt-cli`.
