### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#177]
---
name: Bug report
about: very slow updates
title: "[update speed never goes beyond 50~70 kb/s even if my intrnet connection can reach 1.5 mb/s] "
labels: 'server ,update ,africa'

---

**Describe the bug**
when i type sudo rpm-ostree update or try to switch to kinoite the download speed is too bad and the updates fail and when i run the command again it starts over instead of starting from where it failed in the previous transaction 

**To Reproduce**
1. (sudo rpm-ostree update) OR (sudo rpm-ostree rebase kinoite:fedora/34/x86_64/kinoite)
2. ..

**Expected behavior**
update in about 1 mb/s speed and in case of download failure start from the point where it have failed instead of starting over

**Output**
eceiving objects: 28% (6103/21770) 54.1 kB/s 112.6 MB

**OS version:**
```
BootedDeployment:
● ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210423.n.0 (2021-04-23T08:10:25Z)
                BaseCommit: 7b99463136830fd9b18f8daf5f7973f3e15eaa3532f8dbcbb4f7eb9673170461
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: lm_sensors mono-devel
             LocalPackages: rpmfusion-nonfree-release-34-1.noarch
                            rpmfusion-free-release-34-1.noarch
                    Pinned: yes

```

**Additional context**
i think adding servers nearr africa will solve half the problem

**Comment by travier** [comment]
Although it might look like the download starts from scratch as it starts from 0/XYZ again, rpm-ostree will keep already downloaded objects by default so it will resume where things were left out.

**Comment by allaeddineomc** [comment]
thanks
