### ISSUE TITLE
Silverblue 30 - Lenovo Ideapad 720s-13arr (Ryzen) - Touchpad Issue

### ISSUE THREAD

**Issue by ghost** [fedora-silverblue/issue-tracker#18]
Description:
Touchpad often not recognized upon turning on the computer.

Steps to reproduce:
Turn on the computer.

Actual Results:
localhost kernel: i2c_hid i2c-MSFT0001:00: HID over i2c has not been provided an Int IRQ
localhost kernel: i2c_hid: probe of i2c-MSFT0001:00 failed with error -22

Expected Results:
Working touchpad.

Additional information:
Restarting a few times usually solves the problem (until the computer is restarted again).
Standby mode does not affect the issue.
Touchpad works flawlessly on the latest Ubuntu and Manjaro.
I have tried playing around with "i8042.noloop i8042.nomux i8042.nopnp i8042.reset".

**Comment by tpopela** [comment]
Hi @blankdebut. Does it work in regular Fedora 30 or 31 (you can use the live DVD to try it).

**Comment by blankdebut** [comment]
Hi!
No, it doesn't. Same holds for OpenSUSE, apparently.

**Comment by whot** [comment]
fwiwl, that's a kernel issue so it'd be useful to get the kernel version on Ubuntu where it works. cc @bentiss

**Comment by blankdebut** [comment]
I'll boot up Ubuntu 19.10 and see if it works.
On Manjaro, it worked with every kernel version >=4.19.
As a side note, I rebased to Silverblue 31 earlier today; hasn't made a difference, though.

**Comment by blankdebut** [comment]
Just a short update; I used a USB stick to boot up a live image of Ubuntu 19.10 a couple of times. Running on kernel version 5.3.0. Touchpad worked fine.

**Comment by tpopela** [comment]
Fixed with kernel 5.3.
