### ISSUE TITLE
RTW88/RTW89 Drivers (COPR repo?)

### ISSUE THREAD

**Issue by heyakyra** [fedora-silverblue/issue-tracker#180]
Fedora has no support for certain Realtek cards, and the only way to get them working is to apply changes to an installed kernel which is not possible with Silverblue. 

Since these drivers are not yet shipped with the kernel, a repo with a patched kernel would allow users with these cards to connect to the internet again. See https://github.com/lwfinger/rtw89/issues/17 and https://github.com/lwfinger/rtw88 

https://bugzilla.redhat.com/show_bug.cgi?id=1980878

**Comment by damian01w** [comment]
Kernel 5.16 with support for Realtek 802.11ax WiFi Driver RT89 (rtw89) is available for F35 from koji for testing purposes. See [https://fedoraproject.org/wiki/Test_Day:2022-01-23_Kernel_5.16_Test_Week](https://fedoraproject.org/wiki/Test_Day:2022-01-23_Kernel_5.16_Test_Week) for override the stable kernel in SB until it lands on stable. Works for me on Lenovo ThinkPad T14 Gen 1 with Silverblue.

**Comment by travier** [comment]
Closing as this is likely fixed now.
