### ISSUE TITLE
Fix/reconsider rpm-ostree results visibility of available applications on Fedora Silverblue

### ISSUE THREAD

**Issue by AsciiWolf** [fedora-silverblue/issue-tracker#182]
Moving this from a downstream bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1981097

Description of problem:
When searching for applications using latest GNOME Software 40.2 on Fedora 34 Silverblue, all apps including standard (rpm-ostree) ones are displayed and it is possible to install (layer) them. Previously, on GNOME Software 40.0 (and older Silverblue / GNOME Software releases), this was not the case and only Flatpak results or already layered rpm-ostree results were displayed. I am not sure whether this is a bug (in gnome-software or rpm-ostree) or an intended design change, but please, reconsider this.

The rpm-ostree results were intentionally hidden by adding special quirk[1] because layering apps should be intended for power users and not a common practice on Silverblue and also there were/are various issues[2] happening when layering the rpm-ostree apps and I believe that many of them were still not fixed to this day.

Version-Release number of selected component (if applicable):
gnome-software-40.2-2.fc34.x86_64

How reproducible:
Every time.

Steps to Reproduce:
1. Install Fedora 34 Silverblue using latest available iso.
2. Fully update the system (using rpm-ostree) and reboot the computer.
3. Open GNOME Software and try searching for apps.

Actual results:
GNOME Software returns both Flatpak and rpm-ostree search results.

Expected results:
GNOME Software returns only a Flatpak search results. rpm-ostree results are displayed only for apps that are already installed (system or layered apps).

Additional info:
[1] https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/203
[2] https://gitlab.gnome.org/GNOME/gnome-software/-/issues/604

By the way, it may be possible that on Software 40.0, issue #181 was preventing this bug from happening, however on older Silverblue / GNOME Software releases, only the Flatpak results were also displayed, as mentioned before.

**Comment by AsciiWolf** [comment]
Additional comments from the original bz:

Daniel Rusek:
If making available apps from rpm-ostree sources displayed on Silverblue was an intended design decision, please at least consider making Flatpak sources, not rpm-ostree ones, default on Silverblue. Thanks!

(On Fedora Workstation, Flatpak sources are the default ones, however on Silverblue, rpm-ostree sources are displayed by default. There are some plans to make the RPM sources default on Fedora Workstation, it can make sense on Workstation, but on Silverblue it is the exact opposite - rpm-ostree sources of apps that are not installed should not be displayed at all or at least should not be default.)

Milan Crha:
Thanks for a bug report. While rpm-ostree and the Silverblue is related here, it is not Fedora specific and should be better fixed upstream, thus file it there, please.

With respect of the source preference, there is not code for it, as far as I know. I guess, and only guess, the preselected source is the first returning the application. Which it is depends on various circumstances. There's surely no intention to prefer rpm-ostree packages on the rpm-ostree installations. For example in my Silverblue installation, when I search for "calendar" and pick a "Planner" (which is not installed here), the Flathub source is preselected, not the RPM source.

**Comment by AsciiWolf** [comment]
Related GNOME Software Merge Request: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/689

**Comment by tpopela** [comment]
Then this should be moved back to the https://bugzilla.redhat.com/show_bug.cgi?id=1981097, where you should request the MR to be backported into GNOME Software in Fedora. Or am I missing something that can be be done on Silverblue side?

**Comment by AsciiWolf** [comment]
You are correct. I have made a [new comment](https://bugzilla.redhat.com/show_bug.cgi?id=1981097#c7) under the original bz and reopened it. I am closing this ticket.
