### ISSUE TITLE
[RFE] dnf advanced options on rpm-ostree

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#183]
---
name: Feature request
about: make rpm-ostree as advanced as dnf
title: "[RFE] "
labels: 'rpm-ostree'
assignees: ''

---

I'm always frustrated when i use rpm-ostree and find so many features of dnf missing here such as "--nogpgcheck"

it will be realy handy to add  the "--nogpgcheck" option and other dnf options that make life easyer .

a good and easyer to emplement alternative is to make it possible to register packages installed with (dnf in unlock--hotfix mod) as overlay packages so they aren't lost in every update , also adding a command  "ostree admin lock" to lock the base without having to edit the deployment config will be really cool  .

**Comment by tpopela** [comment]
Hi @allaeddineomc, can you please open an issue against https://github.com/coreos/rpm-ostree/? I can't move this issue there.

**Comment by allaeddineomc** [comment]
done https://github.com/coreos/rpm-ostree/issues/3024
