### ISSUE TITLE
[the installer shows fedora workstation logo instead of silverblue] 

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#184]
The latest iso ![IMG_20210706_125634.jpg](https://user-images.githubusercontent.com/57415185/127292887-e65034e9-ca32-4d72-aa22-822b740cfcce.jpg)

**Comment by tpopela** [comment]
I asked the Anaconda developers and we have to do the following - add Silverblue logos to fedora-logos package and then modify https://github.com/rhinstaller/anaconda/blob/master/data/profile.d/fedora-silverblue.conf#L6 to contain https://github.com/rhinstaller/anaconda/blob/master/data/profile.d/fedora-workstation.conf#L20 that will point Anaconda to the right logo.

**Comment by allaeddineomc** [comment]
nice

**Comment by Honza0297** [comment]
In Rawhide, Fedora Silverblue has the proper logo now.

**Comment by juhp** [comment]
Can confirm I see the SB logo in Fedora-Silverblue-ostree-x86_64-Rawhide-20211115.n.0.iso
