### ISSUE TITLE
[BUG] rpm-ostree install vim-default-editor fails

### ISSUE THREAD

**Issue by petersenna** [fedora-silverblue/issue-tracker#185]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
Can't make vim the default editor by installing vim-default-editor

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. sudo rpm-ostree install vim-default-editor

**Expected behavior**
vim-default-editor gets installed

**Screenshots**
[root@fedora ~]# rpm-ostree install vim-default-editor
Checking out tree 8f26c8d... done
Enabled rpm-md repositories: updates google-chrome fedora-cisco-openh264 fedora updates-archive
Importing rpm-md... done
rpm-md repo 'updates' (cached); generated: 2021-07-30T00:53:40Z solvables: 16370
rpm-md repo 'google-chrome' (cached); generated: 2021-07-29T21:35:43Z solvables: 3
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2021-02-23T00:49:00Z solvables: 4
rpm-md repo 'fedora' (cached); generated: 2021-04-23T10:47:57Z solvables: 63586
rpm-md repo 'updates-archive' (cached); generated: 2021-07-30T02:05:15Z solvables: 22271
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.3223-1.fc34.noarch
  - package vim-default-editor-2:8.2.3223-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2637-1.fc34.noarch
  - package vim-default-editor-2:8.2.2637-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2787-1.fc34.noarch
  - package vim-default-editor-2:8.2.2787-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2811-1.fc34.noarch
  - package vim-default-editor-2:8.2.2811-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2825-1.fc34.noarch
  - package vim-default-editor-2:8.2.2825-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2846-1.fc34.noarch
  - package vim-default-editor-2:8.2.2846-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2875-1.fc34.noarch
  - package vim-default-editor-2:8.2.2875-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2879-1.fc34.noarch
  - package vim-default-editor-2:8.2.2879-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2932-1.fc34.noarch
  - package vim-default-editor-2:8.2.2932-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2956-1.fc34.noarch
  - package vim-default-editor-2:8.2.2956-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.2956-2.fc34.noarch
  - package vim-default-editor-2:8.2.2956-2.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.3046-1.fc34.noarch
  - package vim-default-editor-2:8.2.3046-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.3070-1.fc34.noarch
  - package vim-default-editor-2:8.2.3070-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.3154-1.fc34.noarch
  - package vim-default-editor-2:8.2.3154-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch
  - package nano-default-editor-5.8-3.fc34.noarch conflicts with system-default-editor provided by vim-default-editor-2:8.2.3182-1.fc34.noarch
  - package vim-default-editor-2:8.2.3182-1.fc34.noarch conflicts with system-default-editor provided by nano-default-editor-5.8-3.fc34.noarch

**OS version:**
Fedora Silverblue 34

Please replace this line with output of `rpm-ostree status -b`
State: idle
BootedDeployment:
● fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210730.0 (2021-07-30T00:43:17Z)
                BaseCommit: 8f26c8d1a6fabfc7ec38a852e31ae54bfc28e1cbc6df87d99dd965960e54166e
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: cronie
             LocalPackages: google-chrome-stable-92.0.4515.107-1.x86_64

**Comment by LorbusChris** [comment]
Does `rpm-ostree override remove nano-default-editor --install vim-default-editor` work?

**Comment by petersenna** [comment]
@LorbusChris works like a charm! Thanks a lot!

```
rpm-ostree override remove nano-default-editor --install vim-default-editor
Checking out tree 8f26c8d... done
Enabled rpm-md repositories: updates google-chrome fedora-cisco-openh264 fedora updates-archive
Importing rpm-md... done
rpm-md repo 'updates' (cached); generated: 2021-07-30T00:53:40Z solvables: 16370
rpm-md repo 'google-chrome' (cached); generated: 2021-07-29T21:35:43Z solvables: 3
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2021-02-23T00:49:00Z solvables: 4
rpm-md repo 'fedora' (cached); generated: 2021-04-23T10:47:57Z solvables: 63586
rpm-md repo 'updates-archive' (cached); generated: 2021-07-30T02:05:15Z solvables: 22271
Resolving dependencies... done
Will download: 1 package (21.5 kB)
Downloading from 'updates'... done
Importing packages... done
Applying 1 override and 11 overlays
Processing packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
Writing OSTree commit... done
Staging deployment... done
Freed: 55.3 MB (pkgcache branches: 0)
Removed:
  nano-default-editor-5.8-3.fc34.noarch
Added:
  vim-default-editor-2:8.2.3223-1.fc34.noarch
Use "rpm-ostree override reset" to undo overrides
Run "systemctl reboot" to start a reboot
```
