### ISSUE TITLE
Gnome Boxes cannot capture super key, function keys in Silverblue 34

### ISSUE THREAD

**Issue by Pinjontall94** [fedora-silverblue/issue-tracker#186]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
When trying to use a guest session in Gnome Boxes, silverblue will not release the super key, nor the function keys, so doing things like launching a start menu, or adjusting audio levels in the guest OS now require a mouse.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install gnome boxes, either as a flatpak or layered rpm (bug is present in both).
2. Install an OS as a guest session.
3. Boot the guest session & press the super key, after confirming the keyboard has otherwise been captured by the guest session.

**Expected behavior**
One should be able to use all parts of the keyboard in the guest session (as it worked in Fedora Workstation), save for the specified capture sequence.

**Screenshots**
![Screenshot from 2021-08-12 19-14-17](https://user-images.githubusercontent.com/25357545/129295599-89f27abf-e4f7-40f9-b610-5ba89aec7dff.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210811.0 (2021-08-11T00:46:17Z)
                BaseCommit: a7384d537abbac128a75fa1167a85f7d1d50894abcd111929e80123c27a0085a
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: qt zsh openssl gnome-tweaks neofetch
                            fedora-workstation-repositories mozilla-openh264 gnome-boxes
             LocalPackages: rpmfusion-nonfree-release-34-1.noarch
                            google-chrome-stable-91.0.4472.114-1.x86_64
                            rpmfusion-free-release-34-1.noarch
                            microsoft-edge-dev-93.0.926.1-1.x86_64
```

**Comment by felipeborges** [comment]
Is this a Wayland or X11 session?

Were you prompted to authorize inhibiting shortcuts? 
![Screenshot from 2021-08-16 13-46-25](https://user-images.githubusercontent.com/365434/129558843-8d703733-e051-4236-9a7d-526a2cda66a7.png)

**Comment by Pinjontall94** [comment]
On the host session? Should be Wayland, since I didn't change SB34 from the default. And no, I've never been prompted for the inhibiting shortcuts on SB, which I thought was odd. I've used boxes on F33/Wayland, and that never had this issue. Odd...

**Comment by travier** [comment]
Is this still an issue?

**Comment by travier** [comment]
Fedora 36 is about to go EOL so I'll close this issue. Please provide updated information if this is still an issue.
