### ISSUE TITLE
[BUG] Can't enabled third party repositories in Silverblue

### ISSUE THREAD

**Issue by xerxes1511** [fedora-silverblue/issue-tracker#187]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
after a long time i installed silverblue again.  I wanted to activate the third party repository in gnome software like in silverblue 33 but it is not displayed?  I can activate it in the workstation.
**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. .. open gnome Software
2. .. the third party repository (chrome repository) is no longer displayed if you want to activate it.

**Expected behavior**
I would like to install chrome again

**OS version:**
```
Fedora silverblue 34
```

**Comment by TheOneandOnlyJakfrost** [comment]
In the Gnome Software options panel you can select Software Repositories, where you can enable or disable individual repositories such as Google Chrome.

**Comment by tpopela** [comment]
Yes, it works in Workstation, but doesn't in Silverblue due to some limitations (you have to manually install the fedora-workstation-repositories package). The whole process was reworked for the F35 so it should work in Silverblue out of the box as well.
