### ISSUE TITLE
[BUG] snapd

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#188]
**Describe the bug**
snapd installs and snap packages install normally but doesn't start

**To Reproduce**
1. #rpm-ostree install snapd
2. snap install "anything"
3. try to launch the snap from the icon

**Expected behavior**
the app launches like a normal slow snap

**OS version:**
```
`Version: 34.20210817.0 (2021-08-17T00:48:48Z)`
```

**Comment by TheOneandOnlyJakfrost** [comment]
I'm not certain this is a bug per se, as snap needs to write to a location that exists in the immutable portion of Silverblue, and it also wants to modify top level directories in the system which is against rpm-ostree expectations. There is an issue [ Make it easier to link in or bind folders to root directory? #1711](https://github.com/coreos/rpm-ostree/issues/1711) that would seem to be related to this.

**Comment by allaeddineomc** [comment]
yes it seems to be the problem , snap is a mess anyway
