### ISSUE TITLE
Silverblue 31: "failed to obtain lock 'metadata': Creation of file "/var/run/dnf-metadata.lock.XXXXXX" failed: Permission denied

### ISSUE THREAD

**Issue by maddovr** [fedora-silverblue/issue-tracker#19]
Fresh install of Silverblue 31 with just third party repos, rpmfusion and cisco repos enabled, no packages installed yet. GNOME software fails to find any updates and I tried both `rpm-ostree cleanup -m` and `sudo ostree fsck` `sudo ostree admin cleanup`, but nothing works. `rpm-ostree` works as intended from command line.

**Comment by tpopela** [comment]
That's https://gitlab.gnome.org/GNOME/gnome-software/issues/710

**Comment by tpopela** [comment]
Closing as the discussion was moved to an upstream bug.
