### ISSUE TITLE
[RFE] better flatpak integration 

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#190]
it wold be great to integrate flatpak permissions to gnome control center like ubuntu is doing with snaps , it will make the experience more polished than having to install flatseal , also integrating gtk themes by default wold be great since a lot of users aren't using adwaita anyway and a lot of them don't know how to do overrides

**Comment by TheOneandOnlyJakfrost** [comment]
What is Gnome Control Center? Do you mean settings? That would be a Gnome specific issue or RFE in this case, as would the them overrides, and should be filed at [Gnome Issue Tracker](https://gitlab.gnome.org/groups/GNOME/-/issues)

**Comment by allaeddineomc** [comment]
by the overrides i meant a global override which is unrelated to neither the gnome project or flatpak project , just to have theming working by default 
to achieve this just put this file '' /ostree/deploy/fedora/var/lib/flatpak/overrides/global '' that contains this line  " filesystems=~/.themes;~/.local/share/themes; " by default in the iso

**Comment by tpopela** [comment]
For the flatpaked applications permissions you can use the Applications panel in the GNOME Control Center (aka Settings). If you would like to see more things added there, then you should go to upstream and open the ticket there as @TheOneandOnlyJakfrost is suggesting. When you open the issue, please put the link there for the reference.

**Comment by felipeborges** [comment]
Something in these lines has been proposed at https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1411 Let's continue the conversation over there upstream.

**Comment by tpopela** [comment]
Thank you @felipeborges !
