### ISSUE TITLE
[BUG] Silverblue uses systemd-resolved in foreign mode by default instead of stub mode

### ISSUE THREAD

**Issue by xscd** [fedora-silverblue/issue-tracker#192]
**Describe the bug**
Silverblue uses systemd-resolved in foreign mode by default instead of stub mode

**To Reproduce**
1. Download and install the latest Silverblue ISO (https://silverblue.fedoraproject.org/download)
2. Fire up a terminal and type "resolvectl status"
![Screenshot from 2021-08-24 12-24-50](https://user-images.githubusercontent.com/46658470/130592647-d1e4b417-9682-4283-8e22-4367f223d06b.png)

**Expected behavior**
Should use stub mode same like Fedora Workstation (https://fedoraproject.org/wiki/Changes/systemd-resolved)
![Screenshot from 2021-08-24 12-26-08](https://user-images.githubusercontent.com/46658470/130592899-24831e30-6e69-4097-82e6-6b92532f2503.png)

**Screenshots**
Added above (First screenshot is Silverblue, Second is Workstation) 

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210823.0 (2021-08-23T00:59:35Z)
                    Commit: 82bbbd297940cd57c7765e4fe43bc9553affa7eb962cf055c6c64d1a2ac31401
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39

```

**Additional context**
https://matrix.to/#/!SmxNkRyYfaSczVlhFH:matrix.org/$OKvnMwUxFZDdPgDYKFMKGqBIwD0P0YEWETKrrJHfMNw?via=matrix.org&via=libera.chat

**Comment by xscd** [comment]
Probably related:
https://github.com/coreos/fedora-coreos-tracker/issues/646#issuecomment-747471353
https://github.com/coreos/fedora-coreos-tracker/issues/834#issuecomment-880357903

**Comment by mcatanzaro** [comment]
Sounds like /etc/resolv.conf is not properly symlinked to /run/systemd/resolve/stub-resolv.conf, which would cause systemd-resolved to enter foreign mode. This is supposed to be handled by systemd RPM scriptlets, but I understand those don't generally work in Silverblue, since they only run when creating the ostree image and not on the client machine.

**Comment by tpopela** [comment]
So that would mean that everyone running Silverblue has the broken configuration (I can actually confirm that /etc/resolv.conf is a file on my machine and not a link). @dustymabe any idea about how to address this?

**Comment by mcatanzaro** [comment]
> This is supposed to be handled by systemd RPM scriptlets, but I understand those don't generally work in Silverblue, since they only run when creating the ostree image and not on the client machine.

No telling what else is broken due to RPM scriptlets that expect to be able to touch /etc and /var. Probably a lot. :)

**Comment by dustymabe** [comment]
Is this an issue only on upgraded systems? my F33 SB system (yes, I know it's old and will be re-installed with F35 soon) has the link in place properly:

```
[dustymabe@hattop pass]$ ls -l /etc/resolv.conf 
lrwxrwxrwx. 1 root root 39 Jul 23 09:29 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
```

**Comment by tpopela** [comment]
@dustymabe yes, probably the upgraded systems (this one is upgraded from F31 I think).

**Comment by cgwalters** [comment]
I suspect there is indeed hysteresis (i.e. dependency on the provisioning time) because in older Fedora I believe Anaconda would write out `/etc/resolv.conf` or so, and then the difference between yum and rpm-ostree based upgrades is that it can't be silently changed in `%post`.  If we did want to make that change, it'd need instead to be a systemd unit.

Similar discussion in https://bugzilla.redhat.com/show_bug.cgi?id=1994830#c2

**Comment by 1player** [comment]
> Is this an issue only on upgraded systems? my F33 SB system (yes, I know it's old and will be re-installed with F35 soon) has the link in place properly:

No, I can see the issue on a freshly installed Kinoite, and I have third-party confirmation it's the same on a fresh Silverblue. `/etc/resolv.conf` is a regular file instead of being a symlink to the stub file.

**Comment by tpopela** [comment]
On a freshly installed Silverblue 35:
```
$ file /etc/resolv.conf
/etc/resolv.conf: symbolic link to ../run/systemd/resolve/stub-resolv.conf
```

**Comment by 1player** [comment]
I have literally now just installed Fedora Silverblue 35 in a virtual machine with virt-manager from the ISO `Fedora-Silverblue-ostree-x86_64-35-1.2.iso` with md5sum `af96732f82013274dcb92c5215f3680c`, rebooted, and:

```
[sph@fedora ~]$ ls -l /etc/resolv.conf
-rw-r--r--. 1 root root 55 Nov 15 13:28 /etc/resolv.conf
```

**Comment by tpopela** [comment]
I don't recall the exact version, but it was one of the latest ISOs before the F35 GA. The difference here on my side is that I installed it on bare metal and not in a VM.

**Comment by maxamillion** [comment]
@1player I'm seeing the same thing you are with a fresh install using the Fedora Silverblue 35 GA image. I installed on bare metal on a laptop.

**Comment by dustymabe** [comment]
theory: maybe if you have internet access during the anaconda install the `resolve.conf` gets populated somehow. If you don't (i.e. your laptop wifi isn't connected and no wired connection) maybe it doesn't, which could lead to the different experiences.

**Comment by tpopela** [comment]
I definitely wasn't connected to the Internet when doing the installation - so it might be plausible what you're saying Dusty.

**Comment by xscd** [comment]
I made an offline installation (flatpak gnome boxes without network access) and the issue still exists. So don't think its related to having connection while installation.

**Comment by Mershl** [comment]
Upgraded system SB32->SB33->SB34->SB35 also shows foreign mode with /etc/resolv.conf being an actual file. Do we already have an recommended workaround to clean this up manually?

**Comment by 1player** [comment]
You can fix it by removing /etc/resolv.conf and recreating the symbolic link:

```
ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf 
```

**Comment by tpopela** [comment]
Looks like there might be a fix for this - see https://bugzilla.redhat.com/show_bug.cgi?id=2032085

**Comment by rowbawts** [comment]
Is there a planned solution to fix this without manual intervention other than a clean install?

**Comment by juhp** [comment]
According to the above bug, this has been addressed also in f36 anaconda now recently (stable last week).
Good if more people could confirm if that is the case I suppose.

**Comment by travier** [comment]
Closing as this is now likely fixed.
