### ISSUE TITLE
[question] is it possible to install and boot arch in the same partition as silverblue as an ostree deployment ?

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#193]
is it possible to install and boot arch linux in the same partition as silverblue as an ostree deployment ? and if it's possible how can i do it ?

**Comment by tpopela** [comment]
Please, raise the question on https://discussion.fedoraproject.org/c/desktop/silverblue/6 as I think that you will probably get the answer there. Once you will open the question, please put the link here for the reference.
