### ISSUE TITLE
[RFE] Remove Qgnomeplatform and Qt libraries from the base ostree image

### ISSUE THREAD

**Issue by akarshanbiswas** [fedora-silverblue/issue-tracker#194]
As Fedora Silverblue generally uses flatpaks for application installation, the libraries or the dependencies needed by any application is already provided in the flatpak runtime. There is no need to ship qgnomeplatform or Qt libraries in the base ostree image since it won't be used by any application.

I hope the answer to this [question](https://pagure.io/workstation-ostree-config/blob/main/f/fedora-silverblue.yaml#_12) is provided now.

**Comment by grulja** [comment]
While this is true for apps shipped as flatpaks, there are still majority of KDE and Qt apps we don't ship as flatpaks in Fedora yet and the only way to get them is to install them as regular RPMs. Removing QGnomePlatform from the base we would lose all the integration we can have for Qt apps with GNOME desktop.

**Comment by akarshanbiswas** [comment]
@grulja Shouldn't installing those apps as regular rpms or "package layering" pull in the required dependencies?

**Comment by travier** [comment]
AFAIK it's not directly a dependency as it depends on the desktop environment that is currently used, thus would but unnecessary on KDE Plasma for example.

**Comment by akarshanbiswas** [comment]
In that case let the user installs qgnomeplatform along with the app. A wiki explaining what the package does will be helpful. Though I seriously doubt anyone would install it.
If a KDE/Qt app isn't found in Fedora flatpak repositories, user will look at flathub next. There is also a [dedicated](https://distribute.kde.org/kdeapps.flatpakrepo) KDE flatpak repository for user to enable it on their Silverblue install..

**Comment by travier** [comment]
> In that case let the user installs qgnomeplatform along with the app. A wiki explaining what the package does will be helpful. Though I seriously doubt anyone would install it.

I agree it's somewhat of an edge case but would make a really poor user experience, and hard to figure out, understand or explain from the user point of view.

> If a KDE/Qt app isn't found in Fedora flatpak repositories, user will look at flathub next. There is also a [dedicated](https://distribute.kde.org/kdeapps.flatpakrepo) KDE flatpak repository for user to enable it on their Silverblue install..

This repo is mostly for testing. Stable and tested KDE apps are available preferably on Flathub but a lot are still missing.

**Comment by travier** [comment]
How big is this package? Would it really make a difference?

**Comment by akarshanbiswas** [comment]
> How big is this package? Would it really make a difference?

This package is mostly Qt theme integration with gnome(?). It seems to pull in all the Qt libraries as its dependencies.

As a regular Fedora Silverblue user, in my opinion, gnome-tweaks app is a much better candidate to be included than this package, not just in case of theming, but for other tweaks as well.

**Comment by grulja** [comment]
QGnomePlatform requires qt5-qtbase, qt5-qtwayland and adwaita-qt, which additionally requires qt5-qtx11extras. It definitely doesn't pull in all the Qt libraries.

**Comment by travier** [comment]
> As a regular Fedora Silverblue user, in my opinion, gnome-tweaks app is a much better candidate to be included than this package, not just in case of theming, but for other tweaks as well.

Please file a distinct issue if you think a specific package should be included in Silverblue.

**Comment by tpopela** [comment]
> > As a regular Fedora Silverblue user, in my opinion, gnome-tweaks app is a much better candidate to be included than this package, not just in case of theming, but for other tweaks as well.
> 
> Please file a distinct issue if you think a specific package should be included in Silverblue.

I will just add that we are trying to follow up the same defaults as on Fedora Workstation - so if you want to include something that is not presented even in Workstation, then please open an issue in https://pagure.io/fedora-workstation/issues.

**Comment by akarshanbiswas** [comment]
> I will just add that we are trying to follow up the same defaults as on Fedora Workstation - so if you want to include something that is not presented even in Workstation, then please open an issue in https://pagure.io/fedora-workstation/issues.

I see. Okay.

**Comment by travier** [comment]
Quick check show that this would only get us 73MB back:

```
$ du -shc $(rpm -ql $(rpm -qa | grep qt) qgnomeplatform-qt5-0.8.4-11.fc36.x86_64)
...
73M     total
```

Closing as we follow Workstation and the issue should be discussed there as mentioned above.

**Comment by travier** [comment]
Related post: https://jgrulich.cz/2023/03/08/explained-qgnomeplatform-and-adwaita-qt/
