### ISSUE TITLE
[BUG] skipping boot menu directly to plymouth 

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#195]
**Describe the bug**
the system boots directly without showing boot options after update

**To Reproduce**
1. sudo rpm-ostree update
2. reboot

**Expected behavior**
shows grub menu 

**OS version:**
```
34.20210827.0
```

**Comment by tpopela** [comment]
That's expected and intended, please see https://fedoraproject.org/wiki/Changes/FlickerFreeBoot.
