### ISSUE TITLE
[RFE] grub fix tool

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#196]
i had a bug in grub and i was fixing it , while doing so i bricked the bootloader and it stopped booting with the error message " linux16 command not found " there is only one guide online and it didn't worked , i fixed grub by copying all the contents of /root to / than copying all the contents of one of the deployments i had to / so i had a normal root file system , i ran the grub2 mkconfig thing and rebooted and it worked , figuring all of this and doing it took me more than an hoer , it will be great if you create a script or a detailed guide for fixing grub to save people from falling in the same problem , a script will be better because not everyone knows can follow a guide .

**Comment by tpopela** [comment]
This isn't specific to Silverblue at all. You might want to look in https://docs.fedoraproject.org/en-US/quick-docs/. If there won't be anything, please open the issue in https://pagure.io/fedora-docs/quick-docs or even better provide the patch. When you open the issue or find the relevant section in the existing documentation, please put the link here.

**Comment by allaeddineomc** [comment]
it's specific to fedora silverblue , all other distros can be repaired with the traditional way , it happens only on silverblue because of the unusual filesystem structure when the systm isn't booted

**Comment by tpopela** [comment]
If it's related to Silveblue only, then feel free to add an item to https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/ through https://github.com/fedora-silverblue/silverblue-docs/edit/master/modules/ROOT/pages/troubleshooting.adoc
