### ISSUE TITLE
[BUG] System wedged on refresh-md when wireguard auto-connects

### ISSUE THREAD

**Issue by heyakyra** [fedora-silverblue/issue-tracker#198]
**Describe the bug**
On a Fedora Silverblue 34 system, it has become wedged and unable to cancel a refresh-md.  

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. [Enable Wireguard in NetworkManager](https://fedoramagazine.org/configure-wireguard-vpns-with-networkmanager/) (maybe using [MozWire](https://github.com/NilsIrl/MozWire) and then `nmcli con import type wireguard file /etc/wireguard/us4-wireguard.conf`)
1. Boot system [with no internet access?]
2. Run an `rpm-ostree` command requiring sysroot lock (in my case `usroverlay` or `rollback`)
3. Wait forever to see `Waiting for sysroot lock...` repeated infinitely
4. Instead try `rpm-ostree cancel` and see `Cancelling transaction: refresh-md` is stuck forever
5. Disable the auto-connect with `nmcli con delete us4-wirueguard` + `systemctl reboot` or temporarily unwedge the system with `wg-quick down us4-wireguard`

**Expected behavior**
`refresh-md` fails with a reasonable timeout, and/or `rpm-ostree cancel` command works

**Screenshots**

**OS version:**
```
fedora:fedora/34/x86_64/silverblue
```

**Additional context**
This was confusing when I needed to enable my https://github.com/lwfinger/rtw89 wifi drivers since I was stuck without internet and unable to `cancel` or `rollback` or anything needed to get it

**Comment by travier** [comment]
Could you report that upstream to rpm-ostree? Thanks

**Comment by heyakyra** [comment]
Done https://github.com/coreos/rpm-ostree/issues/3117
