### ISSUE TITLE
[RFE] flipping the way it updates 

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#199]
the current way fedora silverblue updates itself is by downloading packages and installing them into a new deployment that the user can reboot into , i was thinking about what would happen if we change it to install the updates to the booted deployment and put it in entry 0 while it still booted and create a copy of it before the update and put it to deployment 1 , i think this will have no drawbacks and it will make it possible for the users to update without having to restart their systems just like in fedora workstation

**Comment by travier** [comment]
Well, the general idea behind rpm-ostree is that you update atomically from a version to the other and are not using a live-modified system. If you want to apply an update live, you can use the experimental `rpm-ostree ex apply-live` command or install packages with `rpm-ostree install --apply-live foo`.
