### ISSUE TITLE
Can't update from F30 to F31 using GNOME Software

### ISSUE THREAD

**Issue by Zlopez** [fedora-silverblue/issue-tracker#20]
I have a VM running Fedora Silverblue 30 and I wanted to update it to F31 using GNOME Software, but I got the following error.
![Screenshot from 2019-11-05 12-27-47](https://user-images.githubusercontent.com/6943409/68204195-c2020d80-ffc7-11e9-8cc8-04fc8101d009.png)

Here is the output of `rpm-ostree status`:
```
[zlopez@silverblue30 ~]$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora-30:fedora/30/x86_64/silverblue
                   Version: 30.20191105.0 (2019-11-05T02:10:03Z)
                    Commit: 46f37c3330bb2a356fa1a231df4b9fb1d8020877f7758e166d41003ea5000877
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9

  ostree://fedora-30:fedora/30/x86_64/silverblue
                   Version: 30.1.2 (2019-04-25T23:13:10Z)
                    Commit: 982faf58087c9d020780b829d5f24b4e78bd40399b4e4769fc8bc2df9890e301
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
```

**Comment by tpopela** [comment]
It's sadly a recurring problem:

https://discussion.fedoraproject.org/t/unable-to-update-gpg-signatures-found-but-none-are-in-trusted-keyring/2703

https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2018-October/msg00011.html

Hopefully Colin, Dusty or Micah will have an idea..

**Comment by jlebon** [comment]
The remote configuration likely is pointing only at the f30 key for GPG verification. We now ship a remote config file containing the correct settings. Make sure that you have `/etc/ostree/remotes.d/fedora.conf` and that it is unmodified (`sudo cp {/usr,}/etc/ostree/remotes.d/fedora.conf`).

Then if you're already on the `fedora` remote, you should be able to update to f31. Otherwise, you'll need to run `rpm-ostree rebase fedora:fedora/31/x86_64/silverblue` manually so you switch remotes.

**Comment by Zlopez** [comment]
@jlebon I tried to copy the `fedora.conf` (which should be unmodified, because this is a clean VM installation), but without success. I'm still getting the error in GNOME Software.

I know about the manual switch of the remote, I even wrote [article](https://fedoramagazine.org/how-to-rebase-to-fedora-30-beta-on-silverblue/) about this in the past, but I wanted to try it without terminal and it failed.

FYI: My guide is still working, you just need to change `fedora-workstation` to `fedora`. I want to write updated guide for updating from F30 to F31 for the Fedora Magazine. There is a [proposal](https://pagure.io/fedora-magazine-proposals/issue/30) for this article.

**Comment by jlebon** [comment]
> I know about the manual switch of the remote, I even wrote article about this in the past, but I wanted to try it without terminal and it failed.

AFAIK, g-s only knows how to rebase between branches on the same remote, not change remotes entirely. So if you're currently on a custom `fedora-30` remote, g-s will stay there.

> this is a clean VM installation

Hmm interesting. How did you end up on the `fedora-30` remote? The default now should be the `fedora` remote. Though... that change *might* have happened after the f30 install media was created?

**Comment by Zlopez** [comment]
> Hmm interesting. How did you end up on the `fedora-30` remote? The default now should be the `fedora` remote. Though... that change _might_ have happened after the f30 install media was created?

I used the Fedora 30 Silverblue image proposed by GNOME Boxes

**Comment by jlebon** [comment]
https://gitlab.com/libosinfo/osinfo-db/merge_requests/53

**Comment by Zlopez** [comment]
I tried one more thing, I rebased to fedora remote using `rpm-ostree rebase fedora:fedora/30/x86_64/silverblue` and tried the update again using GNOME Software, but after restart I ended up in the F30 instead of F31.

Is this issue with GNOME Software or did I miss something?

**Comment by jlebon** [comment]
> Is this issue with GNOME Software or did I miss something?

So just very quickly browsing [the g-s code](https://gitlab.gnome.org/GNOME/gnome-software/blob/03c18196882844d74dba9c03cb0010b090bf7a9f/plugins/rpm-ostree/gs-plugin-rpm-ostree.c#L1389), it seems like it does know how to download upgrades to new versions. But I don't see the corresponding code for deploying it from cache afterwards. @kalev or @matthiasclasen would know better.

**Comment by Zlopez** [comment]
This is now a blocker for publishing [Fedora Silverblue update article](https://teams.fedoraproject.org/project/asamalik-fedora-magazine/us/105).

**Comment by jlebon** [comment]
I'm not sure I follow. What's the blocker? Does `rpm-ostree rebase fedora:fedora/31/x86_64/silverblue` not work?

**Comment by Zlopez** [comment]
Yes, but the preferred way on Silverblue should be through GNOME Software, which is the first mentioned in the article. This is why the article is currently on hold.

**Comment by jlebon** [comment]
AFAIK, that's the status quo and not a regression. See e.g. https://docs.fedoraproject.org/en-US/fedora-silverblue/updates-upgrades-rollbacks/#upgrading.

**Comment by Zlopez** [comment]
I'm still confused who is the primary audience for Silverblue? I think of it as an OS targeting common users, who are used to control most of the OS through GUI.

**Comment by AsciiWolf** [comment]
Hmm, I also had the impression that Silverblue is/should be targeting more common users, not just geeks who know or want to use terminal for basic tasks. On the other hand, if this is not going to be supported, why is GNOME Software offering the upgrade? I really wonder what is the plan here.

**Comment by tpopela** [comment]
@AsciiWolf and @Zlopez you are right with the target audition. If something doesn't work in GNOME Software, please open an issue in https://gitlab.gnome.org/GNOME/gnome-software/issues and I will talk to Kalev or Richard to get it fixed.

**Comment by Zlopez** [comment]
Issue created here https://gitlab.gnome.org/GNOME/gnome-software/issues/857

**Comment by tpopela** [comment]
Closing as the upstream issue was fixed.
