### ISSUE TITLE
[BUG] Installed PackageKit causing long time to confirmation dialog on reboot/shutdown/logout

### ISSUE THREAD

**Issue by shdwchn10** [fedora-silverblue/issue-tracker#203]
**Describe the bug**
I installed `cockpit` on clean Fedora Silverblue 34 in KVM. `cockpit` has dependency `cockpit-packagekit` which depend on `PackageKit`. After `cockpit` installation it takes ~20sec before shutdown confirmation dialog.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install `cockpit` or just `PackageKit`
2. Reboot
3. Try to shutdown from GNOME Shell panel

**Expected behavior**
zero delay before confirmation dialog

**OS version:**
```
34.20210920.0
```

**Additional context**
Looks similar to #189

**Comment by shdwchn10** [comment]
Errors in journal after trying to shutdown with PackageKit installed:
```
Sep 20 10:55:20 localhost gnome-shell[4335]: Ignored exception from dbus method: Gio.IOErrorEnum: Timeout was reached
Sep 20 10:55:20 localhost gnome-shell[4335]: Failed to get update info from PackageKit: Timeout was reached
Sep 20 10:55:20 localhost gnome-shell[4335]: endSessionDialog: No XDG_SESSION_ID, fetched from logind: 3
```

**Comment by shdwchn10** [comment]
Fedora Workstation 34 doesn't affected. (tested in KVM)

**Comment by travier** [comment]
PackageKit will not really work on Silverblue. [cockpit-packagekit](https://src.fedoraproject.org/rpms/cockpit/blob/f34/f/cockpit.spec#_149) is a recommend for cockpit. Are you sure you did not explicitly installed it?

**Comment by travier** [comment]
`rpm-ostree status| output would help here.

**Comment by shdwchn10** [comment]
@travier 
```
[shdwchn10@fedora ~]$ rpm-ostree status
State: idle
Deployments:
● fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210920.0 (2021-09-20T13:30:10Z)
                BaseCommit: 3bfa46fe1ec7116679e6c69bf0fd2d5d5b9d203e387b2a663a7b4de28bf95565
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: cockpit
```

**Comment by travier** [comment]
`rpm -qa | grep cockpit` and `rpm -qa | grep Package` then :)

**Comment by shdwchn10** [comment]
```
[shdwchn10@fedora ~]$ rpm -qa | grep cockpit
cockpit-bridge-250-1.fc34.x86_64
cockpit-system-250-1.fc34.noarch
cockpit-ws-250-1.fc34.x86_64
cockpit-networkmanager-250-1.fc34.noarch
cockpit-storaged-250-1.fc34.noarch
cockpit-packagekit-250-1.fc34.noarch
cockpit-250-1.fc34.x86_64
```

```
[shdwchn10@fedora ~]$ rpm -qa | grep Package
PackageKit-glib-1.2.4-2.fc34.x86_64
PackageKit-1.2.4-2.fc34.x86_64
```

**Comment by shdwchn10** [comment]
@travier do I have to provide any other info or output?

**Comment by travier** [comment]
This is an, issue in GNOME Software which requires `PackageKit-glib` for an unknown reason, even on Silverblue:
```
$ rpm -q --requires gnome-software | grep packagekit
libpackagekit-glib2.so.18()(64bit)
```

**Comment by travier** [comment]
I've reported that as https://bugzilla.redhat.com/show_bug.cgi?id=2008154

**Comment by shdwchn10** [comment]
Thanks! https://bugzilla.redhat.com/show_bug.cgi?id=2008154 was resolved, but now I can see that `guestfs-tools` package causes same issue when cockpit installed on Fedora Silverblue: https://bugzilla.redhat.com/show_bug.cgi?id=2086302

**Comment by tpopela** [comment]
Thank you for the heads-up @shdwchn10 ! I see that it has been already resolved.
