### ISSUE TITLE
[BUG] Grub error `/grub2/fonts/unicode.pf2' not found when using gfxterm console

### ISSUE THREAD

**Issue by pauldoo** [fedora-silverblue/issue-tracker#204]
## Description

On my Lenovo E595 the grub `console` output mode is very slow and laggy, so I have to set the console mode to `gfxterm` instead.  This makes the grub menus nice and snappy, but unfortunately results in an error being very briefly displayed on the screen before the grub menu appears.

## How to reproduce

1. Edit `/etc/default/grub` and set `GRUB_TERMINAL_OUTPUT` to `gfxterm` (default value is `console`).
2. Apply changes: `sudo grub2-mkconfig -o /etc/grub2-efi.cfg`
3. Reboot.
4. Observe the following error very briefly displayed before the grub menu appears.

```
error: ../../grub-core/fs/fshelp.c:257:file `/grub2/fonts/unicode.pf2' not found.
```

## Expected behaviour

Setting `GRUB_TERMINAL_OUTPUT` to `gfxterm` should not result in errors being displayed before the grub menu appears.

## OS Version

```
> rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210923.0 (2021-09-23T19:02:00Z)
                BaseCommit: 4547905b37f46a790a810248c13ce718e4c42cdbf6f1bff38a311d1503543dfa
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: virt-manager rpmfusion-nonfree-release snapper virt-viewer bcache-tools google-chrome-stable fish ffmpeg
                            fedora-workstation-repositories acpica-tools rpmfusion-free-release
```

## Additional context

```
> cat /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
#GRUB_TERMINAL_OUTPUT="console"
GRUB_TERMINAL_OUTPUT="gfxterm"
GRUB_CMDLINE_LINUX="rd.luks.uuid=luks-0c755fd5-99d6-4578-bb46-328eb72fd038 rd.lvm.lv=vg0/root rhgb quiet"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG=true
```

Also reported here: https://discussion.fedoraproject.org/t/grub2-fonts-unicode-pf2-not-found-error-before-grub-menu-appears/33290/3

**Comment by pauldoo** [comment]
```
> sudo find /boot/grub2
/boot/grub2
/boot/grub2/grub.cfg
/boot/grub2/grubenv
```

**Comment by juhp** [comment]
If it is not silverblue specfic, you might get a quicker answer by opening a grub2 bug in bugzilla.

**Comment by travier** [comment]
Fedora 34 is now EOL. Can you reproduce that on a newer version?

**Comment by travier** [comment]
Fedora 34 is now EOL and the font is bundled into the GRUB binary on newer releases for Secure Boot. Closing.
