### ISSUE TITLE
rpm-ostree refresh metadata

### ISSUE THREAD

**Issue by xerxes1511** [fedora-silverblue/issue-tracker#205]
can I use this command rpm-ostree refresh-md --force and then rpm-ostree upgrade.  I can't find anything in the rpm-ostree documentation

I installed chrome-unstable and it gets updates more often.  The problem is that the repo metadata is not updated that often, so I have to recreate the repo metadata so that the update is displayed

**Comment by travier** [comment]
Answered at: https://discussion.fedoraproject.org/t/refresh-rpm-metadata/33294

**Comment by xerxes1511** [comment]
I wanted to know I can also use rpm-ostree refresh-md - force because otherwise I have to use 3 commands to upgrade

**Comment by HarryMichal** [comment]
Hi @xerxes1511! I believe this report should be either closed despite the suggested workflow being a bit less convenient or at least moved [upstream](https://github.com/coreos/rpm-ostree) where it could be made a bit more actionable than here. Cheers!

**Comment by travier** [comment]
This is probably best reported to rpm-ostree if this is still an issue.
