### ISSUE TITLE
[BUG] Can't upgrade to F35 via GUI

### ISSUE THREAD

**Issue by shdwchn10** [fedora-silverblue/issue-tracker#207]
**Describe the bug**
GNOME Software fails to upgrade to Fedora Silverblue 35

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Run `gsettings set org.gnome.software show-upgrade-prerelease true` to allow Beta upgrades in GNOME Software
2. Open GNOME Software
3. Upgrade to Fedora Silverblue 35

**Expected behavior**
It should be possible to upgrade to next major Fedora release

**Screenshots**
![Screenshot from 2021-09-28 02-33-02](https://user-images.githubusercontent.com/79763381/134998986-324ec3c6-f0c5-4d2f-af06-54e89746f555.png)

**OS version:**
```
34.20210927.0
```

**Additional context**
`rpm-ostree rebase fedora:fedora/35/x86_64/silverblue` works as usual. No problems found.

**Comment by shdwchn10** [comment]
`journalctl -xef` output:
```
Sep 28 16:10:13 fedora rpm-ostree[2061]: Locked sysroot
Sep 28 16:10:13 fedora rpm-ostree[2061]: Initiated txn Rebase for client(id:gnome-software dbus:1.110 unit:app-gnome-gnome\x2dsoftware\x2dservice-1984.scope uid:1000): /org/projectatomic/rpmostree1/fedora
Sep 28 16:10:13 fedora rpm-ostree[2061]: Process [pid: 1984 uid: 1000 unit: user@1000.service] connected to transaction progress
Sep 28 16:10:13 fedora rpm-ostree[2061]: Txn Rebase on /org/projectatomic/rpmostree1/fedora failed: Invalid refspec ostree://fedora/35/x86_64/silverblue
Sep 28 16:10:13 fedora rpm-ostree[2061]: Unlocked sysroot
Sep 28 16:10:13 fedora rpm-ostree[2061]: Process [pid: 1984 uid: 1000 unit: user@1000.service] disconnected from transaction progress
```

**Comment by shdwchn10** [comment]
Bug reproducible even on clean Silverblue installation without any mutations.

**Comment by mcrha** [comment]
Thanks for a bug report. I see the gnome-software uses `ostree://fedora/NNN/x86_64/silverblue` as the refspec, while the rpm-ostree, or something around, changed the refspec to `fedora:fedora/35/x86_64/silverblue`. I've no idea when or why that changed. I can fix it on the gnome-software side, that's trivial, but I'd need to know some details from the related parties. 

I opened an upstream report at:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1463

See it for any further updates.

**Comment by mcrha** [comment]
For the record, this will be fixed on the rpm-ostree side:
https://github.com/coreos/rpm-ostree/pull/3157

**Comment by tpopela** [comment]
Looks like the change that was done in rpm-ostree was not enough - I asked for the clarification in https://github.com/coreos/rpm-ostree/pull/3199

**Comment by rugk** [comment]
Uuups, this is really unfortunate that this was not fixed properly before the Fedora 35 final release.

(Or I had a too old Fedora 34 version, that may also be, but that should have been fixed way earlier. – Given this issue here is not closed, I guess, though, that it is not yet fixed properly. Am I right?)

**Comment by tpopela** [comment]
The relevant updates are shipped in stable and thus this should be fixed.
