### ISSUE TITLE
[BUG] grub bricked after rpm-ostree override reset -a

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#208]
**Describe the bug**
I had gnome software removed from my system because is was behaving badly and consuming 250 mb of ram in idle , and preparing to the upcoming f35 update i decided to restore the override to be sure the system will function as intended so i ran ''' rpm-ostree override reset -a '' than rebooted to enter the deployment with gnome software in i was greeted wit this grub error ![IMG_20210927_110005.jpg](https://user-images.githubusercontent.com/57415185/135051933-fbaf656d-50e8-422d-a5fb-d0962076938d.jpg) 
And now i can't boot into my system 

**To Reproduce**
Steps needed to reproduce the bug:
1. rpm-ostree override remove gnome-software
2. reboot
3. rpm-ostree override restore -a
4. reboot

**Expected behavior**
Boots normally

**OS version:**
``` can't boot to see but the last update i did was this week
```

**Additional context**
Please help I can't use my pc now , all i have access to now is an elementary os boot drive

**Comment by allaeddineomc** [comment]
Fixed temporarily by following this thread 
 https://www.reddit.com/r/Fedora/comments/k1wuzw/grub_unkown_tpm_error/?utm_source=amp&utm_medium=&utm_content=post_body

I hope you can help me get rid of it permanently there is a comment about this in the thread but i won't follow it because silverblue grub is a bit different and way harder to fix compared the grub on fedora workstation

**Comment by allaeddineomc** [comment]
it turned out the issue wasn't related to the override reset , issue fixed by disabling secure boot

**Comment by TheOneandOnlyJakfrost** [comment]
@allaeddineomc , I am closing this issue since you have it resolved.
