### ISSUE TITLE
[BUG] toolbox not entering after update to fedora 35

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#209]
**Describe the bug**
after running toolbox enter toolbox looks for fedora 35 container and when it fails it falls back to the 34 container but still fail to enter it

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. rpm-ostree rebase fedora:fedora/35/x86_64/silverblue && reboot
2. toolbox enter 

**Expected behavior**
enters toolbox normally

**Screenshots**
![Screenshot from 2021-09-29 00-36-27](https://user-images.githubusercontent.com/57415185/135175609-2acfe5a4-27ce-47fe-b2e1-62b8cf71ce5e.png)

**OS version:**
```
35.20210928.n.0 (2021-09-28T08:06:20Z)
```

**Comment by travier** [comment]
Toolbox issue is https://github.com/containers/toolbox/issues/821

**Comment by allaeddineomc** [comment]
i don't think this is going to be fixed anytime soon , the problem exists since ever

**Comment by juhp** [comment]
The simplest workaround currently for users seems to be to downgrade the host toolbox package to F34 toolbox:
of course there is no guarantee that this will continue work flawlessly, but I have tested it.

**Comment by allaeddineomc** [comment]
> The simplest workaround currently for users seems to be to downgrade the host toolbox package to F34 toolbox: of course there is no guarantee that this will continue work flawlessly, but I have tested it.

iin issue https://github.com/containers/toolbox/issues/821 , there is a way you can enter the container with podman , but i couldn't update the container to fedora 35

**Comment by tpopela** [comment]
Closing as there's an upstream issue linked here.
