### ISSUE TITLE
Some app configuration doesn't seem to be remembered?

### ISSUE THREAD

**Issue by allanday** [fedora-silverblue/issue-tracker#21]
Since I switched to Silverblue, I've noticed a few instances of app configuration seemingly not being saved. Examples include:

 - Hexchat's "do not warn if you quit and have connections open" preference
 - Firefox extensions seemingly not remembering preferences (Block Site's list of blocked sites)

(I'll add more as I come across them.)

Is this a Silverblue issue?

**Comment by HarryMichal** [comment]
Hi @allanday! I've never encountered these issues. At least not with Firefox as I do not use Hexchat. Are the issues still present?

**Comment by travier** [comment]
Closing as this is old and would need to be updated & reproduced.
