### ISSUE TITLE
[RFE] add kernel modules

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#211]
A lot of programs require some kernel modules to function correctly , take for example virtualbox , anbox , nbfc-linux , waydroid , looking glass , tuxedo-control-center , fand and many many more , i wish you either add the modules required by these programs and other popular programs to the kernel , or as an alternative solution to avoid the bloat , keep the kernel as it is and add an optional kernel package that can be overlayed and have all these modules  .

It's really crucial to have access to various kernel modules to get the os to be as usable as any linux distro , i think in fedora 35 more modules got removed because all the programs that i use to control my cpu fan suddenly stopped working after the update .

I haven't opened this issue on the regular fedora repos because you can just compile your kernel there but you can't do it on silvery so it's a silverblue specific issue .

**Comment by juhp** [comment]
I am ignorant here, but do kernel modules require overlay?

**Comment by allaeddineomc** [comment]
> I am ignorant here, but do kernel modules require overlay?

you can't overlay kernel modules that aren't built in to the kernel and that's the problem , the request is to compile more modules with the builtin kernel , or add a new kernel package like arch linux is doing with linux-zen , because when it's a full kernel package it can be overlayed

**Comment by travier** [comment]
akmod based kernel modules are supported (see the NVIDIA kernel module). Other modules can be built inside a container and then loaded on the host. See https://github.com/kmods-via-containers/kmods-via-containers for examples.

**Comment by allaeddineomc** [comment]
> akmod based kernel modules are supported (see the NVIDIA kernel module). Other modules can be built inside a container and then loaded on the host. See https://github.com/kmods-via-containers/kmods-via-containers for examples.

that's good for stuff like nvidia drivers but for my issue that's too much of unnecessary work since the modules i'm referring to  are a part of the mainline linux kernel and totally free software so including them is not really a problem for fedora maintainers

**Comment by travier** [comment]
> that's good for stuff like nvidia drivers but for my issue that's too much of unnecessary work since the modules i'm referring to are a part of the mainline linux kernel and totally free software so including them is not really a problem for fedora maintainers

If the modules are part of the mainline kernel then the question becomes about enabling them for the Fedora kernel if they are not here already and this should be filed as a bug against the Fedora kernel in Bugzill: https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora

**Comment by allaeddineomc** [comment]
> I haven't opened this issue on the regular fedora repos because you can just compile your kernel there but you can't do it on silverblue so it's a silverblue specific issue .



> If the modules are part of the mainline kernel then the question becomes about enabling them for the Fedora kernel if they are not here already and this should be filed as a bug against the Fedora kernel in Bugzilla: https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora

**Comment by travier** [comment]
> I haven't opened this issue on the regular fedora repos because you can just compile your kernel there but you can't do it on silverblue so it's a silverblue specific issue.

I think there are several misunderstandings here:
* You can compile and use your own kernel on Silverblue as well just like you can on Fedora Workstation. The easiest way is to install it is via an RPM.
* Users are not expected to compile their own kernel on Fedora Workstation to have things working.

Thus if the drivers are upstream in the kernel then this is a valid bug or request that should be filed in Fedora BugZilla's.

**Comment by tpopela** [comment]
I will close this bug, if you @allaeddineomc will open any bugs as @travier suggested, please put the links here for the reference.
