### ISSUE TITLE
[BUG] Cannot replace kernel using rpm-ostree

### ISSUE THREAD

**Issue by thorhop** [fedora-silverblue/issue-tracker#214]
**Describe the bug**
I've been trying to install a F35 compatible kernel from COPR called `kernel-xanmod-edge`. The process goes all the way passed writing rpmdb, when it fails with the error "Multiple subdirectories found in: usr/lib/modules".

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. use `rpm-ostree override replace` to replace the relevant kernel packages
2. wait until "writing rpmdb" has finished
3. end in the error "error: Multiple subdirectories found in: usr/lib/modules"

**Expected behavior**
rpm-ostree writes a new tree with the new kernel, which I can attempt to reboot into.

**OS version:**
```
● fedora:fedora/35/x86_64/silverblue
                   Version: 35.20211009.n.0 (2021-10-09T08:08:27Z)
                BaseCommit: 5267b8e0612f09d3dc38b16597d0e28f3d3589d87a0a6dd62b8adea45f9cc1c8
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: powerline simple-scan zsh cpu-x tilix gnome-tweaks flatpak-builder gstreamer1-plugin-openh264 waydroid-sensors python3-gbinder-python hwinfo
```

**Additional context**
Here's a little script based off of an AskFedora page (["Multiple installed kernels on silverblue"](https://ask.fedoraproject.org/t/multiple-installed-kernels-on-silverblue/7486/4)). It will fetch and attempt to install the `kernel-xanmod-edge` packages for F35.
```
XANMOD_KERNEL_REPO="https://copr-be.cloud.fedoraproject.org/results/rmnscnce/kernel-xanmod/fedora-35-x86_64/02883255-kernel-xanmod-edge"
rpm-ostree override replace \
  --remove=kernel \
  --remove=kernel-core \
  --remove=kernel-modules \
  --remove=kernel-modules-extra \
  --remove=kernel-headers \
  --remove=kernel-devel \
  --install=${XANMOD_KERNEL_REPO}/kernel-xanmod-edge-5.14.11-xm1.0.fc35.x86_64.rpm \
  --install=${XANMOD_KERNEL_REPO}/kernel-xanmod-edge-core-5.14.11-xm1.0.fc35.x86_64.rpm \
  --install=${XANMOD_KERNEL_REPO}/kernel-xanmod-edge-modules-5.14.11-xm1.0.fc35.x86_64.rpm \
  --install=${XANMOD_KERNEL_REPO}/kernel-xanmod-edge-headers-5.14.11-xm1.0.fc35.x86_64.rpm \
  --install=${XANMOD_KERNEL_REPO}/kernel-xanmod-edge-devel-5.14.11-xm1.0.fc35.x86_64.rpm \
  ${XANMOD_KERNEL_REPO}/kernel-xanmod-edge-5.14.11-xm1.0.fc35.x86_64.rpm
```

**Comment by thorhop** [comment]
Working now, even on the stable fedora:/fedora/35/x86_64/silverblue.

Closing.

**Comment by firefoxlover** [comment]
any updates on this for Fedora 38?
