### ISSUE TITLE
[BUG] Rebase from silverblue/34 to silverblue/35 fails

### ISSUE THREAD

**Issue by sbluman** [fedora-silverblue/issue-tracker#218]
**Describe the bug**
Rebasing from silverblue/34 to silverblue/35 fails with an error message:
```
error: Package 'glibc-gconv-extra' has (currently) unsupported <lua> script in '%post'
``` 

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Be on silverblue/35
2. `rpm-ostree rebase fedora:fedora/35/x86_64/silverblue`
3. Error

**Expected behavior**
Rebased successfully to silverblue/35

**OS version:**
```
● fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210905.0 (2021-09-05T20:59:47Z)
                BaseCommit: d8bab818f5abcfb58d2c038614965bf26426d55667e52018fcd295b9bfbc88b4
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: syncthing steam kitty fedora-workstation-repositories kitty-terminfo
                            gnome-tweaks
                    Pinned: yes
```

**Additional context**
Full output:
```
[me@fedora ~]$ rpm-ostree rebase fedora:fedora/35/x86_64/silverblue
⠦ Receiving objects; 97% (3245/3331) 2.7 MB/s 116.9 MB 
779 metadata, 2552 content objects fetched; 115353 KiB transferred in 46 seconds; 181.2 MB content writteReceiving objects; 97% (3245/3331) 2.7 MB/s 116.9 MB... done
Checking out tree c642c47... done
Inactive requests:
  fedora-workstation-repositories (already provided by fedora-workstation-repositories-35-1.fc35.noarch)
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora rpmfusion-nonfree-steam updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2021-09-21T18:07:30Z solvables: 4
rpm-md repo 'updates' (cached); generated: 2018-02-20T19:18:14Z solvables: 0
rpm-md repo 'fedora' (cached); generated: 2021-10-20T10:41:31Z solvables: 65729
rpm-md repo 'rpmfusion-nonfree-steam' (cached); generated: 2021-08-14T13:52:52Z solvables: 2
rpm-md repo 'updates-archive' (cached); generated: 2021-08-18T13:30:23Z solvables: 0
Resolving dependencies... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
error: Package 'glibc-gconv-extra' has (currently) unsupported <lua> script in '%post'
```

**Comment by tpopela** [comment]
@sbluman is this still an issue?

**Comment by gabx** [comment]
> @sbluman is this still an issue?

Yes, just got the error when upgrading to Fedora 35. I don't understand where does this package come from as it is not installed on my box and the package is not found when I want to install it.

**Comment by juhp** [comment]
> > @sbluman is this still an issue?
> 
> Yes, just got the error when upgrading to Fedora 35. I don't understand where does this package come from as it is not installed on my box and the package is not found when I want to install it.

On my system I see 
`(glibc-gconv-extra(x86-64) = 2.34-25.fc35 if redhat-rpm-config) is needed by (installed) glibc-2.34-25.fc35.x86_64` - I believe it is a new subpackage in F35. 

What rpm-ostree package do you have installed?

**Comment by travier** [comment]
@gabx Have you updated to the latest F34 before rebasing to F35?

**Comment by gabx** [comment]
no, and this was the root of my issue. I left Fedora for a while and upgraded directly to 35 from 33. Doing the usual 33 ----> 34 ----> 35 did the job.

**Comment by travier** [comment]
We probably need to make this clearer in the docs somewhere.

**Comment by travier** [comment]
This is now clarified in https://docs.fedoraproject.org/en-US/fedora-silverblue/updates-upgrades-rollbacks/#upgrading
