### ISSUE TITLE
[Bug] Wacom tablet (CTE-630) and multiple monitor support with annoying behavior

### ISSUE THREAD

**Issue by cjuniorfox** [fedora-silverblue/issue-tracker#219]
Hi,

My setup:
Dell Latitude 5400.
LG Ultrawide 34"
Arrangement:
LG (monitor 2) as left primary monitor and Laptop Display (monitor 1) as secondary at right.

The Wacom tablet behavior on that setup it's completly messed up. It's impossible to use the mouse because the cursor keeps stickyed at the joint place of two displays. When I try to movement the mouse, it moves to the expected direction, but goes right back to the join, like having some software conflict forcing the cursor to go to that place.
When I try to use the stylus, it sticks to laptop's monitor and I unable to move the stylus to the LG Monitor. To use on that monitor, I need to manually map the stylus that. (Settings -> Wacom Tablet -> Tabled -> Map to Monitor). But even in that way, the behavior remais confused. Simple operations like Drag window across does't work as should. 
If i change the display settings to single monitor, the things become to work little more accordinaly as expected. Stylus becomes completely usable and the mouse starts cross around the desktop as expected. But the scroll wheel doesn't work and the right click with work just for some windows. Example, the Firefox. It's unable to use the right click to open the context menu with the Mouse, working as expected with stylus. Other programs, and de the desktop, the mouse's right click works as expected.

Regards

**Comment by juhp** [comment]
This doesn't sound specific to Silverblue?

**Comment by tpopela** [comment]
Yes, it isn't please open the bugs in bugzilla.redhat.com or in upstream probably against https://gitlab.gnome.org/GNOME/gnome-control-center. If you open the bugs, please put here the links please.

**Comment by cjuniorfox** [comment]
Thanks for the answer.
Bug submitted. Follows:
https://bugzilla.redhat.com/show_bug.cgi?id=2020619
