### ISSUE TITLE
[BUG] Outdated language pack for firefox

### ISSUE THREAD

**Issue by marhkb** [fedora-silverblue/issue-tracker#220]
**Describe the bug**
I did a fresh install of silverblue 34 yesterday. Firefox was at v87 directly after the install.
Then I did an `rpm-ostree upgrade`. It seems while firefox went to v93, the the language
pack is still at v87. The consequence is, that firefox is not translated.
I just did the rebase to silverblue 35 but the language pack is still at v87.  

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Do a fresh install of silverblue 34
2. Perform a system upgrade through `rpm-ostree upgrade`
3. firefox's language pack didn't get an update.

**Expected behavior**
The language pack version is in sync with firefox's version.

**Screenshots**
![Bildschirmfoto von 2021-11-02 15-45-48](https://user-images.githubusercontent.com/3630213/139870200-493ff945-fd41-4685-a3f5-a69c1b479e66.png)

**OS version:**
```
fedora:fedora/35/x86_64/silverblue
                   Version: 35.20211102.0 (2021-11-02T00:40:44Z)
                BaseCommit: 1f1bc444c98105e29a2a7ac828818f947001c39af6e20cc9be5e2d1328453782
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: gnome-tweaks gnome-shell-extension-appindicator htop
                            papirus-icon-theme gnome-extensions-app dconf-editor

```
But the bug was also there with silverblue 34 yesterday when I installed it for the first time.

**Comment by tpopela** [comment]
The language packages are handled by Firefox itself (as these are technically the extensions) - we don't have any of them shipped as part of the Firefox in Fedora.

**Comment by marhkb** [comment]
Ok, sorry for the noise. Since I usually only use Arch, I assumed it was similar with Fedora and that the language packs were part of the system installation.

I have now installed the language pack as an add-on and it works.

**Comment by juhp** [comment]
Actually the Fedora firefox rpm does bundle many langpack extensions and has done so for long time:
see eg https://koji.fedoraproject.org/koji/rpminfo?fileStart=100&rpmID=28205348&fileOrder=name#filelist

(I am not sure about the flatpak.)
