### ISSUE TITLE
[BUG]  random reboots when on lock screen

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#222]
**Describe the bug**
when the screen is locked after a login it sometimes restarts the system for no reason loosing all my work

**To Reproduce**
happens randomly

**Expected behavior**
nothing

**OS version:**
```
35.20211103.0 (2021-11-03T00:48:08Z)
```

**Comment by tpopela** [comment]
Are you sure that the bug is Silverblue specific? What's the output of `coredumpctl info` after it crashes?

**Comment by travier** [comment]
Closing has this has been waiting on more info for a long time.
