### ISSUE TITLE
[BUG] Can't resume from suspend with nvidia proprietary driver installed

### ISSUE THREAD

**Issue by lumingzh** [fedora-silverblue/issue-tracker#223]
**Describe the bug**
Fedora silverblue 35 installed on Lenovo R7000P 2021H laptop, AMD Ryzen R7-5800H APU, Nvidia RTX3060m GPU.

I set nvidia dGPU direct connect to monitor in BIOS so the amd iGPU won't be found by system, installed akmod-nvidia and xorg-x11-drv-nvidia/nvidia-cuda driver, blacklist nouveau and append nvidia-drm.modeset=1, login wayland normally (except can't play boot/reboot/shutdown animation correctly).

Then make system suspend and wake it, the laptop just keep black screen, or seems like the system resumed from suspend but the screen can't turn on anymore until reboot. I'm not sure.

Here are journalctl and dmesg messages:
[journal.txt](https://github.com/fedora-silverblue/issue-tracker/files/7490472/journal.txt)
[dmesg.txt](https://github.com/fedora-silverblue/issue-tracker/files/7490471/dmesg.txt)

**Comment by lumingzh** [comment]
BTW, can't adjust screen lightness as well with or without amd iGPU disabled, I don't know if it's relative.

**Comment by lumingzh** [comment]
Ok, I give up and set amd iGPU connect to monitor in BIOS and keep everything else the same. Everything seems works fine except can't adjust screen lightness and it's surprise that I can select wayland via gdm and support the monitor better than amd iGPU without nvidia-drm.modeset=1 or only nvidia dGPU.

I can't set monitor resolution, get monitor's color profile and refresh rate or even can't recognize the monitor at all when using amd iGPU without nvidia-drm.modeset=1 or only nvidia dGPU.

**Comment by tpopela** [comment]
Hi @lumingzh, is this really Silverblue specific? Have you tried the Fedora Workstation? Is it fixed there?

**Comment by lumingzh** [comment]
> Hi @lumingzh, is this really Silverblue specific? Have you tried the Fedora Workstation? Is it fixed there?

No, I didn't try Fedora Workstation, and I really don't want to reinstall everything again so sorry I won't try it, Silverblue is my daily OS now.

But you are right, the named dGPU direct connect technology is a recent motherboard option on so called gaming laptop. I don't think it's Silverblue specific. I think it's about kernel, acpi, driver possible.

I should close this issue, right?

**Comment by tpopela** [comment]
I will close it. You can try to open a bug against the kernel component in Red Hat Bugzilla.
