### ISSUE TITLE
Rawhide Silverblue ostree compose fails with "error: Finalizing rootfs: Adding altfiles to /etc/nsswitch.conf: Too many levels of symbolic links (os error 40)"

### ISSUE THREAD

**Issue by AdamWill** [fedora-silverblue/issue-tracker#230]
The Silverblue ostree is failing to build in Rawhide at present. Here's the failure from the latest Rawhide compose: https://koji.fedoraproject.org/koji/taskinfo?taskID=81129737

As [root.log](https://kojipkgs.fedoraproject.org//work/tasks/9737/81129737/root.log) shows, the error is:

    DEBUG util.py:446:  Migrating /usr/etc/passwd to /usr/lib/
    DEBUG util.py:446:  Migrating /usr/etc/group to /usr/lib/
    DEBUG util.py:446:  error: Finalizing rootfs: Adding altfiles to /etc/nsswitch.conf: Too many levels of symbolic links (os error 40)
    DEBUG util.py:446:  Traceback (most recent call last):
    DEBUG util.py:446:    File "/usr/bin/pungi-make-ostree", line 33, in <module>
    DEBUG util.py:446:      sys.exit(load_entry_point('pungi==4.3.2', 'console_scripts', 'pungi-make-ostree')())
    DEBUG util.py:446:    File "/usr/lib/python3.10/site-packages/pungi/ostree/__init__.py", line 159, in main
    DEBUG util.py:446:      func()
    DEBUG util.py:446:    File "/usr/lib/python3.10/site-packages/pungi/ostree/tree.py", line 151, in run
    DEBUG util.py:446:      self._make_tree()
    DEBUG util.py:446:    File "/usr/lib/python3.10/site-packages/pungi/ostree/tree.py", line 59, in _make_tree
    DEBUG util.py:446:      shortcuts.run(
    DEBUG util.py:446:    File "/usr/lib/python3.10/site-packages/kobo/shortcuts.py", line 409, in run
    DEBUG util.py:446:      raise exc
    DEBUG util.py:446:  RuntimeError: ERROR running command: rpm-ostree compose tree --repo=/mnt/koji/compose/ostree/repo/ --write-commitid-to=/mnt/koji/compose/rawhide/Fedora-Rawhide-20220112.n.0/logs/x86_64/Silverblue/ostree-4/commitid.log --touch-if-changed=/mnt/koji/compose/rawhide/Fedora-Rawhide-20220112.n.0/logs/x86_64/Silverblue/ostree-4/commitid.log.stamp --add-metadata-string=version=Rawhide.20220112.n.0 --force-nocache /mnt/koji/compose/rawhide/Fedora-Rawhide-20220112.n.0/work/ostree-4/config_repo/fedora-silverblue.json

Not sure what's causing this.

**Comment by AdamWill** [comment]
Hmm, Kinoite has the same problem, so this is probably an issue at rpm-ostree level, actually.

**Comment by cgwalters** [comment]
See https://github.com/coreos/rpm-ostree/pull/3308 and https://bugzilla.redhat.com/show_bug.cgi?id=2034360

**Comment by cgwalters** [comment]
Since this is not SB specific, closing in favor of https://bugzilla.redhat.com/show_bug.cgi?id=2034360

**Comment by AdamWill** [comment]
D'oh, sorry, filed an issue at rpm-ostree before seeing your comments.
