### ISSUE TITLE
[BUG] config of ibus does not work

### ISSUE THREAD

**Issue by djypku** [fedora-silverblue/issue-tracker#231]
Have not tested in Fedora Workstation. I will test it later today. 

**Describe the bug**
Changing config by `ibus-setup` does not work. 

**To Reproduce**
1. Install Fedora Silverblue in VirtualBox with zh_CN option.
2. use `ibus-setup` to open config tool and change whatever wanted, for example, keyboard shortcut or adding new input methods. ( for the later, `sudo rpm-ostree install` and `systemctl reboot` may be needed  )
3. Reopening `ibus-setup` or use `ibus read-config`, I can make sure that the changes have been written. However, it does not work actually. I try adding new input methods and keyboard shortcut and both not work.
4. Try `systemctl reboot`, config changes are still here but not work still. 

**Expected behavior**
Config works immediately after changing it.

**Screenshots**
![VirtualBox_Silverblue 副本_14_01_2022_08_45_45](https://user-images.githubusercontent.com/86961676/149431881-159e0d0b-0d15-4c57-8e92-ebd5993115cb.png)
Hopefully you can see here input methods in `ibus-setup` and which actually work are different, though if you do not know Chinese these characters may be very hard. Treat them as pictures if you can.

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/35/x86_64/silverblue
                   Version: 35.1.2 (2021-10-26T02:25:55Z)
                BaseCommit: 34b3a6ad08a934f5db9031929a1f64a788033d151e9074596c6a53af2edf68ac
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: gnome-tweaks kwin dnf xfwm4
```
Noting :  I donot use `xfwm4` nor `kwin` although I install them. `dnf` is used to search for packages and then installed by `prm-ostree`, I know `dnf install` does not work and I do not try it at all.

**Additional context**
Solving option: To install `fcitx5` by `rpm-ostree` and adding some config in `/etc/bashrc`. `fcitx5` works without such problem.
____________________________________________________________________________________________________
After testing I find this bug exists in Fedora workstation, so not your problem.

**Comment by djypku** [comment]
Some of my guessing: `ibus` has to be removed by `rpm-ostree override remove` rather than `rpm-ostree uninstall` for they are in base layer. I guess maybe because of it, `ibus` doed not work.

**Comment by juhp** [comment]
Under Gnome one is supposed to add/remove IMEs using the `gnome-control-center keyboard` panel.
