### ISSUE TITLE
[BUG] No wayland after rpm-ostree update

### ISSUE THREAD

**Issue by tblaisot** [fedora-silverblue/issue-tracker#234]
**Describe the bug**
Since i upgraded with `rpm-ostree upgrade` yesterday, I have loose the ability to launch the session using wayland, only X11 is available.
I don't have NVIDIA drivers.
I am able to launch manually a wayland session 
```
export XDG_RUNTIME_DIR=/run/user/xxx/
sudo mkdir -p $XDG_RUNTIME_DIR
sudo chown xxx:xxx $XDG_RUNTIME_DIR
dbus-run-session -- gnome-shell --display-server --wayland
```
But I have a lot of problem in this session like no audio devices

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Update to latest
2. reboot
3. check session type

**Expected behavior**
I expect wayland to be my default choice and to have at leat the choice available in the cog menu.

**OS version:**
```
rpm-ostree status -b                                           ✔  ▼ 
State: idle
BootedDeployment:
● fedora:fedora/35/x86_64/silverblue
                   Version: 35.20220121.0 (2022-01-21T03:09:39Z)
                BaseCommit: ce3c28c17f6f1fe24268780117536ed33e7b7f6a7d24dc8dff4d5899da2c05ae
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: containerd.io docker-ce docker-ce-cli evolution fzf
                            git-credential-libsecret gnome-tweaks insync
                            NetworkManager-fortisslvpn NetworkManager-fortisslvpn-gnome
                            oddjob oddjob-mkhomedir openssl patch powertop python3-smbc
                            simple-scan sssd-tools system-config-printer zsh
             LocalPackages: 'appimagelauncher-2.2.0-travis995~0f91801.x86_64'
                            displaylink-1.9.1-1.x86_64 sp-200-series-gdi-1.01-0.x86_64
                            XeroxOfficePrtDrv-5.20.661.4684-1.i386
```

**Additional context**
I have tried the following already:
- editing `/etc/gdm/custom.conf` to force wayland
- editing `/usr/lib/udev/rules.d/61-gdm.rules`
- `/usr/libexec/gdm-runtime-config set daemon WaylandEnable true` and restarting gdm

I ham unable to work with x11 as most app won't launch at all.

**Comment by tblaisot** [comment]
After a lot of research in the log I found the following cause to this:
directories `/run/user/<id>` are not created

For gdm the folder `/run/user/42` is not created and make gdm fail to start so it fallback to x11
If I created if from a terminal session and restart gdm service I have the next bug:
For my user the folder `/run/user/<myid>` don't exist and it make gnome-shell fail and comme back to login prompt
If I created if from a terminal session and restart gdm service I am able to login and the desktop seems to work (may be some other services are failing...)

This cause my not be the root one but it is the higher I found in the logs...
Any ideas on what is causing the folders to not be created ? which conf can I check ?

**Comment by HarryMichal** [comment]
I ran into the issue some time ago already. [Suspected](https://bodhi.fedoraproject.org/updates/FEDORA-2022-f38f479b8f) it is an issue in systemd but it seems more like an issue with [SELinux policies](https://bodhi.fedoraproject.org/updates/FEDORA-2022-41fa7610dd) but I haven't confirmed that. The latest version of `selinux-policy` (`35.11`) is still affected by the issue. While fooling around the system I found errors like `Permission denied` for running `mmap`.

**Comment by HarryMichal** [comment]
Found an upstream report for `selinux-policy` -> https://bugzilla.redhat.com/show_bug.cgi?id=2042157

**Comment by tblaisot** [comment]
@HarryMichal Thank a lot, the selinux logs are in fact present and i didn't notice them.
From the upstream bug you link I found this procédure: https://docs.fedoraproject.org/en-US/fedora-silverblue/troubleshooting/#_selinux_problems
After following it I reboot and.. everything work normally !!

Thanks !
