### ISSUE TITLE
Automatically take an ostree snapshot before a major kernel update

### ISSUE THREAD

**Issue by castrojo** [fedora-silverblue/issue-tracker#236]
**Is your feature request related to a problem? Please describe.**
A major kernel upgrade is a significant event (some hardware more significant than others). Sometimes I don't have the time to check when a major kernel update is coming because I'm not following fedora development or whatever, so it'd be nice to have an extra snapshot.

**Describe the solution you'd like**
It'd be nice to opt-in have an automatic ostree snapshot when a major release of the kernel is updated in Fedora and have it labelled as such. Ideally I never have to use it. 

**Describe alternatives you've considered**
An alternative might be documentation on how one could set this up by hand, perhaps via a service unit or something to see how useful it is in the wild.

**Comment by travier** [comment]
With rpm-ostree you usually have 2 deployments available so you can rollback to the previous one after an update if it breaks.

If we pin a specific deployment, then we need a way to signal / unpin it at some later time too.

**Comment by travier** [comment]
I think you might be interesting in https://github.com/coreos/rpm-ostree/issues/577, which I wanted to in the beginning too. Will try to make it happen.

**Comment by xrishox** [comment]
would be nice to have it automatically pin on kernel upgrades. could be unpinned and replaced with a new pin when the next kernel upgrade is released.

**Comment by travier** [comment]
I'll close this issue in favor of the one in the Fedora Atomic Desktop issue tracker: https://gitlab.com/fedora/ostree/sig/-/issues/2

While they are not strictly the same issue, this is one likely to happen as part of that change.
