### ISSUE TITLE
[BUG] systemd reports /tmp and /var are not empty

### ISSUE THREAD

**Issue by cmurf** [fedora-silverblue/issue-tracker#237]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
[    3.731908] systemd[1]: var.mount: Directory /var to mount over is not empty, mounting anyway.
[    4.467631] systemd[1]: tmp.mount: Directory /tmp to mount over is not empty, mounting anyway.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install Fedora-Silverblue-ostree-x86_64-36-20220209.n.0.iso (I used qemu-kvm), using Automatic partitioning.
2. Boot

**Expected behavior**
These directories should be empty?

**Screenshots**

**OS version:**
```
$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220209.n.0 (2022-02-09T04:43:27Z)
                    Commit: 0ad42c912b38a8e86a05f3bc3e918f5ef3395c134f8cb523567f82f8a61f4b19
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
```

**Additional context**

Pretty sure it's not the directories in the root subvolume mounted at `/sysroot`
```
# mount /dev/vda3 /mnt
# btrfs sub list -t /mnt
ID	gen	top level	path	
--	---	---------	----	
256	84	5		home
257	87	5		root
# ls -la /mnt/root/var
ls: cannot access '/mnt/root/var': No such file or directory
# ls -la /mnt/root/tmp
total 0
drwxrwxrwt. 1 root root  0 Feb  9 21:27 .
drwxr-xr-x. 1 root root 74 Feb  9 21:27 ..
# 
```
But rather the tmp and var in the ostree directory
```
# ls -la /mnt/root/ostree/deploy/fedora/deploy/0ad42c912b38a8e86a05f3bc3e918f5ef3395c134f8cb523567f82f8a61f4b19.0/tmp
total 4
drwxrwxrwt. 1 root root  36 Feb  9 21:37 .
drwxr-xr-x. 1 root root 158 Feb  9 21:32 ..
-rwx------. 1 root root  26 Feb  9 21:33 ks-script-2i4hbohr
# ls -la /mnt/root/ostree/deploy/fedora/deploy/0ad42c912b38a8e86a05f3bc3e918f5ef3395c134f8cb523567f82f8a61f4b19.0/var
total 0
drwxr-xr-x. 1 root root   6 Dec 31  1969 .
drwxr-xr-x. 1 root root 158 Feb  9 21:32 ..
drwxr-xr-x. 1 root root  38 Dec 31  1969 lib
# ls -la /mnt/root/ostree/deploy/fedora/deploy/0ad42c912b38a8e86a05f3bc3e918f5ef3395c134f8cb523567f82f8a61f4b19.0/var/lib
total 8
drwxr-xr-x. 1 root root 38 Dec 31  1969 .
drwxr-xr-x. 1 root root  6 Dec 31  1969 ..
lrwxrwxrwx. 2 root root 26 Feb  9 21:28 alternatives -> ../../usr/lib/alternatives
lrwxrwxrwx. 2 root root 21 Feb  9 21:28 vagrant -> ../../usr/lib/vagrant
# 
```
The /tmp case is original tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1306452 which says it should be fixed in https://github.com/rhinstaller/anaconda/pull/3115 which it is with Fedora-Workstation-Live-x86_64-36-20220209.n.0.iso but not Fedora-Silverblue-ostree-x86_64-36-20220209.n.0.iso - so I suspect both cases are probably happening server side since the deployment tree is what has these non-empty directories.

**Comment by jlebon** [comment]
This should be fixed by https://github.com/coreos/rpm-ostree/pull/3387.

**Comment by travier** [comment]
Closing as likely fixed.
