### ISSUE TITLE
Requested Google Permissions are far broader than actually used

### ISSUE THREAD

**Issue by markstos** [fedora-silverblue/issue-tracker#24]
I just installed Silverblue 31. One of the prompts during installation is to connect with a Google account.

Broad permissions are requested, including full Gmail access, as well as full contacts and calendar access.

Upon the installation completing, I looked around for signs of the Google integration. The Nautilus integration with Google drive worked, but I only found the "Google Drive" permission actively used.

There was no email app installed, no contacts app, no calendar app, nor a photo app installed. I went to Gmail in Firefox and it prompted me to log into Google a second time, so it's not integrated with the online through Firefox like Chrome OS is with the Chrome browser. 

**The only Google permission that appears to be used in the default Silverblue install is the Google Drive access**. 

In this pro-privacy era, it seems inappropriate and risky to ask for Gmail, Calendar, Contacts and other access if these permissions may never be used. Both iOS and Android have moved towards prompting for extra permission access when they are first used and that seems more appropriate here as well. 

----

As a counterpoint, Silverblue in some ways mirrors Chrome OS with Crostini: Silverblue offers an immutable host operating system with little more than a browser and focuses on using containers. Of course when you log into a Chromebook you get logged into all Google services as well.  The Chrome OS behavior could be taken as a precedent for the current design, but I think the Chrome OS behavior is better viewed as an opportunity for Sliverblue to stand in contrast with a more privacy-centric approach.

**Comment by lionirdeadman** [comment]
If you install the appropriate apps : email, contacts, calendar, they *will* sync. They are not installed because not everyone wants them and it's easier to add things to a SB system than it is to remove them.

**Comment by markstos** [comment]
I get that the permissions can *potentially* be used. I'm advocating for a privacy-first experience that prompts for extra permissions *when they are first needed* instead of asking for broad permissions up front.

Mobile phone operating systems transitioned to on-first-use permission models years ago. Our desktop OS should keep pace.

**Comment by lionirdeadman** [comment]
Account systems are not very good at doing this. Basically, GVFS (atleast IIRC) gives the account permissions to applications which request it. This means that access to the permissions is centralized and only done once rather than on a per-application basis.

So, we'd either need to know all applications which want this permission to only ask what is neccessary or implement an account system on all applications which would defeat the purpose of the centralized service.

What we could do, and which is what Android does IIRC is have gnome-control-center ask for everything from the account and then have applications which request that data from GVFS have a prompt asking the user if this is fine but this is not what you want.

What exactly are you proposing?

**Comment by markstos** [comment]
The simplest solution seems to be to have checkmark options on the permissions prompt: "Select all the Google services you intend to use on this device."  Then only request from Google from the permissions the user intends to use.

Later if the user wants or needs to adjust the permissions, they should be able to go into settings and update their preferences.

**Comment by tpopela** [comment]
Hi, thank you @markstos for the report. Please open a bug report in https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues as GNOME Online Accounts is the place, where it needs to be fixed.
