### ISSUE TITLE
[BUG] message in dmesg saying security risk from being build with debug on.

### ISSUE THREAD

**Issue by splace** [fedora-silverblue/issue-tracker#240]
**OS version:**
```
● fedora:fedora/rawhide/x86_64/silverblue
                   Version: Rawhide.20220213.n.0 (2022-02-13T06:01:36Z)
                BaseCommit: cf643552e9df98b2aa15154d6bce2dccf49a98c7c80cfa956de558d5c07d8d72
              GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
           LayeredPackages: clapper gstreamer1-plugin-openh264 radeon-profile
```
.
[    0.776130] DMA-API: preallocated 65536 debug entries
[    0.776143] DMA-API: debugging enabled by kernel config
[    0.776148] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275000 ns
[    0.776167] futex hash table entries: 1024 (order: 5, 131072 bytes, linear)
[    0.776837] pinctrl core: initialized pinctrl subsystem

[    0.777918] *************************************************************
[    0.777920] **     NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE    **
[    0.777922] **                                                         **
[    0.777924] **  IOMMU DebugFS SUPPORT HAS BEEN ENABLED IN THIS KERNEL  **
[    0.777926] **                                                         **
[    0.777928] ** This means that this kernel is built to expose internal **
[    0.777930] ** IOMMU data structures, which may compromise security on **
[    0.777932] ** your system.                                            **
[    0.777934] **                                                         **
[    0.777936] ** If you see this message and you are not debugging the   **
[    0.777938] ** kernel, report this immediately to your vendor!         **
[    0.777940] **                                                         **
[    0.777942] **     NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE    **
[    0.777944] *************************************************************
[    0.777982] PM: RTC time: 19:10:30, date: 2022-02-15
.
```

**Comment by travier** [comment]
You are running Rawhide and the kernel used in Rawhide has debug support enabled.

**Comment by splace** [comment]
i see, thanks, hadn't realised when i installed, although compiled-in debug info of some kind (with a small slowdown) isn't an issue, i feel security concerns should have been front and centre.

however this is now mute, since after a basically a perfect initial install, each update/overlay, introduced more problems until even a rollback didn't get me a booting system. (this is being posted on my previous setup.)

if time permits, maybe i could try only updating for new release candidates, (apparently they have no debug stuff) but seems i may be missing other knowledge on all this. 

during the 2-weeks i ran it, i received multiple messages that made no sense, but that could have been part of the system unravelling.

**Comment by travier** [comment]
If you want to test the next version of Fedora, the safest option is usually to try it after it has been branched from Rawhide. Right now Fedora 36 is branched from Rawhide and will be in Beta soon. You can thus give it a try and it should not include debug packages.
