### ISSUE TITLE
[RFE] Add evolution-ews package by default.

### ISSUE THREAD

**Issue by koko-ng** [fedora-silverblue/issue-tracker#243]
**Is your feature request related to a problem? Please describe.**
GNOME online account allows to add a Microsoft Exchange account however it won't sync because evolution-ews isn't installed. It isn't intuitive that you can add an account but that it won't work out of the box, for instance calendar doesn't show in GNOME calendar or in the notification tray.

**Describe the solution you'd like**
Add evolution-ews pacakge by default.

**Describe alternatives you've considered**
Use Evolution flatpak instead of GNOME calendar, it works and sync correctly Exchange accounts. However I have noticed that it uses its own built-in evolution-data-server, every service is D-Bus service is prefixed with org.gnome.Evolution, therefore the calendar in the notification tray still won't show up the events from the exchange accounts.

**Additional context**
I have checked that it is indeed a problem with evolution-data-server and not only with GNOME calendar, calling org.freedesktop.DBus.ObjectManager.GetManagedObjects() on org/gnome/evolution/dataserver/SourceManager doesn't include the exchange account without evolution-ews installed. It however correctly returns the account when evolution-ews is installed or if it is called on the prefixed service of flatpak Evolution.

**Comment by tpopela** [comment]
Hi @koko-ng we are just following the same package set as the Fedora Workstation and as evolution-ews is not preinstalled in Fedora Workstation I would start with asking for the package to be introduced there - https://pagure.io/fedora-workstation/issues . When you will have the issue opened, please put it here for reference.
