### ISSUE TITLE
[RFE] Derive Fedora Silverblue from Fedora CoreOS

### ISSUE THREAD

**Issue by blitmap** [fedora-silverblue/issue-tracker#244]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Base Silverblue on the existing minimal *core* of Fedora CoreOS.  Layer the graphics drivers, X, wayland, GNOME, etc on top of this.  Ideally Kinoite would do the same thing.

I recognize this is a pretty extreme request.  I started with NixOS, and I just can't get comfortable with the language they've created around pure, reproducible builds.  I think OS-Tree distros are honestly resolving a big problem where you regularly reinstall your entire system to *trust* that you're in a clean state.  Immutable OS installs are absolutely the future.  A lot of work has gone into CoreOS to provide a minimal, solid image for a container-capable server.  I'm suggesting that it be evaluated to see if deriving the "desktop experience" from CoreOS makes more sense.  It might result in unified lines of effort, and mean less work to maintain/update Silverblue.

**Comment by awarda-rh** [comment]
This feature request sounds so obvious to me, I suspect there will be some good reason(s) why Silverblue was not based on Fedora CoreOS right from the beginning? I'd really like to learn more about this.

**Comment by travier** [comment]
The parent historical projects (Fedora Atomic and Fedora Atomic Workstation) were close to one another but they've diverged with the Fedora Atomic + CoreOS Container Linux merge into Fedora CoreOS.

Rebasing Silverblue/Kinoite on top of Fedora CoreOS is not "hard" by itself but the infrastructure changes required to make that happen are significant and would require a lot of work.

It is also not really clear if it would really make sense given that the goals and included packages are not the same.

**Comment by blitmap** [comment]
CoreOS is bidding to become an official *edition* of Fedora:

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/OSHZEHWTYSACVKJEPLVL2EVJ3GDY3AE2/

I see 2 advantages:

1) Derive from the existing work of those contributing in CoreOS, freeing up more resources for Silverblue specific features.  Also inheriting CoreOS' security considerations.
2) Attaching to the larger community of Fedora CoreOS.  Volunteers/contributors from both projects would be likely to "cross polinate", and support Silverblue's wider adoption.

**Comment by tpopela** [comment]
We've already talked about this idea in the past (I might have the notes somewhere), but the main problem at that time for Silverblue was that when switching to CoreOS we would have to move away from Anaconda to Ignition and that would mean that we would loose the graphical installer (we are not in the position ATM where we could write our own on top Ignition) and *maybe* that Flatpaks preinstallation that is done by Anaconda as well. I have to say that I really like Colin's idea about the ostree native containers.

**Comment by cgwalters** [comment]
> we would have to move away from Anaconda to Ignition

Not necessarily.  For example, I think a kickstart -> ignition translator would be quite viable.  Also, while a lot of the FCOS documentation is designed around the use of Ignition, nothing requires its *exclusive* use, or honestly even its use at all (although, to suppress the default `core` user would need that, or we'd have to do some other work).  In other words, it would (AFAIK) mostly work to have Anaconda just deploy the FCOS ostree image as is, and just flip the flag that tells Ignition not to require a configuration.

The Ignition and more generally the `coreos-installer` flow is definitely a big aspect of FCOS, but it's not the only one here.

For example, I think automatic updates *on by default* and the "single stream" i.e. not having separate major versioned refs is a big one.  Although again, nothing would require inheriting that either, but the more things that are, the more benefit there is.

**Comment by travier** [comment]
I'll close this issue in favor of the one in the Fedora Atomic Desktop issue tracker: https://gitlab.com/fedora/ostree/sig/-/issues/2

While they are not strictly the same issue, this is one likely to happen as part of that change.

**Comment by blitmap** [comment]
I apologize for commenting on a long-closed thread: My understanding is bootable container images are right around the corner. My hope is that instead of making monolithic images, images are layered at runtime. Somewhere starting simple:

1) Kernel
2) Firmware
3) Nvidia/proprietary graphics
4) Userland
5) Layer representing Kinoite/Silverblue/Sway DE components
