### ISSUE TITLE
[BUG] Several issues in Silverblue open/save dialogs since 20220314 or so

### ISSUE THREAD

**Issue by AdamWill** [fedora-silverblue/issue-tracker#245]
**Describe the bug**
Since Fedora-36-20220314.n.0 or Fedora-36-20220315.n.0, the Open and Save dialogs on Silverblue have changed, and there are some issues openQA ran into. I recall that these dialogs are specially implemented for Silverblue so I'm filing this as a Silverblue-specific issue. The problems:

1. When opening a folder with a single file of the expected type, that file used to show up highlighted in blue, but now it shows up with a grey background sort of outlined in blue: 
![greyblue](https://user-images.githubusercontent.com/916551/158884096-8ba7bd4d-70e0-4ccd-9db7-a8b658e684d7.png)
2. The fonts used on various elements are different. As you can see in that picture, the "Cancel" and "Open" button labels are in boldface; they weren't before, and still aren't on Workstation. The "Name", "Size", "Type" and "Modified" column headers also look a bit odd; they seem smaller, and there are no separators between them. Previously in Silverblue, and still in Workstation, the headers were larger and there were separators between them.
3. When you hit "Save As...", the name portion of the default filename is not pre-selected, as it was before and still is in Workstation. So if you just hit "Save As..." and type "foo" and hit enter, you'll wind up saving the file as 'fooUntitled Document.txt' or 'foopreviousname.pdf' or something like that, rather than 'foo.txt' or 'foo.pdf' as you would previously and still do on Workstation.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install a recent Fedora 36 Silverblue image, run an app like gnome-text-editor or evince, and try opening and saving files.

**Comment by AdamWill** [comment]
I can't tell if this is the case with Rawhide because Silverblue on Rawhide is still running into https://bugzilla.redhat.com/show_bug.cgi?id=2059776 .

**Comment by tpopela** [comment]
Yes, I see it here, but I thought that it's expected. 

> I recall that these dialogs are specially implemented for Silverblue

That's not true. If I'm not mistaken, then these dialogs are provided by the Flatpak portals as GNOME Text Editor or Evince are shipped as Flatpaks on Silverblue (at this moment these are Flatpaks from Fedora 35 - could that play a role). Honestly with Kalev on sabbatical we might actually miss some update in the Fedora 35 Flatpak runtime, but I don't whether it could cause this. @matthiasclasen any idea?

**Comment by AdamWill** [comment]
oh, yeah, that's what I was remembering. Still, it's kinda effectively quite specific to Silverblue, as it's the only thing that ships apps pre-installed as flatpaks.

**Comment by AdamWill** [comment]
Interestingly, eog's "Set Background" dialog has the same bolded button labels:
![eogbold](https://user-images.githubusercontent.com/916551/158891172-4b0ef5ad-23c4-4eae-989e-7e751288a68a.png)
we have a previous version of that screenshot with non-bold button labels (the shade of grey used as the background of the dialog is slightly different too). Current non-flatpak eog shows a bar in the main window rather than a dialog, so can't make a direct comparison to current.

**Comment by AdamWill** [comment]
Looks like indeed Silverblue eog had the 'non-boldface' labels in that dialog in Fedora-36-20220314.n.0, but got the boldface labels in Fedora-36-20220315.n.0.

**Comment by felipeborges** [comment]
These are Portal dialogs provided by https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome

They are GTK4, that's what makes them different from Evince (GTK3).

**Comment by tpopela** [comment]
And there's this build of it https://koji.fedoraproject.org/koji/buildinfo?buildID=1930785 (update to 42.x release) from March 8 that might went into stable few days ago - https://bodhi.fedoraproject.org/updates/FEDORA-2022-21d81706cd - to that might be it..

**Comment by AdamWill** [comment]
Thanks, yeah, that does seem to more or less line up. I guess I'll file an issue there.

**Comment by AdamWill** [comment]
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/20
