### ISSUE TITLE
silverblue 31 installation and boot issue on UEFI 

### ISSUE THREAD

**Issue by MoonLightElf** [fedora-silverblue/issue-tracker#25]
Installation was successful on GPT partitioned USB flash drive. But boot failed. The same issue reproduced on different laptop with USB SSD drive.
Silverblue on BIOS + MBR  USB drive works as expected.

**Comment by MoonLightElf** [comment]
Issues happen in situations as described below.
1. Install silverblue 31 on UEFI + GPT internal drive. The drive  is used .The drive is  not clean,not matter format the ESP or install boot-loader on ESP directly. Installing boot-loader will fail. Sometimes installation finished successfully, but silverblue could not boot from UEFI. (Clean internal SSD may work. But I have not tested.)
2. Install silverblue 31 on UEFI +GPT USB drive. Neither old drive nor brand new drive could not boot silverblue from UEFI.

**Comment by MoonLightElf** [comment]
workaround for GRUB issue on UEFI + GPT platform.
1.Boot silverblue installer on MBR compatible mode.
2.Install silverblue as usual.
3.Make EFI System Partion manually with partitioning tool.
4.Copy /boot including all sub-folders and files to ESP root directory.
5.Setup BIOS to boot from EFI/fedora/grubx64.efi in ESP. 
6.(Optional)If the bios_grub aka grub_core2.img makes the ESP hidden or not be bootable, fix ESP with Gparted.
6.1.(Optional) Hide biosboot partition or delete it.
6.2.(Optional) Mark EFI System Partition with "boot" and "esp" flag.
6.3.(Optional)Reboot and setup BIOS to boot from ESP.

**Comment by martinezjavier** [comment]
@MoonLightElf could you please file a bug in https://bugzilla.redhat.com with product Fedora and component grub2? 

And share all the relevant information about your installed system, specially the content of the following files:

* /boot/efi/EFI/fedora/grub.cfg
* /boot/efi/EFI/fedogra/grubenv
* /boot/loader/entries/*.conf

also if you can share the boot logs with the errors when the machine fails to boot.

**Comment by tpopela** [comment]
Closing this issue, @MoonLightElf please follow the @martinezjavier instructions.
