### ISSUE TITLE
[RFE] Add the 'ncurses' package to the tree to allow the `clear` command to work

### ISSUE THREAD

**Issue by DEM0NAssissan7** [fedora-silverblue/issue-tracker#253]
**Is your feature request related to a problem? Please describe.**
It is related to a problem. The problem is that the `clear` command does not work. The `clear` command is basic and essential for anyone who wants to use a terminal.

**Describe the solution you'd like**
Package the 'ncurses' rpm with the base CoreOS/Fedora system tree to allow the `clear` command to work on the system.

**Describe alternatives you've considered**
To extract the `clear` command from ncurses and package it as a new package (like clear.fc36.rpm).
Either that, or implement it as a bash script.

**Additional context**
![image](https://user-images.githubusercontent.com/42104518/163514417-81d24132-7b22-4886-8fc3-5825e6aef981.png)

**System Information**
From `rpm-ostree status`:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220411.n.0 (2022-04-11T08:14:23Z)
                BaseCommit: ba457eaf75602a9b113040a0417f90721c1d37c05ba2119338af7039c378fa20
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4

**Comment by tpopela** [comment]
Hi @DEM0NAssissan7 ! Thank you for opening the ticket! You're right that this isn't part of the base image (I didn't noticed it myself as it's being pulled in by an overlayed package). I don't have anything against it, I will just sync with @travier - what do you think Timothée?

**Comment by travier** [comment]
We already have ncurses pulled as a dependency on Kinoite from plasma-desktop so agree that we can directly make this an explicit required package.

Made: https://pagure.io/workstation-ostree-config/pull-request/275

**Comment by hferreiro** [comment]
ncurses is already part of Silverblue:

```
$ rpm -q ncurses
ncurses-6.2-8.20210508.fc35.x86_64
```

**Comment by tpopela** [comment]
@hferreiro it's pulled in for you by some package - you can check it with the following script (it will list all overlayed packages and its dependencies that were pulled in):

```
#!/bin/sh

verboseStatus=$(rpm-ostree status -b -v)

baseCommitID=$(echo "$verboseStatus" | grep -Po "BaseCommit:\ \K.*$")
commitID=$(echo "$verboseStatus" | grep -v "BaseCommit" | grep -m 1 -Po "Commit:\ \K.*$")

rpm-ostree db diff "$baseCommitID" "$commitID"
```

**Comment by travier** [comment]
Looks like it was pulled in by some Perl packages in F35 but in F36 anymore.

**Comment by travier** [comment]
It was pulled indirectly by kernel-devel which is no longer in Silverblue by default.

**Comment by travier** [comment]
For F36: https://pagure.io/workstation-ostree-config/pull-request/276

**Comment by tpopela** [comment]
Thank you @travier I think that we can close this for now.
