### ISSUE TITLE
[BUG] after rebase to F36 applications stop reacting to mouse clicks after just a few clicks

### ISSUE THREAD

**Issue by 0xf00f** [fedora-silverblue/issue-tracker#254]
**Describe the bug**

After a rebase to F36 (done on 17.4.2022), applications randomly stop reacting to mouse clicks after just a few clicks. 
After quit and restart the applications work fine for some time, before the problem occurs again.

**To Reproduce**

Many applications are problematic. I noticed this first in the packaged Firefox, Gnome Terminal, and flatpak Gnome Calculator and others.

To reproduce in Gnome Calculator

1. Open Gnome Calculator
2. Using the mouse click the digits 12345678912345..........
3. The application stops reacting to the clicks after about 13-15 digits, the keyboard input continues without issues.
4. I can't close the app via the [X] icon, only via the Top Menu and Quit option (or Ctrl+Q)
5. After a new start, it works OK for a few seconds and then the same thing occurs again.

Similar behavior in the other mentioned apps, it blocks after just a few clicks. In Gnome Terminal I can't even select text output using the mouse. The keyboard input is fine.

I have not tested all included apps.

**Expected behavior**

Applications should not stop reacting to mouse events.

**OS version:**
```
Everything works fine in

fedora:fedora/35/x86_64/silverblue
                   Version: 35.20220417.0 (2022-04-17T21:57:14Z)
                BaseCommit: 83575cdc5c977aaea0ea53fd8a68f42a0e9518e7759c916acf670624afcc5d6a
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F

the issue occurs in

fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220417.n.0 (2022-04-17T08:18:11Z)
                BaseCommit: d9f889696f4149286bfb31954e98d380cc24cfd3fe25f8288879d187cbde96ad
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4

```

**Additional context**

At the very moment the problem occurs there is nothing specific in the journal log.

libinput debug-events shows that all mouse events do occur, so we can conclude that the applications do not react to the events

All layered packages were removed before the rebase, to confirm the issue.
All extensions were removed before the rebase, to confirm the issue.

**Comment by travier** [comment]
This is likely not a Silverblue specific issue. It would be helpful to try and reproduce that on Workstation.

**Comment by 0xf00f** [comment]
> This is likely not a Silverblue specific issue. It would be helpful to try and reproduce that on Workstation.

I have just tried Fedora Workstation 36 Beta (Fedora-Workstation-Live-x86_64-36_Beta-1.4.iso) from a live usb and was not able to reproduce it.

Tried again a rebase to 
  fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220423.n.0 (2022-04-23T08:10:43Z)
                BaseCommit: 78c85db5eb3205fc605a32fea5526c39d12f0479dbfc98f164114effa3cb79df
and I am consistently able to reproduce this in Calculator as many times as needed.

I'd appreciate some pointers on where to start digging to find the cause of the issue.

**Comment by 0xf00f** [comment]
I tried again with a newly created user, and found out that everything is fine.

So it turned out to be a user profile issue, solved by resetting some settings to the defaults. Some of the following solved it.

dconf reset -f /org/gnome/mutter/
dconf reset -f /org/gnome/shell/
dconf reset -f /org/gnome/gnome-session/
dconf reset -f /org/gnome/packagekit/
dconf reset -f /org/gnome/tweaks/
dconf reset -f /org/gnome/login-screen/
