### ISSUE TITLE
[BUG] rpm-ostree: invalid filter directive

### ISSUE THREAD

**Issue by jpds** [fedora-silverblue/issue-tracker#255]
**Describe the bug**

Since upgrading to `35.20220418` from `35.20220414`, every single `rpm-ostree` command shows me:

```
$ sudo rpm-ostree status
ignoring ``: invalid filter directive
...
```

This is a fairly new and vanilla Silverblue installation - so I do not know what could be causing this. I did see an ostree upgrade in the last upgrade run.

**Comment by travier** [comment]
This is https://github.com/coreos/rpm-ostree/issues/3613 which will be part of a new release available soon.
