### ISSUE TITLE
[RFE] Consider extending the list of fonts installed by default on the system

### ISSUE THREAD

**Issue by travier** [fedora-silverblue/issue-tracker#256]
**Is your feature request related to a problem? Please describe.**

Installing new fonts system wide practically requires layering as the instructions from https://docs.fedoraproject.org/en-US/quick-docs/fonts/#unpackaged only mention paths in `/usr` which is read only on rpm-ostree based system like Silverlbue/Kinoite.

Google Chrome also apparently requires dejavu fonts although it does not explicitly requires them in the RPM package. Those fonts are removed from the image in F36.

This is thus not a great user experience.

**Describe the solution you'd like**

We should consider installing some additional and very common fonts by default to make things easier for users. The fonts won't be used by default if I understand the change request linked below.

Workstations users don't have this issue as they can easily install fonts via GNOME Software / dnf.

**Describe alternatives you've considered**

- Figure out alternatives for system wide font management that do not require layering.

**Additional context**

- https://fedoraproject.org/wiki/Changes/DefaultToNotoFonts
- https://pagure.io/fedora-comps/c/59e2ec6627a01a14096f36e5cac5ec68c9daabc3
- https://pagure.io/fedora-comps/c/787345a24b3e423539cf2d8756f704effe0590c4
- https://pagure.io/fedora-comps/c/606182015c82261b0c94891424706ad63ebb4002

**Comment by juhp** [comment]
Chrome flatpak or rpm?

**Comment by tpopela** [comment]
It's the RPM - they have a minimal requirements in the package so it suits all the Linux distributions - https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/rpm/additional_deps;l=1 (the basic ones are not listed there, but are automatically generated)

**Comment by travier** [comment]
Yes, the RPM packaged overlayed.

**Comment by juhp** [comment]
Maybe weak reverse dependencies on chrome could be added to dejavu-fonts?
The Chrome case doesn't really look so ostree specific to me:
I mean if Workstation users of Chrome really need to manually install dejavu fonts that is also a bad experience.

It would be better if Chrome also worked well without dejavu-fonts. How bad is it?

But yes, we want to experiment with tooling for easily adding user fonts in the future.
This has also come up before - for example in the Silverblue Taiga, so thanks for bringing it up here.

**Comment by travier** [comment]
I've just realized that users can add fonts system wide using `/usr/local/share/fonts` and then run `sudo fc-cache -v`.

The docs at https://docs.fedoraproject.org/en-US/quick-docs/fonts/ should mention this path instead of modifying content in `/usr`. I'll update the docs later.

**Comment by travier** [comment]
https://pagure.io/fedora-docs/quick-docs/pull-request/476

**Comment by juhp** [comment]
Maybe worthing mentioning here that I also use `/usr/local/share/fonts` in toolbox for accessing host fonts:

eg
```
sudo mkdir /usr/local/share/fonts
for f in google-noto-cjk google-noto-emoji google-noto-vf stix-fonts; do
    sudo ln -s /run/host/usr/share/fonts/$f /usr/local/share/fonts/
done
```
