### ISSUE TITLE
[BUG] Software: “No updates have been installed on this system.”

### ISSUE THREAD

**Issue by aral** [fedora-silverblue/issue-tracker#258]
**Describe the bug**

I got a notification that an app update had been installed. Clicking on the notification opened the Updates tab of Software.

However, the message there was as follows:

![Screenshot from 2022-04-21 18-00-57](https://user-images.githubusercontent.com/41798/164513210-7b04bfc1-f830-437e-9f7e-04cbdbc11a0f.png)

Closing that dialog showed me the following screen:

![Screenshot from 2022-04-21 18-01-06](https://user-images.githubusercontent.com/41798/164513332-bfb7eff5-510a-4865-b8ec-dc0d1a9a8327.png)

**Expected behavior**

If a notification says an app has been updated, the app should reflect the same thing.

**OS version:**
```
fedora:fedora/36/x86_64/silverblue
Version: 36_Beta.1.4 (2022-03-22T03:27:52Z)

BaseCommit: 99b8bb190924784dd5a3076f830a4bf70f21a34437b3762abba8ca416e9c9798
LayeredPackages: gstreamer1-plugin-openh264 langpacks-en mozilla-openh264
```

**Additional context**

Possibly related to #257

**Comment by RDKRACZ** [comment]
This also happens on stable 35 release

**Comment by mcrha** [comment]
This is filled as https://gitlab.gnome.org/GNOME/gnome-software/-/issues/667
