### ISSUE TITLE
[BUG] openssl has problems with multiple versions of openssl-libs

### ISSUE THREAD

**Issue by neildarlow** [fedora-silverblue/issue-tracker#259]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
Cannot install openssl on fedora Silverblue 36 Beta due to conflicts with multiple openssl-libs package versions.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. .. Execute rpm-ostree install openssl (new install) or rpm-ostree upgrade (rebased Silverblue 35).

**Expected behavior**
The package openssl should be installed or (subject to an update being available) updated.

**Screenshots**
`error: Could not depsolve transaction; 1 problem detected:
 Problem: cannot install both openssl-libs-1:3.0.2-1.fc36.x86_64 and openssl-libs-1:3.0.2-3.fc36.x86_64
  - package openssl-1:3.0.2-1.fc36.x86_64 requires openssl-libs(x86-64) = 1:3.0.2-1.fc36, but none of the providers can be installed
  - conflicting requests`

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220421.n.0 (2022-04-21T08:12:28Z)
                BaseCommit: 9f0c838bc9121906f66e831a9209c6768c78f526045deb6c1a253040239523c6
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: cheese gpaste-ui langpacks-en langpacks-en_GB mozilla-openh264 openssl simple-scan wireguard-tools
```

**Additional context**
openssl is being installed to satisfy the GNOME Shell eclipse (clipboard history) extension.

**Comment by travier** [comment]
This most likely is because we don't yet have the archive repo enabled. This will fix itself once we enable that after the release. You can download the previous version of the package and overlay it in the mean time or wait for the next build (happen daily).

**Comment by tpopela** [comment]
@travier I'm being hit by something similar (or the same), but I see the following from Thursday:

```
 Problem 1: package git-2.35.1-1.fc36.x86_64 requires git-core = 2.35.1-1.fc36, but none of the providers can be installed
  - cannot install both git-core-2.35.1-1.fc36.x86_64 and git-core-2.36.0-1.fc36.x86_64
  - package tig-2.5.5-2.fc36.x86_64 requires git, but none of the providers can be installed
  - conflicting requests
 Problem 2: package vim-common-2:8.2.4621-1.fc36.x86_64 requires vim-data = 2:8.2.4621-1.fc36, but none of the providers can be installed
  - cannot install both vim-data-2:8.2.4621-1.fc36.noarch and vim-data-2:8.2.4804-1.fc36.noarch
  - package vim-enhanced-2:8.2.4621-1.fc36.x86_64 requires vim-common = 2:8.2.4621-1.fc36, but none of the providers can be installed
  - conflicting requests
```
, but both errors are about old versions of packages (tig, vim-enhanced) that are not part of the current deployment:

```
$ rpm -q vim-enhanced tig
vim-enhanced-8.2.4701-1.fc36.x86_64
tig-2.5.5-3.fc36.x86_64
```

I do have the updates-testing enabled all the time (if it makes any difference).

**Comment by SjoerdB93** [comment]
> I do have the updates-testing enabled all the time (if it makes any difference).

Didn't they close the testing repo's? I don't think there's any point to have them enabled by now. I had a dependency conflict like this earlier, and rebasing away from the testing branch of Silverblue actually solved it back then. Now I've got the same issue as described in the opening post, coming from the Nvidia drivers:
```
 Problem: conflicting requests
  - package akmod-nvidia-3:510.60.02-1.fc36.x86_64 requires akmods, but none of the providers can be installed
  - package akmods-0.5.7-7.fc36.noarch requires openssl, but none of the providers can be installed
  - package openssl-1:3.0.2-1.fc36.x86_64 requires openssl-libs(x86-64) = 1:3.0.2-1.fc36, but none of the providers can be installed
  - cannot install both openssl-libs-1:3.0.2-1.fc36.x86_64 and openssl-libs-1:3.0.2-3.fc36.x86_64
```

Hopefully it will be fixed before release as the current target release is two weeks away. But either way it will probably fix itself at one point when the correct repo is enabled, folks are aware of this. In the meantime I've just rebased back to Fedora 35 for now as I prefer to keep my system updated and need my Nvidia drivers. Will check again later this week.

**Comment by neildarlow** [comment]
From the initial response to my report, the problem is caused by the Archive repository not being enabled. I assume that previous packages get moved there when updated ones arrive such that there's only one version ever available in the image. Until that repository is enabled older versions of packages will accumulate and cause this issue to manifest. When Silverblue is officially released the problem will go away.

**Comment by tpopela** [comment]
@dustymabe is there anything that we can do about this so users are not cut from updates (of course without removing the overlayed packages)?

**Comment by dustymabe** [comment]
Indeed this is most likely because the archive repo isn't enabled yet for F36.

Usually issues like this are resolved if you upgrade to tip before layering (or do it in one operation via `rpm-ostree upgrade --install openssl`). I would **NOT** recommend enabling the `updates-testing` yum repo because you're just going to ask for this situation to occur constantly.

**Comment by tpopela** [comment]
@dustymabe I've overlayed these packages when I was doing a new installation few months ago (and I didn't overlay anything new recently). Also I didn't enabled the updates-testing yum repository, but I'm using the `fedora/36/x86_64/testing/silverblue` remote.

I might sound stupid, but I really don't know why the lack of archive repo is preventing me from getting the updates (I've always been using the testing remote in the past before the particular Fedora version is released to get the updates as the stable repositories are frozen due to various freezes). As mentioned in https://github.com/fedora-silverblue/issue-tracker/issues/259#issuecomment-1108122579 both errors are about package versions that are no longer in the current deployment (36.20220418.0 (2022-04-18T12:50:09Z)).

**Comment by dustymabe** [comment]
> Also I didn't enabled the updates-testing yum repository, but I'm using the `fedora/36/x86_64/testing/silverblue` remote.

@tpopela Sorry for being misleading. I wasn't aware you were using the `fedora/36/x86_64/testing/silverblue` remote. If you are using that ref then you will often hit this problem (and we'll never fix that because we won't put packages that haven't hit stable into the archive repo). 

@tpopela Since you are using the testing ref you **will** need to enable the `updates-testing` yum repo. Then the `rpm-ostree upgrade --install openssl` should work.

**Comment by saulfgonzalez** [comment]
> Indeed this is most likely because the archive repo isn't enabled yet for F36.
> 
> Usually issues like this are resolved if you upgrade to tip before layering (or do it in one operation via `rpm-ostree upgrade --install openssl`). I would **NOT** recommend enabling the `updates-testing` yum repo because you're just going to ask for this situation to occur constantly.

I was having the same issue and this solution worked for me (thanks!) 

I would like to know what the difference is between running the command `rpm-ostree upgrade --install openssl` and running separately `rpm-ostree upgrade` and `rpm-ostree install openssl`, which was the first thing I tried and did not work. What does 'upgrade to tip' mean?

**Comment by travier** [comment]
> I would like to know what the difference is between running the command `rpm-ostree upgrade --install openssl` and running separately `rpm-ostree upgrade` and `rpm-ostree install openssl`, which was the first thing I tried and did not work. What does 'upgrade to tip' mean?

The first one does everything in one transaction. The second one in two transactions.
