### ISSUE TITLE
Software's home page is missing sections

### ISSUE THREAD

**Issue by allanday** [fedora-silverblue/issue-tracker#26]
There are several sections missing from the Software home page on Silverblue:

![Screenshot from 2020-01-08 14-58-19](https://user-images.githubusercontent.com/213068/71988425-cba62c80-3227-11ea-94fa-d60aaaf5d1ab.png)

This wasn't an issue for me on a regular Fedora install.

**Comment by HarryMichal** [comment]
Is this still an issue with the redesigned GNOME Software?

**Comment by travier** [comment]
Closing as this is likely stale.
