### ISSUE TITLE
[BUG] Sorry, something went wrong: No such ref 'app/org.gnome.font-viewer/x86_64/stable' in remote fedora in Software → Updates

### ISSUE THREAD

**Issue by aral** [fedora-silverblue/issue-tracker#260]
**Describe the bug**

Got the following error when I opened the Updates tab in Software:

```
Sorry, something went wrong: No such ref 'app/org.gnome.font-viewer/x86_64/stable'
```

**To Reproduce**

Not sure whether it’s reproducible.

**Expected behavior**

There should not be an error.

**Screenshots**

![Screenshot from 2022-04-27 14-05-48](https://user-images.githubusercontent.com/41798/165525336-ddd0f9eb-c45d-4f1c-825e-4a971abf23b6.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220421.n.0 (2022-04-21T08:12:28Z)
                BaseCommit: 9f0c838bc9121906f66e831a9209c6768c78f526045deb6c1a253040239523c6
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: distrobox fish gstreamer1-plugin-openh264 langpacks-en mozilla-openh26
```

**Additional context**

n/a

**Comment by travier** [comment]
Likely fixed now. Feel free to reply here if it's still an issue.
