### ISSUE TITLE
[BUG] Keyboard shortcut for IBus emoji picker overrides GNOME emoji picker

### ISSUE THREAD

**Issue by aral** [fedora-silverblue/issue-tracker#261]
## Summary

Pressing <kbd>CTRL</kbd><kbd>.</kbd> (period) brings up the IBus emoji picker. It should bring up the GNOME emoji picker popover.

## To reproduce

1. Open _Text Editor_
2. In the document, press <kbd>CTRL</kbd><kbd>.</kbd> (period)

## What should happen

The GNOME emoji picker popover should appear.

The keyboard shortcut for the IBus picker should be reverted to <kbd>Ctrl</kbd><kdb>Shift</kbd><kbd>e</kbd> (which was the original shortcut, is also consistent with the letter you see appear on screen, and consistent with the IBus shortcut for entering a unicode character, which is <kbd>Ctrl</kbd><kdb>Shift</kbd><kbd>u</kbd>).

## What actually happens

The IBus emoji picker appears (you see an underlined `e` and you enter a modal state where you can type the name of an emoji and press space to have it inserted or space again to see a popover with related emojis).

### IBus emoji picker (with result of `smile`<kbd>space</kdb>)

![Screenshot from 2022-04-27 15-39-25](https://user-images.githubusercontent.com/41798/165544445-348a6828-f912-43e5-926b-29ebf537009b.png)

### GNOME emoji picker

![Screenshot from 2022-04-27 15-40-04](https://user-images.githubusercontent.com/41798/165544451-94b43fef-c56e-4fc7-a1ad-c6ec7ea02fb6.png)

## OS version:

```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220425.n.0 (2022-04-25T08:12:33Z)
                BaseCommit: aed492e0e146c40c8ef503f3240748611df5e18f18d30ae5ee8c68a347f15600
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: distrobox gstreamer1-plugin-openh264 langpacks-en mozilla-openh264
```

## Additional context

Apparently this change was introduced in https://fedoraproject.org/wiki/Changes/IBus_1.5.25 (thanks to https://social.nahuelwexd.com/@nahuel/108204246431008582 for the sleuthing).

**Comment by narFnarF** [comment]
May I suggest to use the Super key (Windows key) instead?
`Super`+`.`

I feel it would have less conflict with other apps using `Ctrl`+`.` (I assume?)

It would also be consistent with how the shortcut for emoji picker on Windows, which would help discoverability of the feature. (for real, I would have _never_ discovered that feature were it not for Aral mentionning it on Mastodon)

**Comment by juhp** [comment]
@aral You _can_ change the ibus shortcut in ibus-setup

@narFnarF there is some discussion in ibus/ibus#2390

**Comment by tpopela** [comment]
I will close this as it's not specific to Silverblue and it's handled in the issue that Jens mentioned.

**Comment by aral** [comment]
@juhp Thanks, Jen. I did already change it for myself but this really should work by default. I hope the linked-to issue will address this when it is handled but I do feel this could be worked around in Silverblue in the meanwhile as it seems like the kind of thing that will likely persist for a while if we’re to wait for GNOME/IBus to coordinate.

I’m thinking of creating a “Silverblue fixes” script you can run to fix issues with defaults (like missing codecs for web video in Firefox, etc.) I’ll add this there and share it as a temporary workaround until then.
