### ISSUE TITLE
[BUG] firewall-config: command not found

### ISSUE THREAD

**Issue by aral** [fedora-silverblue/issue-tracker#262]
## Summary

According to the Fedora documentation (https://docs.fedoraproject.org/en-US/quick-docs/firewalld/#sec-Viewing_Current_firewalld_Settings), there should be a graphical firewall configuration app available. It doesn’t seem to exist in Silverblue. 

## To reproduce

1. Open a terminal window
2. Type: `firewall-config`

## What should happen

It should run.

## What actually happens

```
bash: firewall-config: command not found
```

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220425.n.0 (2022-04-25T08:12:33Z)
                BaseCommit: aed492e0e146c40c8ef503f3240748611df5e18f18d30ae5ee8c68a347f15600
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: gnome-console gnome-tweak-tool gstreamer1-plugin-openh264 langpacks-en lm_sensors mozilla-openh264
```

**Comment by tpopela** [comment]
Hi @aral, firewall-config isn't even preinstalled on Fedora Workstation so the documentation is misleading and might need to be updated to mention that one needs to install the firewall-config package before trying to use it - feel free to report that in https://pagure.io/fedora-docs/quick-docs/new_issue?title=[master]%20Doc%20issue%20in%20file%20modules%2FROOT%2Fpages%2Ffirewalld.adoc . I also should note that Silverblue and Workstation ship by default with the opened firewall - see i.e. the recent https://pagure.io/fedora-workstation/issue/303 .

**Comment by aral** [comment]
@tpopela Thanks; appreciate the info. My use case was allowing port 80 and 443 for an incoming http/https tunnel for web development. As far as I can see, incoming connections are not open (nor should they be by default, so that’s good.) :)

Hopefully the documentation folks will see this issue or a process will be implemented where issues can be migrated between repositories. (I don’t have a Fedora account.)
