### ISSUE TITLE
[BUG] FreeIPA Enterprise sign-in fails to map subUID and subGID

### ISSUE THREAD

**Issue by StarkZarn** [fedora-silverblue/issue-tracker#263]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
ipa-client does not honor subuid/subgid configured on FreeIPA server. Additionally, creation of a drop-in config file for authselect to populate nsswitch.conf with `subid:  sss` does not appear to work either. Consequently, no subUID or subGID is assigned for domain users which prevents toolbox from working.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Configure a user in FreeIPA, assign subIDs.
2. Starting with a clean silverblue install, run `sudo rpm-ostree install ipa-client`
3. Run `sudo ipa-client-install` with relevant parameters and join the domain/realm.
4. Run `toolbox create`

**Expected behavior**
A user as defined in FreeIPA server should receive subID mappings on enrolled clients, allowing toolbox to work. I don't know for sure, but I would expect this to be reflected in /etc/nsswitch.conf with the `subid` key.

**Screenshots**
N/A

**OS version:**
```
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220501.n.0 (2022-05-01T08:14:53Z)
                BaseCommit: a9969b0c62ebc35d48ae6a472b3154380e6789906e18fa0ca4e806152e2b6d1a
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: ipa-client vim zsh
                    Pinned: yes
```

**Additional context**
I did find notes in FreeIPA documentation talking about this, and it seems like a relatively new feature. I thought maybe despite being on 36 beta, I just didn't have a new enough version of ipa-client and related packages. Running `sudo rpm-ostree update` now yields package conflicts and ipa-client can't be updated.

```
user@hostname]~% sudo rpm-ostree upgrade
⠒ Receiving metadata objects: 1/(estimating) 196 bytes/s 196 bytes... 
Receiving metadata objects: 1/(estimating) 196 bytes/s 196 bytes... done
Checking out tree a8cc56d... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora phracek-PyCharm rpmfusion-nonfree-nvidia-driver rpmfusion-nonfree-steam google-chrome updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2022-04-07T16:52:38Z solvables: 4
rpm-md repo 'fedora-modular' (cached); generated: 2022-05-01T10:02:44Z solvables: 825
rpm-md repo 'updates-modular' (cached); generated: 2022-02-08T18:40:58Z solvables: 0
rpm-md repo 'updates' (cached); generated: 2022-02-08T18:40:57Z solvables: 0
rpm-md repo 'fedora' (cached); generated: 2022-05-01T10:06:39Z solvables: 67991
rpm-md repo 'phracek-PyCharm' (cached); generated: 2022-04-21T04:01:32Z solvables: 5
rpm-md repo 'rpmfusion-nonfree-nvidia-driver' (cached); generated: 2022-04-29T13:28:49Z solvables: 29
rpm-md repo 'rpmfusion-nonfree-steam' (cached); generated: 2022-02-13T17:48:12Z solvables: 2
rpm-md repo 'google-chrome' (cached); generated: 2022-05-02T16:10:54Z solvables: 3
rpm-md repo 'updates-archive' (cached); generated: 2022-02-11T15:18:19Z solvables: 0
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: package sssd-common-2.7.0-1.fc36.x86_64 requires (libsss_autofs(x86-64) = 2.7.0-1.fc36 if autofs), but none of the providers can be installed
  - package freeipa-client-4.9.8-3.fc36.x86_64 requires autofs, but none of the providers can be installed
  - conflicting requests
```

**Comment by zemsten** [comment]
The note I made about package upgrade failures in "Additional context" has been resolved with repo updates. Still running into problems with subUID/subGID though.

**Comment by travier** [comment]
This likely need to be reported upstream to ipa-client to start a discussion and verify that this is currently supported on F36.

**Comment by travier** [comment]
Looks like this is fixed now.
