### ISSUE TITLE
[BUG] Cannot exit Help screen in Installer

### ISSUE THREAD

**Issue by alaviss** [fedora-silverblue/issue-tracker#264]
**Describe the bug**
If you open the help screen in the installer, you cannot close it.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Boot into the installer
2. Click "Help"

**Expected behavior**
A visible button to close the help screen

**Screenshots**
![Screenshot from 2022-05-05 13-01-18](https://user-images.githubusercontent.com/4961280/166984854-cf8bffba-d088-48ea-b4a1-58d96505bfdb.png)

**OS version:**
Fedora Silverblue 35

**Additional context**
I could not reproduce this in regular Fedora Workstation ISO. This was done in Boxes VM.

**Comment by felipeborges** [comment]
This has been fixed in yelp 42 (available in the upcoming Fedora 36) with the port to libhandy's HdyApplicationWindow.
