### ISSUE TITLE
Question: Is gnome-classic-session needed?

### ISSUE THREAD

**Issue by dschier-wtd** [fedora-silverblue/issue-tracker#27]
Hi,

as far as I understood, Fedora Silverblue should be a very modern and leightweight Fedora Distribution. Therefore I think, the removal of the following features / packages should be discussed:

- gnome-classic-session
- gnome-shell-extension-window-list
- gnome-shell-extension-horizontal-workspace
- gnome-shell-extension-launch-new-instance
- gnome-shell-extension-places-menu
- gnome-shell-extension-apps-menu
- gnome-shell-extension-user-theme

Arguments to remove them:

If someone wants to have the gnome-classic-session, rpm will pull in the needed extensions anyway during rpm-ostree install.
extensions.gnome.org lists updates for all of them, almost immediately after each fedora release.

The other 2 preinstalled extensions are out of discussion, from my perspective.

- gnome-shell-extension-background-log -> seems to be there for branding purpose

**Comment by tpopela** [comment]
We were discussing this during our Silverblue planning meeting and we decided that we will leave it in the base image for F32, but we might reconsider that for F33 (we might do a survey to get idea whether the Classic session is extensively used among Silverblue users).

**Comment by Mershl** [comment]
As this issue is still open I'd like to use it to revive this topic for F34. @tpopela Can you give a short update on the topic?

**Comment by tpopela** [comment]
Hi @Mershl , nothing changed as we did have different priorities. Right now it's late for F34, but we might do the survey in the following weeks and target Silverblue 35 with the change. I will keep you updated.

**Comment by tpopela** [comment]
I've opened https://discussion.fedoraproject.org/t/poll-gnome-classic-session-in-silverblue/28299

**Comment by jvnknvlgl** [comment]
Maybe in cojunction with this: does the Xorg session make sense for Silverblue? Especially considering there are now standalone Xwayland releases. The only reason I can see someone using Xorg over Wayland + Xwayland right now would be Nvidia, and that's not really something that works well in Silverblue anyway.

**Comment by daniel-wtd** [comment]
> Maybe in cojunction with this: does the Xorg session make sense for Silverblue? Especially considering there are now standalone Xwayland releases. The only reason I can see someone using Xorg over Wayland + Xwayland right now would be Nvidia, and that's not really something that works well in Silverblue anyway.

Not the majority, but at least the most popular silverblue youtuber uses nvidia. Since it is a scenario which may be needed at least in official edition, I suggest keeping it for now.

**Comment by Mershl** [comment]
> Maybe in cojunction with this: does the Xorg session make sense for Silverblue? Especially considering there are now standalone Xwayland releases. The only reason I can see someone using Xorg over Wayland + Xwayland right now would be Nvidia, and that's not really something that works well in Silverblue anyway.

rpm-fusion has taken great care for their nvidia package to work well on Silverblue, despite being proprietary. Independent of nvidia I think it's too early to drop the Xorg session - personally (as a AMDGPU user) I still have a use-case for the Xorg session with CS:GO where xwayland/mutter have an open issue for frame skips on mouse input.

**Comment by jvnknvlgl** [comment]
@daniel-wtd @Mershl: that's fair, hopefully we can get there in a few releases then.

> rpm-fusion has taken great care for their nvidia package to work well on Silverblue. I've heard it working quite well, despite being a layered package.

I wasn't aware that akmod-nvidia works okay on Silverblue, then maybe I did something wrong when I tried it last week on my ThinkPad P51, but I trust that the people over at RPM Fusion know what they are doing. Nice to hear!

**Comment by travier** [comment]
Given that this amounts to 1.2MB for a potentially useful functionality for some users, I'd say it safe to keep it in:

```
$ du -shc $(rpm -ql gnome-classic-session-42.3-1.fc36.noarch gnome-classic-session-42.3-1.fc36.noarch gnome-shell-extension-common-42.3-1.fc36.noarch gnome-shell-extension-apps-menu-42.3-1.fc36.noarch gnome-shell-extension-launch-new-instance-42.3-1.fc36.noarch gnome-shell-extension-places-menu-42.3-1.fc36.noarch gnome-shell-extension-window-list-42.3-1.fc36.noarch gnome-shell-extension-background-logo-42.0-1.fc36.noarch)
...
1.2M    total
```

This will likely be removed once Workstation decides to remove it from the default installation.
