### ISSUE TITLE
[BUG] gnome-software Crashes on startup on Silverblue 36.20220510.0

### ISSUE THREAD

**Issue by tmstaedt** [fedora-silverblue/issue-tracker#270]
After today's update, gnome-software does not start anymore. Worked until previous deployment:

https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1761

**Comment by tpopela** [comment]
Thank you @tmstaedt for reporting it here. I see that it's being already handled by Milan and he moved the bug to rpm-ostree with https://bugzilla.redhat.com/show_bug.cgi?id=2083715.

**Comment by tpopela** [comment]
@dustymabe @travier is it possible to move the bug into https://github.com/coreos/rpm-ostree/issues or one has to create a new bug there?

**Comment by dustymabe** [comment]
I think maybe let's wait and see where https://bugzilla.redhat.com/show_bug.cgi?id=2083715 goes.

**Comment by tmstaedt** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2022-af207692d6
Solved.

**Comment by travier** [comment]
Closing as per above. Feel free to reopen if this is not fixed.

**Comment by tmstaedt** [comment]
Issue seems to have resurfaced after today's update:

23:50:05:0652 Gs  Failed to setup plugins: Failed to create: /var/cache/rpm-ostree/repomd


tom@linux2 ~]$ rpm-ostree status
State: idle
Deployments:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220617.0 (2022-06-17T00:45:03Z)
                BaseCommit: 5bf39cb84b31d36af49e07dfb57a5c531ad7c13a8b2df91397494bea9bf6e871
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
      ReplacedBasePackages: rpm-ostree-libs rpm-ostree 2022.10-2.fc36 -> 2022.9-1.fc36
           LayeredPackages: cpulimit f36-backgrounds fuse-sshfs gnome-tweak-tool google-chrome
                            google-roboto-condensed-fonts google-roboto-mono-fonts gstreamer1-libav
                            gstreamer1-plugin-openh264 lm_sensors rpmfusion-free-release rpmfusion-nonfree-release
                            sqlitebrowser virt-manager


Worked in previous deployment

**Comment by tmstaedt** [comment]
Well, it was probably time for the rpm-ostree override reset.

But surprisingly, that did not work:

00:22:01:0726 Gs  Failed to setup plugins: failed to obtain lock 'metadata': Datei »/var/run/dnf-metadata.lock.Z4GLO1« konnte nicht angelegt werden: Keine Berechtigung

**Comment by tmstaedt** [comment]
Hmm. Strange confusion. After some upgrade-rollback.., things work again. I guess I should have made the 
`rpm-ostree override reset rpm-ostree rpm-ostree-libs` right away.

Since gnome-software did not come up, I did a rpm-ostree upgrade from terminal, and after reboot, gnome-software crashed.

Now my rpm-ostree status looks like this:

tom@linux2 ~]$ rpm-ostree status
State: idle
Deployments:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220617.0 (2022-06-17T00:45:03Z)
                BaseCommit: 5bf39cb84b31d36af49e07dfb57a5c531ad7c13a8b2df91397494bea9bf6e871
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: cpulimit f36-backgrounds fuse-sshfs gnome-tweak-tool google-chrome
                            google-roboto-condensed-fonts google-roboto-mono-fonts gstreamer1-libav
                            gstreamer1-plugin-openh264 lm_sensors rpmfusion-free-release rpmfusion-nonfree-release
                            sqlitebrowser virt-manager

  fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220617.0 (2022-06-17T00:45:03Z)
                BaseCommit: 5bf39cb84b31d36af49e07dfb57a5c531ad7c13a8b2df91397494bea9bf6e871
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
      ReplacedBasePackages: rpm-ostree-libs rpm-ostree 2022.10-2.fc36 -> 2022.9-1.fc36
           LayeredPackages: cpulimit f36-backgrounds fuse-sshfs gnome-tweak-tool google-chrome
                            google-roboto-condensed-fonts google-roboto-mono-fonts gstreamer1-libav
                            gstreamer1-plugin-openh264 lm_sensors rpmfusion-free-release rpmfusion-nonfree-release
                            sqlitebrowser virt-manager
                    Pinned: yes
