### ISSUE TITLE
[BUG] Flatpak versions of pre-installed packages trail Workstation

### ISSUE THREAD

**Issue by JamesBelchamber** [fedora-silverblue/issue-tracker#273]
The following pre-installed applications are on older versions in Silverblue 36 than Workstation 36:

| Application         | Workstation Version | Workstation Updates | Silverblue Version         |
|---------------------|---------------------|---------------------|----------------------------|
| Calculator          | 42.0                | None                | 41.0                       |
| Calendar            | 42.0                | 42.1                | 41.1                       |
| Characters          | 42.0                | None                | 41.0                       |
| Connections         | 42.1.1              | 42.1.2              | 41.2                       |
| Contacts            | 42.0                | None                | 41.0                       |
| Document Viewer     | 42.1                | 42.2                | 41.3                       |
| Extensions          | <not installed>     | 42.0                | 41.rc                      |
| Logs                | 42.0                | None                | 3.36 (Flatpak mislabelled) |
| Maps                | 42.0                | 42.1                | 41.4                       |
| Sushi               | 41.2                | None                | 41.0                       |
| Text Editor         | 42.0                | 42.1                | 41.1                       |
| Weather             | 42.0                | None                | 41.0                       |
| Disk Usage Analyser | 42.0                | None                | 41.0                       |
| Clocks              | 42.0                | None                | 41.0                       |
| Image Viewer        | 42.0                | 42.1                | 41.1                       |
| Fonts               | 42.0                | None                | 41.0                       |

In addition, Fedora Platform is still on Version 35. Generally, the Fedora Flatpaks seem to be behind the Fedora RPMs.

**Comment by tpopela** [comment]
Yes, that's expected at this point. The work on F36 Flatpak runtime is in progress and should be finished during next week. Then we will start to rebuild the applications against it and start to ship them to users.

**Comment by JamesBelchamber** [comment]
My understanding was that Fedora Flatpaks were updated alongside the RPMs as part of the same build process. I've been digging around koji and bodhi to get an idea of what's happening, but I think I can see many updates that are pushed out as RPMs but not as Flatpaks.

Taking gnome-calculator as an example, I can see that [the RPM](https://src.fedoraproject.org/rpms/gnome-calculator/commits/rawhide) has a busier commit log than [the Flatpak](https://src.fedoraproject.org/flatpaks/gnome-calculator/commits/stable).

Do Fedora Flatpaks not get all the updates that Fedora RPMs do?

**Comment by tpopela** [comment]
It's a manual process - the Flatpak maintainer needs to build Flatpak after the RPM package maintainer builds it. In past we had Kalev working on this, but he's on a long term leave, so we are trying do our best now (things should settle and be stable in few weeks).

**Comment by JamesBelchamber** [comment]
Is the process documented? Can I help? I would also be interested in whether we can add Flatpak to the pipeline as an automated step after the RPMs are updated - possibly if I learn the process I can make some proposals there :eyes:

**Comment by tpopela** [comment]
No it isn't (apart from what is in https://docs.fedoraproject.org/en-US/flatpak/). Are you an active Fedora packager? Or even better a proven packager? Because otherwise it's nearly impossible to do anything (do the builds and so on). For the automation - I suspect that Owen Taylor might know whether there's a way to automate this - I will ask him to comment here.

**Comment by JamesBelchamber** [comment]
I'm not, no. I've got a reasonable amount of experience with build pipelines, and I think I could help with this, but I'm not an active Fedora packager.

**Comment by travier** [comment]
@JamesBelchamber Let's get you started on the road to become a packager to enable you to help us test things here: https://docs.fedoraproject.org/en-US/package-maintainers/Joining_the_Package_Maintainers/

Then we can probably create a group (or there is maybe already one) to grant access to GNOME Flatpaks. WDYT @tpopela ?

**Comment by tpopela** [comment]
@travier yes, I'm thinking about the same. The group will have the co-maintainer status on the stuff inside the flatpaks namespace (GNOME ones, but I think that we can extend it as most Fedora Flatpaks are handled by people from our team). I will look into that once I have the F36 runtime and followup builds ready.

**Comment by JamesBelchamber** [comment]
I'm working through the "Joining the Package Maintainers" page now; I guess in addition to this I will need to find details of how the Flatpaks are built ([this seems relevant](https://docs.fedoraproject.org/en-US/flatpak/)).

In the mean time, on a personal level I've just switched entirely to the Flathub GNOME Flatpaks. I note this is also how Kinoite sources their Flatpaks, and.. it seems fine? I know there are technical differences between the builds but.

Maybe packages that Fedora wants to version alongside the OS should be distributed as part of the base image (or auto-installed layers), with the rest sourced from Flathub? Now the filter is in place this would be fairly trivial to implement, and it would reduce the delta between Silverblue and Workstation (as well as the work that goes into maintaining packages that Silverblue relies on).

**Comment by pauldoo** [comment]
> In the mean time, on a personal level I've just switched entirely to the Flathub GNOME Flatpaks.

> Maybe packages that Fedora wants to version alongside the OS should be distributed as part of the base image (or auto-installed layers), with the rest sourced from Flathub?

I have done something similar.  An issue that I encountered doing that is that some of the Fedora flatpaks are newer than the ones on Flathub.  If the data formats aren't backwards compatible then migrating from Fedora flatpak to the older Flathub flatpak results in errors.

Shotwell is a good example.  The Fedora flatpak is currently on v0.31.3, while Flathub has v0.30.14.  When I switched to the Flathub one it failed to launch (complained about the database version).

**Comment by tpopela** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2022-16d56b1bde (Fedora 36 Flatpak runtime) and https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2022-274a792493 (updated Silverblue default flatpaked application set moved to F36)

Karma is more than welcomed.

**Comment by tpopela** [comment]
Sadly any testing or even deployment (once it's pushed into stable) is blocked by https://pagure.io/fedora-infrastructure/issue/10716

**Comment by Verhoeckx** [comment]
What is the status of this issue?
Is it still blocked?

**Comment by tpopela** [comment]
> What is the status of this issue? Is it still blocked?

Yes, the issue that I've mention above is still unresolved and the whole thing is blocked by it.

**Comment by tpopela** [comment]
Thank you everyone for your patience!
