### ISSUE TITLE
[BUG] gnome-calculator search provider does not work in gnome-shell

### ISSUE THREAD

**Issue by fastrizwaan** [fedora-silverblue/issue-tracker#278]
**Describe the bug**
gnome-calculator search provider does not work 
 /usr/libexec/gnome-calculator-search-provider in flatpak perhaps do not have access to gnome-shell.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. press super key
2. type 2+2

**Expected behavior**
should show gnome calculator like this:

**Screenshots**
![image](https://user-images.githubusercontent.com/1161682/168468550-aa36d991-79c0-4663-92ef-ffe6f38abb57.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220514.0 (2022-05-14T00:45:42Z)
                BaseCommit: 37a03048e5cebd64eb20ad9ff42ad4b7672a7722e9d1f3a6705927c64bb8bbfa
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: 'python*subliminal' encfs flatpak-builder gedit 
                            gnome-tweaks kmod-nvidia meson ninja-build openssl pip tilix
                            xgamma
```

**Additional context**
layering gnome-calculator and removing flatpaked gnome-calculator is a workaround.

**Comment by bobslept** [comment]
On my system it does work. Do you maybe have turned of the Application Search in your settings? 
![image](https://user-images.githubusercontent.com/38557801/168486569-4aa79648-2311-400a-a824-4111fc6604fb.png)
Gives this for me:
![image](https://user-images.githubusercontent.com/38557801/168486620-822c9460-a816-4f7f-8f9e-6c4dfb956ac3.png)

**OS Version**
```
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220515.0 (2022-05-15T00:41:11Z)
                BaseCommit: 4dbd8bd48d7c2faee058ee3735197dfd04acde3635a5211a83cc863d2a69de3b
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
       RemovedBasePackages: firefox 100.0-4.fc36
```

**Comment by fastrizwaan** [comment]
yes, application search was off for gnome calculator. thanks.
