### ISSUE TITLE
No cursor on boot

### ISSUE THREAD

**Issue by kisccz** [fedora-silverblue/issue-tracker#279]
Occasionally when I boot up my computer, after logging in to my account, I have no cursor and my touchpad does not work at all. The only way to fix this I have noticed is to reboot my computer

**Comment by travier** [comment]
This is likely not a Silverblue specific issue.
- What is your current version? `rpm-ostree status`
- Is this reproducible with a fresh new user?
- Is this reproducible with a Workstation LiveISO?

**Comment by travier** [comment]
Closing as this is missing info required for investigation.
