### ISSUE TITLE
[BUG] Password prompt box opens repeatedly on new install of fedora 36

### ISSUE THREAD

**Issue by millerthegorilla** [fedora-silverblue/issue-tracker#280]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
When logged into standard account on recently installed or upgraded to fedora 36, pam auth password box appears requesting to update sofware, 6 or 7 times in succession.  This occurs several times, about an hour apart.  its very annoying.  I have tried changing /etc/rpm-ostreed.conf to 'stage', but I still get the password prompts.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. ..Install or upgrade to fedora 36 silverblue
2. ..create a sudo account and a std user account
3. ..login to std account.  Within a few minutes, update software password prompt appears,again, and again, and again etc...

**Expected behavior**
One password prompt box to appear.  Dismissing it should not lead to another one being spawned.

**Screenshots**

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220512.1 (2022-05-12T20:00:12Z)
                BaseCommit: 298486a9757785902e07482e5a71008e521e9d1c92d7a98e6bc25ac53c966f9f
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: cheese cloud-utils-growpart cockpit cockpit-kdump
                            cockpit-navigator cockpit-networkmanager cockpit-ostree
                            cockpit-pcp cockpit-podman cockpit-sosreport cockpit-system
                            coreos-installer firewall-config gnome-tweaks gparted hexchat
                            langpacks-en mediawriter mozilla-openh264 mtools nmap rpi-imager
                            vim-enhanced virt-manager
```

**Additional context**

**Comment by travier** [comment]
You probably want to disable auto update checking in GNOME Software.

**Comment by millerthegorilla** [comment]
Can I reopen this please, and edit to include a title?

**Comment by tpopela** [comment]
> Why is this issue closed?

Because it had no title and you nearly immediately open a new issue with title and everything, so it looked like a duplicate.

**Comment by millerthegorilla** [comment]
Ok thanks, my mistake on the title, but yh, two separate issues.  Been upgrading my machines...🙂

**Comment by millerthegorilla** [comment]
I have disabled automatic updates in gnome software and also set /etc/rpm-ostreed.conf to none, and the annoying prompts have disappeared, at least so far.
I will have to manually update my machine, though, but I generally do that anyway.

**Comment by millerthegorilla** [comment]
I am not getting this issue on an instance of silverblue running inside a libvirt vm.  On my std user, I am getting just one update prompt, and no others, without making any changes to /etc/rpm-ostreed.conf or to the software centre updates preferences.

**Comment by travier** [comment]
Closing as hopefully this is less of an issue now that https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1561 as been closed/fixed. See also https://github.com/fedora-silverblue/issue-tracker/issues/55
