### ISSUE TITLE
[BUG] GNOME Software seems to have reverted to its original state after upgrade (?)

### ISSUE THREAD

**Issue by aral** [fedora-silverblue/issue-tracker#282]
## Describe the bug

After having used my system for a few weeks, added Flathub, etc., I opened GNOME software today, and it seems to have reverted to its [original, broken state](https://github.com/fedora-silverblue/issue-tracker/issues/257) (I’m assuming after a recent upgrade). 

## To Reproduce

Not sure exactly. Assuming it’s after an upgrade to GNOME Software (?).

## Expected behavior

GNOME Software should not revert and lose its settings.

## Screenshots

![Screenshot from 2022-05-17 13-50-55](https://user-images.githubusercontent.com/41798/168815328-1f405f91-f5e2-412c-878d-ef12ffbdcfdc.png)
![Screenshot from 2022-05-17 13-50-48](https://user-images.githubusercontent.com/41798/168815332-164fb65b-7b97-4f8a-b7a5-3b706f4b587e.png)
![Screenshot from 2022-05-17 13-50-40](https://user-images.githubusercontent.com/41798/168815338-c1af0db6-3fae-40e7-a049-ff56dc2200c4.png)
![Screenshot from 2022-05-17 13-50-28](https://user-images.githubusercontent.com/41798/168815344-b2af2bc2-5dfa-440b-bfe9-d77f666555fc.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220512.0 (2022-05-12T00:44:47Z)
                BaseCommit: fcfc22011d3b76dfc476c13ed9c654dd48837c85658f80655464cfa8d4bfafcc
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: fish gnome-console gnome-tweak-tool gstreamer1-plugin-openh264 langpacks-en lm_sensors
                            mozilla-openh264
```

**Comment by bobslept** [comment]
You current deployment does not contain the fix that was released for this problem. I would suggest to run an update via the terminal with `rpm-ostree upgrade` and see if that fixes the issue.

**Comment by aral** [comment]
@bobslept Will try that now and report back, Bob, thanks :)

**Comment by aral** [comment]
@bobslept Upgrading to the operating system to the latest release version (`36.20220517.0 (2022-05-17T00:49:51Z`) did the trick. Thanks, Bob! Closing.
