### ISSUE TITLE
[RFE] ABRT in default image

### ISSUE THREAD

**Issue by cheese** [fedora-silverblue/issue-tracker#283]
**Describe the solution you'd like**
ABRT is a convenient tool to report problems, especially for ones of segfault. It's installed by default in Workspace.

**Comment by felipeborges** [comment]
While I agree that ABRT can be useful for Silverblue, it is important to consider that most apps in Silverblue are flatpaked, and therefore ABRT won't work to report issues in those. This way ABRT would only work for issues in system components (part of the base image).

For reference https://bugzilla.redhat.com/show_bug.cgi?id=1417572

**Comment by travier** [comment]
The other blocking issue for this one is that it currently pulls in the dnf stack.

**Comment by cheese** [comment]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/considerations_in_adopting_rhel_9/assembly_shells-and-command-line-tools_considerations-in-adopting-rhel-9

The ABRT tool has been removed from RHEL 9. I don't think there will be further effort paid to adapt ABRT to Silverblue.

**Comment by travier** [comment]
Fedora Silverblue is not RHEL. If folks are interested in making ABRT work well in Silverblue then we can make it happen, independently of what RHEL decides.

**Comment by travier** [comment]
This is now tracked in https://gitlab.com/fedora/ostree/sig/-/issues/30
