### ISSUE TITLE
Move Firefox from base image to Flatpak

### ISSUE THREAD

**Issue by JamesBelchamber** [fedora-silverblue/issue-tracker#288]
# Workarounds

See https://docs.fedoraproject.org/en-US/fedora-silverblue/tips-and-tricks/#_hiding_the_default_browser_firefox for the official workaround to hide the Firefox desktop entry (recommended option).

See https://github.com/fedora-silverblue/issue-tracker/issues/288#issuecomment-1315761652 for updates issues / removing it from the base image via an override (not recommended option).

---

# Goal

Move Firefox from a the base image to a default installed Flatpak.

Why?

- Easier to remove for users that don't want it / want to use something else
- Should let us fix the `openh264` issue without relying on client side layering with rpm-ostree

Cons:

- If the browser is removed by mistake, this makes it hard for users to figure it out
- Hardware key support to be determined / confirmed:
	- https://github.com/flatpak/xdg-desktop-portal/issues/989

Tasks to be done: Work is tracked in https://gitlab.com/fedora/sigs/flatpak/fedora-flatpaks/-/issues/13

---

Previous list of things to do below:

- [ ] Figure out the `openh264` story
- [ ] Story for extension management:
	- [ ] https://github.com/flatpak/xdg-desktop-portal/pull/705
	- [ ] https://github.com/fedora-silverblue/issue-tracker/issues/399
- [ ] Migration story for existing users and announcement blog post on Fedora Magazine
- [ ] Actual change to include the Flatpak by default in Silverblue & Kinoite
- [ ] Implement a fallback default browser that installs Firefox again when no browser is available

---

# Original issue text

Lots of people choose not to use Firefox as a browser. Others wish to use the Flatpak instead of the pre-installed version.

Using `rpm-ostree override remove` to remove the package isn't a great experience; you know that you're futzing with the base image. But it makes sense to ship Silverblue with a (working) browser.

A solution is simply to **ship Silverblue with a base image that doesn't include Firefox, and then have Firefox layered by default**. This would make for easy `rpm-ostree remove`'ing for anyone that doesn't want the package, and ensures new users (and inexperienced users) have a working browser.

The alternative is to use Firefox as a Flatpak, but my understanding is that this is not yet ready for prime time (although I don't know where this work is being tracked, since the feature request in flatpak/flatpak#72 was closed).

**Comment by tpopela** [comment]
Hi @JamesBelchamber,

> Lots of people choose not to use Firefox as a browser. Others wish to use the Flatpak instead of the pre-installed version.
>
> Using `rpm-ostree override remove` to remove the package isn't a great experience; you know that you're futzing with the base image. But it makes sense to ship Silverblue with a (working) browser.

They're allowed to remove the one that's in the base image and replace with whatever browser they want. But Silverblue as a product is shipped and will be shipped with Firefox as the default browser. It will also be in the form of an RPM package in the base image until the Firefox Flatpak experience is on par with the RPM one.

> A solution is simply to **ship Silverblue with a base image that doesn't include Firefox, and then have Firefox layered by default**. This would make for easy `rpm-ostree remove`'ing for anyone that doesn't want the package, and ensures new users (and inexperienced users) have a working browser.

That's not technically possible to alter the deployment after installation automatically. I honestly see zero benefits from your proposal, but a lot of maintenance burden.

> The alternative is to use Firefox as a Flatpak, but my understanding is that this is not yet ready for prime time (although I don't know where this work is being tracked, since the feature request in #72 was closed).

A closed issue doesn't mean that it's not being worked on - our capacity is limited (you can see that from the number of opened issues - it's not possible to keep up with them) and how Firefox works in Flatpak isn't anything that we in the Silverblue project can work on. Indirectly Silverblue will benefit from the work that one of our Firefox maintainers works on - https://bugzilla.mozilla.org/show_bug.cgi?id=1278719 (addressing issues from it - when he says that Firefox as a Flatpak is ready, then we can start to think about shipping it as a Flatpak in Silverblue).

**Comment by travier** [comment]
@LorbusChris Before we re-open this BZ, we would need a clear proposal addressing the various concerns that have been raised here.

**Comment by ifeeltiredboss** [comment]
Any changes on that topic? Today I wanted to upgrade to Silverblue 36 but I think it demands the useless Firefox to be reinstalled first.

Meanwhile, I am going to try out MicroOS from OpenSUSE. Thought I'd share how they tackled this. They ship almost nothing on the base image and upon the first log in a service is started to install necessary flatpaks:
- Firefox from Flathub (official Mozilla),
- GNOME text editor,
- calculator, etc.

If somebody would be so kind, share it here for what it's worth: https://discussion.fedoraproject.org/t/dropping-firefox-from-the-base-image/21844

**Comment by pkulak** [comment]
haha, that's why I'm here too. Wanted to upgrade to 37; can't until I re-install Firefox. But I get it. This is a tricky issue, for sure. I guess MicroOS can do the Flathub thing because they are German? Hopefully the world moves to AV1 pronto and we won't have to deal with this anymore.

I think I'm just going to have two Firefox's installed. Does anyone know how to hide the desktop file in /usr/share/applications?

**Comment by travier** [comment]
For those coming here during the rebase to F37, you can temporarily reset/undo your override remove of Firefox, rebase, and then redo the removal. Something like:
```
$ rpm-ostree override reset firefox
$ rpm-ostree rebase ... --reboot
$ rpm-ostree override remove firefox
```

---

We are not shipping Firefox as a Flatpak by default either as it has limitations (see comments above and upstream issue tracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1278719) and it can not support h264 either. On top of that it can not benefit from the openh264 support when installed on the system via the openh264 package provided by Cisco.

---

If you don't want to have two Firefox displayed in the interface, you can probably used a trick from https://wiki.archlinux.org/title/desktop_entries#Hide_desktop_entries to hide the desktop entry or `override remove` it.

**Comment by iaacornus** [comment]
> 

as for removal of firefox, there seems to be a new package, `firefox-langpacks` which depends on firefox, thus `rpm-ostree override remove firefox` may just give an error:

```
Problem: package firefox-langpacks-106.0.4-1.fc37.x86_64 requires firefox = 106.0.4-1.fc37, but none of the providers can be installed
  - conflicting requests
```

So you need to remove the two: `rpm-ostree override remove firefox firefox-langpacks`.

**Comment by travier** [comment]
Adding `NotShowIn=GNOME;KDE` hides the entry.

**Comment by travier** [comment]
https://github.com/fedora-silverblue/silverblue-docs/pull/138

**Comment by Ayush1325** [comment]
I think this issue should be re-evaluated now that [proprietary video codecs are no longer hardware accelerated on and gpus](https://ask.fedoraproject.org/t/proprietary-video-codecs-are-no-longer-hardware-accelerated-by-default-on-amd-gpus-on-fedora-37/28965). This has essentially crippled base image firefox for most use-cases on AMD systems.

The functionality can be restored by using rpm-fusion, but I think we should at least consider if the base image Firefox is better than the fedora Firefox flatpak, since overriding base image seems strictly worse than layering if someone doesn't like flatpak fedora. Also, since Fedora 37, you have to override 2 packages (`firefox`, `firefox-langpacks`) rather than 1.

Note: In my case, I would use Flathub Firefox anyway, but it would be easier to uninstall a flatpak.

**Comment by travier** [comment]
Converting that to a tracker for the work to move Firefox out of the base image into a Flatpak installed by default.

**Comment by travier** [comment]
See related discussions:
- https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/ZHADOQLAIQQRXNHHBE4A54BJBU46EUEN/
- https://github.com/fedora-silverblue/issue-tracker/issues/399

**Comment by tazihad** [comment]
Yes. Please remove Firefox from base image. I literally had to search for hours to install separate codecs to fix Firefox video issue. Also, Silverblue should ship with Extension Manager as flatpak.

**Comment by trytomakeyouprivate** [comment]
maybe add a
```
mv ~/.mozilla/* ~/.var/app/org.mozilla.firefox/.mozilla/*
```

to avoid removal of data? Copy-pasting profiles works flawlessly on Firefox. It should just startup normally without users even noticing.

**Comment by trytomakeyouprivate** [comment]
> If you're interested in removing Firefox from the base image, please create with a proposal addressing the concerns raised here and in linked threads. As it's been said multiple times already, we can not ship the one from Flathub for legal reasons.

Does this also apply to the method used by OpenSuse microOS, where they directly download the package after install?

I mean they ship no Codec, just a single link and a nice installer.

**Comment by BirdInFire** [comment]
> The current set of missing pieces in the Fedora Firefox Flatpak is tracked in https://gitlab.com/fedora/sigs/flatpak/fedora-flatpaks/-/issues/13

So in short you continue to ship the package for nothing (and in the same time force user that use it on flatpak to layer the system to remove the one inside), i mean native messenger is used by a VERY minority of user for keepass, and this minority is from the minority that firefox himself is : Mozilla Firefox | 7.69%.

the H264 problem is fixed since long in flatpak (all you need to do is install the flatpak that come with it), same for hardware token and smart cards (simple change the flatpak permission).

I mean us on Silverblue are knowledgeable enough to add is ourselves by layering it if the flatpak is really unbearable.

**Comment by trytomakeyouprivate** [comment]
I have to defend the Devs here.

Fedora Firefox is really good. Fedora images in general are just useless without the codecs and everything from RPMFusion.

I am on kinoite-main from ublue now, and switched back to Fedora Firefox. Wayland starts immediately, where I got really weird 1min delay in startup on Flatpak Firefox Wayland (default is xwayland). Everything works, as all codecs (also x256) are installed. 

Fedora Silverblue and Kinoite have big problems, but with "batteries included" they are awesome! 

Native firefox now has:

- normal fast startup
- very good performance
- drag and drop
- good dialogs
- better integration, for example loading bars
- KeepassXC and other addons working

**Comment by BirdInFire** [comment]
> I have to defend the Devs here.
> 
> Fedora Firefox is really good. Fedora images in general are just useless without the codecs and everything from RPMFusion.
> 
> I am on kinoite-main from ublue now, and switched back to Fedora Firefox. Wayland starts immediately, where I got really weird 1min delay in startup on Flatpak Firefox Wayland (default is xwayland). Everything works, as all codecs (also x256) are installed.
> 
> Fedora Silverblue and Kinoite have big problems, but with "batteries included" they are awesome!
> 
> Native firefox now has:
> 
> * normal fast startup
> * very good performance
> * drag and drop
> * good dialogs
> * better integration, for example loading bars
> * KeepassXC and other addons working

Again forcing an app into this kind of immutable image is a terrible idea, and if the flatpak don't launch as wayland it's your settings that have a problem because the official firefox flatpak have the env variable to use wayland by default

So they have to remove this app because people like you can layer it, but other don't have to bear this rpm they don't use.

Because koinite and silverblue are made to be flatpak only (by default) for app, so having rpm in it defeat the goal of the OS just remove it.

**Comment by trytomakeyouprivate** [comment]
@BirdInFire No its not misconfigured as the Flatpak is launched as Wayland, which causes that problem. Its some AMD GPU+ Wayland + whatever bug, already reported.

Yes, if the Flatpaks have all the features the RPMs have, remove them. But until then, on a system with working codecs, they are just better.

Native messaging is now Alpha on Ubuntu for Snaps, will come sometime this year on Flatpaks I guess. Still no drag and drop, but coming closer. If all boxes are ticked (I think there was a list somewhere from the Fedora devs) then the RPM Firefox can be removed.

OpenSuse devs said the same, its way better to not need to compile and manage all these huge projects like Libreoffice or Firefox yourself, as they are literally as big as Linux itself. But Flatpaks are not ready yet.

**Comment by BirdInFire** [comment]
> @BirdInFire No its not misconfigured as the Flatpak is launched as Wayland, which causes that problem. Its some AMD GPU+ Wayland + whatever bug, already reported.
> 
> Yes, if the Flatpaks have all the features the RPMs have, remove them. But until then, on a system with working codecs, they are just better.
> 
> Native messaging is now Alpha on Ubuntu for Snaps, will come sometime this year on Flatpaks I guess. Still no drag and drop, but coming closer. If all boxes are ticked (I think there was a list somewhere from the Fedora devs) then the RPM Firefox can be removed.
> 
> OpenSuse devs said the same, its way better to not need to compile and manage all these huge projects like Libreoffice or Firefox yourself, as they are literally as big as Linux itself. But Flatpaks are not ready yet.

Misconfigured on KDE side i mean all Firefox flatpak on a correctly configured gnome all work flawlessly on wayland on multiple device

**Comment by BirdInFire** [comment]
> @BirdInFire No its not misconfigured as the Flatpak is launched as Wayland, which causes that problem. Its some AMD GPU+ Wayland + whatever bug, already reported.
> 
> Yes, if the Flatpaks have all the features the RPMs have, remove them. But until then, on a system with working codecs, they are just better.
> 
> Native messaging is now Alpha on Ubuntu for Snaps, will come sometime this year on Flatpaks I guess. Still no drag and drop, but coming closer. If all boxes are ticked (I think there was a list somewhere from the Fedora devs) then the RPM Firefox can be removed.
> 
> OpenSuse devs said the same, its way better to not need to compile and manage all these huge projects like Libreoffice or Firefox yourself, as they are literally as big as Linux itself. But Flatpaks are not ready yet.

You can also use flatseal (or KDE equivalent) to remove the X11 permission and forcefully launch the flatpak in terminal to report the full error on KDE/Kwin dev to have it fixed

**Comment by trytomakeyouprivate** [comment]
@BirdInFire thanks, already did both

**Comment by BirdInFire** [comment]
> @BirdInFire thanks, already did both

But even if i recognize the fact the rpm have some feature the flatpak don't have ... yet ...
I remain for removing the one from the image and let people who need it do : rpm-ostree install firefox
instead of forcing the rpm on everyone like now.

**Comment by JamesBelchamber** [comment]
Nobody is forcing you to do anything - this is an open source project with an open build process, and you can compile your own images if you wish to.

Can we keep comments on this issue informational and productive, please.

**Comment by BirdInFire** [comment]
> Nobody is forcing you to do anything - this is an open source project with an open build process, and you can compile your own images if you wish to.
> 
> Can we keep comments on this issue informational and productive, please.

actually it's forced because people like me with a secureboot that cannot be disabled cannot create our own image because it will not be signed by fedora and so don't boot.

Don't say it's not productive when you don't know why some tell what's they tell

**Comment by travier** [comment]
> actually it's forced because people like me with a secureboot that cannot be disabled cannot create our own image because it will not be signed by fedora and so don't boot.

If you keep the kernel in your custom image it will boot just fine with Secure Boot enabled.

**Comment by travier** [comment]
Please see https://docs.fedoraproject.org/en-US/fedora-silverblue/tips-and-tricks/#_hiding_the_default_browser_firefox to hide the browser from the image until we're able to remove it.

**Comment by BirdInFire** [comment]
> Please see https://docs.fedoraproject.org/en-US/fedora-silverblue/tips-and-tricks/#_hiding_the_default_browser_firefox to hide the browser from the image until we're able to remove it.

why don't you remove it from the image, but actually make the fedora installer do "rpm-ostree install fedora" at install time, like that normal user don't see the difference and it's moved out of the image (until the flatpak can replace it totally) ?

Everyone is happy people like me can remove it totally, you have it as default (and normal user don't see any difference at all)

**Comment by JamesBelchamber** [comment]
This is what the original issue suggested, and the first few comments
discuss.

**Comment by JamesBelchamber** [comment]
This is what the original issue suggested, and the first few comments discuss.

**Comment by JamesBelchamber** [comment]
@travier can you elucidate on why `rpm-ostree override remove` is not recommended? My understanding is that `rpm-ostree` supports this and it's very robust?

**Comment by BirdInFire** [comment]
> @travier can you elucidate on why `rpm-ostree override remove` is not recommended? My understanding is that `rpm-ostree` supports this and it's very robust?

Because modifying the image by removing something defeat the purpose of an image based system, since the dev system will not be the same as the user anymore.

It's why layering or override remove is not recommended

**Comment by travier** [comment]
If you don't use the Firefox from the image then hiding it should be enough. If launching from the command line is needed, then a shell alias or a `/usr/local/bin` wrapper should also work. Do you have a use case were this does not work?

Removing it from the image increases the time it takes to apply each update (as the remove operation has to be done for each one) and does not reduce the size of those updates as the full base image is downloaded in all cases.

Options that do not modify the image are preferred as they don't trigger potential issues during (mostly major) upgrades. See: https://github.com/fedora-silverblue/issue-tracker/issues/288#issuecomment-1315761652

**Comment by BirdInFire** [comment]
> If you don't use the Firefox from the image then hiding it should be enough. If launching from the command line is needed, then a shell alias or a `/usr/local/bin` wrapper should also work. Do you have a use case were this does not work?
> 
> Removing it from the image increases the time it takes to apply each update (as the remove operation has to be done for each one) and does not reduce the size of those updates as the full base image is downloaded in all cases.
> 
> Options that do not modify the image are preferred as they don't trigger potential issues during (mostly major) upgrades. See: [#288 (comment)](https://github.com/fedora-silverblue/issue-tracker/issues/288#issuecomment-1315761652)

i don't want a fix i want silverblue to fulfill it's promise a flatpak ONLY system by default.

**Comment by travier** [comment]
@BirdInFire

Fedora Silverblue is free and open source software and the Fedora Project is a community project. Changes happen when contributors make them happen.

If you're interested in contributing that change to Silverblue, feel free to look at the first comment that we've updated to outline the steps for the work needed to make this happen.

You may also consider paying someone to work on implementing that change for you.

**Comment by iavael** [comment]
@BirdInFire if that's such a minor change then what's the problem with contributing it yourself?

**Comment by BirdInFire** [comment]
> @BirdInFire if that's such a minor change then what's the problem with contributing it yourself?

Because since they are so against it, it's losing time since they will reject it anyway ?

**Comment by JamesBelchamber** [comment]
> If you don't use the Firefox from the image then hiding it should be enough. If launching from the command line is needed, then a shell alias or a `/usr/local/bin` wrapper should also work. Do you have a use case were this does not work?
> 
> Removing it from the image increases the time it takes to apply each update (as the remove operation has to be done for each one) and does not reduce the size of those updates as the full base image is downloaded in all cases.
> 
> Options that do not modify the image are preferred as they don't trigger potential issues during (mostly major) upgrades. See: [#288 (comment)](https://github.com/fedora-silverblue/issue-tracker/issues/288#issuecomment-1315761652)

It's not so much that I have a use-case for this not working - rather that I consider it a messy, manual solution that relies on the user remembering that there's a version of Firefox installed (in the base image) and that they manually patched it out (which can be annoying e.g when hunting down bugs, only to find that somehow you're using the RPM version of Firefox again..). With the override approach you can see, plain as day in the `rpm-ostree status` output, that Firefox is removed - and it _is_ actually removed!

I understand that the rebase issue exists (though I also understand it's [considered a bug](https://github.com/coreos/rpm-ostree/issues/3944) that is intended to be fixed) but I think this could just be documented tbh (since people are going to want to use overrides for other things, and.. it _is_ a feature of Silverblue :sweat_smile:). I don't think the marginally longer update times really make this a bad idea (at least, it's down to whether you're drag-racing package managers or not - I know a vocal minority _also_ whine about `dnf` being slow but in my experience most people don't really notice/care).

Anyway, not trying to push you either way on this. I would probably recommend using the override, personally. I just wanted to understand the reasoning because there's been a lot of FUD around `rpm-ostree` (_"don't override"_, _"don't layer"_, etc - if you weren't meant to layer then why the heck aren't we just using `ostree` directly..). It's been a bit of a bug-bear of mine because when I tell people about Silverblue one of the key things they're excited about is the ability to use RPMs to layer in/out packages while still getting all the nice, reliable `ostree` stuff (and all an `rpm-ostree reset` away from what is essentially a new install).

**Comment by BirdInFire** [comment]
Another possibility is to have like ubuntu but for silverblue 2 choice at install, one "normal" images with firefox in it and all flatpak installed (like now), and a minimal version (without firefox or any other app with gui .desktop in it and no flatpak installed by default. like that everything must be installed manually from flatpak or layer (for those who need somthing there).

**Comment by JamesBelchamber** [comment]
@BirdInFire you do realise you can build your own image, right? There are two options:

Firstly, [the approach I took](https://github.com/jamesbelchamber/working-linux) (now archived) where I pretty much did exactly what you described - created a minimal base image. You can find the work here, although you'll need to tidy it up and get it working again yourself because became distracted by other things..

Secondly, [Universal Blue](https://ublue.it/) basically allows this - and it's built on Silverblue, but basically leverages OCI containers instead (which is possible but not the default yet in Silverblue).

I appreciate (and somewhat empathise with) your frustration at not knowing how/what you can contribute - Silverblue is a bit like that at the moment. But you need to stop throwing around accusations - there's no hypocrisy, just engineers working on stuff in their own self-interest. That's how all open source works.

If you have more questions maybe [pop over to the Matrix channel](https://matrix.to/#/#silverblue:fedoraproject.org) (it's also on Libera I think - I don't use IRC) - there are quite a few people subscribed to this issue and it's not really a discussion space, but you might find more satisfaction there.

**Comment by BirdInFire** [comment]
> @BirdInFire you do realise you can build your own image, right? There are two options:
> 
> Firstly, [the approach I took](https://github.com/jamesbelchamber/working-linux) (now archived) where I pretty much did exactly what you described - created a minimal base image. You can find the work here, although you'll need to tidy it up and get it working again yourself because became distracted by other things..
> 
> Secondly, [Universal Blue](https://ublue.it/) basically allows this - and it's built on Silverblue, but basically leverages OCI containers instead (which is possible but not the default yet in Silverblue).
> 
> I appreciate (and somewhat empathise with) your frustration at not knowing how/what you can contribute - Silverblue is a bit like that at the moment. But you need to stop throwing around accusations - there's no hypocrisy, just engineers working on stuff in their own self-interest. That's how all open source works.
> 
> If you have more questions maybe [pop over to the Matrix channel](https://matrix.to/#/#silverblue:fedoraproject.org) (it's also on Libera I think - I don't use IRC) - there are quite a few people subscribed to this issue and it's not really a discussion space, but you might find more satisfaction there.

What kind of answer is that ?
Serious the answer is make an image yourself ?

Are you seriously saying that on github issue ?

**Comment by trytomakeyouprivate** [comment]
If these issues are fixed, it really is no work to just stop installing firefox on the main image:

- Fido2 support
- native messaging support working out of the box for apps using it
- no startup lag on AMD + Wayland

And please, just stop developing the Fedora Flatpak Firefox. Nearly noone uses it. It could make sense to build the 99% of code on Fedora Servers, ship it as Fedora flatpak and then have a plugin somehow installable, adding the codecs, from something like RPMFusion. This should be possible.

But still, Flathub Firefox is official and runs well. Why make it more complicated?

With the new verification you could use that and for example only show/install verified apps. I know its a security reason, but this should give the best user experience.

**Comment by BirdInFire** [comment]
> @trytomakeyouprivate
> 
> > no unsandboxed browser with no permissions, trust
> 
> Modern browsers use sandboxing by themselves one way or another. And flatpak sandboxing is not a security mechanism. Also "trust" is negative relationship in information security. It essentially means that you are not sure that component is secure, but have to accept risks and rely on it as is because you have no other option. The opposite thing is _knowledge_, when you don't have to blindly trust component because you have proof that it is secure.

.... more sandbox is always more secure even more when the mechanism is different because a malware must breach 2....

**Comment by travier** [comment]
I'm locking the conversation on the topic because the discussion is out of topic.

**Comment by travier** [comment]
Closing this issue in favor of the one in the Fedora Atomic Desktop issue tracker: https://gitlab.com/fedora/ostree/sig/-/issues/3
