### ISSUE TITLE
Feature: tuned in base layer

### ISSUE THREAD

**Issue by daniel-wtd** [fedora-silverblue/issue-tracker#29]
Hi all,

thanks again for the awesome work. One of the base tools, I am always using, but is missing in Fedora is "tuned". It's a tool to profile some kernel parameters (like sysctl) and other tunings. It can help to improve performance, extend battery life and more. It would be awesome, to see this tool in Fedora Silverblue.

https://tuned-project.org/

In all current versions, it also provides auto-detection of profiles for several use-cases like desktop, balanced, kvm-guest, etc. Therefore only 2 steps are needed:

- package must be part of the base layer
- tuned.service must be enabled per default

Would be awesome to get some feedback here :)

**Comment by tpopela** [comment]
We try to inherit the packages from Fedora Workstation. So I think it would be good to start the discussion there - https://pagure.io/fedora-workstation/issues.

**Comment by daniel-wtd** [comment]
I will do so, thanks a lot!

**Comment by tpopela** [comment]
Closing this issue, feel free to reopen it, once it will be included in Workstation.
