### ISSUE TITLE
[BUG] Laptop with Nvidia not resume from suspend

### ISSUE THREAD

**Issue by djypku** [fedora-silverblue/issue-tracker#293]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
After install `kmod-nvidia` and `xorg-x11-drv-nvidia-cuda` and `xorg-x11-drv-nvidia`, my laptop fails to resume from suspend at chance.
I found some rules of the problem.
1. Suspend immediately after boot will almost always be stuck at resume. Suspend after some minutes can greatly decrease the chance.
2. Boot in secure boot so that fall back to `nouveau` or removing Nvidia drivers can totally avoid such problem.
3. During one boot, if my laptop has suspend and then resume correctly for once, then suspend and resume become safe from then on.
4. Fedora 35 has no such problem. ( see Additional context  )
5. Using Nvidia-470xx can not avoid this problem.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
(1) On Kinoite use `rpm-ostree install kmod-nvidia xorg-x11-drv-nvidia-cuda xorg-x11-drv-nvidia and reboot

(2) `systemctl suspend` or use suspend by KDE ui and then likely to trigger such problem. Especially suspend immediately after boot almost always trigger it.

(3) when such problem occurs, screen is totally dark and even backlight not resumed . Keyboard backlight resumes however, and I can hear fans working. I try to switch to tty and login and input `reboot` or `poweroff` but no respon.

**Expected behavior**
System resumes. Screen get bright. 

**Screenshots**
``
![IMG_20220603_162142](https://user-images.githubusercontent.com/86961676/171820830-dabe8539-e4eb-492f-a3c0-5a3ace783e2f.jpg)
`

**OS version:**
```
● fedora:fedora/36/x86_64/kinoite
                   Version: 36.20220603.0 (2022-06-03T02:41:21Z)
                BaseCommit: 5e74ae1ba32804f8990bc5b0290eb14f81c1e77508823e83e765ef9fbd856190
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: dnf fcitx5-qt gnome-boxes kmod-nvidia libvirt snapper spice-protocol spice-server tlp virt-manager xorg-x11-drv-nvidia
                            xorg-x11-drv-nvidia-cuda
             LocalPackages: expressvpn-3.23.1.0-1.x86_64 rpmfusion-free-release-36-1.noarch rpmfusion-nonfree-release-36-1.noarch

```
Here `dnf` installed is only for seach. I know it is not correct behavior but likely not relevant to my problem. 

**Additional context**
A. Not try in Fedora Workstation yet. Because it is a hardware problem and vm not work for that. I may try installing Fedora on usb later.
 B. I update system from Fedora Kinoite 35 and I pinned F35 so I can go back for try. I find this problem does not exist in F35
``` 
● fedora:fedora/35/x86_64/kinoite
                   Version: 35.20220516.0 (2022-05-16T01:14:07Z)
                BaseCommit: 786b4245c7b5912617eaec4e6275f308db113c746db73ace4d54dc23b8443af3
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: akmod-nvidia dnf fcitx5-qt gnome-boxes snapper spice-protocol spice-server tlp virt-manager xorg-x11-drv-nvidia
                            xorg-x11-drv-nvidia-cuda
             LocalPackages: expressvpn-3.21.0.2-1.x86_64 rpmfusion-free-release-35-1.noarch rpmfusion-nonfree-release-35-1.noarch
                    Pinned: yes

**Comment by travier** [comment]
This is likely a problem with the NVIDIA driver. I would recommend that you try to reproduce this issue on Fedora Workstation and then file a bug report on the RPM Fusion bugzilla.
If you can not reproduce this issue on Workstation then we can re-open this issue to investigate.

**Comment by CheariX** [comment]
What is your output of `rpm -q akmod-nvidia` ?
I had many problems with NVidia 510 + suspend. With 515, it works like charm.
