### ISSUE TITLE
[BUG] Gome-software complains sqlite-libs README.md exist

### ISSUE THREAD

**Issue by dufresnep** [fedora-silverblue/issue-tracker#294]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
Been a few versions, where Gnome-Software shows a tooltip:
```
"Impossible d'installer les mises à jour" (cannot install updates)
"Checkout sqlite-libs-3.38.5-1.i686 (64 bitis installation)"
"Hardlinking... 8c/" a long hash... 
```

**To Reproduce**
Been able to use rpm-ostree update in the past... but not Gnome Software to update.

**Expected behavior**

**Screenshots**
screenshot attached

**OS version:**

```
[paul@fedora ~]$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220603.0 (2022-06-03T02:38:05Z)
                BaseCommit: 334dab1d7125c8781564076f45d58d5fe2cb2624b206b6f13e1f5bc521a0d974
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: gstreamer1-libav neofetch steam
             LocalPackages: rpmfusion-free-release-36-1.noarch
                            rpmfusion-nonfree-release-36-1.noarch
[paul@fedora ~]$ 
```

**Additional context**
![Capture d’écran du 2022-06-04 11-04-16](https://user-images.githubusercontent.com/3400700/172010462-21d0c372-3001-43df-9de7-eb2eea12214f.png)

**Comment by dufresnep** [comment]
Thinking... I have tried rawhide in the past, and switched back to F36
mentioning it because of fc37 in the package name:

[paul@fedora ~]$ rpm-ostree status
State: idle
Deployments:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220603.0 (2022-06-03T02:38:05Z)
                BaseCommit: 334dab1d7125c8781564076f45d58d5fe2cb2624b206b6f13e1f5bc521a0d974
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: gstreamer1-libav neofetch steam
             LocalPackages: rpmfusion-free-release-36-1.noarch
                            rpmfusion-nonfree-release-36-1.noarch

  fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220603.0 (2022-06-03T02:38:05Z)
                BaseCommit: 334dab1d7125c8781564076f45d58d5fe2cb2624b206b6f13e1f5bc521a0d974
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: gstreamer1-libav steam
             LocalPackages: rpmfusion-free-release-36-1.noarch
                            rpmfusion-nonfree-release-36-1.noarch

  fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220521.0 (2022-05-21T00:42:36Z)
                BaseCommit: 3d384f53a1a46d53a06e9eccc3f52a7a0587cb8147b397298559a59f113a1fed
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: gstreamer1-libav steam
             LocalPackages: rpmfusion-free-release-36-1.noarch
                            rpmfusion-nonfree-release-36-1.noarch
                    Pinned: yes

  fedora:fedora/rawhide/x86_64/silverblue
                   Version: Rawhide.20220522.n.0 (2022-05-22T06:03:21Z)
                BaseCommit: 0a9c3709cbbf37e4c078bf519b92e4bfbd02cb12ad18542078fff2eabcf78896
              GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
           LayeredPackages: gstreamer1-libav rpmfusion-free-release-rawhide
                            rpmfusion-nonfree-release-rawhide steam
                    Pinned: yes
[paul@fedora ~]$

**Comment by jlebon** [comment]
Hmm, upgrading via `rpm-ostree upgrade` works, but via GNOME Software it doesn't? And it's trying to install an f37 package when you're on f36?

**Comment by dufresnep** [comment]
I am unsure it is trying to install f37 package when on f36...
[paul@fedora /]$ ls -lh /sysroot/ostree/repo/objects/8c/19961b431b339032a346d461dca137a7e4890f3d37a37cf0d5fbb958b1f189.file 
-rw-r--r--. 2 root root 16K 31 déc  1969 /sysroot/ostree/repo/objects/8c/19961b431b339032a346d461dca137a7e4890f3d37a37cf0d5fbb958b1f189.file
[paul@fedora /]$ 

[paul@fedora /]$ sudo find  / -name *fc37.i686 -print
find: ‘/run/user/1000/doc’: Permission non accordée
find: ‘/run/user/1000/gvfs’: Permission non accordée
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libvdpau/1.5-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/xz-libs/5.2.5-9.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/pango/1.50.7-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/glib2/2.72.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/mesa-libGL/22.1.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libtracker-sparql/3.3.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/elfutils-debuginfod-client/0.187-4.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/lcms2/2.13.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/glibc-gconv-extra/2.35.9000-18.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/atk/2.38.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/fontconfig/2.14.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libepoxy/1.5.10-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/cups-libs/1_3A2.4.1-9.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/colord-libs/1.4.6-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libselinux/3.4-0.rc3.1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/mesa-vulkan-drivers/22.1.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/gtk2/2.24.33-7.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libX11-xcb/1.7.5-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/krb5-libs/1.19.2-9.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libwebp/1.2.2-5.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libnghttp2/1.47.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libunwind/1.6.2-2.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/inih/55-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/lilv-libs/0.24.12-5.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libgcc/12.1.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libuuid/2.38-3.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/fribidi/1.0.12-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libsepol/3.4-0.rc3.1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libwayland-client/1.20.0-4.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/pipewire/0.3.51-2.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libdrm/2.4.110-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/openssl-libs/1_3A3.0.2-4.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/elfutils-libelf/0.187-4.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/gdk-pixbuf2-modules/2.42.8-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libatomic/12.1.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libblkid/2.38-3.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libxcrypt/4.4.28-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/glib-networking/2.72.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/nspr/4.32.0-6.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/cyrus-sasl-lib/2.1.28-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libzstd/1.5.2-2.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/cairo/1.17.6-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/nss/3.77.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libX11/1.7.5-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libnsl/2.35.9000-18.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libtool-ltdl/2.4.7-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libwayland-egl/1.20.0-4.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libjpeg-turbo/2.1.3-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/sqlite-libs/3.38.5-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/at-spi2-core/2.44.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/harfbuzz/4.2.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/mesa-filesystem/22.1.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libgpg-error/1.45-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libstdc_2B_2B/12.1.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/gnutls/3.7.4-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libxml2/2.9.14-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/bluez-libs/5.64-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/gtk3/3.24.34-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libva/2.14.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/vulkan-loader/1.3.211.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libXcursor/1.2.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/mesa-dri-drivers/22.1.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/nss-softokn/3.77.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/ncurses-libs/6.3-2.20220501.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/expat/2.4.8-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/llvm-libs/14.0.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libusb1/1.0.25-8.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/mesa-libglapi/22.1.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/flac-libs/1.3.4-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libgcrypt/1.10.1-2.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/elfutils-libs/0.187-4.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/pipewire-libs/0.3.51-2.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/nss-softokn-freebl/3.77.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/glibc/2.35.9000-18.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/cairo-gobject/1.17.6-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/gdk-pixbuf2/2.42.8-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libwayland-cursor/1.20.0-4.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libproxy/0.4.17-5.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/pipewire-alsa/0.3.51-2.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/pcre2/10.40-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/dbus-libs/1_3A1.14.0-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libtiff/4.3.0-6.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/freetype/2.12.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libicu/69.1-6.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libmount/2.38-3.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libcurl/7.83.1-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/systemd-libs/251-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/libxcrypt-compat/4.4.28-1.fc37.i686
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/nss-util/3.77.0-1.fc37.i686
find: Boucle détectée dans le système de fichiers ; « ‘/sysroot/ostree/deploy/fedora/deploy/a582c1c31e97b40596ea0f5cb1bd323a6308bdd369a08ce1be012083f17f42e7.0’ » est dans la même boucle que ‘/’.
[paul@fedora /]$ 

[paul@fedora /]$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220606.0 (2022-06-06T01:47:39Z)
                BaseCommit: 421ae524f62d85d1ce9398cee5e63b661e48dbce408c290283dc7aff467d39e3
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: gstreamer1-libav neofetch steam telnet vlc
             LocalPackages: rpmfusion-free-release-36-1.noarch
                            rpmfusion-nonfree-release-36-1.noarch
[paul@fedora /]$ 

I guess the fact that the files are in /sysroot/ostree/repo/refs does not really means they are deployed in the currently installed version.

**Comment by dufresnep** [comment]
[paul@fedora /]$ sudo find  / -name *fc37.i686 -print |grep sqlite
find: ‘/run/user/1000/doc’: Permission non accordée
find: ‘/run/user/1000/gvfs’: Permission non accordée
/sysroot/ostree/repo/refs/heads/rpmostree/pkg/sqlite-libs/3.38.5-1.fc37.i686
find: Boucle détectée dans le système de fichiers ; « ‘/sysroot/ostree/deploy/fedora/deploy/a582c1c31e97b40596ea0f5cb1bd323a6308bdd369a08ce1be012083f17f42e7.0’ » est dans la même boucle que ‘/’.
[paul@fedora /]$

**Comment by travier** [comment]
Can you paste here the content of your repo config from `/etc/yumd.repos.d`? I suspect that they might be stuck on F37.

**Comment by dufresnep** [comment]
[paul@fedora ~]$ cd /etc/yum.repos.d/
[paul@fedora yum.repos.d]$ ls -lh
total 72K
-rw-r--r--. 1 root root  292 21 mai 14:31 _copr_phracek-PyCharm.repo
-rw-r--r--. 1 root root  728  6 jun 08:34 fedora-cisco-openh264.repo
-rw-r--r--. 1 root root 1,3K  6 jun 08:34 fedora-modular.repo
-rw-r--r--. 1 root root 1,3K  6 jun 08:34 fedora.repo
-rw-r--r--. 1 root root  986  6 jun 08:34 fedora-updates-archive.repo
-rw-r--r--. 1 root root 1,4K  6 jun 08:34 fedora-updates-modular.repo
-rw-r--r--. 1 root root 1,3K  6 jun 08:34 fedora-updates.repo
-rw-r--r--. 1 root root 1,4K  6 jun 08:34 fedora-updates-testing-modular.repo
-rw-r--r--. 1 root root 1,4K  6 jun 08:34 fedora-updates-testing.repo
-rw-r--r--. 1 root root  199 21 mai 14:31 google-chrome.repo
-rw-r--r--. 1 root root 1,3K  6 jun 08:34 rpmfusion-free.repo
-rw-r--r--. 1 root root 1,3K  6 jun 08:34 rpmfusion-free-updates.repo
-rw-r--r--. 1 root root 1,3K  6 jun 08:34 rpmfusion-free-updates-testing.repo
-rw-r--r--. 1 root root 1,5K 21 mai 14:31 rpmfusion-nonfree-nvidia-driver.repo
-rw-r--r--. 1 root root 1,3K  6 jun 08:34 rpmfusion-nonfree.repo
-rw-r--r--. 1 root root 1,4K 21 mai 14:31 rpmfusion-nonfree-steam.repo
-rw-r--r--. 1 root root 1,3K  6 jun 08:34 rpmfusion-nonfree-updates.repo
-rw-r--r--. 1 root root 1,4K  6 jun 08:34 rpmfusion-nonfree-updates-testing.repo
[paul@fedora yum.repos.d]$ 
[paul@fedora yum.repos.d]$ cat fedora.repo
[fedora]
name=Fedora $releasever - $basearch
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/$basearch/os/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
enabled=1
countme=1
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[fedora-debuginfo]
name=Fedora $releasever - $basearch - Debug
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/$basearch/debug/tree/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-debug-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[fedora-source]
name=Fedora $releasever - Source
#baseurl=http://download.example/pub/fedora/linux/releases/$releasever/Everything/source/tree/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-source-$releasever&arch=$basearch
enabled=0
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
[paul@fedora yum.repos.d]$ 
[paul@fedora yum.repos.d]$ cat fedora-updates.repo
[updates]
name=Fedora $releasever - $basearch - Updates
#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/$basearch/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
enabled=1
countme=1
repo_gpgcheck=0
type=rpm
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[updates-debuginfo]
name=Fedora $releasever - $basearch - Updates - Debug
#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/$basearch/debug/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-debug-f$releasever&arch=$basearch
enabled=0
repo_gpgcheck=0
type=rpm
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

[updates-source]
name=Fedora $releasever - Updates Source
#baseurl=http://download.example/pub/fedora/linux/updates/$releasever/Everything/SRPMS/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-released-source-f$releasever&arch=$basearch
enabled=0
repo_gpgcheck=0
type=rpm
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False
[paul@fedora yum.repos.d]$

**Comment by dufresnep** [comment]
https://pastebin.com/DT8CR3D4

**Comment by travier** [comment]
Can you try cleaning up the package caches and retrying again?

**Comment by travier** [comment]
Fedora 36 is about to go EOL so I'll close this issue. Please provide updated information if this is still an issue.
