### ISSUE TITLE
[BUG] Install of Silverblue fails in current Rawhide with Evince flatpak platform error

### ISSUE THREAD

**Issue by AdamWill** [fedora-silverblue/issue-tracker#298]
If you try and install Silverblue from a recent Fedora Rawhide installer image - e.g. https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20220617.n.0/compose/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-Rawhide-20220617.n.0.iso - it fails, showing a flatpak platform error for Evince:

![silverblueflatpak](https://user-images.githubusercontent.com/916551/174415066-24b79bda-2b03-4943-8d2a-3b981ca2366c.png)

**Comment by tpopela** [comment]
Hi @AdamWill ! Yes, the Fedora Flatpaks were updated for F36 (and infrastructure issues were resolved) so all the applications now require F36 runtime and we have to update pungi config. I've opened https://pagure.io/pungi-fedora/pull-request/1107 for that.
