### ISSUE TITLE
[BUG] No updates since 36.20220617.0

### ISSUE THREAD

**Issue by travier** [fedora-silverblue/issue-tracker#301]
**Describe the bug**

No updates since 36.20220617.0. Also impact Kinoite thus this might be an general issue.

See https://bugzilla.redhat.com/show_bug.cgi?id=2100840

**Comment by travier** [comment]
CC @cgwalters @jlebon

**Comment by travier** [comment]
Coincides perfectly with https://bodhi.fedoraproject.org/updates/FEDORA-2022-39143d1c3e

**Comment by travier** [comment]
We need rpm-ostree-2022.10-3 in F36

**Comment by cgwalters** [comment]
Ugh that we didn't catch this earlier.

(Also still really need to extract the ostree builds out of koji and to work more like FCOS with integrated testing and a pipeline that people who maintain it monitor etc.)

**Comment by travier** [comment]
It's not great that all the Fedora compose failures are conflated into a single ticket as it makes it really hard to track a single variant build :/

**Comment by travier** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2022-bae08a2e98

**Comment by awarda-rh** [comment]
Please excuse if this is a stupid question: do I understand this correctly, that 
(a) the rpm-ostree builds on the silverblue build servers are failing and thus no updates are released?
(b) it is not the local rpm-ostree installed on my f36 silverblue 36.20220617.0 that needs fixing?

**Comment by rowbawts** [comment]
> Please excuse if this is a stupid question: do I understand this correctly, that (a) the rpm-ostree builds on the silverblue build servers are failing and thus no updates are released? (b) it is not the local rpm-ostree installed on my f36 silverblue 36.20220617.0 that needs fixing?

I was wondering the same thing. If a broken build was shipped would there need to be any manual intervention to resolve this on the users end.

**Comment by cgwalters** [comment]
It’s a good question; but no the issue is purely server side, should be deployed soon.

**Comment by travier** [comment]
Yes, this only impacted builds on the Fedora servers. Closing as this is now fixed and we have new updates.
