### ISSUE TITLE
[BUG] Launched toolbox causes boot delays

### ISSUE THREAD

**Issue by SeaDve** [fedora-silverblue/issue-tracker#302]
**Describe the bug**
A launched toolbox causes boot delays (about a minute and a half). However, when I force end the process `toolbox` of user `100000`, there isn't a halt during the shutdown process.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Run `toolbox enter`
2. Run `exit` or `Ctrl + D` (Optional)
3. Shutdown

**Expected behavior**
Shutting down should not be delayed.

**Screenshots**
![1656204365209](https://user-images.githubusercontent.com/64297935/175794888-ac4dc192-3986-4f4c-9bca-12659f1a4493.jpg)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220617.0 (2022-06-17T00:45:03Z)
                BaseCommit: 5bf39cb84b31d36af49e07dfb57a5c531ad7c13a8b2df91397494bea9bf6e871
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: ffmpeg-libs flatpak-builder nautilus-python openssl
             LocalPackages: rpmfusion-free-release-36-1.noarch
```

**Comment by 1player** [comment]
I've already reported it in a few places:

* toolbox: https://bugzilla.redhat.com/show_bug.cgi?id=2081664
* podman: https://bugzilla.redhat.com/show_bug.cgi?id=2084498
* podman upstream: https://github.com/containers/podman/issues/14531

Still no movement yet, but I agree it's extremely annoying. I don't know what triggers it, as there have been times podman was able to be stopped immediately, but not always.

**Comment by SeaDve** [comment]
I think I'll close this as upstream issue?

**Comment by travier** [comment]
All parent bug reports and issues have been fixed!
