### ISSUE TITLE
[BUG] Crash when opening e.g. Steam on rawhide

### ISSUE THREAD

**Issue by morgaesis** [fedora-silverblue/issue-tracker#303]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
When I open Steam after rebasing to rawhide, the screen panics.

__A poem describing the panic__:
First black. Then white.
Screen is normal, but frozen.
The mouse works, nothing else.
A flicker.
Patterned screen. White.
Reboot, rollback.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Rebase to Rawhide
2. Open Steam after login
3. Panic screen

**Expected behavior**
Expected to see Steam open

**Screenshots**
System is unusable, so no screenshots

**OS version:**
```$ rpm-ostree status -b
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● fedora:fedora/rawhide/x86_64/silverblue
                   Version: Rawhide.20220624.n.1 (2022-06-24T16:46:08Z)
                BaseCommit: ce932dc575acbf0333c99023b0b787a18115d7af45b2192e5b30441a38d08379
              GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
           LayeredPackages: gnome-tweaks kitty kitty-terminfo steam syncthing
                            wireguard-tools
```

**Additional context**
Some other programs like Flatpak Chromium do the same.

**Comment by travier** [comment]
This is now old at this point given that Rawhide moves fast so I'll close this issue. Please provide updated information if this is still an issue.

**Comment by coz** [comment]
Problem with current F39 rawhide
[coz@fedora ~]$ fusion-icon
 * Detected Session: mate
 * Searching for installed applications...
python3: /usr/include/python3.12/object.h:215: Py_SIZE: Assertion `ob->ob_type != &PyLong_Type' failed.
Aborted (core dumped)
[coz@fedora ~]$ bleachbit
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 43, in <module>
    import bleachbit.GUI
  File "/usr/share/bleachbit/__init__.py", line 33, in <module>
    from configparser import RawConfigParser, NoOptionError, SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib64/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
[coz@fedora ~]$ blender
bash: blender: command not found
[coz@fedora ~]$ sudo dnf install blender
[sudo] password for coz: 
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
Problem: conflicting requests
  - nothing provides libboost_python311.so.1.81.0()(64bit) needed by blender-1:3.6.0-1.fc39.x86_64
[coz@fedora ~]$ 
 problem is omgoing
