### ISSUE TITLE
[BUG] Unable to change language in Gnome

### ISSUE THREAD

**Issue by escoand** [fedora-silverblue/issue-tracker#310]
**Describe the bug**
After upgrading to F36 I'm unable to change the language in Gnome. No matter what I select in Gnome settings it doesn't change the shown language. Interestingly the login screen and overlays like password screen shows the correct language.

**To Reproduce**
Don't know

**Expected behavior**
Selected language should be used for Gnome.

**Screenshots**
![image](https://user-images.githubusercontent.com/428567/177855093-0814a84c-8e74-4cab-865a-dbe674772bf8.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                   Version: 36.20220707.0 (2022-07-07T00:44:24Z)
                BaseCommit: 05c8b172335c61a0ce63a1a7daa37212b3d48ae98f4e77fae307d96b65331dce
              GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
           LayeredPackages: gnome-tweak-tool langpacks-core-de mozilla-openh264
```

**Additional context**

**Comment by 1player** [comment]
I can't reproduce on 36.20220812.0. I switched to French and back to English. In fact, it never asked me for any password, just to logout after each change.

**Comment by juhp** [comment]
Could you describe the exact steps to reproduce what you are seeing?
(I don't think this is a SB specific issue, if even a bug.)

@1player is correct that Gnome needs to be restarted for the language change to take effect on your desktop.

**Comment by escoand** [comment]
Is there some kind of logging I can provide?

**Comment by travier** [comment]
Can you try doing as https://github.com/fedora-silverblue/issue-tracker/issues/310#issuecomment-1216390738 says or provide the exact steps that lead to your issue?

**Comment by escoand** [comment]
I'm not sure what went wrong. I switched from Fedora Silverblue 35 to 36 beta. I thought it'll be fixed with final release but this didn't happen.

Maybe something in my user config got broken while using the beta.

**Comment by travier** [comment]
Can you try with a fresh new users then?

**Comment by escoand** [comment]
Same problem with a newly created user. I reinstalled Fedora and it's gone.
