### ISSUE TITLE
[BUG] I can't boot in my system

### ISSUE THREAD

**Issue by outweigh** [fedora-silverblue/issue-tracker#321]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in Red Hat Bugzilla or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
I can't boot in the system

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Update Fedora Silverblue
2. Boot in the new image system

**Expected behavior**
It should boot correctly in the system

**Screenshots**
![495](https://user-images.githubusercontent.com/108957859/182912313-747f7d4d-7432-44c6-9c83-53845d65629a.jpg)

**OS version:**
fedora:fedora/36/x86_64/silverblue
                  Version: 36.20220804.0 (2022-08-04T00:47:40Z)
               BaseCommit: 318b9c7a5924a8837a463d694b50d287da0b2c024831ea7853a3562a2f044244
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
      RemovedBasePackages: firefox 103.0.1-1.fc36
          LayeredPackages: firewall-config gnome-tweaks neofetch openssl

**Additional context**

**Comment by travier** [comment]
There is a kernel backtrace up in your "screenshot". You should try to get to it.
Can you try the rollback deployment?

**Comment by outweigh** [comment]
Yes I did that but I want to know how I can update my system without this happen

**Comment by tpopela** [comment]
there might be too many things that may cause your problems - what you might try is get to the working environment, run `rpm-ostree upgrade` and then manually install the older kernel version that is running in the last working environment. If that will work, then open a bug against kernel package in Red Hat Bugzilla. Also this doesn't seem to be related to Silverblue at all, so the Bugzilla is the right venue anyway (and for general questions it might be better to use ask.fedoraproject.org)

**Comment by outweigh** [comment]
Thanks
