### ISSUE TITLE
 Support for Realtek's rtl8192eu-linux driver via COPR(or other repos)

### ISSUE THREAD

**Issue by VihagChaturvedi** [fedora-silverblue/issue-tracker#324]
The driver for rtl8192eu-linux wifi adapter isn't seemingly supported by the kernel OOTB

the official GH repo seems to require dkms, which isnt supported by toolbox or a very complex method via rpm-ostree i am not willing to go through

the drivers are provided via https://github.com/clnhub/rtl8192eu-linux

**Comment by travier** [comment]
If it's an out of tree driver then there is nothing we can do in Fedora short of upstreaming the driver code to the kernel.
I suggest that you ask for/submit an akmod package to be added to [rpm-fusion](https://rpmfusion.org) and that should make it easy to install on Fedora Silverblue.

**Comment by travier** [comment]
https://rpmfusion.org/Packaging/KernelModules/Kmods2 this page should help you get started.

**Comment by travier** [comment]
https://rpmfusion.org/Packaging/KernelModules/Kmods2 this page should help you get started.

**Comment by VihagChaturvedi** [comment]
Sorry for the ping @travier 

> https://rpmfusion.org/Packaging/KernelModules/Kmods2 this page should help you get started.

While trying to compile the driver for myself, I get error like this [pastebin](https://pastebin.com/nhuvy0jM)

Fedora SB(could be KN as well as they are similar by design) seems to lack a directory in the kernel within the `net` folder which causes the install to fail, can you perhaps look into whether or not this is by design?

Directory in question is `/usr/src/kernels/5.18.17-200.fc36.x86_64/net/ipx.h`. This issue could be helpful for future references for installing other drivers from source, hence I want to keep this issue open for longer if that is possible

**Comment by travier** [comment]
I would recommend trying to build this package into a toolbox instead, where you can install any kernel-devel package that maybe be needed to build it.
