### ISSUE TITLE
[BUG] can't overlay libatomic

### ISSUE THREAD

**Issue by afland** [fedora-silverblue/issue-tracker#325]
`libatomic` seems to be broken. The latest update of the [the noise suppression for voice](https://github.com/werman/noise-suppression-for-voice) filter chain in pipewire requires `libatomic`, and I can't seem to overlay it correctly. 

After running `rpm-ostree install libatomic` and rebooting, `rpm-ostree remove libatomic` produces `error: Package/capability 'libatomic' is not currently requested`, so it never installed in the first place?

running `ldd` on librnnoise_ladspa.so` produces
```
	linux-vdso.so.1 (0x00007ffc919ce000)
	libatomic.so.1 => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f2b17b3f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f2b17a61000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2b17a41000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2b1783f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2b17dac000)
```

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Download librnnoise_ladspa.so from the noise suppression for voice repo
2. Run ldd on it
3. Follow the pipewire instructions on the noise suppression for voice repo

**Expected behavior**
The pipewire noise suppression filter chain working as with previous versions

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20220810.0 (2022-08-10T00:46:50Z)
               BaseCommit: 0adbf32421d4bf13c9d691b7ea8019f539f47002988e988078383413bfb73aa5
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
      RemovedBasePackages: firefox 103.0.1-2.fc36 power-profiles-daemon 0.12-1.fc36
          LayeredPackages: distrobox gnome-shell-extension-dash-to-dock gnome-tweaks tlp
```

[journalctl_pipewire.txt](https://github.com/fedora-silverblue/issue-tracker/files/9339440/journalctl_pipewire.txt)

**Comment by 1player** [comment]
As a temporary workaround, might I suggest EasyEffects? Runs in Flatpak, is pipewire native and provides noise cancellation effects.

**Comment by afland** [comment]
> As a temporary workaround, might I suggest EasyEffects? Runs in Flatpak, is pipewire native and provides noise cancellation effects.

Running the noise suppression for voice pipewire filter chain is much more low level and doesn't need any manual button clicking in a GUI, etc. The old version of the librnnoise_ladspa.so doesn't require libatomic, so I'm using that for now. Thanks for the suggestion though, EasyEffects seems great for some of my other use cases

**Comment by travier** [comment]
Likely due to https://github.com/fedora-silverblue/issue-tracker/issues/322

**Comment by afland** [comment]
> Likely due to #322

yup, didin't notice that other packages also weren't persisting
