### ISSUE TITLE
Rawhide Silverblue ostree composes are failing due to "paratype-pt-sans-fonts" package

### ISSUE THREAD

**Issue by AdamWill** [fedora-silverblue/issue-tracker#33]
Just noticed the Silverblue ostree is not building in current Rawhide composes. From [this log](https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20200325.n.0/logs/x86_64/Silverblue/ostree-1/create-ostree-repo.log) it looks like this is the problem:

    error: Packages not found: paratype-pt-sans-fonts

**Comment by tpopela** [comment]
Thank you Adam for the heads-up! The package was renamed and no 'Provides:' with old name were added to a new package. Pinged the developer about it, but to fix it sooner I've created https://pagure.io/workstation-ostree-config/pull-request/164.
