### ISSUE TITLE
Experimental live-fs command contradicts immutability concept & presents security issues?

### ISSUE THREAD

**Issue by mattreallycodes** [fedora-silverblue/issue-tracker#330]
I don't understand the point of the experimental live-fs command since it shifts the filesystem from being immutable to no longer being so. Isn't this usable by would be attackers to manipulate the file system without rebooting, hence invalidating the entire OS immutability security concept?

I know I can disable this command & I can see the utility in being able to shift the FS to a livefs but why at this point not use a different distro? Was there a large demand for being able to create mutability temporarily? Why have this command be usable by default?

Is this the best place to share this?

**Comment by travier** [comment]
This is probably a discussion for the rpm-ostree issue tracker but you can read https://coreos.github.io/rpm-ostree/administrator-handbook/#using-overrides-and-usroverlay for some of the background behind those functionnalities.

In short, this does not let you do more than what was already possible as root so this is not a security issue.

**Comment by travier** [comment]
Closing this one as it is not a security issue. Feel free to comment more with a more concrete description of what would need to be solved.

**Comment by mattreallycodes** [comment]
If you can now execute what could previously be done as root as non root and it invalidates the premise of the OS itself by default. How is that not an inherent security flaw?  What am I missing?

**Comment by jlebon** [comment]
Can you clarify what command you're talking about? Both `rpm-ostree usroverlay` and `rpm-ostree ex apply-live` (aliased also from `rpm-ostree ex livefs`) require root (I guess we should add polkit support for the latter eventually for completeness, but likely as a separate action, and you'd still need authentication).

**Comment by cgwalters** [comment]
> Isn't this usable by would be attackers to manipulate the file system without rebooting, hence invalidating the entire OS immutability security concept?

It's not doing anything that code executing as root on your computer couldn't already do.

**Comment by mattreallycodes** [comment]
I shouldn't be able to execute code that does similar activities to root code on a non root user while rendering the OS temporarily immutable in a secure system.

If someone has root access the whole system is compromised already.
-------- Original Message --------

**Comment by mattreallycodes** [comment]
> Can you clarify what command you're talking about? Both `rpm-ostree usroverlay` and `rpm-ostree ex apply-live` (aliased also from `rpm-ostree ex livefs`) require root (I guess we should add polkit support for the latter eventually for completeness, but likely as a separate action, and you'd still need authentication).

I need to revisit this on my local machine then. I need to determine that there isn't a permissions issue if I can run this without root and that isn't normal. Do you happen to know what the best documentation source is on the command as normal searching doesn't really turn up anything? 

Also is this the best place to have this kind of discussion and if not where is better?
