### ISSUE TITLE
[BUG] LibreOffice flatpak ignores OSTree layers, can't find installed JRE

### ISSUE THREAD

**Issue by XGIVolari** [fedora-silverblue/issue-tracker#336]
The Fedora-specific LibreOffice flatpak doesn't support the OpenJDK flatpak runtime and thus relies on a RPM-based version of Java. On Silverblue with layered Java however, LibreOffice is unable to find a JRE at the supplied default class path, which is /app/lib/jvm/jre-flatpak. When trying to navigate manually to the JRE's location at /lib/jvm through the file picker in LibreOffice's advanced settings, the directory is not present. It can be found however by navigating to /run/host/lib/jvm. Apparently, LibreOffice flatpak ignores any OSTree layering. This also means that all symlinks within /run/host/lib/jvm that link to /etc/alternatives are broken, and the only way to actually select the JRE for use in LibreOffice is by using the only working, versioned folder. (in this case /run/lib/jvm/java-17-openjdk-17.0.4.0.8-1.fc36.x86_64) This means that the correct JRE will have to be manually reselected on every java update, which is far from ideal.

To Reproduce:
Install LibreOffice from Fedora's Flatpak repo, layer java and try to use any java-based extension (e.g. Zotero), then try to navigate to /lib/jvm through LibreOffice's file picker

Expected result:
LibreOffice should find the installed JRE automatically

Actual result:
The JRE needs to be selected at its unlayered location inside /run/host.

**Comment by travier** [comment]
It's by design that Flatpak applications do no look at what's on the host.

In this case we should probably ship Java as part of the LibreOffice Flatpak. It's what the Flatpak from Flathub does: https://github.com/flathub/org.libreoffice.LibreOffice/blob/master/org.libreoffice.LibreOffice.json#L7

**Comment by stbergmann** [comment]
A JRE is included in the LibreOffice flatpak, there's just a bug in the flatpak build scripts after switching from Java 11 to 17.  Taking care...

**Comment by travier** [comment]
Thanks!

**Comment by stbergmann** [comment]
> A JRE is included in the LibreOffice flatpak, there's just a bug in the flatpak build scripts after switching from Java 11 to 17. Taking care...

<https://src.fedoraproject.org/flatpaks/libreoffice/c/ea6db4d204c7614fdec50438862a86b906b85e37> "Adapt container.yaml to switch to java-17-openjdk" should fix this, but a rebuild is currently blocking on <https://bugzilla.redhat.com/show_bug.cgi?id=2121696> "postgresql-private-devel conflicts with libpq-devel over pkgconfig(libpq), blocks rebuild of LibreOffice flatpak"

**Comment by stbergmann** [comment]
> https://src.fedoraproject.org/flatpaks/libreoffice/c/ea6db4d204c7614fdec50438862a86b906b85e37 "Adapt container.yaml to switch to java-17-openjdk" should fix this, but a rebuild is currently blocking on https://bugzilla.redhat.com/show_bug.cgi?id=2121696 "postgresql-private-devel conflicts with libpq-devel over pkgconfig(libpq), blocks rebuild of LibreOffice flatpak"

The rebuilt LibreOffice flatpak at <https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2022-b1708c0bf5> should fix this now.

**Comment by XGIVolari** [comment]
Just installed the new version from Fedora Flatpaks Testing, and everything works now! Thanks a lot for taking care of this so quickly!

**Comment by travier** [comment]
Thanks @stbergmann !
