### ISSUE TITLE
Implement factory reset capability

### ISSUE THREAD

**Issue by jmacato** [fedora-silverblue/issue-tracker#337]
**Describe the bug**
Silverblue is not fully stateless when you try to delete the configuration folders (`/etc/`). User loses all the install-time config and bricks all deployments after a reboot.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. `sudo rm -rf /etc/*`
2. ..
3. profit.. or not 

**Expected behavior**
Deleting `/etc/` and other mutable filesystems should not cripple the system.

**OS version:**
Fedora Silverblue 36 x86_64

**Comment by travier** [comment]
I don't understand what you want to do here. If you want to reset to the default configuration, you can use `ostree admin config-diff` to get a list of config file differing from the default that you can copy back from `/usr/etc` to `/etc`. But you will loose all configuration and any user setup in `/etc/passwd`.

What you should be able to remove is `/var` but I don't think we test that.

We don't claim in the documentation that Silverblue is stateless (I don't know that many projects that are) so I'll will close this one pending a more concrete problem to fix.

**Comment by jmacato** [comment]
I wanted to convey that there should probably be a way to make sure that the user still boots to a usable state even if they nuke their etc and var folders. I know silverblue doesnt claim to be stateless but adding more ways to be resilient is a good thing imo

**Comment by travier** [comment]
Can you define what a "usable state" is for you? Would the users still exists? How does this compare to a factory reset?

**Comment by jmacato** [comment]
@travier by usable state: is basically like on android where the first time prompt will show up, so that users can setup the install like it's freshly installed. Right now when i delete the mutable filesystems, stuff like dbus and systemd just grinds into a halt...

**Comment by travier** [comment]
You're describing a factory reset capability. Moving that to an RFE. See also https://github.com/coreos/fedora-coreos-tracker/issues/399 for a similar discussion.

**Comment by jmacato** [comment]
@travier yeah this is what i wanted to convey, sorry i made this repo late at night lol.. but yes, factory reset that can retain the user files/flatpak apps would be awesome :D

**Comment by jmacato** [comment]
@travier i was able to approximate this, i needed to reset my system again and it was a good thing that i made a snapshot of the freshly installed silverblue on a separate subvol, i restored only the var and root subvols, as well as the boot and boot-efi mounts. It worked like a charm for me at least :)

**Comment by jmacato** [comment]
@travier Hi! Apologies in asking again but is there any discussions/progress wrt to this issue? :)

**Comment by sekalengrengginang** [comment]
factory reset feature like ChromeOS powerwash will be useful.
for example if you want to give Laptop to someone without re-installing silverblue

**Comment by travier** [comment]
@jmacato

Fedora Silverblue is free and open source software and the Fedora Project is a community project. Changes happen when contributors make them happen.

If you're interested in contributing support for that feature in Silverblue, feel free to work on defining how this would look like from a user's perspective, how that would look like from a development perspective, how we could potentially implement that feature, etc.

You may also consider paying someone to work on implementing this feature for you.

**Comment by jmacato** [comment]
@travier Apologies if my previous message sounded entitled, I didn't meant it to be that way, I just thought there was some fixed goalposts for each Silverblue release and was hoping this could be added there somewhat :)

**Comment by AndreiSva** [comment]
I would also appreciate such a feature.

**Comment by LorbusChris** [comment]
Let's reopen this?

**Comment by boredsquirrel** [comment]
this could work pretty well in GNOME, but only in GNOME, as the user creation can be done outside of Anaconda.

For the other desktops this will be more complicated, as they don't have such a user account creation

**Comment by travier** [comment]
As this is a Fedora Silverblue specific tracker and this likely to happen upstream and for all Atomic Desktops, I'm closing this issue in favor of https://gitlab.com/fedora/ostree/sig/-/issues/28.
