### ISSUE TITLE
Bundle gnome-screenshot in the base image

### ISSUE THREAD

**Issue by watzon** [fedora-silverblue/issue-tracker#34]
GNOME is the default DE bundled with Silverblue, but it doesn't seem to come with gnome-screenshot bundled. So keyboard shortcuts _Shift+Ctr+Print_ to take a screenshot and copy it to the clipboard, don't work (even though you do still get the ability to select a region.

Took me a minute to figure out what was wrong.

**Comment by tpopela** [comment]
What Silverblue version you are running? It's expected that the GNOME Screenshot is preinstalled as a Flatpak (starting from Silverblue 32). If you are running an < 32 version, then you have to install the Flatpak manually (with `flatpak install fedora org.gnome.Screenshot`) or overlay the gnome-software package.

**Comment by watzon** [comment]
Ahh that's why, I'm running 31

**Comment by A6GibKm** [comment]
I am running f32 and screenshot wasn't preinstalled and it doesnt respect the adwaita dark theme either.

**Comment by tpopela** [comment]
> I am running f32 and screenshot wasn't preinstalled and it doesnt respect the adwaita dark theme either.

You have to do a clean Silverblue 32 install as Anaconda (the installer is preinstalling Flatpaks). I've done a clean install currently inside VM and confirmed that GNOME Screenshot is preinstalled, shortcut works (pasted the content in GIMP) and also I can confirm that it's not respecting the dark theme. I will pass that to the Fedora Flatpak maintainers.

**Comment by tpopela** [comment]
> it doesnt respect the adwaita dark theme either.

Found the issue - we don't have gnome-theme-extra installed in the runtime. It will be there in the next update. Thank you for reporting @A6GibKm !

**Comment by felipehw** [comment]
@tpopela Could you look the discussion at https://github.com/flathub/flathub/pull/1816 ?

Some points:

> I'm fine with maintaining it here, but I'm not sure it should be Flatpak-ed to begin with, since it won't work in e.g. KDE/Wayland, and we may in future remove the X11 backend or even move the whole UI to gnome-shell and make the app a dummy launcher for it: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2947

> (...) interesting question is whether it is worth it to have a flatpak given the drawback of it only being supported on GNOME+wayland, specially given that there is no clear way to communicate this to the end user.

> Its not, Screenshot is not an app, but part of the Operating System. Its a core utility of GNOME. If your distro doesn't include it, or provide a replacement utility that's a bug with them and shouldn't really spill here. This looks like packaging something for the shake of packaging here.

So ... I wanna ask ro **reconsider** the inclusion of Gnome Screenshot in the vanilla image.
Because:

> Well ... if it is a core utility ... maybe Silverblue should have Gnome Screenshot installed as an RPM inside the vanilla image and not as a Flatpak. (Because it is crazy to have an enormous runtime from fedora Flatpak repo just for Screenshot.)

**Comment by A6GibKm** [comment]
I personally think that it is fine as long as it comes usable out-of the box, the only real downside to its current implementation is having the fedora runtime installed, which might be a little heavy. 

I am completely ignorant on which flatapaks come now installed by default, this might be totally worth the space. Where I can find the list of default flatpaks in Silverblue 32/33?

**Comment by felipehw** [comment]
@A6GibKm 

I installed a fresh Silverblue 32 and here are the results:
```
$ flatpak list
Name                     Application ID                    Version        Branch        Installation
Platform                 org.fedoraproject.Platform                       f32           system
Baobab                   org.gnome.Baobab                                 stable        system
GNOME Calculator         org.gnome.Calculator              3.36.0         stable        system
Calendar                 org.gnome.Calendar                3.36.0         stable        system
GNOME Characters         org.gnome.Characters                             stable        system
Contacts                 org.gnome.Contacts                3.36           stable        system
Evince                   org.gnome.Evince                  3.36.0         stable        system
File Roller              org.gnome.FileRoller                             stable        system
GNOME Logs               org.gnome.Logs                                   stable        system
GNOME Maps               org.gnome.Maps                    3.36.1         stable        system
GNOME Screenshot         org.gnome.Screenshot              3.36.0         stable        system
Weather                  org.gnome.Weather                 3.36.1         stable        system
GNOME Clocks             org.gnome.clocks                  3.36.0         stable        system
Eye of GNOME             org.gnome.eog                                    stable        system
GNOME Fonts              org.gnome.font-viewer             3.32.0         stable        system
gedit                    org.gnome.gedit                   3.32.2         stable        system
$ 
```

**Comment by A6GibKm** [comment]
@ felipehw thanks for the info. The list seems ok. I can notice that GNOME logs are missing tough.

**Comment by tpopela** [comment]
> @felipehw thanks for the info. The list seems ok. I can notice that GNOME logs are missing tough.

They're on the list. What's preinstalled on Fedora Workstation should be preinstalled on Silverblue as well (in Fedora Flatpak if it exists).

**Comment by A6GibKm** [comment]
Oops, you are right.

**Comment by tpopela** [comment]
> @tpopela Could you look the discussion at [flathub/flathub#1816](https://github.com/flathub/flathub/pull/1816) ?

Commented there.

> So ... I wanna ask ro **reconsider** the inclusion of Gnome Screenshot in the vanilla image.

As I mentioned in the Flathub issue we won't be adding Cheese into the base image. Feel free to overlay the RPM package.

**Comment by A6GibKm** [comment]
While the discussion is mostly the same `cheese` and `screenshots` are different apps, I guess you are refering to screenshot? In any case I do agree that their are fine as Flatpak as long as they work.

**Comment by tpopela** [comment]
> While the discussion is mostly the same, `cheese` and `screenshots` are different apps, I guess you are refering to screenshot? In any case I do agree that their are fine as Flatpak as long as they work.

Mea culpa. I don't know why I mistaken it. Thank you for pointing it to me! :)

**Comment by felipehw** [comment]
@tpopela 
Just to avoid confusion... This is the case for Gnome Screenshot?
Because we're not talking about Cheese.

An developer told that maybe Gnome Screenshot turns in a dummy launcher because the implementation could be transferred for gnome shell.

And the app gnome-screenshot don't work in other DEs.

To me... these sounds like strong arguments about why gnome-screenshot is part of the DE and not a functional app by itself (to be distributed like an Flatpak).

**Comment by A6GibKm** [comment]
> An developer told that maybe Gnome Screenshot turns in a dummy launcher because the implementation could be transferred for gnome shell.

Yes, there is an issue for this on gitlab. But these are the kind of things that could happen in a very long time due to very practical reasons.

> And the app gnome-screenshot don't work in other DEs.

3.38 does not even work on Xorg+GNOME.

**Comment by tpopela** [comment]
> @tpopela
> Just to avoid confusion... This is the case for Gnome Screenshot?
> Because we're not talking about Cheese.

See above.

> An developer told that maybe Gnome Screenshot turns in a dummy launcher because the implementation could be transferred for gnome shell.

"maybe" and "could". But in current state it's perfectly fine to have it available as Flatpak and preinstalled. It works here (Wayland, Silverblue 32). If it doesn't work, then please open a bug report upstream.

> And the app gnome-screenshot don't work in other DEs.

Currently Silverblue is officially GNOME only thing. Users of other DEs can remove the app if it doesn't work for them.

**Comment by felipehw** [comment]
Gnome screenshot developers say (from what I understand) that they don't think this app like a standalone, it doesn't work without gnome and neither have plans for use portals (for sandbox technologies like Flatpak).
