### ISSUE TITLE
akmods attempting to call yum

### ISSUE THREAD

**Issue by meisme-dev** [fedora-silverblue/issue-tracker#341]
**Describe the bug**
akmods fails when attempting to install the produced RPM, since it calls `yum` instead of `rpm-ostree`.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1.Run `sudo akmods`.
2. Watch it fail.

**Expected behavior**
akmods succesfully runs.

**Screenshots**
![image](https://user-images.githubusercontent.com/49573906/186711402-7029891e-491e-46d1-ab13-9e3f0892a27b.png)

**OS version:**
```
State: idle
Warning: failed to finalize previous deployment
         error: Bootloader write config: grub2-mkconfig: Child process exited with code 1
         check `journalctl -b -1 -u ostree-finalize-staged.service`
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20220824.0 (2022-08-24T19:32:40Z)
               BaseCommit: 82d3c694d5f585fcb9e2ae37bb0ceda9bc89023cfc633383e4563fd29f1dce30
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
      RemovedBasePackages: firefox 104.0-5.fc36
          LayeredPackages: 'g++' adb akmods chromium cmake cockpit cockpit-podman cryfs cryfs.x86_64 distrobox dnscrypt-proxy docker
                           dotnet firejail flatpak-builder gcc glibc-devel glibc-static gstreamer1-plugin-openh264 java json-glib-devel
                           kvantum langpacks-ar langpacks-en libgee-devel libguestfs-tools libvala libvirt-daemon-config-network
                           libvirt-daemon-kvm lm_sensors.x86_64 lzip make mesa-libGLU neovim nodejs openlibm-devel.x86_64
                           openrgb-udev-rules openssl-devel openssl1.1.x86_64 pip python3-libguestfs python3-pip qemu-kvm sqlite
                           terminator timeshift vala virt-install virt-manager virt-top virt-viewer vte291-devel waydroid

```

**Additional context**
This started when I enabled secure-boot, but I doubt it's related.

**Comment by travier** [comment]
You're probably hitting https://github.com/fedora-silverblue/issue-tracker/issues/322.

You should not run akmods stand-alone.

**Comment by travier** [comment]
Could also be https://github.com/fedora-silverblue/issue-tracker/issues/339

**Comment by meisme-dev** [comment]
> You're probably hitting #322.
> 
> You should not run akmods stand-alone.

The root problem I was trying to solve with `akmods` is solved by a workaround there, thanks.
