### ISSUE TITLE
Can spins use 'Silverblue' in name?

### ISSUE THREAD

**Issue by jkonecny12** [fedora-silverblue/issue-tracker#343]
The Silverblue and it's spins are getting more and more visibility and popularity. I'm really glad for that and want to thank everyone for the great work you are doing. We in Sway SIG are also fans of OSTree based system and want to release an OSTree spin. Now the hard part - name of the spin.

We were looking on possibilities and also [asked community for their ideas](https://fale.io/blog/2022/08/12/fedora-sway-ostree-spin-name). Based on the feedback it seems that people would like to stop using the hard to understand names, like Kinoite or Vauxite. People have hard time to find out what these are about from the name. We in Sway SIG agreed. There is also a [running discussion](https://discussion.fedoraproject.org/t/labs-and-spins-in-the-shadow-of-editions/34143) about the renaming started by @mattdm .

In Sway, we would like to use `Fedora with Sway` and `Fedora Silverblue with Sway` to give people clear understanding of what is the spin about. We were also thinking about `Fedora OSTree with Sway` but we think that `Silverblue` is more known than `OSTree`. I know this was already discussed in [pagure](https://pagure.io/Fedora-Council/tickets/issue/361), however, I think the situation was different back then when there were not so many spins. 

I'm convinced that we should break the current naming scheme because even people around the community have hard time to track what means what, and we should instead use simple names than cryptographic ones.

The question I'm asking here. Are we allowed to use `Silverblue` word in the Sway OSTree based spin? What is your opinion about this? 

_Edit: Rename SilverBlue to Silverblue. Thanks for pointing that out @travier_

**Comment by travier** [comment]
For reference, I started the previous Council discussion about re-using the Atomic branding to have a coherent theme in https://pagure.io/Fedora-Council/tickets/issue/361.

Nit: We write Silverblue not SilverBlue everywhere. Not sure if there is a "rule".

Personally I like the Kinoite branding. It's still **Fedora** Kinoite and it's the part that counts the most: we're part of Fedora first and foremost. It's also shorter than Silverblue KDE. With the "Silverblue + name" logic, only the GNOME variant will be "shorter", much like how Workstation does not mention GNOME right now but we have the Fedora KDE Spin, etc.

Note: I'll let @tpopela speak for Silverblue.

**Comment by travier** [comment]
You might also be interested in https://github.com/fedora-silverblue/issue-tracker/issues/334 which could help share more in terms of efforts.

**Comment by tpopela** [comment]
I don't think that I should have the definitive answer here, but I really like what @travier has done with Kinoite as I think the "Silverblue KDE" wouldn't sound that great as Kinoite. From my point of view by using "Silverblue Sway" you would be closing the opportunity to build a great (and distinctive) identity for your spin as it will be always bound to the Silverblue brand. I will try to ask Allan to chime in as he has way more experience with building the brand identity.

**Comment by allanday** [comment]
I agree with @tpopela .

I'm also not sure that "Silverblue" is a great designator for a shared technological base. Silverblue doesn't intrinsically mean anything... it's really just a code name for this specific project.

What might be interesting would be an alternative brand for OSTree systems, which can be used in combination with more distinctive product names, like how "Intel Inside" is used as a co-brand. That might be useful for Workstation in the future.

**Comment by travier** [comment]
This was my initial idea too behind the Atomic brand revival. We can not reuse the Atomic brand because it has too much history and has an "explosive" / "experimental" feeling but maybe we can com up with something else that showcases stability, container focused, safe upgrades.

**Comment by mattdm** [comment]
> It's rude but it's true, these things need to be said

No. That's **not** how this works. This is not an acceptable way to interact in Fedora spaces. If there's something important to say, say it without personal attacks and without attacks on people's work and contributions. Truth can stand on its own.  Consider this an official warning.

**Comment by travier** [comment]
> It's rude but it's true, these things need to be said

It's not true. I'm the creator of Kinoite and I initially chose the name when I posted it here: https://discussion.fedoraproject.org/t/kinoite-a-kde-and-now-xfce-version-of-fedora-silverblue/147. Please take the time to research the history or to ask about it before spreading misinformation.

As Matthew said, this kind of comments are not welcomed on this tracker. Please stop doing that.

**Comment by jkonecny12** [comment]
I understand your point but I still think that the current solution is great if you have SilverBlue and Kinoite only. However, people are getting confused and forgetting names when there are 4+ like these.

Honestly, I'm still forgetting Vauxite and it will be worse and worse with time. For that reason, I would like to agree on a solution in the future. It may not be SilverBlue but if we go with something else then SilverBlue should follow that otherwise it will create even more confusion between people.

I would say that we are trying to make Fedora more welcoming for the newcomers and these names are not really helping with that.

**Comment by jkonecny12** [comment]
I wonder if we don't want to use the OSTree in that case?

`Fedora OSTree with KDE (aka Kinoite)`
`Fedora OSTree with Sway`
`Fedora OSTree (aka SilverBlue)`

I must say, I like the SilverBlue name which is not helping me right now :rofl:

**Comment by ldelossa** [comment]
Just a random long term Fedora user here chiming in. 

Im interested in Silverblue. Im also a heavy Sway user. I do find it a bit odd that theres a whole new and seemingly unrelated name for the spin called "Kinoite". 

Like mentioned earlier, Silverblue is rather random too (but a cool name regardless), but its the "product" name at this point. From a pure users perspective, id much quicker draw a connection with "Silverblue Sway" then a random (but still cool in its own right!) name "Kinoite". 

This is all very subjective, so raising these points are always tough, but I do do resonate with constancy. Keeping things referring to Silverblue seems more cohesive to me. 

Anyway, ill happily use the spin whether its "Kinoite" or "Silverblue Sway".

**Comment by travier** [comment]
Closing as this is not the place where branding decisions will be taken. The last discussion happened in https://discussion.fedoraproject.org/t/i-am-ok-with-fedora-atomic-brand-now/86235.
