### ISSUE TITLE
New Package Request: podman-docker

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#346]
Please try to answer the following questions about the package you are requesting:

1. the package is not installed in workstation by default but it's totally unnecessary for it , and it's in the repos 

2.  
``` ➜  rpm-ostree install --dry-run podman-docker
Checking out tree 7807435... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates fedora updates-archive
Updating metadata for 'updates-modular'... done
Updating metadata for 'updates'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2022-08-26T07:01:49Z solvables: 4
rpm-md repo 'fedora-modular' (cached); generated: 2022-05-04T21:12:01Z solvables: 825
rpm-md repo 'updates-modular'; generated: 2022-09-07T10:17:47Z solvables: 1467
rpm-md repo 'updates'; generated: 2022-09-10T20:40:07Z solvables: 23560
rpm-md repo 'fedora' (cached); generated: 2022-05-04T21:16:11Z solvables: 67992
rpm-md repo 'updates-archive'; generated: 2022-09-10T21:32:19Z solvables: 35794
Resolving dependencies... done
Installing 4 packages:
  glibc-langpack-en-2.35-15.fc36.x86_64 (updates-archive)
  langpacks-core-en-3.0-25.fc36.noarch (updates)
  langpacks-en-3.0-25.fc36.noarch (updates)
  podman-docker-4:4.2.0-2.fc36.noarch (updates)
Exiting because of '--dry-run' option
```

4.
 ```⬢[root@toolbox edge]# rpm -qi podman-docker
Name        : podman-docker
Epoch       : 4
Version     : 4.2.0
Release     : 2.fc36
Architecture: noarch
Install Date: Sun Sep 11 01:06:46 2022
Group       : Unspecified
Size        : 7338
License     : ASL 2.0 and BSD and ISC and MIT and MPLv2.0
Signature   : RSA/SHA256, Thu Aug 11 16:09:29 2022, Key ID 999f7cbf38ab71f4
Source RPM  : podman-4.2.0-2.fc36.src.rpm
Build Date  : Thu Aug 11 15:44:19 2022
Build Host  : buildvm-a32-06.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://podman.io/
Bug URL     : https://bugz.fedoraproject.org/podman
Summary     : Emulate Docker CLI using podman
Description :
This package installs a script named docker that emulates the Docker CLI by
executes podman commands, it also creates links between all Docker CLI man
pages and podman.
   ```

5. What problem are you trying to solve with this package? Or what functionality does the package provide?

the problem is that silverblue's workflow hugely depend on containers and it mainly uses podman , in some edge cases container images require docker , this package solves this by creating all the required aliases and symlinks for these images to run on podman . 

6. Can the software provided by the package be run from a container? Explain why or why not.

it can be run from a container but since the point of this software is running containers it makes it not very useful inside a container because having containers inside containers is a bit of a mess , and on toolbox it won't function properly as user and only works as root (of the container) which makes stuff even less manageable , so running this software on host is much more useful . 

8. Can the tool(s) provided by the package be helpful in debugging container runtime issues?

yes , and it helps solve the problem where containers just won't run without a docker specific file system or environment variable 

10. Can the tool(s) provided by the package be helpful in debugging networking issues?

no

12. Is it possible to layer the package locally via `rpm-ostree install <package>`? Explain why or why not.

yes it is possible , but such functionality will be very helpful to be available by default for a better experience for developers

**Comment by tpopela** [comment]
As mentioned in the request:

> in some edge cases container images require docker

Do we have to support all the edge cases? From my POV no. I'm curious if there's some meaningful message coming from podman, when one tries to run a container that requires docker (will they get a hint to install podman-docker?).

btw. the Toolbx will be preinstalled on Workstation starting with Fedora 37 so this new package request is applicable to it as well.

**Comment by allaeddineomc** [comment]
docker is "required" only in edge cases , but most of the commands and scripts on the internet for running containerized software are written with docker in mind and need to be edited to run on silverblue , with podman-docker it will be pretty much plug and play for these scripts 

>'m curious if there's some meaningful message coming from podman, when one tries to run a container that requires docker (will they get a hint to install podman-docker?).

i never encountered such message and i'm using podman everyday for literally everything

**Comment by travier** [comment]
You can set your own docker -> podman alias with a simple script in `/usr/local/bin`.

podman does not implement 100% of the docker command line so I don't think we can ship this by default as it would imply that it's fully compatible.

I would say it's up to each user to choose if podman is enough for them or if they really need something only docker does for now.

**Comment by allaeddineomc** [comment]
>You can set your own docker -> podman alias with a simple script in /usr/local/bin.

this package does more than just an alias , it also creates docker socket and more , adding a script to /usr/local/bin is impossible because the location is not writable and adding the script to $HOME/.local/bin is not really a solution since it won't allow for containers as root which are what add docker scripts does , 

>podman does not implement 100% of the docker command line so I don't think we can ship this by default as it would imply that it's fully compatible.

this package makes it clear for the user that it's not really docker on every time the user runs the docker command so it won't be confusing  and i'm not aware of any command that it doesn't emulate including docker build (even when buildah isn't installed)

>I would say it's up to each user to choose if podman is enough for them or if they really need something only docker does for now

if we look at it this way podman is good for almost all use cases and it will just require some additional setup in some cases , adding this package is not for necessity , it's just to help users skip the additional setup

**Comment by travier** [comment]
`/usr/local/bin` is writable on rpm-ostree based systems.

What happens when users install `docker` when `podman-docker` is installed?

**Comment by travier** [comment]
The socket symlink is easily replicated:
```
L+  /run/docker.sock   -    -    -     -   /run/podman/podman.sock
```

The script too:
```
#!/usr/bin/sh
[ -e /etc/containers/nodocker ] || \
echo "Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg." >&2
exec /usr/bin/podman "$@"
```

**Comment by allaeddineomc** [comment]
> What happens when users install `docker` when `podman-docker` is installed?

the packages are conflicting but it's not an issue since fedora silverblue supports rpm package overrides

**Comment by travier** [comment]
Sure, but it's much easier for folks to just `rpm-ostree install podman-docker` or `rpm-ostree install docker` than to figure out `rpm-ostree override remove podman-docker --install docker`.

**Comment by allaeddineomc** [comment]
do they really need to do that ? podman-docker is fully compatible with docker , i think there won't be any point in replacing one with the other

**Comment by travier** [comment]
See https://github.com/fedora-silverblue/issue-tracker/issues/346#issuecomment-1254978621. podman docker doesn't and likely never will implement 100% compatibility with docker, as things like docker Swarm etc. are unlikely to ever be implemented there.

**Comment by travier** [comment]
I'm going to close this one as I don't see things progressing in the future. It can always be revisited if the situation changes.
