### ISSUE TITLE
Create stable/testing/next channel similar to CoreOS

### ISSUE THREAD

**Issue by cgprats** [fedora-silverblue/issue-tracker#348]
Silverblue is an optimal distribution to install on the machines of those who wish to have recent software with minimal maintenance and risk. One negative of silverblue in this usecase is that there is no method to automatically jump between releases (through an rpm-ostree upgrade via CLI or timer). This can pose a significant security issue for users who simply forget to rebase to a new Silverblue version. There is GNOME software which provides a useful and accessible GUI for rebasing to a new release, however that still requires the user to manually intervene and choose to upgrade to the next silverblue release.

One possible enhancement to prevent this would be to create refs that follow the old-stable (previous stable Fedora release that is still maintained), stable (most current Fedora release), next (next Fedora release), and testing (rawhide). The numbered Fedora release should be the default to prevent the system from upgrading between major releases without the user choosing to configure their system to do this. (If the user is at any point prompted to do this graphically would depend on the capabilities of Anaconda or gnome-initial-setup. Otherwise, the user running an rpm-ostree rebase fedora:fedora/stable/x86_64/silverblue would work)

This feature should be safe (or at least as regular silverblue updates) due to the ability to rollback and the fact Silverblue is image based. I have had great success with this on CoreOS.

In theory, it should not require the creation of new images as each channel could simply point to the same images used on the corresponding numbered silverblue channel.

For example (as of 2022/09/14):
 * old-stable would use the same image as Silverblue 35 (There may not be a need for this channel, although it would be convenient for users who use 3rd party GNOME extensions or simply wish to lag a GNOME or glibc version while staying on a supported platform).
 * stable would use the same image as Silverblue 36
 * next would use the same image as Silverblue 37
 * testing would use the same image as Silverblue Rawhide (or could simply not exist)

**Comment by travier** [comment]
I would like to make that happen too and it's quite a change for Fedora so it might take some time. The first steps are to get a better CI setup and I've started working on that in https://github.com/fedora-silverblue/issue-tracker/issues/334.

**Comment by travier** [comment]
I'll close this issue in favor of the one in the Fedora Atomic Desktop issue tracker: https://gitlab.com/fedora/ostree/sig/-/issues/2

While they are not strictly the same issue, this is one likely to happen as part of that change.
