### ISSUE TITLE
SB36 boots to a blank screen unless any usb drive is plugged in

### ISSUE THREAD

**Issue by Windows-Guy** [fedora-silverblue/issue-tracker#349]
I have a core i7 laptop with a broken screen that ive taken off and ive plugged it into an hdmi monitor. When i first installed sb36, it rebooted to a black screen after the install. I finally got it to boot to hdmi and updated it and then it would reboot/start to hdmi every time until today when i got an update. I started to think its booting to my non existent laptop screen except that when i hit the power button it turns off instantly instead of waiting 60 seconds. If i tap f9 at boot and pick what it was going to boot to anyway, it boots w hdmi working. I thought maybe it was wayland but im logging in under xorg. No idea whats going on but i love silverblue and ive spent a lot of time setting this up for what i need. If i cant just turn it on or reboot im going to have to go back to mint, it just works.  I dont have this issue with windows 10, mint20,21, rescuezilla, backbox, rhel8, sb32, tails, uefi bios… so its not my machine

**Comment by Windows-Guy** [comment]
Ps ive had the same issue intermittently w rhel9, fedora36, silverblue34,35,36 so im thinking its wayland, or a timing issue like its looking for something before it had time to initialize, idk but whatever it is its core to fedora and redhat and didnt exist in silverblue32

**Comment by Windows-Guy** [comment]
Intel hd5500

**Comment by travier** [comment]
If you can reproduce this issue with Fedora Workstation 36 then I would suggest opening a bug in Bugzilla with as much details as possible. Thanks

**Comment by Windows-Guy** [comment]
I did a bit more digging on sb36 today. I have a sept 13 backup that i restored to and it turns out that the problem was not in the update after that. The problem seems to be if i do not have my usb flash drive plugged in sb boots to a blank screen and the power button turns the machine off instantly no matter how long i wait. If i have the usb unplugged and i press f9 for the boot menu and hit enter for item 1(sb) it boots. There is no way grub is on my flash drive. Its been wiped w ventoy and some iso’s. So its kind of a security feature:) noone can boot my machine without my flash drive. Its a goofy issue. Ill try an earlier backup and report back

**Comment by Windows-Guy** [comment]
By backup above, i mean whole drive, part table, grub, partitions, everything

**Comment by Windows-Guy** [comment]
My best guess so far is that by having 2 bootable uefi sources or pressing the key to pick what to boot, slows down the boot process enough for the hdmi to go live before its picked up

**Comment by Windows-Guy** [comment]
Ok i went all the way back to my base install plus virt-manager etc no vm dated 9-5 and it boots fine with any of 4 usb flash drives plugged in and it doesnt boot if theyre not plugged in. All of are uefi bootable. Ill format one brb. Humm the plot thickens… i nuked one and put a big blank ntfs partition on it and sb boots with it in and doesnt with it out. Booting is fundemental :) you got any guesses?

**Comment by Windows-Guy** [comment]
That base image is just a fresh install of sb 36 with all the stuff from stephens tech talks youtube video added (i skipped the fonts, extensions and ssl, i just wanted to run kvm) and i updated that rebooted and burnt it. It pretty close to stock

**Comment by Windows-Guy** [comment]
It does seem to hang a bit when it does boot with a usb flash plugged in, then the lighted keyboard blinks off on twice and it boots. Also i have used standard ext4 partitions with one for boot/efi, boot, /, swap (wasnt sure why i needed both boots but it seemed to work that way) i think i did an auto and tried to copy that

**Comment by Windows-Guy** [comment]
I restored a mint 21 image i had from august and i cant get it to not boot. I noticed its logo is on its own screen after the hp logo whereas fedoras is animated and on the hp screen. Not sure that matters but who knows. It may be my manual partitioning. Maybe var needs its own partition off root. I really like that youve got selinux, immutable core, and basically rolling modern automatic updates forever. I thought i was done:) now ive gotta update mint and sb until i decide…

**Comment by travier** [comment]
This seems like a firmware, bootloader or kernel issue. If you can reproduce it with a classic Fedora Workstation installation and report it in Bugzilla that would be great.

**Comment by Windows-Guy** [comment]
Oh… alright :)

this will take a while

**Comment by Windows-Guy** [comment]
The flash drive i wiped out was fedora 36 lol. 
when i get this up ill be installing it w manual ext4 partitions boot/efi, /, and swap to keep w what ive done on sb36

the computer is an
Hp spectre c360 13-4005dx
With intel hd graphics 5500
And a removed built in touch screen

**Comment by Windows-Guy** [comment]
Ok first off the installer does the same thing at launch
Black screen, power off is instant

i have pressed f9 to choose this flash drive to boot to so that trick isnt working

i think im dead in the water here
I cant install it

**Comment by Windows-Guy** [comment]
I wiped out the partitions for my previous install thinking that might change things

it did not
I cant boot to the install iso

i know nothing about bugzilla
Feel free to send all this over there if you want

i gotta get a working computer going so i can send out some invoices

**Comment by Windows-Guy** [comment]
Ive got it installing
I just turned it off on several times
And it came up once
Media tested out fine

**Comment by Windows-Guy** [comment]
Xorg-x11-drv-intel
Sytem failure
Crash function
Intel_enable_ddi

**Comment by Windows-Guy** [comment]
Bug 2127485

**Comment by Windows-Guy** [comment]
Oh btw fastboot was disabled in my bios
When it would only boot w a usb plugged in
Or by selecting it in boot devices

w fastboot on, it doesnt boot no matter what

**Comment by Windows-Guy** [comment]
Just to keep you up to date with what im posting on bugzilla:

Ive also tried rebasing my fedora silverblue to 37 (which must be beta) and that does not fix the issue. Ill try rawhide when i get some time. Ill try things for you if you want. Im pretty sure its related to my specific hardware.

rebasing to rawhide today does not fix the fact that i struggle to get silverblue and fedora to boot
whatever it is, its in both
only solution i have now is to choose bios boot options and pick fedora (which is the only bootable option i have)
then it boots (which is what its trying to do when it doesnt boot)
may be a timing issue with trying to talk to my hdmi monitor before it switches on ... idk

**Comment by travier** [comment]
Note that when you test things here, the bootloader does not get updated in Silverblue when you rebase from one version to the other. You either have to do it manually by syncing the content of `/usr/lib/ostree-boot/` to you EFI partition or do a full re-install with a fresh ISO.

**Comment by Windows-Guy** [comment]
Thx. Ive only been using linux since may. 

how do i go about syncing the content of /usr/lib/ostree-boot/ to you EFI partition

what rebases should i try along with the above
Im not quite sure where testing sits
My guess is its between 37 beta and rawhide

**Comment by travier** [comment]
This is similar to https://github.com/fedora-silverblue/issue-tracker/issues/355. We'll have to write docs for that.

**Comment by Windows-Guy** [comment]
Ive also got what appears to be 2 duplicate entries in grub for a total of 4. Ive never touched it. Ive also not let dbx update because it makes my ventoy usb un bootable. That may be a sign that ventoy is up to no good, but at this point its too late. Ive used it for everything. Is there any chance this will all be fixed in 37?

**Comment by travier** [comment]
Duplicated boot entries is https://github.com/fedora-silverblue/issue-tracker/issues/120

**Comment by p-fruck** [comment]
Seems to related to multiple devices in the HP x360 lineup. I am owning an HP EliteBook x360 1030 G3 with Intel® UHD Graphics 620 (KBL GT2) graphics and facing the following issues: I have the device attached to a USB C display which I use to power on the laptop. If the laptop is closed I am experiencing the same black screen issue. If the laptop is opened, it boots just fine regardless whether it is attached to the USB C display. FB enabled.

**Comment by kuba3351** [comment]
I switched from Dell Latitude 5400 to Lenovo ThinkPad L15 Gen 1, and didn't experienced this issue on Dell, but it exist on Lenovo. I have a workaround for this, when system boots to black screen, I open the lid of the laptop and the screens sometimes initializes properly, but it will be nice if someone can provide a resolution.

**Comment by Windows-Guy** [comment]
Fedora 37 fixed all this
