### ISSUE TITLE
Fedora-Silverblue-ostree-aarch64-Rawhide-20220927.n.0.iso does not boot on Raspberry Pi 4 64Bit

### ISSUE THREAD

**Issue by AWHubGit** [fedora-silverblue/issue-tracker#361]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**

Fedora-Silverblue-ostree-aarch64-37_Beta-1.5.iso and others do not boot

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. write iso with FedoraMediaWriter to USB stick and insert in Raspi4 64Bit and try to boot
2. ..

**Expected behavior**
Fedora-Silverblue-ostree-aarch64-37_Beta is booting to LIVE desktop

**Screenshots**

**OS version:**
Fedora-Silverblue-ostree-aarch64-37_Beta and Silverblue rawhide for aarch64
Please replace this line with output of `rpm-ostree status -b`
not possible

**Additional context**

I have a Raspberry Pi 4 64Bit and a Kingston Traveller USB stick. I have resetted EEPROM on Raspi4 to boot firstly from USB stick.
I have written Raspberry Pi OS (64-bit) https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-09-26/2022-09-22-raspios-bullseye-arm64.img.xz to USB stick with Raspberry Imager. Raspi OS boots until Desktop and works fine. No problem. 

Then I have written on same USB stick with FedoraMediaWriter https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-Rawhide-20220927.n.0.iso and tried to boot as did before with Raspi OS.

Doesn't boot. A red-white screen from Raspi64 (EEPROM?) appears and asks for OS net installation. I tried several times. No success.

I tried to write downloaded Silverblue.iso with BalenaEtcher tool vers 1.7.9 to USB stick. BalenaEtcher tool claims:
Missing Partition Table!
It looks like this is not a bootable image. The image does not appear to contain a partition table, and might not be recognized or bootable by your device.

I think Raspberry Pi searches for a boot partition with FAT32 and doesn't find it.

How to boot/use these isos Fedora-Silverblue for aarch64 on Raspberry Pi 4? What is wrong?

Rgds
AW

**Comment by travier** [comment]
`Fedora-Silverblue-ostree-x86_64-Rawhide-20220927.n.0.iso` from the issue title is for x86_64 only so will not boot on Raspberry Pi. Can you double check that you're using an aarch64 image?

**Comment by travier** [comment]
You should likely use a raw image from https://alt.fedoraproject.org/alt/. See also https://fedoraproject.org/wiki/Architectures/ARM & https://fedoraproject.org/wiki/Architectures/ARM/Installation

**Comment by AWHubGit** [comment]
I am sorry. It's an error from me. I didn't use x86_64.iso. Of course I try to boot with aarch64.iso onyl for Raspi4. Not x86_64.

I tried again.
Fedora-Silverblue-ostree-aarch64-37_Beta-1.5.iso
Fedora-Workstation-Live-aarch64-36-1.5.iso
Fedora-Silverblue-ostree-aarch64-Rawhide-20220927.n.0.iso

All these are not bootable. Always red-white screen from Raspi EEPROM for installation net install.

https://alt.fedoraproject.org/alt/ doesn't list Fedora Silverblue. I want explicitly install Fedora Silverblue.

In FedoraMediaWriter it is offered to install Fedora Silverblue 37 Beta AArch64. Why can't I use this offer?

**Comment by travier** [comment]
This is an installation ISO, not a boot-able disk image. You would have to use it to install the system like you would do on a classic x86_64 installation. I don't know if the Raspberry Pi can do that. You'll likely want to use a pre-installed disk image.

Unfortunately I don't think we make pre-installed images for Silverblue so you'll have to:
- use a pre-install Raw image from Fedora IoT, which is also based on rpm-ostree (see https://getfedora.org/en/iot/download/)
- install it using the arm-image-installer (see https://fedoraproject.org/wiki/Architectures/ARM/Installation)
- then rebase to Silverblue using:
```
$ sudo rpm-ostree rebase fedora:fedora/37/aarch64/silverblue
```

**Comment by LorbusChris** [comment]
@AWHubGit are you using the https://rpi4-uefi.dev/ firmware on the pi? Stock images will only work with that.
If you're not using that firmware, you have to use https://pagure.io/arm-image-installer/ to create a bootable image for the RPi.

**Comment by AWHubGit** [comment]
My intention was to install an immutable OS on Raspi4 aarch64.
I switched to openSUSE microOS
With openSUSE-MicroOS-DVD-aarch64-Snapshot20220926-Media.iso I could boot into Yast and was able to install to SDcard. It is up and running Gnome-Desktop.
