### ISSUE TITLE
Sound doesn't work off fresh install

### ISSUE THREAD

**Issue by j-dominguez9** [fedora-silverblue/issue-tracker#363]
**Describe the bug**
After downloading the latest iso of silverblue, sound doesn't work --neither through laptop speakers (Apple MBP 2017, 13"), connected headphones, nor Bluetooth headphones.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. ..
[alsa-info.txt](https://github.com/fedora-silverblue/issue-tracker/files/9711622/alsa-info.txt)

2. ..

**Expected behavior**
Sound to work

**Screenshots**

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20221003.0 (2022-10-03T00:43:00Z)
               BaseCommit: cf6f4a177210c9ab448082fbe7c84aab98847e02d1e5faf7b71a3be3faf6b8c2
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
      RemovedBasePackages: pipewire-pulseaudio 0.3.59-1.fc36
          LayeredPackages: alsa-firmware alsa-plugins-pulseaudio pulseaudio
[joaquindominguez@silverblue ~]$ 


```

**Comment by travier** [comment]
You've removed/replaced audio related packages. Please try with the default set of packages. If it still does not work, please try to reproduce the issue with Workstation before reporting a bug upstream.

**Comment by j-dominguez9** [comment]
Closing the issue, not bc it is solved, but rather after researching the issue further, concluded it is being caused by incompatible firmware associated with this model (Mackbook Pro 2017, non-touch bar, (14,1)).
