### ISSUE TITLE
Installing from rpmfusion requires two reboots

### ISSUE THREAD

**Issue by A6GibKm** [fedora-silverblue/issue-tracker#37]
When installing rpmfusion as a .rpm repository the system will require one reboot to add the repository and another to install packages from it, is there a way to reduce this to a single reboot? 

This is related to the issue when rebasing will cause issues with packages from rpmfusion.

**Comment by jlebon** [comment]
This is a known UX wart. Discussions about this in https://github.com/coreos/rpm-ostree/issues/1978.

**Comment by A6GibKm** [comment]
Thanks for the link, that was precisely the issue I was referring to.

**Comment by tpopela** [comment]
I will close this as it should be discussed in the rpm-ostree issue.
