### ISSUE TITLE
Upgrade issues with openssl and nvidia

### ISSUE THREAD

**Issue by MonsterObserver** [fedora-silverblue/issue-tracker#376]
**Describe the bug**
Can't upgrade because of openssl
```
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - package akmod-nvidia-3:520.56.06-1.fc37.x86_64 requires akmods, but none of the providers can be installed
  - package akmods-0.5.7-9.fc37.noarch requires openssl, but none of the providers can be installed
  - package openssl-1:3.0.5-2.fc37.x86_64 requires openssl-libs(x86-64) = 1:3.0.5-2.fc37, but none of the providers can be installed
  - cannot install both openssl-libs-1:3.0.5-2.fc37.x86_64 and openssl-libs-1:3.0.5-3.fc37.x86_64
```

**To Reproduce**
`rpm-ostree upgrade`

**Expected behavior**
I expect to upgrade without openssl issues.

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20221101.n.0 (2022-11-01T07:56:01Z)
               BaseCommit: dff191b80d5a36a2bdfb3ba2aad4d5b1fd167c7d8492c11c9902a7c2b14f5e4d
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
      RemovedBasePackages: firefox firefox-langpacks 105.0.1-2.fc37 gnome-software gnome-software-rpm-ostree 43.0-4.fc37 gnome-tour 43.0-1.fc37 yelp 2:42.2-1.fc37
          LayeredPackages: akmod-nvidia ckb-next fish gnome-shell-extension-pop-shell gnome-tweaks libratbag-ratbagd micro neofetch xorg-x11-drv-nvidia
                           xorg-x11-drv-nvidia-cuda xprop

```

**Comment by travier** [comment]
Might be because the archive repo is not yet enabled. Should resolve itself in a day.

**Comment by MonsterObserver** [comment]
> Might be because the archive repo is not yet enabled. Should resolve itself in a day.

Thanks, it did fix itself today, however upgrading again gave me an error about the upgrade removing systemd. I found online that refreshing the metadata with `rpm-ostree refresh-md` would fix this issue, but now it's spitting another error at me:

`error: Updating rpm-md repo 'rpmfusion-nonfree-updates-testing': cannot update repo 'rpmfusion-nonfree-updates-testing': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Downloading successful, but checksum doesn't match. Calculated: 632218ba7684d89f2f3e15a42191c6a0c6e0c39e05594b4d36527ec4737665a5e34dbdb7b9a79df5ddcfb3cabb5f90a39114f59039c50423d3ee5a12f233cbfb(sha512)  Expected: 171a071c759544f3b685ca79e7c3024215a3087353bd4548429bc716229e2cd0ce553403f6ba70c462aa1c5a351bef50496a5a7eea1f3fb62d6962b8d6aadd9a(sha512)`

Is this an issue on my part or is there something wrong with the mirrors?

**Comment by MonsterObserver** [comment]
This fixed itself, closing issue now.
