### ISSUE TITLE
Allow the removal of fedora-workstation-repositories and fedora-flathub-remote

### ISSUE THREAD

**Issue by Mershl** [fedora-silverblue/issue-tracker#379]
**Description**
`fedora-workstation-repositories` is a package providing 3rd party non-free software repositories for `gnome-software`.

`fedora-workstation-repositories` package description:
"Repository files that make some select non-Fedora software available via search in gnome-software."

As of Silverblue 36 `fedora-workstation-repositories` is listed required by the meta-package `fedora-release-silverblue`, which makes it not possible to `override remove fedora-workstation-repositories` on an Silverblue 36 installation.

**To Reproduce**
`rpm-ostree override remove gnome-software-rpm-ostree gnome-software fedora-workstation-repositories`
```
error: Could not depsolve transaction; 1 problem detected:
 Problem: package fedora-release-silverblue-36-20.noarch requires fedora-workstation-repositories, but none of the providers can be installed
  - conflicting requests
```

**Proposal**
A) Move require dependency from `fedora-release-silverblue` to `gnome-software` (see `fedora-workstation-repositories` description above) which should still install the package by default, but allow its removal when doing it in one transaction with `gnome-software`.
B) Degrade require to recommends relation from `fedora-release-silverblue` to `fedora-workstation-repositories` which should still install the package by default, but allow its removal.

**Comment by travier** [comment]
I'd prefer option B and I think it's reasonable. We still want to make sure that it gets included in the image by default so we can probably list it explicitly but users you be fine removing it.

You can also remove the repo configs directly from `/etc` and rpm-ostree won't add them back on upgrades.

**Comment by travier** [comment]
CC @tpopela

**Comment by juhp** [comment]
I think this is not Silverblue specific, so I suggest opening a bug against Fedora's fedora-workstation-repositories component in bugzilla.

**Comment by Mershl** [comment]
> I think this is not Silverblue specific, so I suggest opening a bug against Fedora's fedora-workstation-repositories component in bugzilla.

The hard requirement is specified in the spec of `fedora-release-silverblue`, which is Silverblue specific.

```
$ rpm -qR fedora-release-silverblue-36-20.noarch
fedora-flathub-remote
fedora-release-common = 36-20
fedora-release-ostree-desktop = 36-20
fedora-workstation-repositories
```

**Comment by tpopela** [comment]
Yes, I would go with the "b)" option as well - are you able to create the PR in https://src.fedoraproject.org/rpms/fedora-release?

**Comment by travier** [comment]
Looks like indeed we should do the change for Workstation too at the same time.

**Comment by travier** [comment]
So the suggestion from @juhp makes sense, we should open a bug there or discuss in the PR.

**Comment by Mershl** [comment]
Created https://src.fedoraproject.org/rpms/fedora-release/pull-request/232

**Comment by Mershl** [comment]
Feedback from  sgallagh on the linked PR:

> I think the best approach would be to remove the Requires(meta) entirely and add the packages instead to the Silverblue ISO directly as part of the default installation. That would make them removable, but still installed by default.

@travier @tpopela do you agree with this proposal? which package would be a good candidate to move these dependencies to?

**Comment by travier** [comment]
We can remove the dependency and add those packages to the comps files so that they are included in the image by default but override-able.

**Comment by travier** [comment]
Note that we need to merge the comps change first, do the sync for Silverblue, then remove the dependencies to avoid a situation where we would remove them from the current images.

**Comment by travier** [comment]
PRs:
- https://pagure.io/fedora-comps/pull-request/789
- https://pagure.io/workstation-ostree-config/pull-request/337

Then we can remove the dependency in the `fedora-release` package.

**Comment by Mershl** [comment]
Thank you @travier!

As the comp changes have now been merged let's create a new PR which cleanly removes the `Requires` relations from `fedora-release-silverblue`.

Created https://src.fedoraproject.org/rpms/fedora-release/pull-request/247

**Comment by travier** [comment]
This done for F38+. I should be possible to backport it for F37 given that I backported the additions too.

**Comment by Mershl** [comment]
```
$ rpm-ostree override remove fedora-workstation-repositories fedora-flathub-remote
Removed:
  fedora-flathub-remote-1-5.fc38.noarch
  fedora-workstation-repositories-38-2.fc38.x86_64
```
feels good :+1: (I'm on Silverblue 38)

> I should be possible to backport it for F37

Shall I, do you want?

**Comment by Mershl** [comment]
Created backport for f37: https://src.fedoraproject.org/rpms/fedora-release/pull-request/250

**Comment by edwintorok** [comment]
This seems to have regressed with Fedora 41 (Fedora 40 was fine):
```
sudo rpm-ostree override remove fedora-workstation-repositories
Inactive base removals:
  power-profiles-daemon
Inactive requests:
  tuned-ppd (already provided by tuned-ppd-2.24.0-5.fc41.noarch)
  kernel-tools (already provided by kernel-tools-6.11.5-300.fc41.x86_64)
Checking out tree 78c465f... done
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: package plasma-welcome-fedora-6.1.2-1.fc41.noarch from @System requires fedora-workstation-repositories, but none of the providers can be installed
  - conflicting requests
```

**Comment by juhp** [comment]
plasma-welcome-fedora is not part of Silverblue (perhaps you are on Kinoite or overlayed) - anyway better to open a new issue for KDE/Kinoite perhaps?

**Comment by travier** [comment]
If you really want to remove those packages, then you also have to remove plasma-welcome but they are inactive by default and removing them from /etc is enough, no need to override them to remove them from the image.
