### ISSUE TITLE
Fedora 32 Silverblue DVD install failing with Evince flatpak error

### ISSUE THREAD

**Issue by AdamWill** [fedora-silverblue/issue-tracker#38]
Installs of the [Silverblue DVD installer image in today's Fedora 32 compose](https://kojipkgs.fedoraproject.org/compose/branched/Fedora-32-20200402.n.0/compose/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-32-20200402.n.0.iso) are failing with an error about the Evince flatpak:

"Failed to install flatpaks: flatpak-error-quark: The application org.gnome.Evince/x86_64/stable requires the runtime org.fedoraproject.Platform/x86_64/f32 which was not found (8)"

Not sure what's going on there. More logs and so on can be found in the [test](https://openqa.fedoraproject.org/tests/564924)'s [Logs & Assets tab](https://openqa.fedoraproject.org/tests/564924#downloads).

**Comment by tpopela** [comment]
Thank you Adam for the report! I expect that it will be fixed in the next compose as Kalev made this fix https://pagure.io/pungi-fedora/c/aeef32b50d0cc748f8907b993767c576e5b6257a?branch=master (switch from F31 runtime to a F32 one).

**Comment by AdamWill** [comment]
Yup, indeed fixed in [today's compose](https://openqa.fedoraproject.org/tests/566009). Thanks.

**Comment by lakano** [comment]
@tpopela Do you known if this could be related to this bug #42 ?

**Comment by tpopela** [comment]
@lakano no it isn't. It's a different one.
