### ISSUE TITLE
Silverblue Rawhide installation crashes on UEFI when trying to set up the system.

### ISSUE THREAD

**Issue by lruzicka** [fedora-silverblue/issue-tracker#380]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
After the fresh installation of Silverblue on UEFI based VM, Gnome crashes when the **Start Setup** button is clicked. The system itself is still running in the background, but stays inaccessible because the root password does not exist and the user has not yet been created.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Create an EFI based virtual machine.
2. Use it to run the Silverblue installation.
3. After the installation reboot into the newly created system.
4. Gnome starts and shows the screen that is used to confirm the system setup.
5. Click on the "Start Setup" button. 

Result: The graphical session crashes and the system arrives to an empty TTY1.

**Expected behavior**
The system set up should be performed normally.

**Screenshots**
See the openQA test https://openqa.fedoraproject.org/tests/1579101#
and the recorded video: https://openqa.fedoraproject.org/tests/1579101/video?filename=video.ogv

**OS version:**
This happens on the 20221108 compose of Silverblue

**Additional context**
The BIOS version seems to be working normally.

**Comment by tpopela** [comment]
Can you please get the backtrace from the coredumpctl? Also is this really Silverblue specific? The 20221108 Workstation compose works?

**Comment by lruzicka** [comment]
> Can you please get the backtrace from the coredumpctl? Also is this really Silverblue specific? The 20221108 Workstation compose works?

Yes, the 20221108 compose works, see https://openqa.fedoraproject.org/tests/1577797 (this is the same test case run with Workstation compose). I have also tested locally and Silverblue really fails on EFI VMs.

How do I run the `coredumpctl` when I do not have any access to that system? The installation has not created any users yet, so the system will not let me in. I have tried to set up the root password in a single user mode, but the system did not let me log in after it has booted anyway.

**Comment by AdamWill** [comment]
I filed this in [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2141140) some time ago. Multiple issues in Silverblue on Rawhide showed up at the same time, including this one - all when systemd 252 landed. @cgwalters [suggested](https://bugzilla.redhat.com/show_bug.cgi?id=2141140#c3) it's likely something to do with a change described as:

"* Systemd can optionally do a full preset in the "first boot" condition
      (instead of just enable-only). This behaviour is controlled by the
      compile-time option -Dfirst-boot-full-preset. Right now it defaults
      to 'false', but the plan is to switch it to 'true' for the subsequent
      release."

@lruzicka what we can do to debug this probably is the same trick openQA does to set a root password after the install completes and before rebooting to the installed system, see https://pagure.io/fedora-qa/os-autoinst-distri-fedora/blob/main/f/tests/_do_install_and_reboot.pm#_165 .

**Comment by AdamWill** [comment]
You could've just checked the Bugzilla bug I linked above and found that it was fixed...

**Comment by travier** [comment]
Thanks, I had missed that!
