### ISSUE TITLE
[BUG] The building deployment process is not shown in GNOME Software

### ISSUE THREAD

**Issue by milachew** [fedora-silverblue/issue-tracker#383]
**Describe the bug**
When a new release of Fedora is released, after downloading the update, the Restart and Update button does not show the build deployment progress.
Because of this, the feeling of a broken button is created, although the deployment process can be viewed through `rpm-ostree status`.

**To Reproduce**
1. Get message of new Fedora version.
2. Click download.
3. Click Reboot and Update.
4. To feel perplexed as to why nothing is changing.
5. To understand from the coolers that something is going on. Decide to wait.
6. Get a reboot suggestion after some time.

**Expected behavior**
Move the progress of building the deployment BEFORE the Reboot and Update button appears.

**Screenshots**

https://user-images.githubusercontent.com/113530911/202030917-1042a320-2eb4-4c93-a4e0-56c69c1e6ad5.mov

**OS version:**
```
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20221115.0 (2022-11-15T00:49:34Z)
```

**Comment by tpopela** [comment]
Please report it against the upstream GNOME Software issue tracker - https://gitlab.gnome.org/GNOME/gnome-software/-/issues

**Comment by milachew** [comment]
@tpopela, [done](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1967), thanks!

Is this a purely upstream problem?
Or should this issue not be closed yet?

**Comment by tpopela** [comment]
As we don't have any downstream modifications of GNOME Software it will eventually get into Silverblue from upstream and as it's tracked in https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1967 there's no need for this issue. Thank you for reporting the issue though!
