### ISSUE TITLE
rtw88 breaks since kernel 5.19

### ISSUE THREAD

**Issue by Plamper** [fedora-silverblue/issue-tracker#385]
**Describe the bug**

Since kernel the update for kernel 5.19  I am not able to connect to the internet with said driver. 

**To Reproduce**

Use RTL_8822CE as wifi card
Connect to network
ping google.com for example
nothing happens

**Expected behavior**

I am able to connect to the internet

**OS version:**

Kernel 5.19 and up.
Fedora Silverblue 36 & 37
last known working basecommit d4a525b30f45403bfcf8c3f0b7549953db0a6af435e935436e47a084d92a2466
Doesn't happen on Fedora 37 Live ISO

**dmesg**
```
[   15.014685] wlo1: authenticate with 9c:c9:eb:4f:ab:7b
[   15.420982] wlo1: send auth to 9c:c9:eb:4f:ab:7b (try 1/3)
[   15.424371] wlo1: authenticated
[   15.431133] wlo1: associate with 9c:c9:eb:4f:ab:7b (try 1/3)
[   15.434544] wlo1: RX AssocResp from 9c:c9:eb:4f:ab:7b (capab=0x31 status=0 aid=1)
[   15.434924] wlo1: associated
[   15.605972] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[   15.680282] IPv6: ADDRCONF(NETDEV_CHANGE): wlo1: link becomes ready
[   23.991559] rfkill: input handler enabled
[   25.405352] Lockdown: systemd-logind: hibernation is restricted; see man kernel_lockdown.7
[   26.111440] rfkill: input handler disabled
[   31.199054] rtw_8822ce 0000:01:00.0: failed to get tx report from firmware
[  329.513609] wlo1: deauthenticated from 9c:c9:eb:4f:ab:7b (Reason: 3=DEAUTH_LEAVING)
[  329.562203] rtw_8822ce 0000:01:00.0: timed out to flush pci tx ring[1]
[  329.562324] rtw_8822ce 0000:01:00.0: timed out to flush pci tx ring[3]
[  329.674073] rtw_8822ce 0000:01:00.0: timed out to flush queue 1
[  329.784067] rtw_8822ce 0000:01:00.0: timed out to flush queue 2
[  329.785111] rtw_8822ce 0000:01:00.0: timed out to flush pci tx ring[1]
[  329.785226] rtw_8822ce 0000:01:00.0: timed out to flush pci tx ring[3]
[  329.895095] rtw_8822ce 0000:01:00.0: timed out to flush queue 1
[  330.006078] rtw_8822ce 0000:01:00.0: timed out to flush queue 2
[  333.035292] wlo1: authenticate with 9c:c9:eb:4f:ab:7b
[  333.326499] wlo1: send auth to 9c:c9:eb:4f:ab:7b (try 1/3)
[  333.329960] wlo1: authenticated
[  333.338072] wlo1: associate with 9c:c9:eb:4f:ab:7b (try 1/3)
[  333.341538] wlo1: RX AssocResp from 9c:c9:eb:4f:ab:7b (capab=0x31 status=0 aid=1)
[  333.341915] wlo1: associated
[  340.006315] rtw_8822ce 0000:01:00.0: failed to get tx report from firmware

```

**Comment by tpopela** [comment]
As we share the same kernel with the rest of the Fedora, please report the issue against the Fedora kernel at https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=kernel&version=37

**Comment by travier** [comment]
The Fedora 37 release ISO is using the 6.0 kernel so you might want to try fully updating your system and try again.

**Comment by Plamper** [comment]
The bug has already been reported [here](https://bugzilla.redhat.com/show_bug.cgi?id=2120056) but hasn't gained any attention in the last three months and since it appears to be that only Silverblue is affected. I thought I might as well report it here. Fully updating the system doesn't resolve the problem.

**Comment by travier** [comment]
It's very unlikely that a kernel driver behaves differently on Silverblue than Classic Fedora.

**Comment by Plamper** [comment]
I did a fresh install of Silverblue. Then I reboot and it appears to work. After that I perform an update after I reboot it's broken again and rollback wouldn't change that. After that I tried regular Fedora, wifi works in liveboot but doesn't in the final install. So it's probably a hit or miss situation and I am sometimes just lucky when I boot the USB.
