### ISSUE TITLE
Unable to rebase/update from Fedora 36 to Fedora 37

### ISSUE THREAD

**Issue by cold-distance** [fedora-silverblue/issue-tracker#386]
Hi, I don't know if this report is redundant. If it's redundant, please, close this.

I tried to update yesterday from Fedora 36 Silverblue to Fedora 37 Silverblue for several hours, but I couldn't do it. I found this after doing a simple search in Google, so it's a bug. https://github.com/coreos/rpm-ostree/issues/4150

I tried to update the system with GNOME Software first and the command line second and it was impossible. It seems that rpm-ostree hangs in some part of the process and never finish.

It seems that reseting rpm-ostree can avoid the problem, but that's not an optimal solution for people who modify many RPM packages. I don't use RPM Fusion, but I have some layered packages, among them 'bluez-obexd', that it was added after a bug report because Fedora lost the ability to transfer files. https://bugzilla.redhat.com/show_bug.cgi?id=2090443

By other hand, I have Firefox RPM override because I prefer to use the Flatpak package took from Flathub. IMO it's more orthodox.

I would like to update through GNOME Software, but the command line is OK in the worst of cases.

Sorry if I'm bothering you and my English is not perfect.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Just try to do a standard rebase from Fedora 36 Silverblue to Fedora 37 Silverblue: `rpm-ostree rebase fedora:fedora/37/x86_64/silverblue`
2. You can see that the process hangs in some point.

**Expected behavior**
Obviously, to update the system as usual.

**Screenshots**
If you try to do the process through the command line, this is the warning/error you can see. The screenshot is not mine, but it's public and I have the same error.

![202817116-ca5f59c2-5046-4467-b530-b3affe124b78](https://user-images.githubusercontent.com/43167050/202849760-752ef104-287f-4c13-8def-f39d673e8a77.png)

By other hand, this my current rpm-ostree status. It's useless, but the 'bluez-obex' package and the overriding of Firefox RPM are two non-normal scenarios you can try.
![Captura desde 2022-11-19 12-56-42](https://user-images.githubusercontent.com/43167050/202849841-a12b36ad-7642-43c8-9d7c-5bf471e9c25a.png)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/36/x86_64/silverblue
                  Version: 36.20221116.0 (2022-11-16T02:07:48Z)
               BaseCommit: 72c141b124b0aa045e435d3b4cc8d1746e1a1e8401209e33b74b753e7ff7dde8
             GPGSignature: Valid signature by 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
      RemovedBasePackages: firefox 106.0.4-1.fc36
          LayeredPackages: android-tools bluez-obexd fatsort fira-code-fonts firewall-config igt-gpu-tools inxi
                           lm_sensors lshw neofetch radeontop steam-devices webp-pixbuf-loader
```

**Comment by SViN24** [comment]
I had issues during the 37 beta which i am not sure are applicable anymore but they were related to firefox and firefox-langpacks(which requires firefox but is part of the default install)
I recommend  you re install firefox, update to the new release and then re-remove firefox.

**Comment by cold-distance** [comment]
I just updated to Fedora 37 and I have the same bug when I try to override Firefox.

**Comment by SViN24** [comment]
> I just updated to Fedora 37 and I have the same bug when I try to override Firefox.

You need to remove firefox-langpacks first and then remove firefox.
