### ISSUE TITLE
Include git docs

### ISSUE THREAD

**Issue by morgaesis** [fedora-silverblue/issue-tracker#387]
`git` is bundled with Fedora Silverblue, but not its manpages. This is annoying, since many `git` commands want to show the manpages.

Example:
```
$ git --help
usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
...

$git commit --help
No manual entry for git-commit
```

Please add git manpages to the base bundle 😃

**Comment by tpopela** [comment]
I see that it's included in Workstation:

[liveuser@localhost-live ~]$ rpm -qa | grep "^git-"
git-core-2.37.3-1.fc37.x86_64
git-core-doc-2.37.3-1.fc37.noarch
git-2.37.3-1.fc37.x86_64

We don't exclude it intentionally https://pagure.io/workstation-ostree-config/blob/main/f/comps-sync-exclude-list.yml, but we probably have to explicitly add it to https://pagure.io/workstation-ostree-config/blob/main/f/fedora-common-ostree.yaml#_16 . @travier what do you think?

**Comment by travier** [comment]
So it's about adding the `git-core-doc` package right?
I'm fine with adding it. I'm wondering why we have it in Workstation and not in Silverblue/Kinoite.

**Comment by travier** [comment]
Ah, we're excluding the full git package and only including git-core instead.

**Comment by travier** [comment]
Maybe we should just include the full Git? For Fedora CoreOS we use `git-core` to not get Perl, but for Silverblue/Kinoite we already have Perl in the image.

**Comment by travier** [comment]
Hum, we don't have Perl anymore in Silverblue now, only on Kinoite.

**Comment by travier** [comment]
https://pagure.io/workstation-ostree-config/pull-request/322

**Comment by travier** [comment]
Still open to adding the full Git package but it will bring back Perl to Silverblue.

**Comment by morgaesis** [comment]
Adding Perl is overkill IMO.

Did you intentionally change `blueberry -> blueman`?

**Comment by miabbott** [comment]
> Adding Perl is overkill IMO.
> 
> Did you intentionally change `blueberry -> blueman`?

That happened as part of the comps sync process - https://pagure.io/workstation-ostree-config/blob/main/f/comps-sync.py

See https://www.fedoraproject.org/wiki/How_to_use_and_edit_comps.xml_for_package_groups for more info about comps

**Comment by travier** [comment]
I bundled another commit with a minor change in the PR 😅

**Comment by travier** [comment]
F37 backport: https://pagure.io/workstation-ostree-config/pull-request/323

**Comment by travier** [comment]
I've merged the change for F37. This will be in tomorrow's build.
