### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by quFCrWbL2** [fedora-silverblue/issue-tracker#394]
**Describe the bug**
Every time I log in to a new session my screen is flickering. At the latest, this happens after I enter my password, sometimes even before. When I suspend, wake it up again and enter my password it works just fine. The flickering is less visible when changing the refresh rate of my monitor.
Happens with Xorg and Wayland sessions.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Just boot up
2. and log in

**Expected behavior**
Gnome should start without any screen issues

**Screenshots**
Not visible on Screenshots/records if relevant I can make some pictures with an external camera.

**OS version:**
```
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20221216.0 (2022-12-16T00:47:25Z)
               BaseCommit: 1b2be2082985d83f317766eb6c0a82a58c2cdb426a5a119ae3a0428acb71beab
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
      RemovedBasePackages: firefox firefox-langpacks 108.0-2.fc37
                           gnome-disk-utility 43.0-1.fc37 gnome-system-monitor 42.0-2.fc37
                           gnome-tour 43.0-2.fc37 yelp 2:42.2-1.fc37
          LayeredPackages: gnome-tweaks langpacks-en openssl
```

**Comment by travier** [comment]
This is likely a driver issue and you need to include your hardware information in your reports. This should be reported for the kernel in Fedora's Bugzilla.

**Comment by travier** [comment]
https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora
