### ISSUE TITLE
GnuCash install

### ISSUE THREAD

**Issue by donwatkins** [fedora-silverblue/issue-tracker#395]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
GnuCash is not included in the list of applications that can be installed from the Software Center. It's necessary to issue the following command from the command line to correct the default 'filter' which does not allow GnuCash to be installed. 

$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

**To Reproduce**

$ flatpak install gnucash
**Expected behavior**
When issuing the above command from the command line after a fresh install of Fedora Silverblue 37 I got the following error. 

**Screenshots**
![Screenshot from 2022-12-29 10-02-21](https://user-images.githubusercontent.com/9942121/210013271-3cd36314-3329-4548-b338-a32990b3b40c.png)

**OS version:**
```
Please replace this line with output of `rpm-ostree status -b`
```

**Additional context**

**Comment by jkonecny12** [comment]
Hi,

to work with `flatpak` you need to use full name.
try:
``flatpak install org.gnucash.GnuCash``

**Comment by travier** [comment]
I can install GnuCash with @jkonecny12 commands above. Closing.

**Comment by juhp** [comment]
I think you simply haven't enabled FlatHub?
After that you should see:
```shellsession
$ flatpak install gnucash
Looking for matches…
Found ref ‘app/org.gnucash.GnuCash/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: 
```
