### ISSUE TITLE
erro: bus owner changed, aborting + GNOME Software  segmentation fault

### ISSUE THREAD

**Issue by FastOSlinux** [fedora-silverblue/issue-tracker#4]
$rpm-ostree upgrade
error: Bus owner changed, aborting.
[fastos@localhost ~]$ gnome-software
19:42:47:0903 Gs  plugin rpm-ostree took 1,0 seconds to do setup
19:42:47:0903 Gs  enabled plugins: desktop-categories, fwupd, os-release, shell-extensions, appstream, fedora-pkgdb-collections, desktop-menu-path, epiphany, flatpak, hardcoded-blacklist, hardcoded-featured, hardcoded-popular, modalias, rewrite-resource, rpm-ostree, odrs, provenance, repos, generic-updates, provenance-license, icons, key-colors, key-colors-metadata
19:42:47:0903 Gs  disabled plugins: dummy, packagekit, packagekit-local, packagekit-offline, packagekit-proxy, packagekit-refresh, packagekit-upgrade, packagekit-url-to-app, packagekit-refine, packagekit-history, systemd-updates, packagekit-refine-repos
19:42:49:0990 Gs  hiding category audio-video featured applications: found only 0 to show, need at least 9
19:42:50:0456 Gs  hiding category games featured applications: found only 0 to show, need at least 9
19:42:51:0418 Gs  Only 2 apps for popular list, hiding
Segmentation fault (imagem do núcleo gravada)
[fastos@localhost ~]$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/30/x86_64/silverblue
                   Version: 30.20190708.0 (2019-07-08T00:43:42Z)
                BaseCommit: fec20ca6916a4b20365d6eaaaa1ae09a6d8cfacc215a0988c17c69dd4cd9e511
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
           LayeredPackages: arj file-roller smc-dyuthi-fonts

  ostree://fedora:fedora/30/x86_64/silverblue
                   Version: 30.20190701.0 (2019-07-01T00:36:21Z)
                BaseCommit: f5efad3126a7bc90b88c0a3ba382c15eb3119e123eef3b1f1e2c4a7f7480fcc1
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
           LayeredPackages: arj file-roller smc-dyuthi-fonts

  ostree://fedora:fedora/30/x86_64/silverblue
                   Version: 30.1.2 (2019-04-25T23:13:10Z)
                    Commit: 982faf58087c9d020780b829d5f24b4e78bd40399b4e4769fc8bc2df9890e301
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
                    Pinned: yes

**Comment by cgwalters** [comment]
Can you attach the output of `journalctl -b -r -u rpm-ostreed`?

**Comment by rochamorelli** [comment]
@FastOSlinux [your comment](https://discussion.fedoraproject.org/t/upgrade-issue-bus-owner-changed-aborting/2059/6) totally worked for me

> try sudo ostree fsck
and
sudo ostree admin cleanup

thks

**Comment by FastOSlinux** [comment]
> Can you attach the output of `journalctl -b -r -u rpm-ostreed`?
[fastos@localhost ~]$ rpm-ostree update
error: Bus owner changed, aborting.
[fastos@localhost ~]$ journalctl -b -r -u rpm-ostreed
-- Logs begin at Mon 2019-06-24 22:15:39 -03, end at Thu 2019-07-18 14:39:54 -03. --
jul 18 14:39:52 localhost.localdomain systemd[1]: rpm-ostreed.service: Failed with result 'signal'.
jul 18 14:39:52 localhost.localdomain systemd[1]: rpm-ostreed.service: Main process exited, code=killed, status=11/SEGV
jul 18 14:39:51 localhost.localdomain rpm-ostree[6703]: Initiated txn Upgrade for client(id:cli dbus:1.632 unit:gnome-terminal-server.service uid:1000): /org/projectatomic/rpmostree1/fedora
jul 18 14:39:50 localhost.localdomain rpm-ostree[6703]: client(id:cli dbus:1.632 unit:gnome-terminal-server.service uid:1000) added; new total=2
jul 18 14:39:50 localhost.localdomain rpm-ostree[6703]: Allowing active client :1.632 (uid 1000)
jul 18 14:39:47 localhost.localdomain rpm-ostree[6703]: Txn RefreshMd on /org/projectatomic/rpmostree1/fedora successful
jul 18 14:39:46 localhost.localdomain rpm-ostree[6703]: Initiated txn RefreshMd for client(id:gnome-software dbus:1.624 unit:dbus-:1.2-org.gnome.Software@0.service uid:1000): /org/projectatomic/rpmostree1/fedora
jul 18 14:39:46 localhost.localdomain rpm-ostree[6703]: client(id:gnome-software dbus:1.624 unit:dbus-:1.2-org.gnome.Software@0.service uid:1000) added; new total=1
jul 18 14:39:46 localhost.localdomain rpm-ostree[6703]: Allowing active client :1.624 (uid 1000)
jul 18 14:39:46 localhost.localdomain systemd[1]: Started RPM-OSTree System Management Daemon.
jul 18 14:39:46 localhost.localdomain rpm-ostree[6703]: In idle state; will auto-exit in 62 seconds
jul 18 14:39:45 localhost.localdomain rpm-ostree[6703]: Reading config file '/etc/rpm-ostreed.conf'
jul 18 14:39:45 localhost.localdomain systemd[1]: Starting RPM-OSTree System Management Daemon...
jul 18 14:38:57 localhost.localdomain systemd[1]: rpm-ostreed.service: Failed with result 'signal'.
jul 18 14:38:57 localhost.localdomain systemd[1]: rpm-ostreed.service: Main process exited, code=killed, status=11/SEGV
jul 18 14:38:56 localhost.localdomain rpm-ostree[4789]: Initiated txn Upgrade for client(id:cli dbus:1.565 unit:gnome-terminal-server.service uid:1000): /org/projectatomic/rpmostree1/fedora
jul 18 14:38:56 localhost.localdomain rpm-ostree[4789]: client(id:cli dbus:1.565 unit:gnome-terminal-server.service uid:1000) added; new total=1
jul 18 14:38:55 localhost.localdomain rpm-ostree[4789]: Allowing active client :1.565 (uid 1000)
jul 18 14:38:55 localhost.localdomain systemd[1]: Started RPM-OSTree System Management Daemon.
jul 18 14:38:55 localhost.localdomain rpm-ostree[4789]: In idle state; will auto-exit in 61 seconds
jul 18 14:38:54 localhost.localdomain rpm-ostree[4789]: Reading config file '/etc/rpm-ostreed.conf'
jul 18 14:38:54 localhost.localdomain systemd[1]: Starting RPM-OSTree System Management Daemon...
jul 18 14:38:54 localhost.localdomain systemd[1]: rpm-ostreed.service: Failed with result 'signal'.
jul 18 14:38:54 localhost.localdomain systemd[1]: rpm-ostreed.service: Main process exited, code=killed, status=11/SEGV
jul 18 14:38:53 localhost.localdomain rpm-ostree[2388]: Initiated txn Upgrade for client(id:gnome-software dbus:1.465 unit:session-3.scope uid:1000): /org/projectatomic/rpmostree1/fedora
jul 18 14:38:53 localhost.localdomain rpm-ostree[2388]: Txn RefreshMd on /org/projectatomic/rpmostree1/fedora successful
jul 18 14:38:51 localhost.localdomain rpm-ostree[2388]: Initiated txn RefreshMd for client(id:gnome-software dbus:1.465 unit:session-3.scope uid:1000): /org/projectatomic/rpmostree1/fedora
jul 18 14:38:51 localhost.localdomain rpm-ostree[2388]: Txn RefreshMd on /org/projectatomic/rpmostree1/fedora successful
jul 18 14:38:50 localhost.localdomain rpm-ostree[2388]: g_variant_dict_clear: assertion 'ensure_valid_dict (dict)' failed
jul 18 14:38:49 localhost.localdomain rpm-ostree[2388]: g_variant_dict_clear: assertion 'ensure_valid_dict (dict)' failed
jul 18 14:38:49 localhost.localdomain rpm-ostree[2388]: Initiated txn RefreshMd for client(id:gnome-software dbus:1.465 unit:session-3.scope uid:1000): /org/projectatomic/rpmostree1/fedora
jul 18 14:38:49 localhost.localdomain rpm-ostree[2388]: client(id:gnome-software dbus:1.465 unit:session-3.scope uid:1000) added; new total=1
jul 18 14:38:49 localhost.localdomain rpm-ostree[2388]: Allowing active client :1.465 (uid 1000)
jul 18 14:38:49 localhost.localdomain systemd[1]: Started RPM-OSTree System Management Daemon.
jul 18 14:38:49 localhost.localdomain rpm-ostree[2388]: In idle state; will auto-exit in 63 seconds
jul 18 14:38:49 localhost.localdomain rpm-ostree[2388]: Deleting outdated cached update for OS 'fedora'
jul 18 14:38:48 localhost.localdomain rpm-ostree[2388]: Reading config file '/etc/rpm-ostreed.conf'
jul 18 14:38:48 localhost.localdomain systemd[1]: Starting RPM-OSTree System Management Daemon...
[fastos@localhost ~]$

**Comment by rochamorelli** [comment]
> @FastOSlinux [your comment](https://discussion.fedoraproject.org/t/upgrade-issue-bus-owner-changed-aborting/2059/6) totally worked for me
> 
> > try sudo ostree fsck
> > and
> > sudo ostree admin cleanup
> 
> thks

Updating my comment, this only works once.

I have to re-issue these commands every time to be able to `rpm-ostree update` or `rpm-ostree upgrade`

**Comment by cgwalters** [comment]
Can you use `coredumpctl` to find the crash?  And in particular `coredumpctl info` should give us a stack trace.

**Comment by rochamorelli** [comment]
Indeed @cgwalters . Lately cannot upgrade at all my SB, but when I add some layered package with `rpm-ostree install smth` I can see some upgrades.

I'm not able to read this dump, no useful info for me from it of what's broken with gnome-software :/

Thanks for your attention

```
[XXX@fedora30-sb ~]$ gnome-software  
Segmentation fault (core dumped)
```

```
[XXX@fedora30-sb ~]$ coredumpctl info
           PID: 7385 (gnome-software)
           UID: 1000 (XXX)
           GID: 1000 (XXX)
        Signal: 11 (SEGV)
     Timestamp: Wed 2019-07-24 18:19:45 -03 (44min ago)
  Command Line: /usr/bin/gnome-software --gapplication-service
    Executable: /usr/bin/gnome-software
 Control Group: /user.slice/user-1000.slice/user@1000.service/dbus\x2d:1.2\x2dorg.gnome.Software.slice/dbus-:1.2-org.gnome.Software@4.se>
          Unit: user@1000.service
     User Unit: dbus-:1.2-org.gnome.Software@4.service
         Slice: user-1000.slice
     Owner UID: 1000 (XXX)
       Boot ID: 38081f8d9e5b44b18ad5543425f172cf
    Machine ID: 72d62b959693452c97b177e8fc355370
      Hostname: fedora30-sb
       Storage: /var/lib/systemd/coredump/core.gnome-software.1000.38081f8d9e5b44b18ad5543425f172cf.7385.1564003185000000.lz4
       Message: Process 7385 (gnome-software) of user 1000 dumped core.
                
                Stack trace of thread 7913:
                #0  0x00007faf800c084c n/a (libcurl.so.4)
                #1  0x00007faf800c0b0b curl_multi_socket_action (libcurl.so.4)
                #2  0x00007faf801c037a n/a (libostree-1.so.1)
                #3  0x00007faf9144cedd g_main_context_dispatch (libglib-2.0.so.0)
                #4  0x00007faf9144d270 n/a (libglib-2.0.so.0)
                #5  0x00007faf9144d313 g_main_context_iteration (libglib-2.0.so.0)
                #6  0x00007faf801bd8d6 n/a (libostree-1.so.1)
                #7  0x00007faf8017e0a2 n/a (libostree-1.so.1)
                #8  0x00007faf801896ae ostree_repo_remote_fetch_summary_with_options (libostree-1.so.1)
                #9  0x00007faf8016633a ostree_repo_remote_fetch_summary (libostree-1.so.1)
                #10 0x00007faf80303722 n/a (libflatpak.so.0)
                #11 0x00007faf80303efc n/a (libflatpak.so.0)
                #12 0x00007faf80348f9c flatpak_installation_list_remote_refs_sync_full (libflatpak.so.0)
                #13 0x00007faf80349242 flatpak_installation_list_installed_refs_for_update (libflatpak.so.0)
                #14 0x00007faf803bf317 gs_flatpak_add_updates (libgs_plugin_flatpak.so)
                #15 0x00007faf803c2f35 gs_plugin_add_updates (libgs_plugin_flatpak.so)
                #16 0x0000564a495f0dfb n/a (gnome-software)
                #17 0x0000564a495f1372 n/a (gnome-software)
                #18 0x0000564a495f2433 n/a (gnome-software)
                #19 0x00007faf912d7907 n/a (libgio-2.0.so.0)
                #20 0x00007faf91476f14 n/a (libglib-2.0.so.0)
                #21 0x00007faf914764e2 n/a (libglib-2.0.so.0)
                #22 0x00007faf9057d5a2 start_thread (libpthread.so.0)
                #23 0x00007faf904aa303 __clone (libc.so.6)
                
                Stack trace of thread 7385:
                #0  0x00007faf9049f5c7 __poll (libc.so.6)
                #1  0x00007faf9144d1de n/a (libglib-2.0.so.0)
                #2  0x00007faf9144d313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007faf91304495 g_application_run (libgio-2.0.so.0)
                #4  0x0000564a4959149d main (gnome-software)
                #5  0x00007faf903d2f33 __libc_start_main (libc.so.6)
                #6  0x0000564a4959154e _start (gnome-software)
                
                Stack trace of thread 7412:
                #0  0x00007faf9049f5c7 __poll (libc.so.6)
                #1  0x00007faf9144d1de n/a (libglib-2.0.so.0)
                #2  0x00007faf9144d313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007faf80901a9d n/a (libdconfsettings.so)
                #4  0x00007faf914764e2 n/a (libglib-2.0.so.0)
                #5  0x00007faf9057d5a2 start_thread (libpthread.so.0)
                #6  0x00007faf904aa303 __clone (libc.so.6)
                
                Stack trace of thread 7915:
                #0  0x00007faf904a4fad syscall (libc.so.6)
                #1  0x00007faf91498f56 g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007faf9141e031 n/a (libglib-2.0.so.0)
                #3  0x00007faf9141e656 g_async_queue_timeout_pop (libglib-2.0.so.0)
                #4  0x00007faf91476fb9 n/a (libglib-2.0.so.0)
                #5  0x00007faf914764e2 n/a (libglib-2.0.so.0)
                #6  0x00007faf9057d5a2 start_thread (libpthread.so.0)
                #7  0x00007faf904aa303 __clone (libc.so.6)
                
                Stack trace of thread 7406:
                #0  0x00007faf9049f5c7 __poll (libc.so.6)
                #1  0x00007faf9144d1de n/a (libglib-2.0.so.0)
                #2  0x00007faf9144d313 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007faf9144d361 n/a (libglib-2.0.so.0)
                #4  0x00007faf914764e2 n/a (libglib-2.0.so.0)
                #5  0x00007faf9057d5a2 start_thread (libpthread.so.0)
                #6  0x00007faf904aa303 __clone (libc.so.6)
                
                Stack trace of thread 7408:
                #0  0x00007faf9049f5c7 __poll (libc.so.6)
                #1  0x00007faf9144d1de n/a (libglib-2.0.so.0)
                #2  0x00007faf9144d5a3 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007faf9133fd6a n/a (libgio-2.0.so.0)
                #4  0x00007faf914764e2 n/a (libglib-2.0.so.0)
                #5  0x00007faf9057d5a2 start_thread (libpthread.so.0)
                #6  0x00007faf904aa303 __clone (libc.so.6)
```

**Comment by cgwalters** [comment]
This is likely https://bugzilla.redhat.com/show_bug.cgi?id=1697566 - can you try updating manually to the fixed libcurl?

**Comment by rochamorelli** [comment]
They [pushed](https://bugzilla.redhat.com/show_bug.cgi?id=1697566#c84) a few day ago.
I cannot find a rpm for it, will try to build.

Thanks again @cgwalters for your attention ;)

**Comment by FastOSlinux** [comment]
last update fixed, everything working
