### ISSUE TITLE
Cannot set password for newly created user in Gnome

### ISSUE THREAD

**Issue by glidingthrough** [fedora-silverblue/issue-tracker#400]
**Describe the bug**
Cannot add password for newly created user in Gnome 43 GUI - keeps reporting 'Try to avoid common words' when it contains none, and the confirm password field is greyed out so I cannot progress. Not reproducible on Fedora Workstation, solely a Silverblue bug.

**To Reproduce**
1. Open Gnome Settings -> Users
2. Unlock and type in sudo password
3. Scroll to bottom and click on +Add User
4. Complete Name and Username fields with 'test'
5. Select 'Set password now'
6. Type in a mix of characters for the password, including lower case, upper case, numbers and special characters (I use the password generator including in Bitwarden); specifically don't use any common words.

**Expected behavior**
The password to be accepted as 'strong'.

**Screenshots**
![image](https://user-images.githubusercontent.com/97669346/212527881-3e182a8e-9247-4a11-adc5-96952c7a654d.png)

**OS version:**
fedora:fedora/37/x86_64/silverblue
Version: 37.20230114.0 (2023-01-14T00:42:55Z)
BaseCommit: 67a0e03a3ba5b42b960867fb95f50e3e9f6bf49082c3f37551ba2bf263594e68
GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
RemovedBasePackages: firefox firefox-langpacks 108.0.1-3.fc37
LayeredPackages: tailscale
LocalPackages: mullvad-vpn-2022.5.0-1.x86_64

**Additional context**
Suggested solution is to rpm-ostree install cracklib-dicts; not yet tested.

**Comment by travier** [comment]
> Suggested solution is to rpm-ostree install cracklib-dicts; not yet tested.

If you can verify that this package installed on Fedora Workstation by default and fixes the issues when overlayed on Silverblue that would be great and we could add it to the image by default.

Thanks

**Comment by felipeborges** [comment]
cracklib-dicts seems installed in the default Fedora Workstation and also in my Silverblue install too, but in Silverblue I am able to change the password as expected with no issues like OP has.

![image](https://user-images.githubusercontent.com/365434/212670932-2e131876-ef6c-4434-ba6c-d13d2ab10ada.png)

Could you please try running `G_MESSAGES_DEBUG=all gnome-control-center` and let us know if something gets printed in the console while attempting to enter a password?

We use libpwquality, which seems to use cracklib.

**Comment by tpopela** [comment]
@felipeborges it's not part of the base image - at least for me:

```
1 $ rpm -q cracklib-dicts
package cracklib-dicts is not installed
```

I'm currently running on  37.20230115.0. Can you please try `rpm -e --test cracklib-dicts` on Silverblue and Workstation as well and paste the input here?

**Comment by felipeborges** [comment]
> @felipeborges it's not part of the base image - at least for me:
> 
> ```
> 1 $ rpm -q cracklib-dicts
> package cracklib-dicts is not installed
> ```

Interesting. I wonder what pulled it in for me. I currently have no layered packages and my instance has been upgraded version-by-version since fedora 35.

```
$ rpm -q cracklib-dicts
cracklib-dicts-2.9.7-30.fc37.x86_64
```

> 
> I'm currently running on 37.20230115.0. Can you please try `rpm -e --test cracklib-dicts` on Silverblue and Workstation as well and paste the input here?

In Silverblue
```
error: Failed dependencies:
	(cracklib-dicts >= 2.8 if cryptsetup) is needed by (installed) libpwquality-1.4.4-11.fc37.x86_64
	(cracklib-dicts >= 2.8 if passwd) is needed by (installed) libpwquality-1.4.4-11.fc37.x86_64
```

In a Fedora Workstation 37 VM
```
error: Failed dependencies:
	(cracklib-dicts >= 2.8 if cryptsetup) is needed by (installed) libpwquality-1.4.4-11.fc37.x86_64
	(cracklib-dicts >= 2.8 if passwd) is needed by (installed) libpwquality-1.4.4-11.fc37.x86_64
	cracklib-dicts is needed by (installed) anaconda-core-37.12.6-1.fc37.x86_64
```

**Comment by tpopela** [comment]
So it might be a fallout from https://src.fedoraproject.org/rpms/libpwquality/c/303154338d6d3650bc343c4852009be8a1fdc199?branch=rawhide / https://bugzilla.redhat.com/show_bug.cgi?id=2006063 that hit the stable repositories few days ago, @felipeborges what's your libpwquality version? Mine is libpwquality-1.4.5-1.fc37.x86_64 which is the new one without hard requirement on cracklib-dicts.

**Comment by felipeborges** [comment]
I'm still in libpwquality-1.4.4-11.fc37.x86_64

**Comment by travier** [comment]
Then we'd say that we probably need an explicit dependency to cracklib-dicts in the package that includes GNOME Settings.

**Comment by jn64** [comment]
The change in libpwquality-1.4.5 is wrong. It should be fixed there. https://bugzilla.redhat.com/show_bug.cgi?id=2158891

**Comment by travier** [comment]
Short term we can also include that manually in Silverblue until it is fixed.

**Comment by glidingthrough** [comment]
Sorry for the slow reply. I take it you don't need me to check whether it's on Workstation anymore - from what I have read it sounds like you've figured out both a short-term and long-term solution :+1:

**Comment by travier** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2158891 > This should be fixed now.
