### ISSUE TITLE
GDM causes black screen if disabled in an image

### ISSUE THREAD

**Issue by TH3-S4LM0N** [fedora-silverblue/issue-tracker#401]
### Description
Disabling GDM in a OCI container image causes a black screen on boot, but works as intended when run on the actual installed os.

### Reproduce
- Create a container containing `RUN systemctl disable gdm`
- Rebase to that image
- Black screen on boot

### Expected Behavior
A terminal.

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.1.7 (2022-11-05T06:01:00Z)
                   Commit: bfe9de223c9a4ba4a793d3e01f6b09024c919685ee73c896af767958725cac79
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A

```
Running in a Qemu/KVM virtual machine on Arch Linux for testing if it matters.

**Comment by travier** [comment]
You base image is old. We need more details to be able to diagnose.

**Comment by TH3-S4LM0N** [comment]
> We need more details to be able to diagnose.

Ok, I created a full new vm with the latest image (`37.20230117.0`). Then I ran `sudo systemctl disable gdm`, rebooted and was greeted by a terminal as expected. I re-enabled it, rebooted and gdm came up. I rebased to [this image](https://github.com/TH3-S4LM0N/sb-systemd-gdm-bug) I made to display this with `rpm-ostree rebase ostree-unverified-registry:ghcr.io/th3-s4lm0n/sb-systemd-gdm-bug`. Note that I don't think this image would be based off the latest image, but if i pull from `silverblue:latest` it errors out that the manifest is unknown. Anyway then I reboot and get the black screen.

**Comment by travier** [comment]
You can try with https://quay.io/repository/fedora-ostree-desktops/silverblue?tab=tags which should be fresher.

**Comment by TH3-S4LM0N** [comment]
Exact same thing with `FROM quay.io/fedora-ostree-desktops/silverblue:37.20230118.0.a4bd7c6a`.

**Comment by travier** [comment]
Looks like this is related to building in unified core mode (which is how those images are made).

**Comment by travier** [comment]
This will be fixed by https://pagure.io/workstation-ostree-config/pull-request/246.

In the meantime, you can manually enable the missing units:
```
$ systemctl enable getty@.service
```

**Comment by travier** [comment]
I'll likely backport this to the test images.

**Comment by travier** [comment]
This is fixed in F39.
