### ISSUE TITLE
suspending issue

### ISSUE THREAD

**Issue by allaeddineomc** [fedora-silverblue/issue-tracker#402]
**Describe the bug**
entering suspend sometimes causes the system to enter a state where it looks like it's suspended but the power indicator light on the laptop shows that the system isn't suspended (normally awake) , recovering from this state is impossible and the only way to get the system back to work is by a hard power off  

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. suspend by closing the lid or pressing the power button 

**Expected behavior**
normal suspend 

**Screenshots**

**OS version:**
```
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20230115.0 (2023-01-15T00:45:42Z)
               BaseCommit: a5f26673e144d96f00a38f1a36eb7cfd20e46fdb7ecc33ad6183923a8cf37483
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
      RemovedBasePackages: firefox firefox-langpacks 108.0.1-3.fc37 gnome-terminal-nautilus gnome-terminal 3.45.90-1.fc37

```

**Additional context**
the issue started around fedora 36 i didn't report it because it was occasional , after the latest kernel update it became so frequent that the system is barely usable

**Comment by travier** [comment]
This is likely a kernel bug that would have to be reported in Fedora's Bugzilla instance for the kernel package with information about your hardware: https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora

**Comment by travier** [comment]
If an application segfault then you should get a coredump via coredumpctl and be able to post the backtrack here or report a bug for the specific app.

I don't think however that xdg-desktop-portal would prevent the system from waking up.

**Comment by allaeddineomc** [comment]
couldn't get that same segfault again so it's probably unrelated , the issue here isn't with waking up it's with going to sleep , the indicator LED shows that the laptop isn't sleeping even when the system looks like it's sleeping
since that app is a gnome thing i will rebase to kinoite to see if the issues i have still appear there

**Comment by allaeddineomc** [comment]
i have to get some work done this month and since this bug seems hard to track i need to deploy a 2 month old commit to get myself temporarly out of this sticky situation , i can't find any documentation on how to find old commits , can you please help with that ?

**Comment by allaeddineomc** [comment]
i tried that solution and i got to see the commit names but trying to pull a month old commit failed , i guess it's an issue to report ?

**Comment by travier** [comment]
Have you increased the depth until you found your commit?

**Comment by travier** [comment]
Please paste the commands that you've tried and the errors you have.

**Comment by allaeddineomc** [comment]
> Have you increased the depth until you found your commit?

yes i used a depth of 30 to get the month old commit name 

here is the command i entered :
``` rpm-ostree deploy e51b8435e2b53e5ce5ee3bdb1ada6a46ca182e4614f6fb529c8e475499d907cd ```
and here is the output :
``` Validating checksum 'e51b8435e2b53e5ce5ee3bdb1ada6a46ca182e4614f6fb529c8e475499d907cd'
1 metadata, 0 content objects fetched; 592 B transferred in 4 seconds; 0 bytes content written
 ```
and stays like this forever until i use Control+C

**Comment by miabbott** [comment]
> error: While fetching mirrorlist 'https://ostree.fedoraproject.org/mirrorlist': While fetching https://ostree.fedoraproject.org/mirrorlist: [28] Timeout was reached

That indicates a network error trying to talk to the mirrors; does this consistently happen?

I did `sudo ostree pull --commit-metadata-only --depth -1 fedora:fedora/37/x86_64/silverblue` to get the the commit history of the F37 Silverblue repo and found that commit you referenced in the repo:

```
$ ostree log fedora/37/x86_64/silverblue | grep -A 5 "commit e51b8435e2b53e5ce5ee3bdb1ada6a46ca182e4614f6fb529c8e475499d907cd"
commit e51b8435e2b53e5ce5ee3bdb1ada6a46ca182e4614f6fb529c8e475499d907cd
Parent:  a83d055a7e741b7b5965410a521d9901d480cc418d2896c018231c9d4be59cb0
ContentChecksum:  19096d9b8c2d04f5c7a325bfaa28d26a2568f0630de111e4852a25ccc1af5390
Date:  2022-12-25 00:38:50 +0000
Version: 37.20221225.0
(no subject)
```

If I `ostree admin cleanup` and try `rpm-ostree deploy` of that commit, it does eventually complete.  Though it did take some time.

```
$ sudo rpm-ostree deploy e51b8435e2b53e5ce5ee3bdb1ada6a46ca182e4614f6fb529c8e475499d907cd
Validating checksum 'e51b8435e2b53e5ce5ee3bdb1ada6a46ca182e4614f6fb529c8e475499d907cd'
1 metadata, 0 content objects fetched; 591 B transferred in 1 seconds; 0 bytes content written
⠐ Receiving objects; 98% (8914/9080) 11.3 MB/s 632.3 MB                                                                                                                                                                                       
1648 metadata, 7432 content objects fetched; 623373 KiB transferred in 58 seconds; 1.4 GB content written
Receiving objects; 98% (8914/9080) 11.3 MB/s 632.3 MB... done
Checking out tree e51b843... done
...
```

**Comment by allaeddineomc** [comment]
yes the error happens every time i try to pull an old commit , i will try the ```ostree admin cleanup``` command and see if i get any good results
thanks

**Comment by allaeddineomc** [comment]
i just noticed the hardened kernel issue and it gave me an idea , why would i use an old version of silverblue when i can probably just use a different kernel , what kernel do you recommend and where do i find it ?
if there is anywhere where i can get an LTS kernel without having to recompile it would be great

**Comment by miabbott** [comment]
> if there is anywhere where i can get an LTS kernel without having to recompile it would be great

I did a quick search of `fedora kernel lts` and found this COPR repo - https://copr.fedorainfracloud.org/coprs/kwizart/kernel-longterm-5.10/

Not sure if it is what you are looking for specifically, but as far as I know there is no officially supported LTS kernel made available by the Fedora project.

**Comment by allaeddineomc** [comment]
this lts kernel isn't for f37
i also tried that clean-up command and it took forever than failed to deploy , time to open another issue before selling my laptop and getting a thinkpad or switching to RHEL XD
