### ISSUE TITLE
RPM fusion GPG key directory issue

### ISSUE THREAD

**Issue by S7venLights** [fedora-silverblue/issue-tracker#406]
Hi I was asked by rpm fusion, to move this issue here: 
https://github.com/rpmfusion-infra/ansible-rpmfusion/issues/3

everything explained briefly in there. Basically Nvidia driver GPG keys were missing after rebasing to kionite.

**Comment by travier** [comment]
This is the issue tracker for Silverblue, not Kinoite.

This should be fixed with https://pagure.io/workstation-ostree-config/pull-request/340, which should be in the latest update.

**Comment by S7venLights** [comment]
Thanks, well I switched from Silverblue to Kionite, so I really had no way of knowing where the issue lay, thanks for the info and for an amazing OS (ツ)
