### ISSUE TITLE
firewalld prevents the use of GNOME Public folder

### ISSUE THREAD

**Issue by A6GibKm** [fedora-silverblue/issue-tracker#41]
When I try to access my public files on another machine on my network using nautilus I get `HTTP Error could not connect: No route to host`. Disabling firewalld.service fixes it, but it is not desirable.

**Comment by A6GibKm** [comment]
update: `firewall-cmd --set-default-zone=FedoraWorkstation` solves it. Why this is not the default zone?

**Comment by tpopela** [comment]
Thank you @A6GibKm for the bug report! It's a fallout after we moved from using the fedora-release-workstation to fedora-release-silverblue. Opened https://src.fedoraproject.org/rpms/firewalld/pull-request/5 (for F32) and https://src.fedoraproject.org/rpms/firewalld/pull-request/4 (for Rawhide)

**Comment by A6GibKm** [comment]
Thanks!

**Comment by A6GibKm** [comment]
By any chance, could this also affect IoT edition? I remember having an issues where firewalld didn't allow to run a pihole or mount a http server for my local network.
