### ISSUE TITLE
Backport rpm-ostree, gnome-software patches to fix upgrade blocking bug in time for 43.4

### ISSUE THREAD

**Issue by sanecito** [fedora-silverblue/issue-tracker#412]
**Describe the bug**
gnome-software is using libdnf directly and trying to access rpm-ostree's caches which prevents gnome-software from getting updates currently and will block users from easily upgrading with gnome-software from 43 to 44

**Screenshots**
![image](https://user-images.githubusercontent.com/3056597/216837710-df2baaf9-f86e-4e15-afc5-c6e5682906cc.png)

![image](https://user-images.githubusercontent.com/3056597/216837774-2b524934-9b6e-45be-9b30-f3f432659ac0.png)
(Metadata screenshot not taken by me, but the "failed to obtain lock 'metadata'" error string is what can be displayed)

**OS version:**

```
BootedDeployment:
● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20230205.0 (2023-02-05T00:43:31Z)
               BaseCommit: 0c6c7982a70b6fec67b9d51c1676f13f86605570f8333ff2f48fa2d0d56a8f47
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
          LayeredPackages: gnome-shell-extension-appindicator gnome-tweaks ibus-table-code
                           libappindicator-gtk3 protonvpn
            LocalPackages: protonvpn-stable-release-1.0.1-1.noarch
```

Theoretically any version that has this commit: https://gitlab.gnome.org/GNOME/gnome-software/-/commit/e6c3d4d616ec5575b6400221d5613505029debf6

**Additional context**

There are already patches for this bug, but they are only included in 44 with no plans by Gnome contributors to patch into 43.x. General recommendation by Philip Withnall (and others): "If it’s an important fix for Silverblue users, then the Fedora distro packagers might want to consider backporting it in their packaging." [1 month ago](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1793#note_1628544)
The gnome-software bug is recorded here:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1793
Based on my understanding of the patch writers the following three patches would need to be backported to Silverblue running 43.x:

- https://github.com/coreos/rpm-ostree/pull/4097
- https://github.com/coreos/rpm-ostree/pull/4099
- https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1531

**Comment by travier** [comment]
It's not clear from your report which version of Silverblue is impacted.

**Comment by sanecito** [comment]
Updated ticket to have more specific Silverblue version info, not just the bug inducing commit in gnome-software

**Comment by travier** [comment]
This looks a lot like:
- https://github.com/fedora-silverblue/issue-tracker/issues/257
- https://github.com/fedora-silverblue/issue-tracker/issues/327

Is this an error that you are experiencing right now? Again, it's not clear from your report.

**Comment by sanecito** [comment]
I am still seeing the issue which is why I'm trying to raise it before the last point release of 43.x making it more difficult to have patch in 43.x that allows for easy upgrades to 44 via gnome-software. Thanks for catching this being a duplicate; looks like I missed because the key text I was using to search: "failed to obtain lock 'metadata'" wasn't used in that open issue.

Closing and moving info including the known, documented solution (backporting the patches found in 44's planned release) to the older open issue
