### ISSUE TITLE
Issues with Rawhide 

### ISSUE THREAD

**Issue by thorrrr** [fedora-silverblue/issue-tracker#416]
Hello Guys
I am using latest version of Rawhide Silverblue  but finding a couple of issues. 
Toolbox create throws and error your not pointing to any version  had to add Fedora 37

Also the silverblue rpm fusion path fails on rawhide
sudo rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

This errors

![image](https://user-images.githubusercontent.com/8170673/218256976-07b7f21d-a034-4859-b4a0-81e1b9edd7f5.png)

**Comment by thorrrr** [comment]
Close please I went to stable version

**Comment by travier** [comment]
Once problem per issue please.

There is no toolbox image for Rawhide yet: https://github.com/containers/toolbox/issues/1233. Should be fixed soon.

Not sure why RPM Fusion setup failed (likely because they need to update their release number to 39 too).

Closing.
