### ISSUE TITLE
rpm ostree Error binding to address (GUnixSocketAddress):

### ISSUE THREAD

**Issue by SoiledBrush** [fedora-silverblue/issue-tracker#419]
I am testing Silverblue in a vm with gnome boxes
`error: Error binding to address (GUnixSocketAddress): No such file or directory `

This error appears on any rpm-ostree command. Fedora 38 and Rawhide
Fedora 37 Silverblue isn`t affected

OS version
```
[test@fedora ~]$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230214.n.1 (2023-02-14T18:06:27Z)
               BaseCommit: 6e4c46e79adcd4d6ff94c81b9ca9a7d3cd74f3e76aa045d19a315537d43cd11f
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
          LayeredPackages: langpacks-en
```

![Screenshot from 2023-02-15 14-43-34](https://user-images.githubusercontent.com/43366389/218977071-7d55ac57-0af3-407a-b5ca-bbbd3bd3478c.png)

**Comment by jkonecny12** [comment]
Facing the same issue on Fedora Sericea

**Comment by tpopela** [comment]
This is https://bugzilla.redhat.com/show_bug.cgi?id=2169622. Closing this as it's reported in Bugzilla.
