### ISSUE TITLE
Installation failed on rawhide iso 20200408: flapak-error-quark

### ISSUE THREAD

**Issue by lakano** [fedora-silverblue/issue-tracker#42]
Hello,
I can't install Silverblue, I've tried to download 2 times the ISO of 2020-04-08, I've tried with 2 different USB keys, and each time I've verified the integrity with Fedora Media Writer and at boot time.
I've keep language / keyboard / timezone by default, and my SSD each time for encryption.
The installation start correctly, but this fatal error happen 5 ~ 10 minutes after.
« The following error occurred while installing. This is a fatal error and installation will be aborted. Failed to install flatpaks: flatpak-error-quark: Aborded due to failure (4) »

BTW: Is the schedule of Silverblue is the same as for Fedora WS ? Because, I've seen since yesterday that should be in Final Freeze, it's why I would like to give a luck, a second time to Silverblue (was on SB30 but too much bugs for me).

Another precision, I've reported a bug one year ago about installation with encrypted disk for non-us keyboard ( https://discussion.fedoraproject.org/t/bug-dm-crypt-password-saved-in-qwerty/1204 ), I see the bug is still present ( I'm pretty sure you would like people from other country could have secure installation too... ? ). But yes, now, you have added a popup to inform the user he'll need to fill it in us keyboard at boot time, it's better than nothing, but so, this could be useful to ask/permit to switch to US keyboard layout just for filling the password.

Regards,

**Comment by tpopela** [comment]
Hi @lakano,

> I can't install Silverblue, I've tried to download 2 times the ISO of 2020-04-08, I've tried with 2 different USB keys, and each time I've verified the integrity with Fedora Media Writer and at boot time.
> I've keep language / keyboard / timezone by default, and my SSD each time for encryption.
> The installation start correctly, but this fatal error happen 5 ~ 10 minutes after.
> « The following error occurred while installing. This is a fatal error and installation will be aborted. Failed to install flatpaks: flatpak-error-quark: Aborded due to failure (4) »

That's https://bugzilla.redhat.com/show_bug.cgi?id=1822753. We are working on the fix.

> BTW: Is the schedule of Silverblue is the same as for Fedora WS ? Because, I've seen since yesterday that should be in Final Freeze, it's why I would like to give a luck, a second time to Silverblue (was on SB30 but too much bugs for me).

More or less. What could help you is to avoid trying the Rawhide, but instead go for SB32 composes. As these working fine after https://github.com/fedora-silverblue/issue-tracker/issues/38 was fixed.


> Another precision, I've reported a bug one year ago about installation with encrypted disk for non-us keyboard ( https://discussion.fedoraproject.org/t/bug-dm-crypt-password-saved-in-qwerty/1204 ), 

There was an issue opened here - https://github.com/fedora-silverblue/issue-tracker/issues/3 and then moved to https://github.com/coreos/rpm-ostree/issues/1930. You can track the progress there, but it's not that easy as it looks.


> I see the bug is still present ( I'm pretty sure you would like people from other country could have secure installation too... ? ).

Like me in Czech Republic? I do have LUKS protected partitions.

> But yes, now, you have added a popup to inform the user he'll need to fill it in us keyboard at boot time, it's better than nothing, but so, this could be useful to ask/permit to switch to US keyboard layout just for filling the password.

We also updated the plymouth theme to include the current layout - https://hansdegoede.livejournal.com/22565.html.

We are actively working on improving the experience, but we do have limited resources. Patches and help are welcome.
