### ISSUE TITLE
New Package Request: foot-terminfo for Sway Spin of Fedora Silverblue

### ISSUE THREAD

**Issue by davidthewatson** [fedora-silverblue/issue-tracker#421]
1. Is the package installed by default in Fedora Workstation? If it is not, we will ask you to [open an issue in the issue tracker](https://pagure.io/fedora-workstation/issues) for the [Fedora Workstation Working Group](https://docs.fedoraproject.org/en-US/workstation-working-group/).

        Yes, I believe so. I'm running the rawhide build of Fedora Silverblue with Sway. Since this is functionally identical to the Sway version of Workstation, I believe that makes it a requirement for foot to work reliably for things that depend on foot-terminfo. Foot is the default terminal on sway.

3. What, if any, are the additional dependencies on the package? What is the output of this command on a system without overrides or locally installed packages:

        ncurses-base-6.4-3.20230114.fc38 in Fedora Rawhide

4. What is the size of the package and its dependencies?
        
        [watson@fedora ~]$ bash
        [watson@fedora ~]$ rpm -qi foot-terminfo
        Name        : foot-terminfo
        Version     : 1.13.1
        Release     : 2.fc38
        Architecture: x86_64
        Install Date: Mon 20 Feb 2023 12:42:14 AM EST
        Group       : Unspecified
        Size        : 8252
        License     : MIT
        Signature   : RSA/SHA256, Wed 01 Feb 2023 08:30:02 PM EST, Key ID 75cf5ac418b8e74c
        Source RPM  : foot-1.13.1-2.fc38.src.rpm
        Build Date  : Wed 18 Jan 2023 10:56:46 PM EST
        Build Host  : buildvm-x86-32.iad2.fedoraproject.org
        Packager    : Fedora Project
        Vendor      : Fedora Project
        URL         : https://codeberg.org/dnkl/foot
        Bug URL     : https://bugz.fedoraproject.org/foot
        Summary     : Terminfo files for foot terminal
        Description :
        Terminfo files for foot terminal.

5. What problem are you trying to solve with this package? Or what functionality does the package provide?

        [watson@fedora ~]$ toolbox enter
        Error: terminfo entry not found for foot

6. Can the software provided by the package be run from a container? Explain why or why not.

        Yes, I believe so. That's how I'm running it.

        [watson@fedora ~]$ toolbox enter
        Error: terminfo entry not found for foot
        
        ⬢[watson@toolbox watson]$ dnf search foot-terminfo
        Copr repo for helix owned by varlad                                                             21 kB/s | 8.6 kB     00:00    
        ============================================= Name Exactly Matched: foot-terminfo =============================================
        foot-terminfo.x86_64 : Terminfo files for foot terminal
        ⬢[watson@toolbox watson]$ sudo dnf install foot-terminfo
        Last metadata expiration check: 0:07:21 ago on Mon 20 Feb 2023 10:03:06 PM EST.
        Dependencies resolved.
        ===============================================================================================================================
         Package                          Architecture              Version                           Repository                  Size
        ===============================================================================================================================
        Installing:
         foot-terminfo                    x86_64                    1.13.1-2.fc38                     rawhide                     12 k
        
        Transaction Summary
        ===============================================================================================================================
        Install  1 Package
        
        Total download size: 12 k
        Installed size: 8.1 k
        Is this ok [y/N]: y
        Downloading Packages:
        foot-terminfo-1.13.1-2.fc38.x86_64.rpm                                                          19 kB/s |  12 kB     00:00    
        -------------------------------------------------------------------------------------------------------------------------------
        Total                                                                                           11 kB/s |  12 kB     00:01     
        Running transaction check
        Transaction check succeeded.
        Running transaction test
        Transaction test succeeded.
        Running transaction
          Preparing        :                                                                                                       1/1 
          Installing       : foot-terminfo-1.13.1-2.fc38.x86_64                                                                    1/1 
          Verifying        : foot-terminfo-1  13.1-2.fc38.x86_64                                                                    1/1 
        
        Installed:
          foot-terminfo-1.13.1-2.fc38.x86_64                                                                                           
        
        Complete!
        ⬢[watson@toolbox watson]$ toolbox enter                 
        ⬢[watson@toolbox watson]$ 

7. Can the tool(s) provided by the package be helpful in debugging container runtime issues?

        Yes, I think so.

8. Can the tool(s) provided by the package be helpful in debugging networking issues?

        I don't believe so, but I'm not sure.

9. Is it possible to layer the package locally via `rpm-ostree install <package>`? Explain why or why not.

        Perhaps, but again, I'm not sure. I tried this, but the results I saw were inconclusive.

**Comment by tpopela** [comment]
@davidthewatson this is not the right place to report this RFE as this is solely about Silverblue, but please report it in https://gitlab.com/fedora/sigs/sway/SIG/-/issues which should be the right issue tracker for Sericea.

**Comment by travier** [comment]
Note that there is no Fedora variant called Silverblue Sway. Silverblue comes with GNOME.

The rpm-ostree variant of Fedora that comes with Sway by default is called Sericea: https://fedoraproject.org/wiki/Changes/Fedora_Sway_Spin

**Comment by travier** [comment]
Moved to https://gitlab.com/fedora/sigs/sway/SIG/-/issues/19
