### ISSUE TITLE
Hostname change results in poor internet speeds

### ISSUE THREAD

**Issue by mahtjarohst** [fedora-silverblue/issue-tracker#423]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
If you change the hostname of any silverblue or kinoite system, you won't be able to load any websites, nor install any packages because the hostname is not being resolved.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Change hostname, whether it be graphically or through hostnamectl.
2. Open up firefox and navigate to any website, or attempt to install/upgrade a flatpak application.

**Expected behavior**
I expect my system to work normally

**Screenshots**

**OS version:**
```
BootedDeployment:
● fedora:fedora/37/x86_64/kinoite
Version: 37.20230222.0 (2023-02-22T09:35:54Z)
BaseCommit: 02d854af025327f66264c40f38d66b4804d12273668806841ae0515f600ed185
GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
RemovedBasePackages: firefox firefox-langpacks 110.0-3.fc37
LayeredPackages: distrobox kate
```
This bug is present on all versions

**Additional context**

**Comment by travier** [comment]
> This bug is present on all versions

What version? Please fill out the forms with more details.

**Comment by mahtjarohst** [comment]
I am on fedora 37 right now if that helps. It occurs on any version of silvervlue or kinoite.

**Comment by mahtjarohst** [comment]
BootedDeployment:
● fedora:fedora/37/x86_64/kinoite
                  Version: 37.20230222.0 (2023-02-22T09:35:54Z)
               BaseCommit: 02d854af025327f66264c40f38d66b4804d12273668806841ae0515f600ed185
             GPGSignature: Valid signature by ACB5EE4E831C74BB7C168D27F55AD3FB5323552A
      RemovedBasePackages: firefox firefox-langpacks 110.0-3.fc37
          LayeredPackages: distrobox kate

**Comment by mahtjarohst** [comment]
This is a pretty big problem, I need to be able to differentiate between all of my systems hostnames. It makes remotely accessing the correct system them very difficult when they are all named fedora.

**Comment by travier** [comment]
Is this still an issue on Fedora Silverblue 39? Thanks

**Comment by travier** [comment]
Closing as Fedora 37 is now EOL and this would a clear reproducer to be able to investigate.
