### ISSUE TITLE
toolbox does not work with flatpak version of Tilix

### ISSUE THREAD

**Issue by sramkrishna** [fedora-silverblue/issue-tracker#43]
It seems that the flatpak version of tilix does not work with toolbox. I havent quite figured out why yet. Toolbox gives an error about containers not migrated when trying to enter a container. I'm not sure if other people are seeing this, but would like confirmation that others are seeing this as well.

I put this in the old pagure.io issue tracker - so duplicating it here with this response from Tomas Popela:
Hi @sramkrishna! What exactly you see? Also I expect that the flatpak version of Tilix won't work as it will try to exec the command in the flatpak and not on the host. Also this issue tracker is deprecated and you should use https://github.com/fedora-silverblue/issue-tracker/issues.

**Comment by sramkrishna** [comment]
Also worth nothing that that tilix flatpak is something that I realized takes effort to build and make. It might be more appropriate for me to put an issue with tilix than silverblue.

**Comment by tpopela** [comment]
Yes, this should be handled in Tilix (upstream) first. They already do have some support for Flatpak - https://github.com/gnunn1/tilix/tree/master/experimental/flatpak. I asked Rishi to look at it during the F33 cycle. I'm closing this as we can't really do anything in Silverblue about this. (and we are tracking it in https://teams.fedoraproject.org/project/silverblue/us/19)
