### ISSUE TITLE
RPMs using alternatives do not install properly in rpm-ostree container

### ISSUE THREAD

**Issue by bsherman** [fedora-silverblue/issue-tracker#430]
**Describe the bug**
`rpm-ostree install` of an RPM which uses the alternatives system (eg, `netcat`) fails when run in a Containerfile.

**To Reproduce**
Given a simple Containerfile:
```
FROM quay.io/fedora-ostree-desktops/silverblue:37.20230311.0.09be88fd
RUN rpm-ostree install netcat && ls -l /usr/bin/nc
```
Run build: `podman build -f Containerfile --tag test-netcat`

rpm-ostree install will log an informative message:
`admindir /var/lib/alternatives invalid`

And the example will fail with `/usr/bin/nc` not found.

**Expected behavior**

RPMs depending on alternatives should succeed when built via container rpm-ostree install.

**OS version:**
```
quay.io/fedora-ostree-desktops/silverblue:37.20230311.0.09be88fd
```

**Additional context**

As a workaround, one can `mkdir -p /var/lib/alternatives` in Containerfile before `rpm-ostree install`. However, then `ostree container commit` will fail due to existence of files in /var... a specific example:
```
Found file: "var/lib/alternatives/nc"
```
This error being similar to #413 , the further workaround is to rm the file.

**Comment by travier** [comment]
See:
- https://github.com/coreos/fedora-coreos-tracker/issues/677
- https://github.com/fedora-sysv/chkconfig/issues/9
- https://docs.fedoraproject.org/en-US/fedora-coreos/alternatives/

Packages using alternative are not working well with rpm-ostree based systems right now.

**Comment by bsherman** [comment]
Thank you for the references.

**Comment by travier** [comment]
https://github.com/fedora-sysv/chkconfig/pull/135 has been merged. I have not checked the implications for existing and new systems yet.

**Comment by travier** [comment]
This is now tracked in https://gitlab.com/fedora/bootc/tracker/-/issues/7 for the bootc side of things and https://gitlab.com/fedora/ostree/sig/-/issues/51 for the Atomic Desktops part.

**Comment by travier** [comment]
This will be fixed in F41. See updates in: https://gitlab.com/fedora/ostree/sig/-/issues/51. There is not automatic migration right now for existing systems but this should be reasonably easy to do and test. Documentation PRs welcomed.
