### ISSUE TITLE
Enable RPMFusion and more repos to be options in the KDE start dialog

### ISSUE THREAD

**Issue by trytomakeyouprivate** [fedora-silverblue/issue-tracker#438]
**Is your feature request related to a problem? Please describe.**
On KDE verions of Fedora, there is no user guidance to enabling RPMfusion or other repos. Discover has a built-in "enable Flathub" button, but this is a bit hidden away.

**Describe the solution you'd like**
An extra page in KDEs welcome dialog to enable

- RPMfusion-free
- RPMfusion-nonfree
- Flathub
- Additional repos used by [Nobara](https://nobaraproject.org/) (no legal consequences if not shipped by default)

Comments:

- Nobara uses some tweaks that include a custom Kernel. This could be possible, but likely a deep mod not prioritized
- Enabling ffmpeg for example requires to `override remove` a lot of free broken packages, this could be automated for user-friendlyness, as its just a few commands after adding the repo

**Describe alternatives you've considered**
Adding these repos manually in the CLI or just using Flatpaks.

**Comment by travier** [comment]
This is https://pagure.io/fedora-kde/SIG/issue/295
