### ISSUE TITLE
Use themes for Grub

### ISSUE THREAD

**Issue by boredsquirrel** [fedora-silverblue/issue-tracker#439]
**Is your feature request related to a problem? Please describe.**
The default Grub looks pretty ugly, especially on HiDPI screens, where its very small.

Enabling grub-themes (I think there is a breeze one?) would improve usability a lot, especially if you need to dualboot or downgrade.

**Describe the solution you'd like**
A Fedora-specific Grub-theme, maybe a DE-specific one like Breeze.

**Describe alternatives you've considered**
Running these scripts to make it work:

1. [Get grub themes](https://github.com/vinceliuice/grub2-themes)
2. install it through its CLI
3. Fix grub using a wrong configuration

**Additional context**
Dependend on #120

**Comment by travier** [comment]
It's unlikely that we'll do extra work to support GRUB theming so I'll close this one.
