### ISSUE TITLE
Fedora Flatpak applications don't have all available localizations

### ISSUE THREAD

**Issue by matheusqueirozzabin** [fedora-silverblue/issue-tracker#44]
Hi guys! Thank's for the excelent job maintaining SB!
I don't know if it is a flatpak issue or a Fedora issue. As SB doesn't come with a bug reporter app, I've came here to report this.
Installing Gnome Calendar and Geary from Fedora flatpak repo doesn't come with system locale.
Anyone knows how to fix or properly report that?

**Comment by tpopela** [comment]
Hi @matheusqueirozzabin. Yes, that's true and we are aware of it. We are working on a solution (looks like it is stalled, but I asked the developers for status) - https://teams.fedoraproject.org/project/silverblue/us/87.

**Comment by tpopela** [comment]
With today's Fedora Flatpak update, the Fedora Flatpaks contains all the available localizations.
