### ISSUE TITLE
Replace Toolbox with Distrobox

### ISSUE THREAD

**Issue by trytomakeyouprivate** [fedora-silverblue/issue-tracker#440]
**Is your feature request related to a problem? Please describe.**
This may be controversial. I dont understand why two seperate projects need to be maintained. Toolbox has support for some other OS images now, but Distrobox seems way more advanced, especially for desktop usage with its "export" functionality.

I think merging Toolbox into Distrobox would benefit development, as Distrobox afaik has the exact same usage and behavior.

Integrating Distrobox by default (like Opensuse microOS does) would also make the distro more appealing as "the Distro that can run all others" as by-default-configurations are often a decisionmaker for Distributions.

**Describe the solution you'd like**
Remove Toolbox, add a function to convert the boxes to Distrobox, alias the toolbox command (for scripts or such), add Distrobox.

**Describe alternatives you've considered**
```
rpm-ostree update override remove toolbox --install distrobox

printf """
alias toolbox=distrobox""" >>~/.bashrc
```

**Comment by miabbott** [comment]
This seems like an issue better suited for the `toolbx` folks; please open a similar issue with them here - https://github.com/containers/toolbox/issues
