### ISSUE TITLE
Switching windows via keys does not focus windows of JetBrains Android studio and toolbox

### ISSUE THREAD

**Issue by tmstaedt** [fedora-silverblue/issue-tracker#443]
I often use gnome key combinations to switch between windows of different apps or the same app. 
Recently, a glitch surfaced that when I switch between a window and Jetbrains Android studio or jetbrains toolbox, the jetbrains window would not get the focus, requiring me to use the mouse to focus that window.
I still had a pinned older version of fedora silverblue 37, dated shortly after release

>   fedora:fedora/37/x86_64/silverblue
                  Version: 37.20221107.n.0 (2022-11-07T07:56:30Z)
               BaseCommit: 4ee0def25f687c435bbc948aab8d35b08f2830dbf57632ff79bb931a159a3cb9

booted that version and window switching works normally.

My current version is 

> ● fedora:fedora/37/x86_64/silverblue
                  Version: 37.20230320.0 (2023-03-20T00:48:14Z)
               BaseCommit: 008ef1f466e75de52c3981399f3eb5244ea730448e13f3ed2a20504e4efbe898

**Comment by travier** [comment]
Can you use `rpm-ostree db diff` to get the list of packages that changes between those two releases?

It's likely a bug in a GNOME component that would need to be reported in bugzilla.

**Comment by travier** [comment]
I've realized that `37.20221107.n.0` is too far out so it will be hard to figure out which package change. You would have to "bisect" which commit introduced the change exactly to narrow down the package update.

**Comment by MrThursby** [comment]
I have the same problem

**Comment by tmstaedt** [comment]
Problem appears to be gone in silverblue 38. Just did a rebase to the latest prerelease beta.

**Comment by travier** [comment]
Closing as this is apparently fixed in Fedora 38. Please provide updated information if this is still an issue.
