### ISSUE TITLE
Impossible to properly use GNOME extensions out-of-box

### ISSUE THREAD

**Issue by matheusqueirozzabin** [fedora-silverblue/issue-tracker#45]
Currently using Silverblue with Fedora 32 rebase.

It's impossible to properly use extensions via [GNOME Shell Extensions website](https://extensions.gnome.org/). It's possible to install them, but as it's config UI cannot be opened (probably by Silverblue design), it's frustrating.

I read that's possible to install extensions via GNOME Software, but I cannot find them by search, neither an option to enable some repository that contains them.

Theres a recommended way to properly use GNOME extensions on Silverblue, or that is actually an issue? Even thats not an issue, theres shouldn't be an out-of-box way to do that?

Reiterating from my past issues, thanks for the amazing job!

**Comment by tpopela** [comment]
> Currently using Silverblue with Fedora 32 rebase.
> 
> It's impossible to properly use extensions via [GNOME Shell Extensions website](https://extensions.gnome.org/). It's possible to install them, but as it's config UI cannot be opened (probably by Silverblue design), it's frustrating.

From where are you trying to open the configuration UI?

> 
> I read that's possible to install extensions via GNOME Software, but I cannot find them by search, neither an option to enable some repository that contains them.

The support for extension was moved to a separate application - Extension. Please install it with `flatpak install fedora org.gnome.Extensions` or with GNOME Software.

> 
> Theres a recommended way to properly use GNOME extensions on Silverblue, or that is actually an issue? Even thats not an issue, theres shouldn't be an out-of-box way to do that?
> 
> Reiterating from my past issues, thanks for the amazing job!

Thank you!

**Comment by matheusqueirozzabin** [comment]
I've tried to open config UI with `fedora org.gnome.Extensions`. When I clicked on config button on Extensions app, GNOME opened a shell dialog window saying "impossible to find `gnome-extension-... command` or something like that. It's happened with 4 differents extensions.

Now I've reinstalled Firefox extension, reinstalled all extensions and it's working properly... I'm feeling dumb.

Can close this if you want. Sorry.

**Comment by fmuellner** [comment]
> I've tried to open config UI with `fedora org.gnome.Extensions`. When I clicked on config button on Extensions app, GNOME opened a shell dialog window saying "impossible to find `gnome-extension-...` command or something like that.

That means gnome-shell is still at version 3.36.0 and tries to launch the extensions-app that was split out. Unfortunately the flatpak only works out-of-the-box with 3.34.x or 3.36.1 onwards, for 3.36.0 it requires the separate `gnome-extensions-app` package to be installed.

(The 3.36.1 update should be available, so that's a better fix than layering the package)
