### ISSUE TITLE
No Fedora 38 ISOs for aarch64

### ISSUE THREAD

**Issue by travier** [fedora-silverblue/issue-tracker#453]
**Describe the bug**

Due to https://pagure.io/releng/issue/11385, there are no Fedora 38 ISOs for aarch64

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Go to https://silverblue.fedoraproject.org/download
2. Try to download the Fedora 38 aarch64 ISO

**Expected behavior**

Get a Fedora 38 aarch64 ISO. We currently link to the Fedora 37 one.

**Comment by fwilhe** [comment]
Any updates on this? It has been a while. There seems to be an up-to-date rawhide iso for aarch64, but that is not linked on the downloads page too. The 38 directory only contains a x86 iso.

**Comment by xmstspider** [comment]
I just wonder if anyone cares that the ISO is still missing.

As I understood from the comments in the [issue](https://pagure.io/releng/issue/11385), the fix is trivial (as shown [here](https://pagure.io/fedora-infra/ansible/pull-request/1375)) so does anyone know why this wasn't still fixed?

Thank you

**Comment by travier** [comment]
Release ISOs are only ever published once. If you want an official release ISO for aarch64, then it would need to be requested to releng and go through the testing process before it is released.

Otherwise you can use the net boot installer and provide a kickstart to do the installation.

**Comment by JamesBelchamber** [comment]
> Release ISOs are only ever published once. If you want an official release ISO for aarch64, then it would need to be requested to releng and go through the testing process before it is released.

Can we do this? Not doing so implies that we are no longer supporting aarch64, and if that's the case then it feels like something we should formally do rather than by accident?

**Comment by juhp** [comment]
Probably the easiest workaround currently would be to install SB 37 and then rebase to 38.
I agree that is not ideal, but in practice the experience is probably not drastically worse than updating from 38 GA.
I assume the aarch64 image will be back for F39 (current rawhide SB is available).

**Comment by travier** [comment]
> > Release ISOs are only ever published once. If you want an official release ISO for aarch64, then it would need to be requested to releng and go through the testing process before it is released.
> 
> Can we do this?

Definitely. Here are the rough steps (taken from the release process):

- Reach out to Fedora QA
- Pick an existing build or aks for a new build of Silverblue F38
- Ask the Fedora QA team and people to test it
- Report back here and to releng and ask for it to be promoted as an additional release artifact

> Not doing so implies that we are no longer supporting aarch64, and if that's the case then it feels like something we should formally do rather than by accident?

aarch64 is still supported.

**Comment by travier** [comment]
Another option is to reach out to the [Respins SIG](https://fedoraproject.org/wiki/Respins-SIG) and ask them to do on for Silverblue aarch64 as I can not find one in https://kojipkgs.fedoraproject.org/compose/38/ (have not checked all dates).

**Comment by tpopela** [comment]
There are some updates in https://pagure.io/releng/issue/11385 - so we should follow what's going on there.

**Comment by wolverian** [comment]
Right now I'm not sure there's any way to install Sericea on aarch64. https://fedoraproject.org/sericea/download/ doesn't mention aarch64 at all. It's unclear to me if Sericea is under Silverblue or another team/responsibility.

**Comment by travier** [comment]
Please file Sericea issues in the Sway issue tracker: https://gitlab.com/fedora/sigs/sway/SIG/-/issues

**Comment by travier** [comment]
Thanks @jamesmotherway. I've filed https://gitlab.com/fedora/websites-apps/fedora-websites/fedora-websites-3.0/-/issues/249 to get it fixed.

**Comment by travier** [comment]
We did not fix this issue directly but we now have Fedora 39 ISOs so that's good enough.
