### ISSUE TITLE
Can't install steam in f32, and error in the error

### ISSUE THREAD

**Issue by A6GibKm** [fedora-silverblue/issue-tracker#46]
`rpm-ostree install steam`
Returns
```Forbidden base package replacements:
  libnghttp2 1.40.0-2.module_f32+8199+88b63a05 -> 1.40.0-2.fc32 (fedora)
This likely means that some of your layered packages have requirements on newer or older versions of some base packages. Doing `rpm-ostree cleanup -m` and `rpm-ostree upgrade` first may help. For more details, see: https://github.com/projecResolving dependencies... done```

Note that I only have layered `bat exa exfat-utils fd-find ffmpeg-libs fuse-exfat ripgrep`.

Doing `rpm-ostree cleanup -m` and `rpm-ostree upgrade`  does not help. Also note that the webpage  
"https://github.com/projecResolving dependencies" does no exists, what should be the correct url this should print?.

**Comment by tpopela** [comment]
> `rpm-ostree install steam`
> Returns
> 
> ```
>   libnghttp2 1.40.0-2.module_f32+8199+88b63a05 -> 1.40.0-2.fc32 (fedora)
> This likely means that some of your layered packages have requirements on newer or older versions of some base packages. Doing `rpm-ostree cleanup -m` and `rpm-ostree upgrade` first may help. For more details, see: https://github.com/projecResolving dependencies... done```
> 
> Note that I only have layered `bat exa exfat-utils fd-find ffmpeg-libs fuse-exfat ripgrep`.
> 
> Doing `rpm-ostree cleanup -m` and `rpm-ostree upgrade`  does not help. Also note that the webpage  
> "https://github.com/projecResolving dependencies" does no exists, what should be the correct url this should print?.
> ```

The truncated link is this bug - https://github.com/coreos/rpm-ostree/issues/1989.

And regarding the libnghttp2 module - I really don't know how the modules are handled in ostree - looks like something from the base image depends on an older nghttp2 build (https://apps.fedoraproject.org/packages/libnghttp2/overview/) than the one that stream was built against. @dustymabe @miabbott any idea?

I could suggest to use Steam from Flathub, until this is resolved.

**Comment by A6GibKm** [comment]
Sadly the game I want to run requires the latest mesa which isn't in flathub build yet.

**Comment by returntrip** [comment]
> Sadly the game I want to run requires the latest mesa which isn't in flathub build yet.

Maybe try to install steam in a `toolbox`?

**Comment by dustymabe** [comment]
> rpm-ostree install steam

A shot in the dark - try `rpm-ostree upgrade --install steam`. If that doesn't work then you'll probably want to wait a week until fedora 32 is released and everything settles back in to its normal pattern.

**Comment by tpopela** [comment]
Hi @A6GibKm, does it work now, when F32 was released?

**Comment by A6GibKm** [comment]
I am closing this as some time ago I was able to layer steam without issues.
