### ISSUE TITLE
Ryzen-Controller not installable

### ISSUE THREAD

**Issue by firefoxlover** [fedora-silverblue/issue-tracker#463]
**Describe the bug**
[Bug reported here](https://gitlab.com/ryzen-controller-team/ryzen-controller/-/issues/204)

Trying to layer the RPM from the project, to have a GUI controlling RyzenAdj which works fine.

```
fedora rpm-ostree(ryzen-controller.post)[25987]: ln: the symlink '/usr/local/bin/ryzen-controller' could not be created: File or directory not found
```

I get this error trying to layer the rpm on Fedora Kinoite 38. Does anyone know the solution?

As far as I know there is no shell that you can enter to manipulate the new system image. I dont know why this error should occur.

**To Reproduce**

1. [Download rpm](https://gitlab.com/ryzen-controller-team/ryzen-controller/-/jobs/3178939815/artifacts/browse/dist/rpm/)
2. Try to layer it

**Expected behavior**
It reports it cant create a file, but this should normally be no problem?

**OS version:**
```
Fedora Kinoite 38.20230421.0 (2023-04-23T21:47:10Z)
```

I dont think this is Kinoite specific, so I guess this is the general OSTree Fedora issuetracker? I also dont think this applies on Workstation.

**Comment by travier** [comment]
RPM package should never install things in `/usr/local`. This is an upstream bug, please report it there.
