### ISSUE TITLE
Unable to visit university websites when connecting to its WPA2-Enterprise wifi on VPN

### ISSUE THREAD

**Issue by sith-on-mars** [fedora-silverblue/issue-tracker#465]
**Describe the bug**

I found myself unable to open any of my university's websites if I connected to my university wifi (WPA2-Enterprise) when using a VPN. No matter which connection method I tried and which server I tried it remained the same. I have tried multiple VPN providers (Mullvad, iVPN, and Windscribe), and the results were the same.

However, I was able to connect to my university's websites when I connected to my phone hotspot instead of my university wifi. I didn't have this VPN issue when using other Linux OS  before.

```
State: idle
BootedDeployment:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230428.0 (2023-04-28T01:33:41Z)
               BaseCommit: d235a0905e77f62ab0bbd90a8bd321b7246a76672cd6d639d52afe93ff82d20c
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
          LayeredPackages: akmod-nvidia gnome-tweaks kvantum langpacks-de langpacks-en
                           langpacks-en_GB langpacks-zh_CN supergfxctl
                           xorg-x11-drv-nvidia-cuda
            LocalPackages: ivpn-3.10.14-1.x86_64 ivpn-ui-3.10.15-1.x86_64
                           mullvad-vpn-2023.3-1.x86_64 windscribe-2.6.14-0.x86_64
```

**Additional context**

**Comment by travier** [comment]
I don't think this is a Silverblue specific issue. I'd recommend checking your systemd-resolved configuration, network settings, performing manual DNS lookups, pinging IP addresses.

As this is a wide support question, I'd recommend that you use the Fedora forums to get help.

**Comment by sith-on-mars** [comment]
I'll post it in the support forum. However, I'm pretty sure it's a Silverblue specific issue, since I never encountered this strange bug in other distros, immutable or not. It would be great if the developers could try to fix it. Thanks!

**Comment by travier** [comment]
We'll need much more info (as I've written above) to be able to investigate.

**Comment by miabbott** [comment]
xref: https://discussion.fedoraproject.org/t/silverblue-38-unable-to-visit-university-websites-when-connecting-to-its-wpa2-enterprise-wifi-on-vpn/81725/

**Comment by sith-on-mars** [comment]
Sorry I don't have the spare device to test right now. Using VM can't be a substitute, since both Workstation and Silverblue 38 in VM didn't have the issue I had. Now I'm not sure if it might be an upstream Fedora issue...

**Comment by sith-on-mars** [comment]
I found that the problem only happened when I used the VPN app, not when I connected VPN through Wireguard configuration files.
