### ISSUE TITLE
system encryption with non us keyboard is broken

### ISSUE THREAD

**Issue by guria9** [fedora-silverblue/issue-tracker#467]
**Describe the bug**
system encryption with non us keyboard is broken. install works, you boot , you cant login. silverblue is useless.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. install silverblue (tried 37 and 38 with and without internet connection) select english as language and german (no deadkeys) as keyboard layout, than make the disk config to automatic with encryption use a long (24chars +) decryption password (fully visible in the installer - all correct displayed) which contains special characters (there it also shows my correct before set keyboard layout de)
2. reboot after install - no keyboard layout is shown in the decryption boot screen, try to login using your set keyboard layout.
3. see you cant decrypt disk
4.  wait long enough than a "entering emergency mode" message is shown and you can drop into a sh
( in the emergency shell you can see that the keyboard layout is us - maybe thats normal)

**Expected behavior**
The decryption boot screen from fedora workstation shows my keyboard layout. Silverblue doesnt do that!
I tried to login with all converted to us keyboard layout, also didnt work.

**Additional /run/initramfs/rdosreport.txt**
okay, just no i wont waste more time on that. lsblk not present in the drop shell. df not present. im no expert at all. so no logs. i moved it to /boot 
booted live iso. not there nice. im done with silverblue for the this year.

**OS version:**
37 & 38

**Comment by guria9** [comment]
i tried fedora 38 workstation and i have the same issue. 
it seems to be a recent patch since all my 37 installations of workstation worked fine. no clue what the issue is.

**Comment by miabbott** [comment]
This appears to be a duplicate of #3

See also: https://discussion.fedoraproject.org/t/keyboard-layout-is-always-english-when-unlocking-encrypted-drives-on-silverblue-kinoite-sericea/81095

**Comment by guria9** [comment]
duplicate
