### ISSUE TITLE
enhance the emergency shell

### ISSUE THREAD

**Issue by guria9** [fedora-silverblue/issue-tracker#468]
add an info on how to move the /run/initramfs/rdosreport.txt
how to mount and how to list drives. 
otherwise no regular user can provide logs with reasonable effort.

**Comment by guria9** [comment]
is this link in the emergency shell ? if not it does not help when you facing problems to waste more time searching for it.

**Comment by miabbott** [comment]
The emergency shell that you get in Silverblue is the same that you get on vanilla Fedora. If you would like to have additional information provided in the emergency shell changed, you would need to file a bug with `dracut` (I think).

If you are unhappy with the content of the docs, you are welcome to propose changes here - https://pagure.io/fedora-docs/quick-docs
