### ISSUE TITLE
Pen Tablet (Huion WH1409) cursor disappears. Wired Not working, Weird behavior of software.

### ISSUE THREAD

**Issue by roired** [fedora-silverblue/issue-tracker#47]
Good day,
Since started using Silverblue, I've been experiencing some weird behavior with my pen tablet. This tablet is a Wired/Wireless Huion WH1409 pen tablet (device, from now on). The issue also appears when using a Wacom Graphire A5 wired tablet.

**Sysinfo (Desktop Computer with AMD Ryzen 5 1600, Radeon RX570 on B350M chipset)**
1- active deployment as 2020.04.24 (layered and local packages needed for audio/video processing):
```
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/31/x86_64/silverblue
                   Version: 31.20200422.0 (2020-04-22T20:58:35Z)
                BaseCommit: 70bde311366d9ae9f0191e56c2c90c338ae000f2ad6938f030cb486622b466cc
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: fedora-workstation-repositories ffmpeg gnome-tweak-tool
                            gstreamer-plugins-bad gstreamer-plugins-ugly gstreamer1-libav
                            gstreamer1-plugins-ugly gstreamer1-plugins-ugly-free variety
             LocalPackages: rpmfusion-free-release-31-1.noarch
                            rpmfusion-nonfree-release-31-1.noarch
```
2- lsusb report with device unplugged:
```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 0451:ca01 Texas Instruments, Inc. 
Bus 001 Device 004: ID 0451:8027 Texas Instruments, Inc. 
Bus 001 Device 002: ID 0451:8142 Texas Instruments, Inc. TUSB8041 4-Port Hub
Bus 001 Device 007: ID 1ea7:0907 SHARKOON Technologies GmbH 
Bus 001 Device 006: ID 045e:07a5 Microsoft Corp. Wireless Receiver 1461C
Bus 001 Device 003: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
3- lsusb report with device wired (device reports itself as  ID 256c:006e )
```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 0451:ca01 Texas Instruments, Inc. 
Bus 001 Device 004: ID 0451:8027 Texas Instruments, Inc. 
Bus 001 Device 002: ID 0451:8142 Texas Instruments, Inc. TUSB8041 4-Port Hub
Bus 001 Device 007: ID 1ea7:0907 SHARKOON Technologies GmbH 
Bus 001 Device 006: ID 045e:07a5 Microsoft Corp. Wireless Receiver 1461C
Bus 001 Device 009: ID 256c:006e  
Bus 001 Device 003: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
4- lsusb report with device wireless (device reports itself as  ID 256c:006e )
```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 0451:ca01 Texas Instruments, Inc. 
Bus 001 Device 004: ID 0451:8027 Texas Instruments, Inc. 
Bus 001 Device 002: ID 0451:8142 Texas Instruments, Inc. TUSB8041 4-Port Hub
Bus 001 Device 007: ID 1ea7:0907 SHARKOON Technologies GmbH 
Bus 001 Device 006: ID 045e:07a5 Microsoft Corp. Wireless Receiver 1461C
Bus 001 Device 012: ID 058f:6366 Alcor Micro Corp. Multi Flash Reader
Bus 001 Device 011: ID 256c:006e  
Bus 001 Device 010: ID 058f:6254 Alcor Micro Corp. USB Hub
Bus 001 Device 003: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

As this device is not a Wacom, it does not report itself as a Wacom digitizer, thus nothing appears on System Setings>Wacom

**Issues**:
1) When working wireless, after a random period of time, ranging from 5 seconds to some minutes, the pen cursor disappears from the screen (mouse pointer is still present). Drawing becomes blind. This is experienced in the following software: MyPaint, Inkscape, Gimp, Blender.
This happens system wide though. The cursor from the pen disappears, and is a guess trial and error to select, click...
(Note: this behavior is also present in the Wacom Graphire A5 wired pen tablet)

2) When connection is wired, the device is also there as reported by lsusb, but unusable.

3) Unplugging causes some apps to crash (while writing down this report, Firefox crashed on unplugging the device), presumed to be the active software when unplugging the device.

4) Once issue 1 appears using some software, i.e. MyPaint, opening another, (Gimp, Inkscape, Blender) renders them unusable. Options from toolbars can be selected, though no action is performed, the software behaves like a screenshot. Needs a logout/reboot.

**How to reproduce the issues?**:
1.1- plug in the device in wireless mode (wired for the Wacom)
2.1- open MyPaint (or Inkscape, Gimp, Blender) and draw something for a while
2.1.1- just move around the system destkops and windows for a while (no need to draw anything)
3.1- pen cursor disappears (mouse pointer is still present)

1.2- plug in the device in wired mode
2.2- nothing happens. Pen pointer does not appear on the screen, so can't use pen tablet

Note: This weird behavior is specific to Silverblue. I didn't experience this issue before using Silverblue, when using Ubuntu 19.x. Haven't tested this with regular Fedora Workstation as just went from Ubuntu directly to Silverblue.

Please, let me know what kind of log files are needed, or any other important info, in order to throw more insight into this issue and help devs to address it.

Thanks for your assistance.
Regards,
RR

**Comment by tpopela** [comment]
Hi @roired 

> Note: This weird behavior is specific to Silverblue. I didn't experience this issue before using Silverblue, when using Ubuntu 19.x. Haven't tested this with regular Fedora Workstation as just went from Ubuntu directly to Silverblue.

The best thing would be to try to boot the Fedora Workstation Live ISO (ideally the F32 one, once the F32 will be available) and test it there. If you will see the same problems there, then you will need to open a bug report in Red Hat Bugzilla.

**Comment by roired** [comment]
Good day @tpopela ,

> The best thing would be to try to boot the Fedora Workstation Live ISO (ideally the F32 one, once the F32 will be available) and test it there. If you will see the same problems there, then you will need to open a bug report in Red Hat Bugzilla.

I will rebase to Silverblue 32 this weekend. Before rebasing, will do as you say. Will get a regular workstation ISO and do a test with the Live system. Then do the same on SB32 and compare behaviors, then post here any result. And if needed, open the bur report as you pointed out.

Thanks a lot.
Regards,
RR

**Comment by roired** [comment]
Good day @tpopela,

Finally. I finally got to a stage on the project to get back to using the pen tablet, and did as you said. I used default Fedora 32 Workstation, and the issue is there. Actually, behavior is the same as on Silverblue. This is weird. Therefore, I will open the bug now.
Thanks a lot.
Regards,
RR

**Comment by tpopela** [comment]
Thank you @roired. Feel free to put a link to the bug you open here!
