### ISSUE TITLE
error: Removing extensions/rpmostree/private/commit: unlinkat(devices): Directory not empty

### ISSUE THREAD

**Issue by Danik1601** [fedora-silverblue/issue-tracker#472]
**Describe the bug**
My version of Silverblue is already month old and there were no updates all this time. At some point I suspected that something is wrong and tried to check for updates with `sudo rpm-ostree upgrade` in terminal. The terminal shows this output: `error: Removing extensions/rpmostree/private/commit: unlinkat(devices): Directory not empty`. I immediately tried to fix this with `sudo rpm-ostree cleanup`  using `-bprm` arguments but still no luck. Specifically, terminal outputting `cleanup: GDBus.Error:org.projectatomic.rpmostreed.Error.Failed: syscore cleanup: cleaning tmp rootfs: Removing extensions/rpmostree/private/commit: unlinkat(devices): Directory not empty` after running `sudo rpm-ostree cleanup -b`  command.

**To Reproduce**
- Check for updates in Gnome Software
OR
- Run `sudo rpm-ostree upgrade` in terminal

**Expected behavior**
Upgrade check, list of available upgrades, upgrades installation

**Screenshots**
![image](https://github.com/fedora-silverblue/issue-tracker/assets/17238959/59c5277b-1953-4f67-81aa-569ba2b0b4c0)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230509.0 (2023-05-09T00:47:02Z)
               BaseCommit: fa62e262bd5d8afe7de1fda8f2865cee3a1734c62d299bab4e2e1d00f4c33f3e
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
          LayeredPackages: langpacks-en
```

**Additional context**
Fedora Silverblue 38 running in VirtualBox VM (EFI and Secure Boot enabled)
VirtualBox 7.0.8 with Extension Pack 7.0.8
Windows 11 host with AMD CPU and AMD GPU

**Comment by travier** [comment]
Looks like an rpm-ostree issue. Please report it there.

**Comment by travier** [comment]
If you could find where the `extensions/rpmostree/private/commit` folder/files are that would help

**Comment by LorbusChris** [comment]
@Danik1601 this dirname has shown up before: https://github.com/coreos/rpm-ostree/issues/2325#issuecomment-728964210

**Comment by travier** [comment]
Closed upstream as likely due to filesystem corruption: https://github.com/coreos/rpm-ostree/issues/4457#issuecomment-1621059164
