### ISSUE TITLE
Improve legibility of rpm-ostree (both normal and docker images)

### ISSUE THREAD

**Issue by firefoxlover** [fedora-silverblue/issue-tracker#473]
Nala for apt really is the best UI possible.

DNF is better than apt forever, simpler than Nala but very usable.

now rpm-ostree is really bad, especially with docker images, where it just spams the screen with "fetching chunk" messages.

Its already pretty well readable, but it could be a way better experience. Would this be reported in the coreos repos?

I think to summarize:
- displaying used repos and if there are changes
- Header and Border around it (depending on terminal width)
- Headers in Colors and bold
- Indentation
- Colored lists
- version changes in red (this is awesome)
- summaries of updates
- live changing text instead of printing it on top of each other (for example the "fetching ostree chunk" message).

**Comment by firefoxlover** [comment]
Comparison:

## Nala
![grafik](https://github.com/fedora-silverblue/issue-tracker/assets/78762110/264d7bfc-bd74-4cf6-8190-d852577ad041)

## rpm-ostree (layering)
![grafik](https://github.com/fedora-silverblue/issue-tracker/assets/78762110/5b80f5b6-9099-4ffd-9b9e-e1c56bf59f9b)

## DNF
![grafik](https://github.com/fedora-silverblue/issue-tracker/assets/78762110/94f01ee8-9a6b-4ee8-9d9e-1526c144cd5b)

**Comment by miabbott** [comment]
This is an enhancement request for `rpm-ostree`; I would suggest you file this on the https://github.com/coreos/rpm-ostree repo.
