### ISSUE TITLE
Consider reverting ostree upgrade until the flatpak regression is fixed

### ISSUE THREAD

**Issue by BuonHobo** [fedora-silverblue/issue-tracker#474]
Look here for context: https://github.com/ostreedev/ostree/issues/2900

This issue is present in silverblue and I can't update or install flatpaks unless I roll back to the previous image. Would it make sense to go back to an earlier version of ostree until this issue is fixed?

**Comment by travier** [comment]
Workaround in: https://discussion.fedoraproject.org/t/flatpak-updating-bug-due-to-libostree-update-with-solution/84696

Unfortunately we can't easily revert a single package for Silverblue in the Fedora infra right now 😕.

**Comment by travier** [comment]
F38 update to test: https://bodhi.fedoraproject.org/updates/FEDORA-2023-464fae1680

**Comment by 1player** [comment]
This can be closed, no? The issue has been solved for months now.
