### ISSUE TITLE
Package doesn't get upgraded and is available in the servers (ostree)

### ISSUE THREAD

**Issue by rscm** [fedora-silverblue/issue-tracker#476]
**Describe the bug**
The package ostree doesn't get updated to the latest version even though is present in the servers and available.

I've tried rpm-ostree refresh-md and nothing. I also tried rpm-ostree refresh-md --force.

I checked using toolbox and the latest version of the package for dnf is 2023.4-2

the lastest upgrade was (you can see that ostree gets upgraded to 2023.4-1 not the latest version)
```
❯ rpm-ostree db diff 64950853bc03976810dcb216f6da771680bf61043d01b381625d31164709d269 c351a6e4ab7c0a8b4180801e69031905bea69243a259804e86fd54ef3533b917
ostree diff commit from: 64950853bc03976810dcb216f6da771680bf61043d01b381625d31164709d269
ostree diff commit to:   c351a6e4ab7c0a8b4180801e69031905bea69243a259804e86fd54ef3533b917
Upgraded:
  btrfs-progs 6.3.1-1.fc38 -> 6.3.2-1.fc38
  cldr-emoji-annotation 1:43-1.fc38 -> 1:43.1-1.fc38
  cldr-emoji-annotation-dtd 1:43-1.fc38 -> 1:43.1-1.fc38
  cups 1:2.4.4-1.fc38 -> 1:2.4.5-1.fc38
  cups-client 1:2.4.4-1.fc38 -> 1:2.4.5-1.fc38
  cups-filesystem 1:2.4.4-1.fc38 -> 1:2.4.5-1.fc38
  cups-ipptool 1:2.4.4-1.fc38 -> 1:2.4.5-1.fc38
  cups-libs 1:2.4.4-1.fc38 -> 1:2.4.5-1.fc38
  emacs-filesystem 1:28.2-4.fc38 -> 1:28.2-7.fc38
  firefox 114.0-1.fc38 -> 114.0.2-1.fc38
  firefox-langpacks 114.0-1.fc38 -> 114.0.2-1.fc38
  gstreamer1 1.22.3-2.fc38 -> 1.22.4-1.fc38
  libaom 3.6.0-1.fc38 -> 3.6.1-1.fc38
  libdav1d 1.1.0-1.fc38 -> 1.2.1-1.fc38
  liburing 2.3-2.fc38 -> 2.4-2.fc38
  ostree 2023.3-3.fc38 -> 2023.4-1.fc38
  ostree-grub2 2023.3-3.fc38 -> 2023.4-1.fc38
  ostree-libs 2023.3-3.fc38 -> 2023.4-1.fc38
  sudo 1.9.13-1.p2.fc38 -> 1.9.13-2.p2.fc38
  sudo-python-plugin 1.9.13-1.p2.fc38 -> 1.9.13-2.p2.fc38

```

this is the output of dnf info inside a pod (toolbox), there you can see the latest is version 2023.4-2

```
❯ sudo dnf info ostree
Última comprobación de caducidad de metadatos hecha hace 0:02:38, el mar 27 jun 2023 18:25:46.
Paquetes disponibles
Nombre       : ostree
Versión      : 2023.1
Lanzamiento  : 2.fc38
Arquitectura : i686
Tamaño       : 250 k
Fuente       : ostree-2023.1-2.fc38.src.rpm
Repositorio  : fedora
Resumen      : Tool for managing bootable, immutable filesystem trees
URL          : https://ostree.readthedocs.io/en/latest/
Licencia     : LGPLv2+
Descripción  : libostree is a shared library designed primarily for
             : use by higher level tools to manage host systems (e.g. rpm-ostree),
             : as well as container tools like flatpak and the atomic CLI.

Nombre       : ostree
Versión      : 2023.4
Lanzamiento  : 2.fc38
Arquitectura : x86_64
Tamaño       : 247 k
Fuente       : ostree-2023.4-2.fc38.src.rpm
Repositorio  : updates
Resumen      : Tool for managing bootable, immutable filesystem trees
URL          : https://ostree.readthedocs.io/en/latest/
Licencia     : LGPL-2.0-or-later
Descripción  : libostree is a shared library designed primarily for
             : use by higher level tools to manage host systems (e.g. rpm-ostree),
             : as well as container tools like flatpak and the atomic CLI.
```

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. rpm-ostree upgrade - and nothing on ostree 2023.4-2
2. flatpak update still has the bug

**Expected behavior**
Upgrade ostree from ostree-2023.4-1.fc38.x86_64 to ostree-2023.4-2.fc38.x86_64 and being able to use flatpak

**OS version:**
```
❯ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230624.0 (2023-06-24T00:44:45Z)
               BaseCommit: c351a6e4ab7c0a8b4180801e69031905bea69243a259804e86fd54ef3533b917
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
      RemovedBasePackages: firefox firefox-langpacks 114.0.2-1.fc38 gnome-software gnome-software-rpm-ostree 44.2-1.fc38
          LayeredPackages: akmod-nvidia android-tools distrobox gnome-tweaks kernel-tools printer-driver-brlaser rpmfusion-free-release rpmfusion-nonfree-release starship steam-devices tailscale terminator xboxdrv xorg-x11-drv-nvidia
```

**Additional context**
The package was marked in stable yesterday
https://bodhi.fedoraproject.org/updates/FEDORA-2023-464fae1680

and is present in the mirrors the system direct me to use through the metalink (https://mirrors.fedoraproject.org/metalink?repo=updates-released-f38&arch=x86_64)

this is the first mirror (100 score)
http://fedora.c3sl.ufpr.br/linux/updates/38/Everything/x86_64/Packages/o/ostree-2023.4-2.fc38.x86_64.rpm
this is the second mirror (99 score)
https://edgeuno-bog2.mm.fcix.net/fedora/linux/updates/38/Everything/x86_64/Packages/o/ostree-2023.4-2.fc38.x86_64.rpm

**Comment by chrisawi** [comment]
This is ultimately the same issue as #475. Composes have been failing for several days, apparently due to a samba update. The [fix for that](https://bodhi.fedoraproject.org/updates/FEDORA-2023-dea6c15882) is in the compose running now, so hopefully this one will succeed:

https://kojipkgs.fedoraproject.org/compose/updates/Fedora-38-updates-20230628.0/logs/x86_64/Everything/ostree-1/create-ostree-repo.log

**Comment by rscm** [comment]
thanks for the info

looks like that was it, because I had a ton of packages upgraded

well ostree is upgraded now so this issue is closed

thanks again
