### ISSUE TITLE
Fusion icon for compiz reloaded on F39 python errorerror

### ISSUE THREAD

**Issue by coz** [fedora-silverblue/issue-tracker#479]
[coz@fedora ~]$ fusion-icon
 * Detected Session: mate
 * Searching for installed applications...
python3: /usr/include/python3.12/object.h:215: Py_SIZE: Assertion `ob->ob_type != &PyLong_Type' failed.
Aborted (core dumped)

**Comment by coz** [comment]
Most recent update with python caused the core dump

**Comment by travier** [comment]
This is the issue tracker for Fedora Silverblue. Please file issue following a template.
