### ISSUE TITLE
Unable to connect to SMB share

### ISSUE THREAD

**Issue by roired** [fedora-silverblue/issue-tracker#48]
Good day,
For system specs, check [here](https://github.com/fedora-silverblue/issue-tracker/issues/47).

Since started using Silverblue, I've never been able to connect to the SMB shared drive over the network using SMB protocol. I can connect if I activate FTP sharing and use ftp protocol to connect to the shared drive, though I rather have less protocols and ports open.

**Issue**:
1- When trying to connect to an SMB shared drive/folder over LAN using Nautilus (Connect to Server: smb:///xxx.xxx.xxx.xxx/smbshare), Nautilus always reports same error:

> **Could Not Display "smbshare"**
> The file is of an unknown type

**How to reproduce the issue**:
Attempt to connect to an SMB shared drive/folder over LAN using Nautilus "Connect to Server"

Is this due to some kind of licensing issue with SMB?

Please, let me know what kind of log files are needed, or any other important info, in order to throw more insight into this issue and help devs to address it.

Thanks for your assistance.
Regards,
RR

**Comment by ondrejholy** [comment]
Thanks for your report.

Does it work from command line over `gio` tool? For example:
```
$ gio mount  smb://192.168.122.184/test
Password required for share test on 192.168.122.184
User [user]: user
Domain [SAMBA]: 
Password: 
$ gio list smb://192.168.122.184/test/
VID_20190326_113343.mp4
...
```

If not, does it work over `smbclient` (or `mount.cifs`)? For example:
```
$ smbclient //192.168.122.184/test -U user
Enter SAMBA\user's password: 
Try "help" to get a list of possible commands.
smb: \> ls
  .                                   D        0  Wed Feb 19 15:32:51 2020
  ..                                  D        0  Fri May 17 16:54:20 2019
  VID_20190326_113343.mp4             N 99802649  Tue Apr  2 16:59:53 2019
...
```

Does it work from another system (e.g. Fedora Workstation)?

Just note that I don't see this issue on Fedora Silverblue 30 / Workstation 31 with my testing share.

**Comment by roired** [comment]
Good day @ondrejholy , 
I did those testing you provided and these are the results (none worked):
for the gio mount:
`Failed to mount Windows share: Software caused connection abort`

for the gio list:
`The specified location is not mounted`
(expected as the mount did not exit successfuly)

and for the smbclient:
`protocol negotiation failed: NT_STATUS_CONNECTION_DISCONNECTED`

So no success  there. It does work from Windows, and it did before when I had Ubuntu. I have to charge the old tablet that runs on Fedora Workstation to check it, as is the only device that is not able to run Silverblue due to 32bit UEFI for 64bit OS.
I will edit this when I get the chance to test from regular workstation.

Thanks a lot for your advise.
Regards,
RR

**Comment by ondrejholy** [comment]
>  `Failed to mount Windows share: Software caused connection abort`

I saw this error reported recently when the server required NT1 protocol version and NT1 was disabled on the client. The recent samba releases have NT1 disabled by default if I am not mistaken. Try to add `client min protocol = NT1` into your `smb.conf` file and try it again...

**Comment by roired** [comment]
Good day @ondrejholy 

You are right. The issue was the NT1 protocol. Once added to the `smb.conf` file in `/etc/samba/smb.conf` it did connect to the SMB share without any issues. I presume we can set this as solved.

Thanks a lot for solving the issue!
Regards,
RR
