### ISSUE TITLE
git request-pull is broken 

### ISSUE THREAD

**Issue by mripard** [fedora-silverblue/issue-tracker#483]
**Describe the bug**

The `git request-pull` command doesn't work on Fedora Silverblue 38.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Run `git request-pull`

The output is:
```
$ git request-pull 
git: 'request-pull' is not a git command. See 'git --help'.
```

**Expected behavior**

With Fedora 38, the (correct) output is: 

```
$ git request-pull 
usage: git request-pull [options] start url [end]

    -p                    show patch text as well

```

**OS version:**

This can be reproduced in a pristine Silverblue container:

```
$ podman run -it quay.io/fedora-ostree-desktops/silverblue:38 /bin/bash
bash-5.2# git request-pull 
git: 'request-pull' is not a git command. See 'git --help'.
```

**Comment by travier** [comment]
`git request-pull` is part of the `git` package which we have excluded from the image as it brings unwanted dependencies (Perl): https://pagure.io/workstation-ostree-config/blob/main/f/fedora-common-ostree.yaml#_20

```
$ rpm -qf /usr/libexec/git-core/git-request-pull
git-2.41.0-1.fc38.x86_64
```

You should install the full `git` package in a toolbox and use this command from there or overlay the `git` package on your system.
