### ISSUE TITLE
No bluetooth adapter after update (silverblue 37/38)

### ISSUE THREAD

**Issue by successfully-failed** [fedora-silverblue/issue-tracker#484]
After update macbook air 2017 bluetooth adapter disappeared

Bluetooth was working fine on fedora 38 ostree commit 

510b5d118502cfba59f6f3678620f0187aa4c323bec1c78c3c61928c923bdba1

and was broken in commit 

5fd95fb4487c3a2b40a3feecdd37e6b7584718dcc775f1eaa3ee6280305e1cf9   and after.

The error in gnome settings was:
"No bluetooth adapter found"

No bluetooth adapter was also found in:
- bluetoothctl
- rfkill

missing controler's name is:

Apple, Inc. Bluetooth USB Host Controller

Same problem appeared also in fedora silverblue 37.

Propably the new kernel issue.

**Comment by miabbott** [comment]
```
$ rpm-ostree db diff 510b5d118502cfba59f6f3678620f0187aa4c323bec1c78c3c61928c923bdba1 5fd95fb4487c3a2b40a3feecdd37e6b7584718dcc775f1eaa3ee6280305e1cf9
ostree diff commit from: 510b5d118502cfba59f6f3678620f0187aa4c323bec1c78c3c61928c923bdba1
ostree diff commit to:   5fd95fb4487c3a2b40a3feecdd37e6b7584718dcc775f1eaa3ee6280305e1cf9
Upgraded:
  gst-editing-services 1.22.3-1.fc38 -> 1.22.5-1.fc38
  gstreamer1 1.22.4-1.fc38 -> 1.22.5-1.fc38
  gstreamer1-plugin-libav 1.22.3-1.fc38 -> 1.22.5-1.fc38
  gstreamer1-plugins-bad-free 1.22.3-1.fc38 -> 1.22.5-1.fc38
  gstreamer1-plugins-base 1.22.3-1.fc38 -> 1.22.5-1.fc38
  gstreamer1-plugins-good 1.22.3-1.fc38 -> 1.22.5-1.fc38
  gstreamer1-plugins-good-qt 1.22.3-1.fc38 -> 1.22.5-1.fc38
  gstreamer1-plugins-ugly-free 1.22.3-1.fc38 -> 1.22.5-1.fc38
  kernel 6.3.12-200.fc38 -> 6.4.4-200.fc38
  kernel-core 6.3.12-200.fc38 -> 6.4.4-200.fc38
  kernel-modules 6.3.12-200.fc38 -> 6.4.4-200.fc38
  kernel-modules-core 6.3.12-200.fc38 -> 6.4.4-200.fc38
  kernel-modules-extra 6.3.12-200.fc38 -> 6.4.4-200.fc38
  openssh 9.0p1-15.fc38 -> 9.0p1-16.fc38
  openssh-clients 9.0p1-15.fc38 -> 9.0p1-16.fc38
  openssh-server 9.0p1-15.fc38 -> 9.0p1-16.fc38
```

Based on the packages changed, I suspect something changed in the kernel that is affecting your bluetooth adapter

The changelog for the kernel shows a bluetooth related change landing in 6.4.3 - https://packages.fedoraproject.org/pkgs/kernel/kernel-core/fedora-38-updates.html

I would recommend that you file a BZ with the Fedora kernel for your issue, because it is unlikely to be limited to just Fedora Silverblue - https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=kernel

**Comment by travier** [comment]
See also: https://discussion.fedoraproject.org/t/fedora-silverblue-sericea-after-rpm-ostree-update-lost-the-bluetooth-functionality-bcm2046b1/86513

**Comment by travier** [comment]
Fedora 38 is EOL. Please comment here if you still have this issue on a stable version of Fedora and we will re-open this bug. Thanks
