### ISSUE TITLE
Silverblue Live

### ISSUE THREAD

**Issue by Naheem** [fedora-silverblue/issue-tracker#489]
**Is your feature request related to a problem? Please describe.**
The current Silverblue installer is not live media. You cannot test it before install.

The payload however likely is ready to be used as live media (it is an image that is booted), so it is strange to have an old skool style installer

**Describe the solution you'd like**
The install media should be able to boot Silverblue as live media

**Describe alternatives you've considered**
None

**Additional context**
With the new web based installer being prototyped in Fedora Workstation, moving to a live media might become a no brainer.

There is also the question of silverblue positioning. If it is no longer a focus, then its fine, but if it is meant to push forwards ahead of Fedora Workstation, it is currently not managing that in this specific regard

**Comment by ChocolateLoverRaj** [comment]
I think this would also enable decreasing the brightness while installing which would really be nice for bright screens.

**Comment by travier** [comment]
This is now tracked in https://gitlab.com/fedora/ostree/sig/-/issues/32 thus closing this one. Thanks for the report.
