### ISSUE TITLE
Silverblue's random Logouts

### ISSUE THREAD

**Issue by roired** [fedora-silverblue/issue-tracker#49]
Good day,
This issue is an interesting one because of its randomness. 
For system specs, check [here](https://github.com/fedora-silverblue/issue-tracker/issues/47).

In order to provide some presumed valuable info, most of the time I'm on Silverblue I have these software running:

- Firefox
- Thunderbird (flatpak)
- Signal (flatpak)
- Godot (downloaded from Godot's site)
- VSCodium (appimage)
- Nautilus File manager

Other software I use regularly:

- MyPaint (flatpak)
- Inkscape (flatpak)
- Gimp (flatpak)
- Blender (flatpak)
- LMMS (appimage)
- Audacity (flatpak)

**Issue**:
As title states, I'm experiencing random logouts when working on Silverblue. This means that I have some software opened, where I'm working on (does not matter so much the software, as does not seem to affect which one is open and active), and suddenly, screen goes black and I face the Login screen.
Login in again, if Firefox was open before the "autologout", will recall all opened windows and tabs.

**How to reproduce the issue?**:
Well, this issue doesn't happen on a daily basis, though it's not the first nor the second time it happens. So I have no clue on how to force it to happen. It just randomly happens. Sometimes after a random logout the chance of having more "autologouts" rises. I have yet to find any pattern on this.

Please, let me know what kind of log files are needed, or any other important info, in order to throw more insight into this issue and help devs to address it.

Thanks for your assistance.
Regards,
RR

**Comment by tpopela** [comment]
Isn't GNOME Shell crashing? Can you please try to paste here the output of `coredumpctl list` ?

**Comment by roired** [comment]
Good day @tpopela ,
Hadn't  thought of Gnome Shell crashing. It might be. The extensions I have on are DashToPanel, Wintile (had Shelltile before), WorkspacesToDock, PanelOSD, OpenWeather, LockKeys, and UserThemes. Some say that extensions could cause issues, though I think I use pretty basic extensions.

Regarding the `coredumpctl list`, I presume you ask for that after a crash. Right now I don't remember when was the last time I had a random Logout, so I just got the output right now and here it is:
`IME                            PID   UID   GID SIG COREFILE  EXE
Tue 2020-01-21 21:35:02 CET    1671  1000  1000   5 missing   /usr/bin/gnome-shell
Sun 2020-01-26 19:30:02 CET    1668  1000  1000   5 missing   /usr/bin/gnome-shell
Wed 2020-01-29 08:45:41 CET    2054  1000  1000   6 missing   /usr/bin/gnome-software
Fri 2020-01-31 18:45:05 CET    1773  1000  1000   6 present   /usr/bin/Xwayland
Fri 2020-01-31 18:46:50 CET   10530  1000  1000   6 present   /usr/bin/Xwayland
Sat 2020-02-01 19:40:02 CET    1674  1000  1000   5 present   /usr/bin/gnome-shell
Sun 2020-02-09 13:12:35 CET    1271    42    42   5 error     /usr/bin/ibus-daemon
Sun 2020-02-16 18:37:46 CET   12622  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-02-16 18:38:36 CET   12775  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-02-16 19:48:13 CET   17261  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-02-16 19:48:35 CET   17347  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-02-16 20:57:00 CET   21266  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sat 2020-02-22 21:26:53 CET   27639  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sat 2020-02-22 21:41:43 CET   30671  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sat 2020-02-22 21:51:25 CET   13185  1000  1000  11 present   /usr/lib64/firefox/firefox
Wed 2020-03-04 20:36:00 CET   15797  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Wed 2020-03-04 21:40:03 CET    1653  1000  1000   5 present   /usr/bin/gnome-shell
Sat 2020-03-07 11:00:03 CET    1656  1000  1000   5 present   /usr/bin/gnome-shell
Sat 2020-03-07 13:07:02 CET   21825  1000  1000   5 present   /usr/bin/gnome-shell
Mon 2020-03-09 21:49:27 CET    7239  1000  1000   7 present   /usr/lib64/firefox/firefox
Mon 2020-03-09 22:01:59 CET    8265  1000  1000   7 present   /usr/lib64/firefox/firefox
Sun 2020-03-15 19:01:30 CET    1720  1000  1000   6 present   /usr/bin/Xwayland
Sun 2020-03-15 19:06:29 CET    9738  1000  1000   6 present   /usr/bin/Xwayland
Sun 2020-03-15 19:11:08 CET   15698  1000  1000   6 present   /usr/bin/Xwayland
Sat 2020-03-21 19:18:49 CET   49721  1000  1000  11 present   /var/home/userello/Software/Godot_v>
Wed 2020-03-25 11:50:55 CET   28937  1000  1000   7 present   /criptext
Wed 2020-03-25 11:51:12 CET   28884  1000  1000   7 present   /criptext
Wed 2020-03-25 11:58:15 CET   27600  1000  1000  11 present   /app/bin/gnome-calendar
Wed 2020-03-25 13:30:17 CET    8654  1000  1000  11 present   /tmp/.mount_pcloudvYfCDy/pcloud
Thu 2020-03-26 09:23:02 CET    1679  1000  1000   5 present   /usr/bin/gnome-shell
Fri 2020-03-27 19:04:26 CET   43293  1000  1000   5 present   /app/bin/inkscape
Mon 2020-03-30 13:55:03 CEST  13743  1000  1000   5 present   /usr/bin/gnome-shell
Mon 2020-03-30 17:04:36 CEST  29112  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Wed 2020-04-01 14:49:02 CEST  29677  1000  1000   5 present   /usr/bin/gnome-shell
Wed 2020-04-01 19:37:11 CEST  23137  1000  1000  11 present   /var/home/userello/Software/Godot_v>
Thu 2020-04-02 18:33:05 CEST  14967  1000  1000  11 present   /tmp/.mount_VSCodiFUCCCU/usr/shar>
Fri 2020-04-03 13:29:01 CEST   8246  1000  1000  11 present   /tmp/.mount_pcloudbrexFG/pcloud
Mon 2020-04-06 13:57:02 CEST   1696  1000  1000   5 present   /usr/bin/gnome-shell
Fri 2020-04-10 13:43:20 CEST   2090  1000  1000   7 present   /pcloud
Sun 2020-04-12 18:15:14 CEST   2044  1000  1000   7 present   /pcloud
Sun 2020-04-12 18:29:17 CEST  18384  1000  1000   7 present   /pcloud
Sun 2020-04-12 18:37:05 CEST  24518  1000  1000   7 present   /pcloud
Mon 2020-04-13 19:19:49 CEST   2058  1000  1000   7 present   /pcloud
Wed 2020-04-15 19:15:03 CEST   1674  1000  1000   5 present   /usr/bin/gnome-shell
Fri 2020-04-17 20:33:59 CEST   2069  1000  1000   7 present   /pcloud
Fri 2020-04-17 20:53:11 CEST  12212  1000  1000   7 present   /pcloud
Wed 2020-04-22 17:01:29 CEST   9388  1000  1000  11 present   /tmp/.mount_VSCodivzE4u4/usr/shar>
Thu 2020-04-23 20:20:08 CEST  18062  1000  1000  11 present   /var/home/userello/Software/Godot_v>
Fri 2020-04-24 12:47:36 CEST   3543  1000  1000   7 present   /usr/lib64/firefox/firefox
Fri 2020-04-24 16:29:20 CEST  18077  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Fri 2020-04-24 16:33:27 CEST  18512  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Fri 2020-04-24 16:34:50 CEST  18739  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Fri 2020-04-24 16:42:23 CEST  19367  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Fri 2020-04-24 17:08:03 CEST  21666  1000  1000   5 present   /pcloud
Fri 2020-04-24 17:08:03 CEST   1678  1000  1000   5 present   /usr/bin/gnome-shell
Fri 2020-04-24 18:08:40 CEST  32189  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sat 2020-04-25 13:12:11 CEST  12953  1000  1000  11 present   /var/home/userello/Software/Godot_v>
Sat 2020-04-25 21:28:47 CEST  49716  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sat 2020-04-25 21:40:13 CEST  50820  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sat 2020-04-25 21:52:47 CEST  51855  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 13:27:38 CEST   2074  1000  1000   7 present   /tmp/.mount_pcloudS0tZc3/pcloud
Sun 2020-04-26 16:29:57 CEST  22459  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 16:30:22 CEST  22629  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 17:15:40 CEST  26423  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 17:26:48 CEST  27461  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 17:28:19 CEST  28029  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 17:44:46 CEST  29354  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 17:48:39 CEST  31363  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 17:56:08 CEST   6500  1000  1000  11 present   /usr/bin/simplescreenrecorder
Sun 2020-04-26 18:13:38 CEST   2101  1000  1000   7 present   /pcloud
Sun 2020-04-26 18:14:47 CEST  12634  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 18:16:31 CEST  13067  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 18:18:08 CEST  13418  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 18:24:54 CEST   8117  1000  1000   7 present   /pcloud
Sun 2020-04-26 18:24:55 CEST  12731  1000  1000  11 present   /app/bin/obs
Sun 2020-04-26 18:37:58 CEST   8421  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 18:38:47 CEST   8768  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 18:51:11 CEST  10048  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 18:52:27 CEST  10496  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 19:59:25 CEST  15519  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 20:06:03 CEST  16154  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Sun 2020-04-26 20:53:03 CEST  19614  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Mon 2020-04-27 19:56:58 CEST   8980  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Mon 2020-04-27 21:07:07 CEST  16602  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Mon 2020-04-27 21:11:20 CEST  16887  1000  1000   6 present   /var/home/userello/Software/Godot_v>
Mon 2020-04-27 21:21:58 CEST  18105  1000  1000  11 present   /var/home/userello/Software/Godot_v>
Mon 2020-04-27 21:34:21 CEST  19278  1000  1000  11 present   /var/home/userello/Software/Godot_v>
Mon 2020-04-27 21:38:38 CEST  19688  1000  1000   6 present   /var/home/userello/Software/Godot_v>
lines 67-89/89 (END)`

If you need other info, please let me know and I'll get it. I will be rebasing to 32 this weekend so maybe the issue disappears then. I will add changes here if any takes place before rebasing.
Thanks a lot.
Regards,
RR

**Comment by tpopela** [comment]
I see many Godot, Xwayland and GNOME Shell crashes, so I suspect it's all related.

**Comment by roired** [comment]
Good day @tpopela ,
Now that you mention that, I think I recall some issues filed in Godot related to using Godot under Wayland, and that their recommended setup was using X. That might also be the cause for Workspaces showing Godot in two different workspaces in certain situations causing some sort of brief (second or two seconds) lock.
Apologies. I didn't know anything about the coredump thing before you talked about it. I will try to remember this before posting any issue in the future.
Godot is working on native Wayland support. So it does make sense that the problem here is related to Godot crashing with Wayland, and causing the Shell to crash, therefore, the random log outs.

Thanks a lot. I will keep an eye on it.
Regards,
RR

**Comment by tpopela** [comment]
I will close this for now, but feel free to reopen/comment when you again see the same crash and we will try to debug it further.
