### ISSUE TITLE
Gnome version "Not Available"

### ISSUE THREAD

**Issue by erayrafet** [fedora-silverblue/issue-tracker#490]
**Describe the bug**
Gnome version reported as "Not Available" in the Settings app.

**Expected behavior**
The version to be stated as 43.4 or 44.4.

**Screenshots**
![image](https://github.com/fedora-silverblue/issue-tracker/assets/34194191/0ebd6d7a-d058-46f8-979a-7e107b27495a)

**OS version:**
```
[erayrafet@fedora ~]$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/38/x86_64/silverblue
                  Version: 38.20230826.0 (2023-08-26T01:05:02Z)
               BaseCommit: 6d036a2ebf131c046ec1dba4ac3dbf5a4e3af0d0afeeeebf04b2fb9f5e346579
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
      RemovedBasePackages: gnome-terminal-nautilus gnome-terminal 3.48.1-1.fc38
          LayeredPackages: alsa-tools ffmpeg-free gnome-console gnome-tweaks gparted
                           gstreamer1-plugin-openh264 gstreamer1-plugins-bad-freeworld
                           gstreamer1-plugins-ugly hdparm idevicerestore intel-gpu-tools
                           intel-media-driver inxi java libavcodec-freeworld libva-utils
                           neofetch p7zip p7zip-plugins powertop python3-pip
                           python3-wxpython4 rpmfusion-free-release
                           rpmfusion-nonfree-release smartmontools WoeUSB

```

**Additional context**
Sometimes the correct version gets displayed but I can't pinpoint an exact reason.

**Comment by felipeborges** [comment]
Upstream issue https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2072

**Comment by fedelibre** [comment]
I cannot reproduce it on my laptop. Is it still valid?

In the About section there's a shorter frame where GNOME version is not listed at all:

![Schermata del 2023-10-12 23-01-25](https://github.com/fedora-silverblue/issue-tracker/assets/1644647/d25bfef4-7fce-40cf-98b0-e4324ebd608c)

and if I click the *System details* I can read the GNOME version:

![Schermata del 2023-10-12 23-01-34](https://github.com/fedora-silverblue/issue-tracker/assets/1644647/63544811-5399-4005-8b75-7d7e4c43d4fc)

**Comment by LorbusChris** [comment]
Not reproducible on `Fedora Linux 38.20231011.0 (Silverblue)` for me either

**Comment by erayrafet** [comment]
![image](https://github.com/fedora-silverblue/issue-tracker/assets/34194191/96f377d9-232f-40e4-8052-67c39678bb82)
The Gnome version seems to be showing up correctly although I need to test it further. Will report back. Oddly, my disk size is Unknown and has been. I run the OS from an SSD in a USB caddy.

**Comment by erayrafet** [comment]
![image](https://github.com/fedora-silverblue/issue-tracker/assets/34194191/68e537e2-9c87-4d43-8a2c-891699976c4a)
This is on the latest Arch Linux with Gnome 45. It's definitely an issue upstream. How do we report that?

**Comment by miabbott** [comment]
@erayrafet it looks like you found the existing upstream issue - https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2072

**Comment by erayrafet** [comment]
> @erayrafet it looks like you found the existing upstream issue - https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2072

https://github.com/fedora-silverblue/issue-tracker/issues/490#issuecomment-1698724133

It was linked here actually.

**Comment by erayrafet** [comment]
![image](https://github.com/fedora-silverblue/issue-tracker/assets/34194191/879dba97-13b8-4362-bad8-f1c775f75f8c)
Not reproducible anymore with F39.
