### ISSUE TITLE
Cannot add google account

### ISSUE THREAD

**Issue by alcir** [fedora-silverblue/issue-tracker#491]
**Describe the bug**
In practice I rebased from Fedora 38 to 39.
I can't use a previously configured Google account in gnome-online-accounts, and I can't add a new one.

**To Reproduce**
1. Go to Online Accounts.
2. Select Google.
3. The "Sign in with Google" form appears.
4. But you can't type the email.

**OS version:**
```
● fedora:fedora/39/x86_64/testing/silverblue
                  Version: 39.20230914.0 (2023-09-14T01:08:53Z)
               BaseCommit: fe03fc0dc3efb44bb23d00b36420e3cf515a1858763f0639861968a4c612ce40
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: gstreamer1-plugin-openh264 langpacks-en levien-inconsolata-fonts python3-fedora simple-scan syncthing tcpdump
```

**Additional context**
Weird thing is that in a fresh install of Silverblue 39, there are no problems.
Please have a look at this https://bugzilla.redhat.com/show_bug.cgi?id=2238599

**Comment by travier** [comment]
Can you update your report with the answers from the new bug template: https://github.com/fedora-silverblue/issue-tracker/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title= ?

Thanks

**Comment by alcir** [comment]
Ok. I installed Fedora Silverblue 38, setup the account, then updated to 39. Works.
Strange thing, on the PC I'm facing the issue, the problem is here using also a brand new user. Just to exclude some garbage in my home directory or the like.

**Comment by alcir** [comment]
Ok. I'm going to close this issue, as it doesn't look specific to Silverblue.
Thanks.
