### ISSUE TITLE
Orca not shipped as part of base installation

### ISSUE THREAD

**Issue by ndarilek** [fedora-silverblue/issue-tracker#5]
Hello,

I'm a blind screen reader user, and can't seem to launch Orca via either Alt-Super-S, or Alt-f2 "orca" when booted into the installation media. I need this to work in order to perform an independent installation.

Further, when I attempt the side-by-side installation method, I can't seem to log in using my credentials, and poking around in the installed ostree doesn't reveal an /usr/bin/orca.

Has it been removed from the base installation? If so, this makes me a bit sad, since it essentially excludes me from independently installing Silverblue as I've done with every edition of Workstation going back to 21. I'm a developer who wants the atomic benefits of Silverblue, particularly when upgrades have at times rendered my system inaccessible, but I need to be able to perform the installation independently, and to use Orca from the GDM login screen. Orca should be an included dependency that folks remove if they don't need it, not something whose ability to opt into I can't even get to.

Thanks.

**Comment by tpopela** [comment]
Hi Nolan,

> I'm a blind screen reader user, and can't seem to launch Orca via either Alt-Super-S, or Alt-f2 "orca" when booted into the installation media. I need this to work in order to perform an independent installation.

Currently, there is no live media and the "installation" one only runs an Anaconda and as far as I know, Anaconda doesn't support accessibility.

> Further, when I attempt the side-by-side installation method, I can't seem to log in using my credentials, and poking around in the installed ostree doesn't reveal an /usr/bin/orca.

Yes, for some reason it's blacklisted in https://pagure.io/workstation-ostree-config/blob/master/f/comps-sync-blacklist.yml#_151. I will open the PR to include it there.

> Has it been removed from the base installation?

It looks like it was never part of the Silverblue's base image. Let's add it there.

**Comment by tpopela** [comment]
Opened https://pagure.io/workstation-ostree-config/pull-request/153

**Comment by ndarilek** [comment]
When you write that the installer isn't live media, does that mean the 
installer is text-based and not running in Wayland/X?


I've used the Workstation live CD installation accessibly for years, and 
I thought that was Anaconda, but maybe I'm misunderstanding what 
Anaconda actually is?


Is it possible to pipe the installer's output over a serial port and 
connect remotely?


Thanks for opening an issue to unblacklist Orca.

**Comment by tpopela** [comment]
> When you write that the installer isn't live media, does that mean the installer is text-based and not running in Wayland/X?

No, that means, that there's just Anaconda (the installer) running in graphics mode on X. You don't have the whole desktop environment available (as there is the whole GNOME available in the live media of Fedora Workstation. Silverblue doesn't have that kind of installer (yet).

> I've used the Workstation live CD installation accessibly for years, and I thought that was Anaconda, but maybe I'm misunderstanding what Anaconda actually is?

Anaconda is the installer itself - that you run in regular Fedora Workstation by clicking the "Install to Hard drive" option in the initial dialog when you boot the live cd (or there's a launcher in the GNOME Shell's overview).

> Is it possible to pipe the installer's output over a serial port and connect remotely? 

I really don't know if it's possible.

> Thanks for opening an issue to unblacklist Orca.

You are welcome.

**Comment by tpopela** [comment]
For the missing live CD (or the accessible installator) I've created https://teams.fedoraproject.org/project/silverblue/us/88 so we can track it.

I would like to close the issue as both things are "resolved" or at least tracked, but I don't have the rights to do so. @sanjabonic or @matthiasclasen can you please do so?

**Comment by miabbott** [comment]
Closed per @tpopela comment.

Additional work tracked via:
  - https://pagure.io/workstation-ostree-config/pull-request/153
  - https://teams.fedoraproject.org/project/silverblue/us/88
