### ISSUE TITLE
GDM Starts in X11 After Boot; Switches to Wayland When Restarted

### ISSUE THREAD

**Issue by spiralman** [fedora-silverblue/issue-tracker#500]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
GDM Starts in X11 After Boot; Switches to Wayland When Restarted

**To Reproduce**
I have a clean installation of Silverblue 39 Beta on a Framework 13 AMD. When it first boots, GDM is running in X11/XOrg (I see a flash of the old "X" cursor, and only X11 login options are available in the menu). However, if I log in and log out again, or restart the GDM unit via `systemctl` from a VT, it uses Wayland

**Expected behavior**
Wayland should be used by default when the system first boots.

**Screenshots**

The session worker appears to start correctly:

```
Oct 31 16:17:30 fedora gdm-launch-environment][1265]: Gdm: GdmSessionWorker: session opened creating reply...
Oct 31 16:17:30 fedora gdm-launch-environment][1265]: Gdm: GdmSessionWorker: state SESSION_STARTED
Oct 31 16:17:30 fedora gdm-launch-environment][1265]: Gdm: GdmSession worker: watching pid 1314
```

But then it seems some component decides its not working and restarts in X11 mode:

```
Oct 31 16:17:31 fedora gdm[1252]: Gdm: GdmLocalDisplayFactory: display status changed: 2
Oct 31 16:17:44 fedora gdm[1252]: Gdm: GdmSession: Emitting 'session-exited' signal with exit code '0'
Oct 31 16:17:44 fedora gdm[1252]: Gdm: GdmSession: stopping conversation gdm-launch-environment
Oct 31 16:17:44 fedora gdm[1252]: Gdm: GdmSessionWorkerJob: Stopping job pid:1265
Oct 31 16:17:44 fedora gdm[1252]: Gdm: GdmCommon: sending signal 15 to process 1265
Oct 31 16:17:44 fedora gdm[1252]: Gdm: GdmDisplay: Greeter exited: 0
Oct 31 16:17:44 fedora gdm[1252]: Gdm: GdmDisplay: initiating display self-destruct
Oct 31 16:17:44 fedora gdm[1252]: Gdm: GdmDisplay: Session never registered, failing
```

See full logs attached: [gdmlogs.txt](https://github.com/fedora-silverblue/issue-tracker/files/13221654/gdmlogs.txt)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20231030.n.0 (2023-10-30T08:04:16Z)
               BaseCommit: a13e015fc00dd962bc1f3db380c4a114bfaf798ddbc49d1eb8d3faeb00a9889e
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: langpacks-en
```

**Additional context**
The attached logs are the logs from the GDM service for a recent boot, and include me restarting the service using `systemctl` and GDM restarting correctly using Wayland.

I'm not really able to re-install stock Fedora 39 Beta at the moment, but would be open to other debugging if anybody has thoughts on how else to debug the issue. The logs don't seem very clear about what is going wrong.

**Comment by travier** [comment]
Have you tried updating the firmware?
- https://knowledgebase.frame.work/framework-laptop-bios-and-driver-releases-amd-ryzen-7040-series-r1rXGVL16
- https://community.frame.work/t/amd-ryzen-7040-series-bios-3-03-and-driver-bundle-release/38655

**Comment by JannikWilhelm** [comment]
I had the same problem, updating BIOS to 3.03 fixed the Problem. Now Wayland is the default Display server even on a fresh boot.
