### ISSUE TITLE
Updates-archive repo error is preventing rebase/install on Fedora 39

### ISSUE THREAD

**Issue by GuiltyDoggy** [fedora-silverblue/issue-tracker#501]
**Describe the bug**
Getting the following error when using `rpm-ostree`:

`error: Updating rpm-md repo 'updates-archive': cannot update repo 'updates-archive': Yum repo downloading error: Downloading error(s): repodata/2e7db4492173b6c437fd1299dc335e63d09f24cbdadeac5175a61b787c2f7a44-filelists.xml.zck - Cannot download, all mirrors were already tried without success; Last error: Status code: 403 for https://fedoraproject-updates-archive.fedoraproject.org/fedora/39/x86_64/repodata/2e7db4492173b6c437fd1299dc335e63d09f24cbdadeac5175a61b787c2f7a44-filelists.xml.zck (IP: 108.138.94.50)`

Affects multiple scenarios: 
- Cannot rebase to Fedora Silverblue 39. (Affects non F39 machines)
- Cannot use `rpm-ostree` to install/upgrade current F39 machines (Affects machines already on F39)

**To Reproduce**
Please describe the steps needed to reproduce the bug:
A1. [On machine currently running F39] - run `rpm-ostree upgrade`

B1. [On machine currently running F38] - run `sudo rpm-ostree rebase fedora:fedora/39/x86_64/silverblue`

C1. [On fresh install of Silverblue F39] - run `rpm-ostree install vim`

**Expected behavior**
Expect system to upgrade, rebase, or install normally, for scenarios A1, B1, C1 above respectively.

**Screenshots**
![Screenshot_20231107_085403](https://github.com/fedora-silverblue/issue-tracker/assets/52749251/290e4951-c474-46b0-8f97-020651208388)

![Screenshot_20231107_090811](https://github.com/fedora-silverblue/issue-tracker/assets/52749251/b38117c8-ca64-460d-812b-faa580ea7504)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.1.5 (2023-10-31T22:06:37Z)
                   Commit: 3f6c3c54e77690b576ced4cf01528b8415a691bcf5afbe5df203b046ff396c67
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
```

**Additional context**

**Comment by dustymabe** [comment]
seems like downloading the repo metadata works fine for me from Fedora CoreOS:

```
[core@cosa-devsh ~]$ sudo rpm-ostree install htop 
Checking out tree 92feb22... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora updates-archive
Updating metadata for 'fedora-cisco-openh264'... done
Updating metadata for 'updates'... done
Updating metadata for 'fedora'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264'; generated: 2023-03-14T10:57:01Z solvables: 4
rpm-md repo 'updates'; generated: 2023-11-07T01:31:21Z solvables: 9604
rpm-md repo 'fedora'; generated: 2023-11-03T02:50:25Z solvables: 70825
rpm-md repo 'updates-archive'; generated: 2023-11-07T02:12:54Z solvables: 7726
Resolving dependencies... done
Will download: 1 package (190.0 kB)
Downloading from 'fedora'... done
Importing packages... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
Writing OSTree commit... done
Staging deployment... done
Added:
  htop-3.2.2-3.fc39.x86_64
Changes queued for next boot. Run "systemctl reboot" to start a reboot
```

**Comment by GuiltyDoggy** [comment]
Well it appears to be working now. Seems to have been a transient issue. Closing.

**Comment by vwbusguy** [comment]
I saw this was closed an hour ago but we just had another report about it from the #fedora channel on Libera IRC from a user trying to upgrade Silverblue.

**Comment by bmaya** [comment]
Hi, 

I'm the one who's been having trouble. Same errors listed in the OP:
`Updating metadata for 'updates-archive'... done
error: Updating rpm-md repo 'updates-archive': cannot update repo 'updates-archive': Yum repo downloading error: Downloading error(s): repodata/4a5f5a36381e29d9a70665b60eab96d702e5fb5c1a61904cea685dd5d83df2d0-primary.xml.zck - Cannot download, all mirrors were already tried without success; repodata/2e7db4492173b6c437fd1299dc335e63d09f24cbdadeac5175a61b787c2f7a44-filelists.xml.zck - Cannot download, all mirrors were already tried without success; Last error: Status code: 403 for https://fedoraproject-updates-archive.fedoraproject.org/fedora/39/x86_64/repodata/4a5f5a36381e29d9a70665b60eab96d702e5fb5c1a61904cea685dd5d83df2d0-primary.xml.zck (IP: 2600:9000:26c2:3000:2:e7e4:4740:93a1)
`

**Comment by vwbusguy** [comment]
As an update, it looks like this now fixed (shout out to Kevin Fenzi for invalidating the CloudFront cache).  Verified with @bmaya.
