### ISSUE TITLE
No new stable compose since 39.20231103.n.0

### ISSUE THREAD

**Issue by travier** [fedora-silverblue/issue-tracker#502]
**Describe the bug**

Now that the Fedora 39 release is out, we're waiting for the freeze to be lifted and a new build to be pushed with updates.

**To Reproduce**

1. Install Fedora Silverblue 39
2. Try to update

**Expected behavior**

Update to latest compose

**Screenshots**

N/A

**OS version:**

```
Fedora 39
```

**Additional context**

releng issue for tracking: https://pagure.io/releng/issue/11773

**Comment by travier** [comment]
Previous instance of this for Fedora 38: https://github.com/fedora-silverblue/issue-tracker/issues/454

**Comment by rscm** [comment]
I'm also affected. If you need me to do something to help/test just ask (I thought I was alone)

ref:
https://www.reddit.com/r/Fedora/comments/17q7ml1/when_will_be_the_updates_available_for_silverblue/
https://discussion.fedoraproject.org/t/when-will-be-the-updates-available-for-silverblue-39/95353

**Comment by lebrinkma** [comment]
The bug seems to be resolved by now, my Fedora 39 silverblue just updated to version 39.20231109.0.

**Comment by travier** [comment]
We're now good for everyone but Onyx, which will be fixed tomorrow:
```
ostree remote summary fedora | grep -E "39/(x86_64|aarch64)/(silverblue|kinoite|sericea|onyx)" -A3 --no-group-separator | grep -v 'Latest Commit' | grep -v '^      '                                                                                                                                                ~|12:37
* fedora/39/aarch64/kinoite
    Version (ostree.commit.version): 39.20231109.0
* fedora/39/aarch64/sericea
    Version (ostree.commit.version): 39.20231103.n.0
* fedora/39/aarch64/silverblue
    Version (ostree.commit.version): 39.20231109.0
* fedora/39/x86_64/kinoite
    Version (ostree.commit.version): 39.20231109.0
* fedora/39/x86_64/onyx
    Version (ostree.commit.version): 39.20231103.n.0
* fedora/39/x86_64/sericea
    Version (ostree.commit.version): 39.20231109.0
* fedora/39/x86_64/silverblue
    Version (ostree.commit.version): 39.20231109.0
```

**Comment by travier** [comment]
Hum, it's not fixed for Onyx and Sericea on !x86_64 but that looks like another issue.
