### ISSUE TITLE
New Package Request: systemd-container

### ISSUE THREAD

**Issue by chrisawi** [fedora-silverblue/issue-tracker#503]
Please try to answer the following questions about the package you are requesting:

1. Is the package installed by default in Fedora Workstation? 

It's not in comps, so I had assumed it wasn't, but I just discovered that it is in fact installed by default as a dependency of libvirt via gnome-boxes and likely has been since the package was split out of systemd circa F24.

3. What, if any, are the additional dependencies on the package? 

No additional dependencies

4. What is the size of the package and its dependencies?

```
Size        : 1458352
```

5. What problem are you trying to solve with this package? Or what functionality does the package provide?

systemd-container provides `machinectl` and `systemd-nspawn`.  One particular use case is `machinectl shell gdm@ ...` for running commands as the gdm user to configure the login session.

6. Can the software provided by the package be run from a container? Explain why or why not.

No, it's part of systemd and can be used to create containers itself.

8. Can the tool(s) provided by the package be helpful in debugging container runtime issues?

9. Can the tool(s) provided by the package be helpful in debugging networking issues?

10. Is it possible to layer the package locally via `rpm-ostree install <package>`? Explain why or why not.

Yes

**Comment by travier** [comment]
Sounds like a good idea to me.

**Comment by travier** [comment]
https://pagure.io/workstation-ostree-config/pull-request/431

**Comment by travier** [comment]
Merged https://pagure.io/workstation-ostree-config/pull-request/431. This will be in Fedora 40.
