### ISSUE TITLE
Add ibus-rime into the base image

### ISSUE THREAD

**Issue by lumingzh** [fedora-silverblue/issue-tracker#504]
**Is your feature request related to a problem? Please describe.**

ibus-libpinyin in the base image has some serious bugs with wayland:
- https://github.com/libpinyin/ibus-libpinyin/issues/347
- https://github.com/libpinyin/ibus-libpinyin/issues/396
- https://github.com/libpinyin/ibus-libpinyin/issues/436

**Describe the solution you'd like**

add another IME like rime (ibus-rime) into base image, this will give users one more choice.
- OS: Fedora Silverblue 39.20231117.0 (2023-11-17T00:55:33Z)
- ibus: 1.5.29-rc2
- ibus-libpinyin: 1.15.4
- libpinyin: 2.8.1
- libwayland: 1.22.0
- Xwayland: 23.2.2

**Comment by juhp** [comment]
I don't think this is a Silverblue specific issue, is it?

A workaround should be to overlay ibus-rime: `rpm-ostree install ibus-rime`.

**Comment by epico** [comment]
I tried Fedora Workstation 39, it seems work.

I will try to reproduce the issues, and check them.

**Comment by travier** [comment]
I think it is a Silverblue issue if the default input method installed does not work and another one works better but is not in the image by default.

**Comment by juhp** [comment]
I don't think so - because we have the same default IMEs in Workstation (they are all part of @input-methods yum group)

**Comment by epico** [comment]
I think he wants to add another input method, not replace the current one.

In China, we use Pinyin input method like ibus-libpinyin by default.

I just installed Fedora Silverblue 39, ibus-libpinyin seems work.

**Comment by lumingzh** [comment]
The configuration of rime is not user friendly, so maybe it's not a good idea to add it.
