### ISSUE TITLE
No update description for ostree packages in Gnome Software

### ISSUE THREAD

**Issue by Jacalz** [fedora-silverblue/issue-tracker#506]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**

The rpm packages through ostree never seem to show any update descriptions. It always says "No update description available." yet my Laptop with Fedora Workstation shows the description correctly.

Flatpak packages do show update descriptions if I remember (don't have one to update at the moment).

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Open Gnome Software
2. Check for updates
3. Click on a package to view information
4. Notice that there is no description

**Expected behavior**
There should be a text describing what was updated for the package.
The kernel update usually says something along the lines of "The Linux Kernel 6.5.12 contains various important bug fixes across the tree."

**Screenshots**
![image](https://github.com/fedora-silverblue/issue-tracker/assets/25466657/2bddf7a2-1c19-450c-a476-2150d76b2c63)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20231121.0 (2023-11-21T02:20:56Z)
               BaseCommit: 704d8016ce68160988166244d46b3b8411f4f8c93586e883115172cc2825373f
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: ffmpeg-free fish gstreamer1-plugin-openh264 langpacks-en_GB
                           libavcodec-freeworld libva-intel-driver mozilla-openh264
            LocalPackages: rpmfusion-free-release-39-0.2.noarch
```

**Additional context**
I think this has been the cases for as long as I've used Silverblue (about half a year).

**Comment by travier** [comment]
This looks like https://gitlab.gnome.org/GNOME/gnome-software/-/issues/667 ? Not sure what's going on.

**Comment by Jacalz** [comment]
Yeah. I think you're right. I'll let you or someone else decide if this should stay open or not :)

**Comment by Jacalz** [comment]
But why though? As far as I can see, the issue is still present on Fedora 41 with Gnome 47 even though the upstream issues was closed for resolving it in Gnome 43. I've never had update descriptions working on Silverblue.

**Comment by Jacalz** [comment]
This issue was opened after the upstream issue was closed.

**Comment by travier** [comment]
Ah, I had missed that. Re-opening.

**Comment by travier** [comment]
It would be good to open an issue upstream again then.
