### ISSUE TITLE
RTL88x2bu based Wifi adapter that works on Fedora workstation is not working well with Fedora Silverblue

### ISSUE THREAD

**Issue by vasili111** [fedora-silverblue/issue-tracker#507]
**Device I am using**
This is the usb Wifi adapter that I am using: https://www.amazon.com/gp/product/B0BWMQW4GB

This is the output of `lsusb`:
```
my_user@fedora:~$ lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID 046d:08b6 Logitech, Inc. Logi Webcam C920e
Bus 003 Device 003: ID 04d9:fa58 Holtek Semiconductor, Inc. USB Laser Game Mouse
Bus 003 Device 002: ID 045e:07f8 Microsoft Corp. Wired Keyboard 600 (model 1576)
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0bda:b812 Realtek Semiconductor Corp. RTL88x2bu [AC1200 Techkey]
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**On Fedora Silverblue:**

I installed latest version of Fedora Silverblue. I was able to connect without installing additional drivers by plugging out and plugging in usb Wifi adapter. **But** the connection is not stable and is dropping very often. I was also able to fully update system yesterday but it did not helped. So, on Fedora Silverblue this usb Wifi adapter does not works well.

<br>

**On Fedora Workstation:**
After I installed Fedora Workstation and usb Wifi adapter worked without any problem.

So, the problem seems to be only Fedora Silverblue specific.

Right now, I have installed Fedora Workstation on my PC and that is why I cannot give exact version of Fedora Silverblue that I have used but it was fully updated yesterday version. If necessary I can install back Fedora Silverblue and give exact version or do some additional tests that may help to fix this issue.

**Comment by vasili111** [comment]
After more testing I found that Fedora Workstation also has similar problem. So this issue not Fedora Silverblue specific

**Comment by travier** [comment]
You should probably report that in Bugzilla as a bug for the kernel.
