### ISSUE TITLE
Packages downgrade on SB32 rebase

### ISSUE THREAD

**Issue by barnscott** [fedora-silverblue/issue-tracker#51]
Just upgraded/rebased to Silverblue 32 beta and noticed these packages downgraded. Was wondering if someone might know if that is intentional or not:

Downgraded:
buildah 1.14.8-1.fc31 -> 1.14.0-0.31.dev.git82ff48a.fc32
conmon 2:2.0.15-1.fc31 -> 2:2.0.14-1.fc32
containers-common 1:0.2.0-1.fc31 -> 1:0.1.41-1.fc32
crun 0.13-2.fc31 -> 0.13-1.fc32
libdnf 0.47.0-1.fc31 -> 0.45.0-3.fc32
libinput 1.15.5-1.fc31 -> 1.15.4-1.fc32
libmodulemd 2.9.3-1.fc31 -> 2.9.1-1.fc32
librepo 1.11.3-1.fc31 -> 1.11.1-4.fc32
libssh 0.9.4-2.fc31 -> 0.9.3-2.fc32
libssh-config 0.9.4-2.fc31 -> 0.9.3-2.fc32
podman 2:1.9.0-1.fc31 -> 2:1.8.2-2.fc32
podman-plugins 2:1.9.0-1.fc31 -> 2:1.8.2-2.fc32
skopeo 1:0.2.0-1.fc31 -> 1:0.1.41-1.fc32
slirp4netns 1.0.0-1.fc31 -> 0.4.3-6.0.dev.gita8414d1.fc32
vim-minimal 2:8.2.587-1.fc31 -> 2:8.2.525-1.fc32

Additional context:

$ rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● ostree://fedora:fedora/32/x86_64/silverblue
                   Version: 32.20200424.n.0 (2020-04-24T08:16:12Z)
                BaseCommit: 0750349ac...
              GPGSignature: Valid signature by 97A1AE57...
           LayeredPackages: cockpit cockpit-ostree cockpit-podman fedora-workstation-repositories kmod-nvidia xorg-x11-drv-nvidia

  ostree://fedora:fedora/31/x86_64/silverblue
                   Version: 31.20200422.0 (2020-04-22T20:58:35Z)
                BaseCommit: 70bde31136...
              GPGSignature: Valid signature by 7D22D5...
           LayeredPackages: cockpit cockpit-ostree cockpit-podman fedora-workstation-repositories kmod-nvidia xorg-x11-drv-nvidia

**Comment by tpopela** [comment]
I think that this is expected. The F32 is in a freeze state before the release, but for the F31 the updates are still pushed to stable, but for F32, they are sitting in updates-testing and will be pushed to stable once F32 will be released.
