### ISSUE TITLE
Nvidia driver not working, Nvidia-smi shows no device

### ISSUE THREAD

**Issue by sith-on-mars** [fedora-silverblue/issue-tracker#510]
**Describe the bug**

I have a hybrid Nvidia laptop, but for some reasons, Nvidia is not working when switching to hybrid mode. `nvidia-smi` says `No devices were found`. Right clicking apps doesn't show the launching using Nvidia option. I'm using Silverblue 39, secure boot is disabled. Is there anyway to solve it?

Here is the [output](https://privatebin.xi.ht/?605e38bd370d8118#9vmWN4tNirHJKuZDE6kqy1GspkvYcKrZFyE7jUwbXBwM) of `nvidia-bug-report.sh`.

**OS version:**
```
dadstick@fedora:~$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20231125.0 (2023-11-25T02:15:38Z)
               BaseCommit: 2723814808ed65020a86253cdcc496eb1cc501ee174a8f5a536c66dc6ea5d192
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: akmod-nvidia distrobox gnome-tweaks libgda libgda-sqlite python3-smbc supergfxctl system-config-printer xorg-x11-drv-nvidia-cuda
```

**Additional context**

**Comment by travier** [comment]
There isn't much we can do to help here as NVIDIA drivers are not part of Fedora as they are not open source. You might have better results with the NVIDIA images from Universal Blue: https://universal-blue.org/images/nvidia/
