### ISSUE TITLE
rpm-ostree uprade fails for akmod-nvidia while kernel also to be updated from 6.5. to 6.6 on silverblue 39

### ISSUE THREAD

**Issue by tmstaedt** [fedora-silverblue/issue-tracker#511]
Just did a rpm-ostree upgrade and it fails with

Up until November 25th all updates to silverblue 39 with akmod-nvidia went normal, but now kernel is to be updated and it fails:

`Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - package akmod-nvidia-3:535.129.03-1.fc39.x86_64 from rpmfusion-nonfree-nvidia-driver requires akmods, but none of the providers can be installed
  - package akmod-nvidia-3:535.129.03-1.fc39.x86_64 from rpmfusion-nonfree requires akmods, but none of the providers can be installed
  - package akmods-0.5.8-2.fc39.noarch from fedora requires (kernel-devel-matched if kernel-core), but none of the providers can be installed
  - package kernel-devel-matched-6.5.12-300.fc39.x86_64 from updates requires kernel-core = 6.5.12-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.12-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.12-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.6-300.fc39.x86_64 from fedora requires kernel-core = 6.5.6-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.10-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.10-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.11-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.11-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.9-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.9-300.fc39, but none of the providers can be installed
  - cannot install both kernel-core-6.5.12-300.fc39.x86_64 from updates and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.6-300.fc39.x86_64 from fedora and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.10-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.11-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.12-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.9-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
`

> tom@linux2:~$ rpm-ostree status
State: idle
Deployments:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20231125.0 (2023-11-25T02:15:38Z)
               BaseCommit: 2723814808ed65020a86253cdcc496eb1cc501ee174a8f5a536c66dc6ea5d192
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: akmod-nvidia at cpulimit f36-backgrounds fuse-sshfs gnome-tweak-tool
                           google-roboto-condensed-fonts google-roboto-mono-fonts gstreamer1-plugin-openh264 lm_sensors
                           nethogs rpmfusion-free-release rpmfusion-nonfree-release sqlitebrowser virt-manager vnstat
                   Pinned: yes

also from above rpm-ostree upgrade:
Enabled rpm-md repositories: rpmfusion-nonfree-nvidia-driver google-chrome rpmfusion-free phracek-PyCharm rpmfusion-nonfree-steam fedora-cisco-openh264 rpmfusion-free-updates rpmfusion-nonfree-updates rpmfusion-nonfree updates fedora updates-archive
Importing rpm-md... done
rpm-md repo 'rpmfusion-nonfree-nvidia-driver' (cached); generated: 2023-11-24T21:19:35Z solvables: 29
rpm-md repo 'google-chrome' (cached); generated: 2023-11-28T19:35:27Z solvables: 3
rpm-md repo 'rpmfusion-free' (cached); generated: 2023-11-04T16:49:08Z solvables: 445
rpm-md repo 'phracek-PyCharm' (cached); generated: 2023-08-10T15:35:19Z solvables: 5
rpm-md repo 'rpmfusion-nonfree-steam' (cached); generated: 2023-08-10T16:27:35Z solvables: 2
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2023-03-14T10:57:01Z solvables: 4
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2023-11-24T19:24:24Z solvables: 91
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2023-11-24T19:44:29Z solvables: 29
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2023-11-04T17:26:32Z solvables: 208
rpm-md repo 'updates' (cached); generated: 2023-11-28T01:19:49Z solvables: 14067
rpm-md repo 'fedora' (cached); generated: 2023-11-01T00:12:39Z solvables: 70825
rpm-md repo 'updates-archive' (cached); generated: 2023-11-26T03:04:34Z solvables: 12832

**Comment by tmstaedt** [comment]
Installed akmods, and tried upgrade again, but

Resolving dependencies... done
error: Could not depsolve transaction; 2 problems detected:
 Problem 1: package akmods-0.5.8-2.fc39.noarch from fedora requires (kernel-devel-matched if kernel-core), but none of the providers can be installed
  - package kernel-devel-matched-6.5.12-300.fc39.x86_64 from updates requires kernel-core = 6.5.12-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.12-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.12-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.6-300.fc39.x86_64 from fedora requires kernel-core = 6.5.6-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.10-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.10-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.11-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.11-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.9-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.9-300.fc39, but none of the providers can be installed
  - cannot install both kernel-core-6.5.12-300.fc39.x86_64 from updates and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.6-300.fc39.x86_64 from fedora and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.10-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.11-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.12-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.9-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - conflicting requests
 Problem 2: conflicting requests
  - package akmod-nvidia-3:535.129.03-1.fc39.x86_64 from rpmfusion-nonfree-nvidia-driver requires akmods, but none of the providers can be installed
  - package akmod-nvidia-3:535.129.03-1.fc39.x86_64 from rpmfusion-nonfree requires akmods, but none of the providers can be installed
  - package akmods-0.5.8-2.fc39.noarch from fedora requires (kernel-devel-matched if kernel-core), but none of the providers can be installed
  - package kernel-devel-matched-6.5.12-300.fc39.x86_64 from updates requires kernel-core = 6.5.12-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.12-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.12-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.6-300.fc39.x86_64 from fedora requires kernel-core = 6.5.6-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.10-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.10-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.11-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.11-300.fc39, but none of the providers can be installed
  - package kernel-devel-matched-6.5.9-300.fc39.x86_64 from updates-archive requires kernel-core = 6.5.9-300.fc39, but none of the providers can be installed
  - cannot install both kernel-core-6.5.12-300.fc39.x86_64 from updates and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.6-300.fc39.x86_64 from fedora and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.10-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.11-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.12-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - cannot install both kernel-core-6.5.9-300.fc39.x86_64 from updates-archive and kernel-core-6.6.2-201.fc39.x86_64 from @System
  - package kernel-6.6.2-201.fc39.x86_64 from @System requires kernel-core-uname-r = 6.6.2-201.fc39.x86_64, but none of the providers can be installed

**Comment by tmstaedt** [comment]
Well, this is resolved by first removing akmod-nvidia from the layered packages, reboot, then do the rpm-ostree upgrade, which upgrades the kernel to 6.6., reboot again and install akmod-nvidia again

**Comment by sith-on-mars** [comment]
I’m on a newly installed Silverblue and I still couldn’t install Nvidia packages. The error message is the same. I checked that my kernel has already been updated to 6.6.
