### ISSUE TITLE
Podman throws database configuration mismatch error

### ISSUE THREAD

**Issue by bgoblyos** [fedora-silverblue/issue-tracker#513]
**Describe the bug**
Running any `podman` command will result in the following error:
`Error: database libpod root directory (staticdir) "/home/bence/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/var/home/bence/.local/share/containers/storage/libpod": database configuration mismatch`

The only difference is that one of those is the `/var` home directory, while the other is the `/home` symlink, which is why I'm assuming this is a Silverblue-specific issue.

**To Reproduce**

1. Run `podman ps` as an unprivileged user

**Expected behavior**
Podman should perform the specified operation.

**OS version:**
```
fedora:fedora/39/x86_64/kinoite
               Version: 39.20231202.0 (2023-12-02T01:01:03Z)
               BaseCommit: ccfa8149aa09987b851ab1a4eaacba351180a8c99e6a624cf982c44f4d42a95a
               GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
               LayeredPackages: akmod-nvidia bat borgmatic distrobox eza fira-code-fonts fish htop kate minicom mozilla-fira-mono-fonts mozilla-fira-sans-fonts neovim rpmfusion-free-release
                           rpmfusion-nonfree-release steam-devices syncthing virt-install virt-manager xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda
```

**Additional context**
I discovered the issue when trying to enter a `distrobox` container. The issue did not occur when I used the system yesterday, when I was on the 2023-11-30 image. It was most likely the following, though I'm not 100% sure as the image was cleaned up since then:

```
commit bafc1c00671564cf85d5c172cdfef200523d283cb0ca8dbe6e66030d98eebab8
Parent:  7b34073bef872b8db8c1994886fd0694c8fd5041d7a94b386e47ce78b1459fb9
ContentChecksum:  7c3371f8cb9f9597fe9ae376379be6a6232680e3e8fe972db733e7725326e10f
Date:  2023-11-30 01:22:13 +0000
Version: 39.20231130.0
```

Any help on how to correct this misconfiguration (if at all possible) would be appreciated.

**Comment by bgoblyos** [comment]
Update: I can confirm that `podman` is working as expected on the following deployment:
```
fedora:fedora/39/x86_64/kinoite
                  Version: 39.20231114.0 (2023-11-14T01:01:13Z)
               BaseCommit: ecbae6e7fde091aee2416342cb3424d257eba0d1c1752ecd5b82b93781f5cc2e
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: akmod-nvidia bat borgmatic distrobox eza fira-code-fonts fish htop kate minicom mozilla-fira-mono-fonts mozilla-fira-sans-fonts neovim rpmfusion-free-release
                           rpmfusion-nonfree-release steam-devices syncthing virt-install virt-manager xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda
                   Pinned: yes
```

It's over two weeks old so it's probably not useful for tracking down the issue, but at least it seems to confirm that it really is an issue with libpod and not a configuration error on my end.

**Comment by travier** [comment]
See https://github.com/fedora-silverblue/issue-tracker/issues/516#issuecomment-1851547132 for workarounds.
