### ISSUE TITLE
no clear way to restore system (grub, chroot)

### ISSUE THREAD

**Issue by sHaggYcaT** [fedora-silverblue/issue-tracker#515]
**Describe the bug**
No documentation, which works with silverblue, how to fix grub issues (and Fedora manuals don't work)
rpm-ostree and other tools are non-functional in the chroot envinronment.

No clear way how to recover system, and restore grub (efi or non-efi). 

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. delete your grub partion, which belongs to your silverblue system
2. try to restore it: check documentation, and found nothing working. 
3. try to use rpm-ostree and other specific silverblue tools while you're in the chroot env (using one of trees)

**Expected behavior**
Clear way how to restore your bootloader in the website documentation or in the man pages

**Comment by 616b2f** [comment]
I guess it could be closed as a duplicate to #403

**Comment by travier** [comment]
See also https://discussion.fedoraproject.org/t/how-to-restore-grub-cfg-in-silverblue/105895/2
