### ISSUE TITLE
grubby / sdubby installed by default

### ISSUE THREAD

**Issue by chrisawi** [fedora-silverblue/issue-tracker#517]
Now that unified core is re-enabled in 39.20231213, I compared the latest two compose logs to see if it was introducing any unexpected changes, and I found one odd thing: `grubby` has been replaced by `sdubby`, which also pulls in `systemd-boot-unsigned`.

I don't think either one is wanted. grubby was already excluded in [comps-sync-exclude-list.yml](https://pagure.io/workstation-ostree-config/blob/f39/f/comps-sync-exclude-list.yml#_39), but I think it was being pulled in via Recommends from `crypto-policies-scripts`. Maybe grubby (and sdubby?) should be added to this list as well: https://pagure.io/workstation-ostree-config/blob/f39/f/fedora-common-ostree.yaml#_84

**Comment by travier** [comment]
Indeed, sdubby should not be included. PR: https://pagure.io/workstation-ostree-config/pull-request/442

Test build in https://gitlab.com/fedora/ostree/ci-test/-/pipelines/1106846652/

**Comment by travier** [comment]
Merged, will be in the next build (when https://github.com/fedora-silverblue/issue-tracker/issues/516 is fixed).

**Comment by chrisawi** [comment]
Thanks, that gets us back to the status quo, but what about `grubby` itself? My understanding is that it's not compatible with rpm-ostree, which is why it's excluded from the comps sync.

**Comment by travier** [comment]
`grubby` should not be included as it is indeed conflicting with rpm-ostree. Setting kernel arguments should be done via `rpm-ostree kargs`. Is it included somewhere?

**Comment by travier** [comment]
Hum, looks like it's include in all variants. Will have to remove it as well.

**Comment by travier** [comment]
- Rawhide: https://pagure.io/workstation-ostree-config/pull-request/445 (test: https://gitlab.com/fedora/ostree/ci-test/-/pipelines/1109293022)
- F39: https://pagure.io/workstation-ostree-config/pull-request/444 (test: https://gitlab.com/fedora/ostree/ci-test/-/pipelines/1109293131)

**Comment by travier** [comment]
Merged. Will be in tomorrow's build for F39+.
