### ISSUE TITLE
Sound device not detected after Silverblue 32 upgrade, due to missing alsa-sof-firmware

### ISSUE THREAD

**Issue by ptomato** [fedora-silverblue/issue-tracker#52]
On a Lenovo Thinkpad Carbon X1 7th gen, the sound device was working fine on Silverblue 31. After rebase to Silverblue 32 and reboot, only the "Dummy output" device was detected by PulseAudio. As for ALSA, `aplay -l` showed no sound cards found.

After poking around in the Red Hat bugzilla, I tried layering `alsa-sof-firmware` with `rpm-ostree`. This restored everything back to a working state. It seems like this package should probably be included in the Silverblue image by default.

**Comment by tpopela** [comment]
Hi @ptomato, yes, the configs needs to be synced with fedora-comps. Once https://pagure.io/workstation-ostree-config/pull-request/167 is merged, the next SB compose should contain the alsa-sof-firmware. Thank you for letting us know!
