### ISSUE TITLE
python3-dnf gets included in latest testing compose for fedora 39

### ISSUE THREAD

**Issue by karuboniru** [fedora-silverblue/issue-tracker#521]
**Describe the bug**
As title `python3-dnf` gets included in latest testing for fedora 39 (`39.20231224.0`)

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Update to `fedora:fedora/39/x86_64/testing/silverblue 39.20231224.0`
2. Check updates:
```
$ rpm-ostree db diff 193ea6d455cbc325f098f4b1bb9e393a01a6af1a3509129f3c36758e432b6ee9 0ff5bd75c66f0aa583ff6c66b27aa4d3cbc9f52884750331fa3f364aac723f31
ostree diff commit from: 193ea6d455cbc325f098f4b1bb9e393a01a6af1a3509129f3c36758e432b6ee9
ostree diff commit to:   0ff5bd75c66f0aa583ff6c66b27aa4d3cbc9f52884750331fa3f364aac723f31
Upgraded:
  LibRaw 0.21.1-5.fc39 -> 0.21.2-1.fc39
  alsa-sof-firmware 2023.09.2-1.fc39 -> 2023.12-1.fc39
  brlapi 0.8.5-4.fc39 -> 0.8.5-9.fc39
  brltty 6.6-4.fc39 -> 6.6-9.fc39
  crypto-policies 20231113-1.gitb402e82.fc39 -> 20231204-1.git1e3a2e4.fc39
  crypto-policies-scripts 20231113-1.gitb402e82.fc39 -> 20231204-1.git1e3a2e4.fc39
  firefox 120.0.1-1.fc39 -> 121.0-2.fc39
  firefox-langpacks 120.0.1-1.fc39 -> 121.0-2.fc39
  gjs 1.78.1-1.fc39 -> 1.78.1-2.fc39
  gstreamer1 1.22.7-1.fc39 -> 1.22.8-1.fc39
  gstreamer1-plugin-libav 1.22.7-1.fc39 -> 1.22.8-1.fc39
  gstreamer1-plugins-bad-free 1.22.7-1.fc39 -> 1.22.8-2.fc39
  gstreamer1-plugins-bad-free-libs 1.22.7-1.fc39 -> 1.22.8-2.fc39
  gstreamer1-plugins-base 1.22.7-1.fc39 -> 1.22.8-1.fc39
  gstreamer1-plugins-good 1.22.7-1.fc39 -> 1.22.8-1.fc39
  gstreamer1-plugins-good-qt 1.22.7-1.fc39 -> 1.22.8-1.fc39
  gstreamer1-plugins-ugly-free 1.22.7-1.fc39 -> 1.22.8-2.fc39
  gtk-update-icon-cache 3.24.38-3.fc39 -> 3.24.39-1.fc39
  gtk3 3.24.38-3.fc39 -> 3.24.39-1.fc39
  ibus 1.5.29~rc2-5.fc39 -> 1.5.29~rc2-6.fc39
  ibus-gtk3 1.5.29~rc2-5.fc39 -> 1.5.29~rc2-6.fc39
  ibus-gtk4 1.5.29~rc2-5.fc39 -> 1.5.29~rc2-6.fc39
  ibus-libs 1.5.29~rc2-5.fc39 -> 1.5.29~rc2-6.fc39
  ibus-setup 1.5.29~rc2-5.fc39 -> 1.5.29~rc2-6.fc39
  kernel 6.6.7-200.fc39 -> 6.6.8-200.fc39
  kernel-core 6.6.7-200.fc39 -> 6.6.8-200.fc39
  kernel-modules 6.6.7-200.fc39 -> 6.6.8-200.fc39
  kernel-modules-core 6.6.7-200.fc39 -> 6.6.8-200.fc39
  kernel-modules-extra 6.6.7-200.fc39 -> 6.6.8-200.fc39
  libphonenumber 8.13.19-2.fc39 -> 8.13.27-1.fc39
  libssh 0.10.5-2.fc39 -> 0.10.6-2.fc39
  libssh-config 0.10.5-2.fc39 -> 0.10.6-2.fc39
  man-pages 6.05-3.fc39 -> 6.05-5.fc39
  mesa-dri-drivers 23.3.1-3.fc39 -> 23.3.1-4.fc39
  mesa-filesystem 23.3.1-3.fc39 -> 23.3.1-4.fc39
  mesa-libEGL 23.3.1-3.fc39 -> 23.3.1-4.fc39
  mesa-libGL 23.3.1-3.fc39 -> 23.3.1-4.fc39
  mesa-libgbm 23.3.1-3.fc39 -> 23.3.1-4.fc39
  mesa-libglapi 23.3.1-3.fc39 -> 23.3.1-4.fc39
  mesa-libxatracker 23.3.1-3.fc39 -> 23.3.1-4.fc39
  mesa-va-drivers 23.3.1-3.fc39 -> 23.3.1-4.fc39
  mesa-vulkan-drivers 23.3.1-3.fc39 -> 23.3.1-4.fc39
  mozjs115 115.4.0-1.fc39 -> 115.6.0-1.fc39
  python-unversioned-command 3.12.1-1.fc39 -> 3.12.1-2.fc39
  python3 3.12.1-1.fc39 -> 3.12.1-2.fc39
  python3-brlapi 0.8.5-4.fc39 -> 0.8.5-9.fc39
  python3-libs 3.12.1-1.fc39 -> 3.12.1-2.fc39
  rpm-ostree 2023.11-1.fc39 -> 2023.12-1.fc39
  rpm-ostree-libs 2023.11-1.fc39 -> 2023.12-1.fc39
  toolbox 0.0.99.4-8.fc39 -> 0.0.99.5-1.fc39
  zchunk-libs 1.3.2-1.fc39 -> 1.4.0-1.fc39
Added:
  deltarpm-3.6.3-11.fc39.x86_64
  dnf-data-4.18.2-1.fc39.noarch
  js-jquery-3.6.4-2.fc39.noarch
  libcomps-0.1.20-1.fc39.x86_64
  libdnf-0.72.0-1.fc39.x86_64
  libdnf-plugin-subscription-manager-1.29.39-1.fc39.x86_64
  python-systemd-doc-235-5.fc39.x86_64
  python3-cloud-what-1.29.39-1.fc39.x86_64
  python3-dateutil-1:2.8.2-10.fc39.noarch
  python3-decorator-5.1.1-7.fc39.noarch
  python3-dnf-4.18.2-1.fc39.noarch
  python3-dnf-plugins-core-4.4.4-1.fc39.noarch
  python3-hawkey-0.72.0-1.fc39.x86_64
  python3-iniparse-0.5-6.fc39.noarch
  python3-inotify-0.9.6-32.fc39.noarch
  python3-libcomps-0.1.20-1.fc39.x86_64
  python3-libdnf-0.72.0-1.fc39.x86_64
  python3-librepo-1.17.0-1.fc39.x86_64
  python3-six-1.16.0-12.fc39.noarch
  python3-subscription-manager-rhsm-1.29.39-1.fc39.x86_64
  python3-systemd-235-5.fc39.x86_64
  python3-unbound-1.19.0-1.fc39.x86_64
  rpm-plugin-systemd-inhibit-4.19.1-1.fc39.x86_64
  subscription-manager-1.29.39-1.fc39.x86_64
  subscription-manager-rhsm-certificates-20220623-3.fc39.noarch
  unbound-anchor-1.19.0-1.fc39.x86_64
  unbound-libs-1.19.0-1.fc39.x86_64
  usermode-1.114-8.fc39.x86_64
  virt-what-1.25-4.fc39.x86_64
  web-assets-filesystem-5-20.fc39.noarch
```
3. And `dnf4` `dnf-3` is provided:
```
$ rpm -qf `which dnf-3` `which dnf4` 
python3-dnf-4.18.2-1.fc39.noarch
python3-dnf-4.18.2-1.fc39.noarch
```

**Expected behavior**
dnf should not be included in ostree variant of fedora 

**OS version:**
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 15min ago
BootedDeployment:
● fedora:fedora/39/x86_64/testing/silverblue
                  Version: 39.20231224.0 (2023-12-24T02:18:05Z)
               BaseCommit: 0ff5bd75c66f0aa583ff6c66b27aa4d3cbc9f52884750331fa3f364aac723f31
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
      RemovedBasePackages: firefox firefox-langpacks 121.0-2.fc39
          LayeredPackages: fcitx5 fcitx5-autostart fcitx5-chinese-addons fcitx5-configtool fcitx5-gtk fcitx5-mozc fcitx5-qt zsh
```

**Additional context**
I am unsure which build between `39.20231219.0` and `39.20231224.0` introduced those package, but must be somewhere in between.

**Comment by travier** [comment]
Hum, we would need to find out which updates is bringing this package in as a dependency.

**Comment by karuboniru** [comment]
> Hum, we would need to find out which updates is bringing this package in as a dependency.

By checking [koji's log](https://kojipkgs.fedoraproject.org/compose/updates/Fedora-39-updates-testing-20231220.0/logs/x86_64/Everything/ostree-1/create-ostree-repo.log), the update seems to be `Fedora-39-updates-testing-20231220.0`

**Comment by travier** [comment]
That's the version of the compose. What we need is to find which one of the package update from Bodhi that is in testing, is pulling dnf in.

**Comment by chrisawi** [comment]
It appears to be `toolbox` adding a Recommends on `subscription-manager`.

https://bodhi.fedoraproject.org/updates/FEDORA-2023-c12a2a84a4

**Comment by travier** [comment]
Thanks a lot. I commented there.

**Comment by debarshiray** [comment]
I didn't know that `python3-dnf` RPM included the `%{_bindir}/dnf-3` and `%{_bindir}/dnf4` symbolic links.  Does anybody know why?  I would have expected the `dnf` RPM to provide those.

The Git history points at [these](https://src.fedoraproject.org/rpms/dnf/c/9c312c7cb701e40c65c26a5aa8a727fb4f37bc58) [two](https://src.fedoraproject.org/rpms/dnf/c/35d31efb392d68e6dba0d833cccd7fb199a43856) commits, but they don't include any justification for this.

**Comment by chrisawi** [comment]
> I didn't know that `python3-dnf` RPM included `%{_bindir}/dnf-3` and `%{_bindir}/dnf4`. Does anybody know why? I would have expected the `dnf` RPM to provide those.

`dnf-3` has always been in that package; that commit just changed the line to use `%{name}`. The -3 apparently means python3; there was a parallel python2 version called `dnf-2`.

I'd guess that `dnf4` was added to that package so that it can still be used after `dnf5` has obsoleted the main `dnf` package.

**Comment by debarshiray** [comment]
> > I didn't know that `python3-dnf` RPM included `%{_bindir}/dnf-3` and `%{_bindir}/dnf4`. Does anybody know why? I would have expected the `dnf` RPM to provide those.
> 
> `dnf-3` has always been in that package; that commit just changed the line to use `%{name}`. The -3 apparently means python3; there was a parallel python2 version called `dnf-2`.

If you keep going back in history, you get to [this](https://src.fedoraproject.org/rpms/dnf/c/56fbe46c247d1029ef8278baae09b7d78c754fbf) commit, but it still doesn't say anything.
 
> I'd guess that `dnf4` was added to that package so that it can still be used after `dnf5` has obsoleted the main `dnf` package.

Well, it still doesn't explain why a package named `python3-dnf`, which seems to be about the Python APIs for DNF, would ship the actual binary.  I would expect the binary to be part of a package called `dnf` or `dnf4`.

Note that `python3-dnf` is a sub-package of the `dnf` source package.  So, whichever DNF major version would be shipped in one, it would be the same in the other.

**Comment by debarshiray** [comment]
> > > I didn't know that `python3-dnf` RPM included `%{_bindir}/dnf-3` and `%{_bindir}/dnf4`. Does anybody know why? I would have expected the `dnf` RPM to provide those.
> > 
> > 
> > `dnf-3` has always been in that package; that commit just changed the line to use `%{name}`. The -3 apparently means python3; there was a parallel python2 version called `dnf-2`.
> 
> If you keep going back in history, you get to [this](https://src.fedoraproject.org/rpms/dnf/c/56fbe46c247d1029ef8278baae09b7d78c754fbf) commit, but it still doesn't say anything.

Oh, wait.  The `%changelog` says:
```
+- packaging: python3-dnf depends on dnf. (RhBug:1119032) (Ales Kozumplik)
+- Ship /usr/bin/dnf-3 to run DNF under Py3. (RhBug:1117678) (Ales Kozumplik)
```

... which are these two bugs:
* https://bugzilla.redhat.com/show_bug.cgi?id=1119032
* https://bugzilla.redhat.com/show_bug.cgi?id=1117678

I still don't understand the second one.

The first one is also strange.  Having `python3-dnf` require `dnf` sounds like a library requiring one of its applications.  Or does `python3-dnf` really spawn the `dnf(8)` binary.

**Comment by chrisawi** [comment]
> The first one is also strange. Having `python3-dnf` require `dnf` sounds like a library requiring one of its applications. Or does `python3-dnf` really spawn the `dnf(8)` binary?

I traced that requirement (through like eight layers of whitespace ping-pong) to where it was removed [in 2015](https://src.fedoraproject.org/rpms/dnf/c/accb5298aeea755032a9c0eeb21ed2c487f8135d). This commit appears to be where `/usr/bin/dnf` was first made a symlink. Until then, the `dnf` package contained the python2 version, and `python3-dnf` the python3 version (as it still does now).

AFAICT, the dnf executable script (currently `/usr/bin/dnf-3`) has always been in the same package as the dnf python modules. I presume you want the latter without the former.

**Comment by debarshiray** [comment]
I see.  Thanks for that archaeology.

I am trying to understand how deep we need to go to make `subscription-manager` not pull in a DNF executable on Fedora Silverblue.  Whether it can be achieved by moving things around in DNF's RPM packaging, or something else.

Anyway, I think this immediate issue can be closed because I submitted another update to drop the `Recommends: subscription-manager` from `toolbox`:
https://bodhi.fedoraproject.org/updates/FEDORA-2024-1505a8df50

We can continue discussing this in the higher level Workstation Working Group issue:
https://pagure.io/fedora-workstation/issue/391

**Comment by travier** [comment]
> We can continue discussing this in the higher level Workstation Working Group issue: [pagure.io/fedora-workstation/issue/391](https://pagure.io/fedora-workstation/issue/391)

Great, thanks!
