### ISSUE TITLE
Podman machine - no qemu-system-x86_64

### ISSUE THREAD

**Issue by motorto** [fedora-silverblue/issue-tracker#522]
This issue tracker is intended only for Silverblue specific issues. We would like to ask you to try to reproduce the issue on a relevant Fedora Workstation release. If you will be able to reproduce there, then please report it in [Red Hat Bugzilla](https://bugzilla.redhat.com/) (see [How to file a bug](https://docs.fedoraproject.org/en-US/quick-docs/howto-file-a-bug/)) or in upstream (preferred for GNOME projects) and not in this issue tracker.

**Describe the bug**
Unable to create machines with `podman machine` because there isn't qemu-system-x86_64 installed.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. `podman machine init`

**Expected behavior**
Being podman pre-installed, all features of it should be working.

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20231225.0 (2023-12-25T00:34:40Z)
                   Commit: 572a397342da60f6d9b6e9f80f0afbc27cf4c07b3f728cd6f684f84994d4d7df
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
```

**Additional context**

```
$ podman machine init 
Error: exec: "qemu-system-x86_64": executable file not found in $PATH
```

**Comment by travier** [comment]
We don't include it by default in Fedora Workstation. You don't really need podman machine on Linux as you can run all containers directly on the host. Not sure what to do here.

**Comment by stove-panini** [comment]
Looks like these were added as of `41.20241203.0`. Podman machine is nice to have when testing containers for different architectures.

**Comment by travier** [comment]
We are not including qemu for now. See: https://gitlab.com/fedora/ostree/sig/-/issues/58

**Comment by travier** [comment]
A likely path forward will be to use a systemd system extension (sysext). See https://github.com/travier/fedora-sysexts.
