### ISSUE TITLE
Broken update since rpm-ostree-2023.12-1.fc39.x86_64

### ISSUE THREAD

**Issue by karuboniru** [fedora-silverblue/issue-tracker#523]
**Describe the bug**
`rpm-ostree update` will fail if executed from 39.20231224.0 of fedora/39/x86_64/testing/silverblue.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Update to 39.20231224.0 of fedora/39/x86_64/testing/silverblue
2. `rpm-ostree update`
3. Got:
```
note: automatic updates (stage) are enabled
2 metadata, 0 content objects fetched; 788 B transferred in 1 seconds; 0 ?? content written
Checking out tree dd00e1d... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora updates-testing updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2023-03-14T10:57:01Z solvables: 4
rpm-md repo 'updates' (cached); generated: 2023-12-26T01:37:53Z solvables: 16861
rpm-md repo 'fedora' (cached); generated: 2023-11-01T00:12:39Z solvables: 70825
rpm-md repo 'updates-testing' (cached); generated: 2023-12-26T03:49:33Z solvables: 1721
rpm-md repo 'updates-archive' (cached); generated: 2023-12-26T01:55:57Z solvables: 18884
Resolving dependencies... done
Applying 2 overrides and 29 overlays
Processing packages... done
error: opendir(usr/lib/rpm-ostree/tmpfiles.d): 没有那个文件或目录
```
`没有那个文件或目录` should be translation of `no such file or directory`

**Expected behavior**
It should bring me newer release

**Screenshots**

**OS version:**
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● fedora:fedora/39/x86_64/testing/silverblue
                  Version: 39.20231224.0 (2023-12-24T02:18:05Z)
               BaseCommit: 0ff5bd75c66f0aa583ff6c66b27aa4d3cbc9f52884750331fa3f364aac723f31
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
      RemovedBasePackages: firefox firefox-langpacks 121.0-2.fc39
          LayeredPackages: fcitx5 fcitx5-autostart fcitx5-chinese-addons fcitx5-configtool fcitx5-gtk fcitx5-mozc fcitx5-qt zsh
```

**Additional context**

**Comment by karuboniru** [comment]
I believe this is due to https://github.com/coreos/rpm-ostree/pull/4697, it seems that the building process should populate files in `/usr/lib/rpm-ostree` while this hasn't done in this case cusing updating to fail.

Will check if the same is true for latest testing compose, if so maybe I should downvote [the update](https://bodhi.fedoraproject.org/updates/FEDORA-2023-b147ec959a) to stop the package from landing to stable

**Comment by travier** [comment]
Wow, thanks for testing this out.

**Comment by cgwalters** [comment]
Should be fixed by https://github.com/coreos/rpm-ostree/pull/4727 - we should make a new release soon.

**Comment by HuijingHei** [comment]
> Should be fixed by [coreos/rpm-ostree#4727](https://github.com/coreos/rpm-ostree/pull/4727) - we should make a new release soon.

Check [4727](https://github.com/coreos/rpm-ostree/pull/4727) is included in 2023.12-1, maybe also need https://github.com/coreos/rpm-ostree/pull/4746

**Comment by travier** [comment]
Should be fixed with https://github.com/coreos/rpm-ostree/releases/tag/v2024.1 when it lands in Fedora.

**Comment by cgwalters** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2024-2a4f3dce00

**Comment by HuijingHei** [comment]
Upgrade to `rpm-ostree-2024.1-4.fc39.x86_64`, can remove package successfully.

```
[root@cosa-devsh ~]# rpm -q rpm-ostree
rpm-ostree-2023.11-1.fc39.x86_64
[root@cosa-devsh ~]# rpm-ostree override replace https://bodhi.fedoraproject.org/updates/FEDORA-2024-2a4f3dce00
[root@cosa-devsh ~]# reboot
[core@cosa-devsh ~]$ rpm -q rpm-ostree
rpm-ostree-2024.1-4.fc39.x86_64

[core@cosa-devsh ~]$ ls /usr/lib/rpm-ostree
ls: cannot access '/usr/lib/rpm-ostree': No such file or directory

[core@cosa-devsh ~]$ sudo rpm-ostree override remove chrony
Checking out tree 621d18a... done
Resolving dependencies... done
Applying 3 overrides
Processing packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
Writing OSTree commit... done
Staging deployment... done
Pruned images: 0 (layers: 51)
Freed: 2.2 MB (pkgcache branches: 0)
Removed:
  chrony-4.5-1.fc39.x86_64
Use "rpm-ostree override reset" to undo overrides
Run "systemctl reboot" to start a reboot
```

**Comment by travier** [comment]
This may be a different issue, but this one is now blocked by https://bugzilla.redhat.com/show_bug.cgi?id=2252000

**Comment by travier** [comment]
Testing https://bodhi.fedoraproject.org/updates/FEDORA-2024-2a4f3dce00 resolves this issue would be nice.

**Comment by travier** [comment]
This should have been fixed now.
