### ISSUE TITLE
Unable to successfully reset root password using rescue mode

### ISSUE THREAD

**Issue by miabbott** [fedora-silverblue/issue-tracker#524]
When trying to follow the instructions on [resetting the root password using rescue mode](https://docs.fedoraproject.org/en-US/quick-docs/reset-root-password/#_how_to_reset_the_root_password_in_rescue_mode), I found that I'm unable to login with my user account or root account afterwards.

1. Using a fresh Silverblue 39 install, I appended `rw init=/bin/bash` to the `linux` line in the boot entry. 
2. I used `passwd` to configure the root password from the resulting shell. 
3. Because `touch /.autorelabel` does not work with ostree-based hosts, I tried using `/sbin/restorecon -v /etc/{passwd,shadow}` (see https://github.com/coreos/fedora-coreos-docs/pull/48) to fix any SELinux labeling before using `/sbin/reboot -f`.
4. After rebooting, my user login and root login no longer worked.

I was unable to observe any errors on the console during the login attempts.

**Comment by noelmiller** [comment]
Thanks to Colin, there is also another option and will be simpler to execute: https://github.com/ublue-os/main/issues/469#issuecomment-1885264886
