### ISSUE TITLE
Incompatible firefox-langpacks version

### ISSUE THREAD

**Issue by gjask** [fedora-silverblue/issue-tracker#525]
**Describe the bug**
Default Firefox installation refuses to use czech localization as it is of incompatible version. I assume there is incompatible version of langpack packed into `firefox-langpacks` package. ~~It is possible this is Workstation issue, but currently I have no available system to test it on myself.~~ I've tried to replicate this issue in freshly installed (and updated) Workstation in Boxes but it works as expected. So this seems to be Silverblue issue.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Select czech localization during Silverblue installation (I don't know if there is other way to change localization to already installed system, I suppose there should be some, but I haven't tested it)
2. Update system after installation
3. Open extension tab in Firefox and check if langpack is available and applied

**Expected behavior**
Firefox should be localized into Czech and show installed czech langpack in extension tab.

**Screenshots**
![Snímek obrazovky z 2024-01-10 21-22-19](https://github.com/fedora-silverblue/issue-tracker/assets/3306648/5255ad08-a188-4765-a30d-7bfb22a4b01c)

**OS version:**
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 4h 40min ago
BootedDeployment:
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20240110.0 (2024-01-10T00:43:08Z)
               BaseCommit: 8ceba7ffc72ba4a0a23390797d30b6a24edfc07053111292ac42b4365bc8e27f
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: distrobox ffmpeg-free fzf gnome-tweak-tool htop httpie ipython
                           langpacks-cs libavcodec-freeworld mozilla-openh264 mycli
                           python3-csvkit rpmfusion-free-release rpmfusion-nonfree-release
                           tilix vim virtualenv wl-clipboard
```

**Additional context**
```
$ rpm -qa | grep firefox
firefox-langpacks-121.0-3.fc39.x86_64
firefox-121.0-3.fc39.x86_64
```

**Comment by chrisawi** [comment]
I can't reproduce this here with `LANG=cs_CZ.utf8 /usr/bin/firefox`. Firefox correctly loads the langpack version 121 and is translated.

From the timestamp, this must be an ostree-packaged file, but maybe Firefox has a stale cache? Can you try a fresh profile, or even a fresh user account?

**Comment by gjask** [comment]
> From the timestamp, this must be an ostree-packaged file, but maybe Firefox has a stale cache? Can you try a fresh profile, or even a fresh user account?

Yeah, it works just fine for newly created user.

**Comment by travier** [comment]
Thanks for the investigation. This would likely be better fixed in Firefox. Not sure what else we could do in Silverblue.

**Comment by gjask** [comment]
Well it probably could be also fixed in Firefox package. Firefox rpm already contains a bash script responsible for creating symlink for a langpack in home directory. This is done so new version of langpack is installed with new version of firefox from package. This script could be upgraded to work around this issue in Silverblue (eg. copy file instead of symlink).

https://src.fedoraproject.org/rpms/firefox/blob/f39/f/firefox.sh.in#_214

It still may be a good idea to check with upstream if they have a good way to fix this. But from my point of view it is downstream feature that is broken.

**Comment by travier** [comment]
Hum, interesting, this would indeed be a Fedora specific bug. But then the question becomes: why does this script not work on Silverblue?

**Comment by gjask** [comment]
> Hum, interesting, this would indeed be a Fedora specific bug. But then the question becomes: why does this script not work on Silverblue?

Oh it does in a way. It creates symlink same as on Workstation. I have (not yet confirmed) theory that Firefox reloads metadata from extension only when file timestamp changes. And it does on Workstation when new version of rpm is installed. But on Silverblue that original file always has zero timestamp across deployments. So Firefox doesn't reload extension a believes in its own cached that says that is an old one.

**Comment by travier** [comment]
Hum, so there are multiple layers of caching here. 😕

**Comment by gjask** [comment]
I don't think there are multiple layer of cache. Until now I have noticed only one and that is extension metadata firefox does store in `extensions.json` in profile dir.

That script from fedora RPM just makes sure there is prepared symlink in home dir pointing to current langpack installed from `firefox-langpacks` anytime when Firefox is started.

**Comment by travier** [comment]
It's probably best to submit a bug in bugzilla for the firefox package as the developers there should have more knowledge about how all of this works.

**Comment by xhorak** [comment]
Yes, it's the timestamp what's checked during checking newer version. It's a downstream issue, I'll fix the launch script.

**Comment by gjask** [comment]
@xhorak How is it going? Can I do something to help?

**Comment by xhorak** [comment]
> @xhorak How is it going? Can I do something to help?

It should be fixed by upcoming firefox-122.0 release.

**Comment by gjask** [comment]
Thanks. I did check open PRs but I had to miss it. Also I should have checked commits, my bad. :D

**Comment by gjask** [comment]
And it seems to be already present in current build and working correctly. Thank you for fixing the issue.

**Comment by travier** [comment]
Fix for reference: https://src.fedoraproject.org/rpms/firefox/c/588e3b01fb7467b97e71f7e1c04832e690a1d36c?branch=rawhide
