### ISSUE TITLE
Ambigous error in rpm-ostree

### ISSUE THREAD

**Issue by barnscott** [fedora-silverblue/issue-tracker#53]
I came across an error message with rpm-ostree, and while it was rather simple to identify the issue, the error message itself is rather ambiguous. Was thinking it might benefit from from clarification.

Context: just before running rpm-ostree i was doing some layer package clean up and had removed a couple layers and repos. After doing so, I got the following error after attempting an upgrade:

```
$ rpm-ostree upgrade
note: automatic updates (stage) are enabled
1 metadata, 0 content objects fetched; 569 B transferred in 3 seconds
Checking out tree 53eecca... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2020-03-17T20:10:45Z
rpm-md repo 'updates' (cached); generated: 2020-04-30T01:55:47Z
rpm-md repo 'fedora' (cached); generated: 2020-04-24T11:00:23Z
Importing rpm-md... done
error: Packages not found: kmod-nvidia, xorg-x11-drv-nvidia
```

The issue was created because I accidentally also disabled my RPMFusion/nVidia repo. Just enabling that repo resolved the issue.

"Packages not found" sounds like the packages were missing from my ostree commit, which was confusing. Might want to add clarification, like "Packages have been orphaned" or "Upstream repo for packages not found".

I suspect this may not be the right place to submit this feature request. If not, please redirect me. Appreciate it.

**Comment by jlebon** [comment]
> "Packages not found" sounds like the packages were missing from my ostree commit, which was confusing.

"Packages not found" errors can only ever refer to layered packages from yum repos because we never have a need to download packages which we already have in the OSTree. :)

**Comment by barnscott** [comment]
Yup, makes sense! And that's why I found the message ambiguous, cuz the packages did already exist in ostree but the package manager was saying "packages not found". One might wonder why the package manager is looking for them since they are already layered. This would be Really hard to troubleshoot if I had orphaned PPAs in which packages were removed.

**Comment by travier** [comment]
Closing this one. If you think we should still improve the rpm-ostree UX, please file an issue in the upstream repo.
