### ISSUE TITLE
On freshly installed Silverblue, org.gnome.font-viewer crashes when opened through Activities.

### ISSUE THREAD

**Issue by lruzicka** [fedora-silverblue/issue-tracker#535]
**Describe the bug**
On a freshly installed Silverblue 40 Workstation, the Fonts application (org.gnome.font-viewer) crashes when started with Activities. The stupid thing is that it only crashes once and works for all consecutive attempts. Also, when started with `flatpak run org.gnome.font-viewer` command, it works all the time.

This can only be seen on a newly installed Silverblue. Once the application has started successfully, it will do so consecutively.

**To Reproduce**
1. Install Silverblue from the latest ISO.
2. Press `super` to open Activities.
3. Type `Fonts`.
4. Press Enter.
5. See the crash, or alternatively the app will not start at all.
6. Try again, this time, it will start.

**Expected behavior**
The application should start successfully even the first time.

**OS version:**

* org.fedoraproject.Platform:39
* org.fedoraproject.Sdk:39
* org.gnome.font-viewer:45

**Additional context**
For more details, see this bug report: https://gitlab.gnome.org/GNOME/gnome-font-viewer/-/issues/78

**Comment by chrisawi** [comment]
What happens if you run `coredumpctl dump > core` directly?

Also, is this crash the most recent one listed in the output of `coredumpctl`? If not, you need to use:

    flatpak-coredumpctl org.gnome.font-viewer -m /app/bin/org/gnome/font-viewer

By default, it will use the latest coredump, regardless of source.

**Comment by A6GibKm** [comment]
I tried to reproduce with gnome-font-viewer 46.0 from Flathub without success on Silverblue 40. The app does not crash.

**Comment by travier** [comment]
Thanks for the update.
