### ISSUE TITLE
F40 cannot layer mozilla-openh264

### ISSUE THREAD

**Issue by kanru** [fedora-silverblue/issue-tracker#536]
**Describe the bug**

If mozilla-openh264 was previously layered it prevents rebasing to F40.
After removed mozilla-openh264 and rebased to F40, mozilla-openh264 cannot be layered again unless first removing `noopenh264` from the base.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Run `rpm-ostree install mozilla-openh264`

```
error: Could not depsolve transaction; 1 problem detected:
 Problem: package noopenh264-0.1.0~openh264_2.4.0-1.fc40.x86_64 from @System conflicts with openh264 provided by openh264-2.4.0-2.fc40.x86_64 from fedora-cisco-openh264
  - package openh264-2.4.0-2.fc40.x86_64 from fedora-cisco-openh264 obsoletes noopenh264 < 1:0 provided by noopenh264-0.1.0~openh264_2.4.0-1.fc40.x86_64 from @System
  - package mozilla-openh264-2.4.0-2.fc40.x86_64 from fedora-cisco-openh264 requires openh264(x86-64) = 2.4.0-2.fc40, but none of the providers can be installed
  - conflicting requests
```

**Expected behavior**
Both `mozilla-openh264` and `openh264` should be layered.

**Screenshots**
N/A

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240301.n.0 (2024-03-01T08:13:52Z)
               BaseCommit: 015c2ff0f7b415c438ce656e2d40ca81d6d3dc6c6b012b95bb4e6c05f46bdfd5
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
          LayeredPackages: btrbk fish gnome-boxes starship syncthing
            LocalPackages: ibus-chewing-2.0.0-2.fc39.x86_64
```

**Additional context**
N/A

**Comment by travier** [comment]
You now need to remove the `noopenh264` package when layering the `openh264` one:

```
$ rpm-ostree override remove noopenh264 --install openh264 --install mozilla-openh264
```

**Comment by OptimoSupreme** [comment]
Isn't `noopenh264` obsolete though? Why is it included in the first place?

**Comment by juhp** [comment]
No it is a placeholder which is obsoleted by the real openh264 package in the cisco repo.

**Comment by juhp** [comment]
This seems like a reasonable candidate for CommonBugs

**Comment by nanonyme** [comment]
@OptimoSupreme noopenh264 provides OpenH264 API through stubs that can be built against. The idea is that you would then drop-in OpenH264 to provide the actual implementation.

**Comment by OptimoSupreme** [comment]
@nanonyme so I guess my question is when would you actually need the noopenh264 package? From what I found and what was said before, I needed to remove the package just to install openh264.

**Comment by nanonyme** [comment]
It's needed as a dependency of the packages I mentioned before. They will load the API's with stubs and gracefully report OpenH264 is not supported and move on. There isn't really any other problem here than that depsolver refuses to remove the conflicting noopenh264 in favour of openh264.

**Comment by juhp** [comment]
I think this is a limitation of rpm-ostree?  Though I can't find any existing reported there, which makes me wonder.
(The closest issue seems to be coreos/rpm-ostree#4533).
Perhaps it is because openh264 is from a different repo?

**Comment by juhp** [comment]
In fact it is not just rebase, even after upgrading https://github.com/fedora-silverblue/issue-tracker/issues/536#issuecomment-1974780009 is still needed to overlay openh264

**Comment by juhp** [comment]
I am still not clear how noopenh264 gets pulled into SB40 though?
In retrospect it seems better to have excluded it but I think it is too late for that now I guess.

**Comment by nanonyme** [comment]
My educated guess is it gets pulled in as dependency of gstreamer OpenH264 plugin or ffmpeg.

**Comment by nanonyme** [comment]
IMHO this is a missing feature, unclear where. Probably rpm-ostree.

**Comment by jlebon** [comment]
It seems like it gets pulled as a weak dep of `libavcodec-free` (which gets pulled in by [`gstreamer1-plugin-libav`](https://pagure.io/workstation-ostree-config/blob/cddc298be53e2749aa3feccb88776b68aa1b542d/f/fedora-common-ostree-pkgs.yaml#L75)).

We also ship `libavcodec-free` in f39 and `libopenh264.so.7()(64bit)` is also a weak dep there. 

Anyway, opened https://pagure.io/workstation-ostree-config/pull-request/508 (and [an f40 backport](https://pagure.io/workstation-ostree-config/pull-request/509)) which I think should fix this but I didn't test it yet.

**Comment by nanonyme** [comment]
Make sure to test trying to view OpenH264 content doesn't result in a crash afterwards but instead failure on missing codec.

**Comment by nanonyme** [comment]
The thing is, they both provide same soname libraries. Whatever the setup, it should be so that everything switched to loading OpenH264 library when present. With flatpak runtimes this is simple, the extension can just be mounted on top of noopenh264 like how it's done in freedesktop-sdk.

**Comment by rathann** [comment]
> The thing is, they both provide same soname libraries. Whatever the setup, it should be so that everything switched to loading OpenH264 library when present.

You can achieve that by making openh264 parallel installable putting `libopenh264.so.7` in `%{_libdir}/openh264/` and dropping an appropriate config into `/etc/ld.so.conf.d`.

**Comment by nanonyme** [comment]
That might actually even be safer than removal. Then if you have OpenH264 with different soname, video frameworks fallback to noopen264.

**Comment by travier** [comment]
Make sure to send all of those suggestions to the noopenh264 maintainers (maybe via a bugzilla) otherwise they likely won't see it here.

**Comment by nanonyme** [comment]
I think you mean OpenH264 maintainers?

**Comment by travier** [comment]
https://pagure.io/workstation-ostree-config/pull-request/508#comment-202306

**Comment by nanonyme** [comment]
Yeah, this was expected. You can't just drop a package in the middle of dep chain without removing all reverse dependencies

**Comment by OptimoSupreme** [comment]
So now that this has been figured out, can I ask what the intended method is for adding openh264 functionality to Firefox on a baseline Silverblue?

**Comment by travier** [comment]
https://github.com/fedora-silverblue/issue-tracker/issues/536#issuecomment-1974780009

**Comment by travier** [comment]
It looks like it's unlikely that we'll be able to remove this package from the images so I'll close this issue.
