### ISSUE TITLE
Location for treefiles/manifests used in composing ostree

### ISSUE THREAD

**Issue by jmpolom** [fedora-silverblue/issue-tracker#538]
Where can the treefiles/manifests be found that are used to generate the official ostrees used for Silverblue?

~~At one point these were (somewhat buried) on pagure but discoverable. Now, they no longer seem to be there and I am unable to find them after looking for many hours.~~ I have located the source manifests/treefiles/compose config repo: https://pagure.io/workstation-ostree-config

~~Please provide a link to where these are maintained now.~~ I would appreciate if this info was added prominently into documentation somewhere and kept up to date with current locations.

Users should not have to go dumpster diving for this.

**Comment by travier** [comment]
The location has never changed and is linked from https://github.com/fedora-silverblue#contributing

Can you clarify where you would like to have this?

**Comment by travier** [comment]
I've copied all the links in https://github.com/fedora-silverblue/issue-tracker/pull/541

**Comment by travier** [comment]
Ideally we would recentralize everything under a single namespace on GitLab:
- https://github.com/fedora-silverblue/issue-tracker/issues/334
- https://gitlab.com/fedora/ostree/sig/-/issues/4

But this hasn't happened yet as we need to migrate all the issues, etc. and that takes time.
