### ISSUE TITLE
Login problems with LUKS volumes

### ISSUE THREAD

**Issue by Minter1** [fedora-silverblue/issue-tracker#54]
While in F31 I had changed by LUKS password. I think by using the following:
`
sudo cryptsetup luksChangeKey /dev/sdX`

I then upgraded from Silverblue F31 to F32 and all was well. After the first update that required reboot I was unable to login. The LUKS password worked but the login didn't and I would be returned to the login screen after a delay.

I have found that if I enter the old LUKS password, get a login failure, and then enter the new LUKS password then everything works and I am able to login.

So I am not sure if I had just entered an incorrect LUKS password after the upgrade and therefore this not an upgrade/F32 issue or a LUKS issue?

In addition, now I receive an error when I check for updates: 

> Unable to get list of updates: Error calling the StartServiceByName for org.freedesktop,fwpd: timeout was reached

Also, I am not sure if this is related?

**Comment by halfline** [comment]
Can you edit `/etc/gdm/custom.conf` to set `Enable=true` in the `[debug]` section, reboot, reproduce, and then post the full output of `# journalctl -b` ?

**Comment by Minter1** [comment]
Hi, thanks for your response. Full output attached as requested:

[SB F32 startup journal.txt](https://github.com/fedora-silverblue/issue-tracker/files/4580255/SB.F32.startup.journal.txt)

**Comment by alex-theoto** [comment]
Your journal show the same error on a specific time. Nothing helpful...

**Comment by travier** [comment]
Closing as this has been inactive and waiting on info for a long time.
