### ISSUE TITLE
GDM broken after switching Gnome session to X11 once

### ISSUE THREAD

**Issue by caemputer** [fedora-silverblue/issue-tracker#542]
**Describe the bug**
Both X11 and Wayland Gnome sessions boot in to a black screen and spam journalctl repeatedly with these lines until gdm is stopped:
`Mär 28 16:03:35 silverblue /usr/libexec/gdm-wayland-session[2116]: invalid input: `
`Mär 28 16:15:23 silverblue /usr/libexec/gdm-x-session[3104]: invalid input: `

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Use the Gnome Wayland session
2. Log out
3. Select the Gnome X11 session
4. Log in

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240328.n.0 (2024-03-28T08:09:28Z)
               BaseCommit: f726d0be3361a42a8ac175b08851de67a2d97c9c01ee130a3abcd32720120f9c
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
      RemovedBasePackages: firefox firefox-langpacks 124.0.1-2.fc40
                           gnome-disk-utility 46.0-1.fc40 gnome-system-monitor 46~rc-1.fc40
                           gnome-terminal-nautilus gnome-terminal 3.50.1-6.fc40
                           gnome-tour 45.0-5.fc40 toolbox 0.0.99.5-8.fc40
                           yelp 2:42.2-5.fc40
          LayeredPackages: akmod-nvidia distrobox langpacks-de xorg-x11-drv-nvidia
```
I've also tried without any modifications of the base image
```
State: idle
BootedDeployment:
● fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240328.n.0 (2024-03-28T08:09:28Z)
                   Commit: f726d0be3361a42a8ac175b08851de67a2d97c9c01ee130a3abcd32720120f9c
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
```
This problem was initially observed with the Fedora 39 image, I updated to 40 in hopes of maybe resolving this issue through that but it did not help.

**Additional context**

Here's the dmesg output when trying to launch the Wayland session: [dmesg.log](https://github.com/fedora-silverblue/issue-tracker/files/14791882/dmesg.log)
And here is the output of journalctl -xb: [journalctl.log](https://github.com/fedora-silverblue/issue-tracker/files/14791886/journalctl.log)

I've also tried hunting down any cache or config directories of gdm and removing them. This also did not resolve the issue.

**Comment by chrisawi** [comment]
> Mär 28 16:03:35 silverblue /usr/libexec/gdm-wayland-session[2116]:  [a] | silverblue                | fedora:fedora/40/x86_64/silverblue                
> Mär 28 16:03:35 silverblue /usr/libexec/gdm-wayland-session[2116]:  [b] | devel                     | docker.io/library/archlinux:latest                
> Mär 28 16:03:35 silverblue /usr/libexec/gdm-wayland-session[2116]:  [c] | devel-stable              | docker.io/library/debian:latest                   
> Mär 28 16:03:35 silverblue /usr/libexec/gdm-wayland-session[2116]:  [d] | general                   | docker.io/library/archlinux:latest  

Any idea what that output is from? Distrobox? And why is GDM seemingly running that instead of gnome-session?

Can you test with a new user account?

It might be helpful to enable GDM debug logging in `/etc/gdm/custom.conf`.

P.S. The journalctl `-x` flag just adds noise when sharing logs with others (and is pretty useless in general, imho).
