### ISSUE TITLE
Latest F39 release contains Kernel with broken Bluetooth

### ISSUE THREAD

**Issue by 0rzech** [fedora-silverblue/issue-tracker#545]
**Describe the bug**
Latest release contains Kernel 6.7.11, which has Bluetooth-related oops and hangs the system.

**To Reproduce**
1. Rebase to the latest release.
2. Reboot the system.
3. Log in to desktop environment.
4. Bluetooth "disappears" from the system.
5. System hangs when trying to reboot.

**Expected behavior**
Bluetooth works as expected.

**Screenshots**
N/A

**OS version:**
```
  fedora:fedora/39/x86_64/silverblue
                  Version: 39.20240402.0 (2024-04-02T00:39:43Z)
               BaseCommit: 634c8097165e6aab2baeaca6ae6d1ea2a7f11fba9f4955297bcf0fc2507047be
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
```

**Additional context**
> 6.7.11 also trigger oops around BT

https://lore.kernel.org/all/f52daf9a-f934-4756-8a94-e7e383fbcb85@straussaudio.ch/

Kernel 6.7.10 works fine for me.

**Comment by travier** [comment]
Please report a bug for the kernel in Fedora's Bugzilla: https://docs.fedoraproject.org/en-US/quick-docs/bugzilla-file-a-bug/

**Comment by 0rzech** [comment]
Done: https://bugzilla.redhat.com/show_bug.cgi?id=2272702 .

**Comment by 0rzech** [comment]
The issue does not occur in Kernel 6.8.4 from
```
● fedora:fedora/39/x86_64/silverblue
                  Version: 39.20240406.0 (2024-04-06T00:37:27Z)
               BaseCommit: cbe8469254d044f04e28fe77f04f95c31834d067bd63fe356c8edf227fda056b
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
```
