### ISSUE TITLE
speech-dispatcher and espeak-ng missing in Silverblue 40

### ISSUE THREAD

**Issue by tpopela** [fedora-silverblue/issue-tracker#555]
When rebasing to Silverblue 40, I've noticed that espeak-ng and speech-dispatcher packages were among the removed ones, which shouldn't happen, because they're needed for accessibility. Apparently the packages are included on the Fedora 40 Workstation ISO.

On SB 39, the espeak-ng is needed by speech-dispatcher-espeak-ng which is needed by speech-dispatcher, which is needed by python3-speechd which is needed by orca.

The requirement is still there - https://src.fedoraproject.org/rpms/orca/blob/f40/f/orca.spec#_36 and python3-speechd is part of SB40, so I suspect it broke with https://src.fedoraproject.org/rpms/speech-dispatcher/c/bde1d9d236eb13eb6ee516bb749633d2e9e443c5?branch=rawhide ?

**Comment by travier** [comment]
I indeed have (from 40.20240415.0 to 40.20240423.0 Kinoite):

```
Removed:
  dotconf-1.3-35.fc40.x86_64
  espeak-ng-1.51.1-8.fc40.x86_64
  libao-1.2.0-27.fc40.x86_64
  pcaudiolib-1.1-14.fc40.x86_64
  qt6-qtspeech-speechd-6.6.2-1.fc40.x86_64
  speech-dispatcher-0.11.5-3.fc40.x86_64
  speech-dispatcher-espeak-ng-0.11.5-3.fc40.x86_64
Added:
  openssh-askpass-9.6p1-1.fc40.2.x86_64
  speech-dispatcher-libs-0.11.5-5.fc40.x86_64
```

Looks like Orca should depend on speech-dispatcher ?

**Comment by travier** [comment]
They are likely included on the Workstation ISO because this updated RPM landed after the Final Freeze.

**Comment by travier** [comment]
And we had broken updates for Silverblue in the last few days, just when this landed.

**Comment by travier** [comment]
Either we update the dependency in Orca, or we update our comps group to explicitly list this package.

**Comment by travier** [comment]
We have a desktop-accessibility group where we could add that.

**Comment by travier** [comment]
Comps PR: https://pagure.io/fedora-comps/pull-request/959

**Comment by travier** [comment]
- F41: https://pagure.io/workstation-ostree-config/pull-request/510
- F40: https://pagure.io/workstation-ostree-config/pull-request/511

**Comment by travier** [comment]
On Kinoite 40:
```
Added:
  dotconf-1.3-35.fc40.x86_64
  espeak-ng-1.51.1-8.fc40.x86_64
  libao-1.2.0-27.fc40.x86_64
  pcaudiolib-1.1-14.fc40.x86_64
  qt6-qtspeech-speechd-6.6.2-1.fc40.x86_64
  slirp4netns-1.2.2-2.fc40.x86_64
  speech-dispatcher-0.11.5-5.fc40.x86_64
  speech-dispatcher-espeak-ng-0.11.5-5.fc40.x86_64
```
So looks like we're good again now. Thanks for the report!
