### ISSUE TITLE
change default for camera and imageviewer

### ISSUE THREAD

**Issue by userforsource** [fedora-silverblue/issue-tracker#557]
Change the defaults from cheese to snapshot and image viewer to loupe like what we have in workstation that has been replace this with the new ones from gnome. But same not happen in silverblue.

**Comment by chrisawi** [comment]
Silverblue matches the default apps from Workstation, but that doesn't currently have any effect on upgrades for flatpak apps. This is tracked in https://gitlab.com/fedora/ostree/sig/-/issues/8

**Comment by travier** [comment]
I've just done a fresh installation of Fedora 40 and those are already the default apps.

As @chrisawi said, we can not update existing installations yet, so you will have to install them manually.
