### ISSUE TITLE
Consider including Sushi, a quick previewer for Nautilus

### ISSUE THREAD

**Issue by metmarkosaric** [fedora-silverblue/issue-tracker#56]
[Sushi](https://gitlab.gnome.org/GNOME/sushi), a quick file previewer for Nautilus (Files), is not included on Silverblue. It's included in Fedora and in Gnome by default. 

It's a small integration that makes a big difference in terms of productivity and speed. You select a file and tap the space bar to see a larger preview. No need to open the file itself. 

I think it's worth considering to include Sushi in Nautilus in Fedora Silverblue too. Thanks!

**Comment by tpopela** [comment]
Thank you @metmarkosaric ! We looked at it and we won't put it in the base image as it brings too many dependencies, but we will try to flatpak it as it should work.

**Comment by metmarkosaric** [comment]
Sounds good @tpopela! A Flatpak version of Sushi and/or Nautilus will work too! Thanks!

**Comment by felipeborges** [comment]
A Sushi Flatpak is on the way to the fedora-testing flatpak repository https://bodhi.fedoraproject.org/updates/FEDORA-FLATPAK-2020-3a1fee0f7b

We are yet to decide whether Sushi will get included in the base image, offered to install in Nautilus once a user attempts to use it (press SPACE on a selected file), or simply be available in the repo for users to manually install it.

**Comment by metmarkosaric** [comment]
That's good to hear, thanks @felipeborges! 

@tpopela mentioned that there are too many dependencies so I guess that a prompt to install it once a user presses the space bar on a selected file is the second best option.

**Comment by tpopela** [comment]
Once the Flatpak will hit the stable repository I will add Sushi to the lorax config for Anaconda. For the updates we will have to figure out a general solution and not some apps specific ones.
