### ISSUE TITLE
On-screen keyboard in the installer

### ISSUE THREAD

**Issue by Evolto2019** [fedora-silverblue/issue-tracker#562]
**Is your feature request related to a problem? Please describe.**
It is hard to install Silverblue on a tablet without physical keyboard. For example, on a Surface 3 which has only 1 USB 3.0 port, with the Silverblue installation USB media plugged, there is no port left for a physical keyboard. And clicking a text box (e.g. LUKS password) in Anaconda won't activate the on-screen keyboard, making it almost impossible to complete the installation.

**Describe the solution you'd like**
Enable the on-screen keyboard during installation when a touchscreen is detected.

**Describe alternatives you've considered**
Allow users to access settings in Anaconda so that they can enable the on-screen keyboard manually or implement a live CD as described in https://github.com/fedora-silverblue/issue-tracker/issues/489 to achieve the same goal.

**Comment by travier** [comment]
This is likely an Anaconda feature request. It might be fixed with the new Web UI that is upcoming.

**Comment by travier** [comment]
This will be fixed when we add Live ISO support to Atomic Desktops. This is now tracked in https://gitlab.com/fedora/ostree/sig/-/issues/32 thus closing this one. Thanks for the report.
