### ISSUE TITLE
[rpm-ostree] error: Bus owner changed, aborting. This likely means the daemon crashed

### ISSUE THREAD

**Issue by boooooooaq** [fedora-silverblue/issue-tracker#566]
**Describe the bug**
When running rpm-ostree upgrade / install / uninstall / update I get almost every time:
error: Bus owner changed, aborting. This likely means the daemon crashed; check logs with `journalctl -xe`.

Full journalctl -xe output:
[https://pastebin.com/YzqRf72e](https://pastebin.com/YzqRf72e)

**To Reproduce**
What I did to reproduce this in a Boxes vm is the following:
Note: I only succeeded to reproduce it ones.
 
1. install all my layered pkg's: `rpm-ostree install btop distrobox gparted guestfs-tools libvirt-daemon-config-network libvirt-daemon-kvm openrgb python3-libguestfs qemu-kvm steam-devices timeshift virt-install virt-manager virt-top virt-viewer zsh` 
2. Follow [This](https://github.com/FilBot3/fedora-silverblue-gpu-passthrough) guide for PCI-Passthrough, in my case what I did in the vm:
2.1 `sudo rpm-ostree kargs \
  --append-if-missing="intel_iommu=on" \
  --append-if-missing="iommu=pt" \
  --append-if-missing="rd.driver.pre=vfio_pci" \
  --reboot
`
2.2 `sudo rpm-ostree initramfs \
  --enable \
  --arg="--add-drivers" \
  --arg="vfio-pci" \
  --reboot`

after the last step I get the error: Bus owner changed, aborting. This likely means the daemon crashed; check logs with `journalctl -xe`.

**Expected behavior**
rpm-ostree upgrade / installs / uninstalls successfully  

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240522.0 (2024-05-22T00:58:59Z)
               BaseCommit: f4e339b385beb28685580790296a05876b04c8dfde93f563531f508c7a0e861e
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
          LayeredPackages: btop distrobox gparted guestfs-tools libvirt-daemon-config-network libvirt-daemon-kvm openrgb python3-libguestfs qemu-kvm steam-devices timeshift virt-install virt-manager virt-top virt-viewer zsh
            LocalPackages: mullvad-vpn-2024.3-1.x86_64
                Initramfs: --add-drivers vfio-pci
```

**Additional context**
I still sometimes succeed to upgrade my system after enough reboots I would estimate my success rate on my actual system to be ~1/50.

It usually go's as follows:
```❯ rpm-ostree upgrade
2 metadata, 0 content objects fetched; 788 B transferred in 1 seconds; 0 bytes content written
Checking out tree 0c3e3bd... done
Enabled rpm-md repositories: rpmfusion-nonfree-nvidia-driver fedora updates copr:copr.fedorainfracloud.org:phracek:PyCharm google-chrome rpmfusion-nonfree-steam fedora-cisco-openh264 updates-archive
Importing rpm-md... done
rpm-md repo 'rpmfusion-nonfree-nvidia-driver' (cached); generated: 2024-05-21T08:54:29Z solvables: 29
rpm-md repo 'fedora' (cached); generated: 2024-04-14T18:51:11Z solvables: 74881
rpm-md repo 'updates' (cached); generated: 2024-05-23T01:04:16Z solvables: 14222
rpm-md repo 'copr:copr.fedorainfracloud.org:phracek:PyCharm' (cached); generated: 2024-03-18T11:54:41Z solvables: 14
rpm-md repo 'google-chrome' (cached); generated: 2024-05-22T20:54:18Z solvables: 3
rpm-md repo 'rpmfusion-nonfree-steam' (cached); generated: 2024-04-20T13:10:45Z solvables: 2
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2024-03-12T11:45:42Z solvables: 3
rpm-md repo 'updates-archive' (cached); generated: 2024-05-22T01:41:39Z solvables: 13161
Resolving dependencies... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
Generating initramfs... done
Writing OSTree commit... done
error: Bus owner changed, aborting. This likely means the daemon crashed; check logs with `journalctl -xe`.`
```
Also I use ext4 instead of btrs if that's of any important's in this case.

Any help would be appreciated!

**Comment by travier** [comment]
Please file an upstream issue for [rpm-ostree](https://github.com/coreos/rpm-ostree).
