### ISSUE TITLE
Bridging Matrix/IRC Silverblue rooms

### ISSUE THREAD

**Issue by returntrip** [fedora-silverblue/issue-tracker#57]
Can someone look into bridging the 2 rooms please?

I have asked in #fedora-admin but it seems they do not handle the bridges.

If you have the right contact name I would be happy to ask for help.

Update: it seems jwf from the commops team might be able to help. Will update this issue when I get a reply.

**Comment by returntrip** [comment]
@matthiasclasen would you be OK to give me (https://matrix.to/#/@jflory7:matrix.org) or jfw (https://matrix.to/#/@jflory7:matrix.org) admin access to the Matrix room so we can bridge it to its IRC counterpart?

**Comment by returntrip** [comment]
@tpopela is this something you could discuss with Matthias?

The alternative is to create a new Matrix room (with a slightly different name) amd communicate that to the users, but that would suck IMO.

Currently there are nearly 80 users in the Matrix room, I think it would be great to bring them into the Silverblue community 😃.

**Comment by tpopela** [comment]
I don't know anything about Matrix, nor used it. You can get in touch with Matthias on the #silverblue IRC channel and figure out what's needed.

**Comment by returntrip** [comment]
Yeah I just do not find him in the IRC channel (maybe cause I use Riot), i think his nick was mclasen, right?

**Comment by matthiasclasen** [comment]
I'm not a fan of bridging at all

**Comment by returntrip** [comment]
> I'm not a fan of bridging at all

I think IRC bridging with Matrix is quite good.

The only pain point is a frequent (every couple of days) request to authenticate the nick.

Have you had problem with Matrix in the specific or is it a general aversion to IRC bridging?

In any case I do not think we can bridge the existing room cause there an ownership issue.

**Comment by tpopela** [comment]
Closing as it was done yesterday.
