### ISSUE TITLE
Don't include non-fundamental/repleaceble apps by default

### ISSUE THREAD

**Issue by AleIlMagno** [fedora-silverblue/issue-tracker#571]
**Describe the bug**
Some apps, like Firefox, don't need to be preinstalled and, because Silverblue is image-based, you can't really uninstall "system" apps.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install Fedora Silverblue
2. ..

**Expected behavior**
No non-strictly-necessary and easy-to-install-later apps.

**OS version:**
Any

**Additional context**
It's the first thing I noticed after installing Silverblue, because of a bit of drama with Firefox, and also simply because I wanted a common hardened version of it (Librewolf). I'm not saying to include Librewolf by default, but for things like browsers and other non-system stuff there are many alternatives avaiable as flatpaks that somone would like to use instead of the one already installed.

**Comment by travier** [comment]
See:
- https://github.com/fedora-silverblue/issue-tracker/issues/288
- https://gitlab.com/fedora/ostree/sig/-/issues/3
