### ISSUE TITLE
Bad shim signature in 40.20240617.0 deployment

### ISSUE THREAD

**Issue by 0rzech** [fedora-silverblue/issue-tracker#573]
**Describe the bug**
The latest Silverblue deployment is unbootable, because of
```
error: ../../grub-core/kern/efi/sb.c:182:bad shim signature.
error: ../../grub-core/loader/i386/efi/linux.c:258:you need to load the kernel first.

Press any key to continue...
```

**OS version:**
```
fedora:fedora/40/x86_64/silverblue
                Version: 40.20240617.0 (2024-06-17T00:42:18Z)
             BaseCommit: c7bdc9ecab9df0609da0e04b685ca7608174e6cb81d49e1cf4b70b798557018e
           GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
```

**Additional context**
The system has secure boot enabled, obviously.

**Comment by 0rzech** [comment]
Ok, I guess this is another variant of #120 and #543 ?

**Comment by 0rzech** [comment]
Yep, this is another variant of the aforementioned issues. Workaround from https://github.com/fedora-silverblue/issue-tracker/issues/543#issuecomment-2048350047 helped.

**Comment by juhp** [comment]
I just ran into this too - so am I now forced to run though workaround commands to get later deployment working?

**Comment by 0rzech** [comment]
You have to run those commands.

Yeah, perhaps it would bebetter not to close this issue, so others affected will have it easier to find it.

**Comment by travier** [comment]
I've updated the title of https://github.com/fedora-silverblue/issue-tracker/issues/543 to mention this error. Closing to keep things in a single place.

**Comment by juhp** [comment]
Those commands worked for me

**Comment by dubst3pp4** [comment]
I've just rolled back to image `40.20240614.0`. Can I expect that there will be a new image soon, so that I can skip `40.20240617.0`? Or do I have to run the mentioned commands anyway?

**Comment by 0rzech** [comment]
@dubst3pp4 You have to run those commands. AFAIU, updating bootloader, shims etc. is currently scheduled for F41 and perhaps will be backported to F40: https://github.com/fedora-silverblue/issue-tracker/issues/120#issuecomment-2082215645 .

@JCenatus AFAIU, because the problem is with signatures, any deployment past `40.20240617.0` will not work until #120 and #543 are solved, or until you apply the workaround.

**Comment by juhp** [comment]
@JCenatus there won't be a fix (anytime soon by the looks of it) - I was also "scared" initially, but it's actually just copying a few deployed efi files over from /usr to /boot, but yeah.

**Comment by 0rzech** [comment]
@JCenatus I think @juhp's interpretation of the situation is on point. The workaround makes a backup copy of replaced files and then copies newer versions of those files from current deployment to efi partition. In future this will happen automatically, along with updating the bootloader itself.

I didn't test that, but perhaps disabling secure boot might allow you to skip the workaround, but I think it's not worth it to disable secure boot, given the workaround is simple and has helped me and other people.

In general, I recommend reading the linked issues and their comments to better understand what's happening and what to expect... and what not to do. 😉

**Comment by dubst3pp4** [comment]
@juhp @0rzech Thanks for the detailed explanation! Although I'm with @JCenatus, I will try the mentioned steps...

**Comment by dubst3pp4** [comment]
> @juhp @0rzech Thanks for the detailed explanation! Although I'm with @JCenatus, I will try the mentioned steps...

worked without problems. Thanks again.

**Comment by travier** [comment]
Let's keep things in a single place: https://github.com/fedora-silverblue/issue-tracker/issues/543
