### ISSUE TITLE
`rpm -qi basesystem`  shows the update date not installed date

### ISSUE THREAD

**Issue by tazihad** [fedora-silverblue/issue-tracker#575]
`rpm -qi basesystem` shows the update date to new image. But it should show the first time installed date of the system.  

Here the `Install Date` should be the date I have installed the system. Instead it shows the last update date. And now there's no way to know the exact date I have installed Atomic system.

```
rpm -qi basesystem
Name        : basesystem
Version     : 11
Release     : 20.fc40
Architecture: noarch
Install Date: Tuesday 18 June 2024 06:34:57 AM
Group       : Unspecified
Size        : 0
License     : LicenseRef-Fedora-Public-Domain
Signature   : RSA/SHA256, Tuesday 23 January 2024 06:17:23 AM, Key ID 0727707ea15b79cc
Source RPM  : basesystem-11-20.fc40.src.rpm
Build Date  : Tuesday 23 January 2024 06:11:15 AM
Build Host  : buildvm-x86-20.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
Bug URL     : https://bugz.fedoraproject.org/basesystem
Summary     : The skeleton package which defines a simple Fedora system
Description :
Basesystem defines the components of a basic Fedora system
(for example, the package installation order to use during bootstrapping).
Basesystem should be in every installation of a system, and it
should never be removed. As the package has no content, it is Public Domain.
 zihad@fedora  ~  

```

**Comment by travier** [comment]
By design, rpm-ostree builds each version from scratch. This means that RPMs are always freshly installed for each update and `rpm` will thus only show you the date the update has been composed (created).

You should use something else to find out when your system was installed. Maybe look at the Anaconda log in `/root/`?
