### ISSUE TITLE
Fedora Contributor Badges

### ISSUE THREAD

**Issue by returntrip** [fedora-silverblue/issue-tracker#58]
Was chatting with mattdm on the AMA today and asked how can contributors to the Silverblue GitHub repo get some badges for their PRs to the Silverblue docs/site. He suggested this: 

"<m​attdm> Stefano -- on badges.... I think this could be done if there were a hook on the github site feeding things into fedmsg. Or, someone on the silverblue team could create badges to be awarded manually."

Who could help with this?

**Comment by tpopela** [comment]
I really don't know. If anyone figures out how to feed the stuff from GitHub to fedmsg, then I might do it (how would one map the GitHub accounts to FAS?), but I really don't have capacity to do this.

**Comment by felipeborges** [comment]
It seems that the FAS API has an endpoint for user searching based on email https://fedora-infra.github.io/fas3-api-haskell/Fedora-FAS-Types-SearchType.html#t:SearchType

The github API allows to retrieve the user's email address https://developer.github.com/v3/users/

So basically:
1. retrieve the user email from the github API
2. Feed it to the FAS API to get the user id.
3. Award the user id.

**Comment by travier** [comment]
Nothing really happened here for a while so I'll close this. We will ideally move to the next Fedora Git forge once ready and the badge support will be plugged there for all Fedora projects and not just us.
