### ISSUE TITLE
Not enough space allocated to the default boot partition

### ISSUE THREAD

**Issue by trafotin** [fedora-silverblue/issue-tracker#580]
**Describe the bug**
After enough images are pinned, Silverblue users are presented with a warning that their boot partition is either running low or running out of memory. The boot partition is given 629 MB, both in the case of a 500 GB of SSD and a 1 TB NVMe.

There was speculation if it was because [1024 MB was hinted for the boot partition in the documentation's screenshots](https://docs.fedoraproject.org/en-US/fedora-silverblue/installation/#manual-partition) for manual partitioning.

The only way to fix the boot partition is to either delete images or resize the boot partition using something like GParted. In my case, I deleted my pinned images. [What I did in detail](https://universal-blue.discourse.group/t/boot-partition-is-running-low-on-space/1477/12).

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Pin at least 2 images using ostree
2. GNOME Disk Usage Analyzer (Baobab) delivers notification that the boot partition is running out of or is out of space.

**Expected behavior**
At least 1024 MB needs to be allocated to the boot partition. If this is true, does the default behavior of Anaconda need to change?

There might need to tooling to make managing images easier. In the case of uBlue, this could be done through ujust or a GUI tool.

**Screenshots**
![Screenshot from 2024-07-05 23-35-56](https://github.com/fedora-silverblue/issue-tracker/assets/108948841/186094ac-5b06-4f89-9cf3-bf67fe79b4ac)
![Screenshot from 2024-07-03 23-07-12](https://github.com/fedora-silverblue/issue-tracker/assets/108948841/d83de2cd-a4d7-4a65-b22d-ba2fedd184c5)

**OS version:** Universal Blue Bluefin (Fedora 40 GNOME)
```
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 8h ago
BootedDeployment:
● ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx-nvidia:stable
                   Digest: sha256:1ab513c88dea2aacb07c9405bf9e1a0b7400d2788352218e70413063fbb3c66b
                  Version: 40.20240702.0 (2024-07-02T20:02:06Z)
          LayeredPackages: adobe-source-sans-pro-fonts adobe-source-serif-pro-fonts
                           mullvad-vpn pipx
            LocalPackages: veracrypt-1.26.7-1.x86_64

```

**Additional context**
[Extended discussion from the uBlue forums](https://universal-blue.discourse.group/t/boot-partition-is-running-low-on-space/1477).

**Comment by travier** [comment]
As we use a distinct `/boot` partition, you will be limited in the amount of deployments that you can keep pinned.

If you want to keep more deployments pinned then you need to setup a bigger `/boot` partition on installation.

There were also discussions around increasing the size of the ESP partition: https://fedoraproject.org/wiki/Changes/BiggerESP

**Comment by travier** [comment]
New installations should have a 600MB ESP and 1GB boot partition. If you want to pin more boot entries then you'll have to increase the size of the partition at installation time.

As there isn't much we can do to fix existing systems (apart from reinstalling them), I'll close this issue.
