### ISSUE TITLE
Games crashing when there's a pending update

### ISSUE THREAD

**Issue by BuonHobo** [fedora-silverblue/issue-tracker#584]
**Describe the bug**
I'm not 100% sure about it, but over months of usage I've noticed a correlation between system instability (that I experience as videogames crashing) and having a pending update.
I set up rpm-ostree to automatically stage updates, and whenever I see that videogames (flatpak steam) are crashing there's always a pending update in rpm-ostree status.
When I reboot into the new deployment everything is stable again.
What can I do to make sure that there's an actual correlation?

**To Reproduce**
1. Set rpm-ostreeed.conf to staging
2. Boot your computer, wait for a couple hours to make sure that there's a pending update
3. Try to play a heavy videogame from flatpak steam
4. The game is gonna crash within half an hour of more intensive gameplay, even if you restart it or switch game
5. After a reboot, no crash should be experienced

**Expected behavior**
The pending updates should not influence the system stability.

**Screenshots**
N.A.

**OS version:**
```
❯ rpm-ostree status -b
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: last run 1h 25min ago
BootedDeployment:
● fedora:fedora/40/x86_64/silverblue
                  Version: 40.20240728.0 (2024-07-28T01:03:15Z)
               BaseCommit: 1caf22c407ab4fe91c4316cd80e1170b724a44d7ab2c4c0c60b5c2b9c2df08a0
             GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
      RemovedBasePackages: gnome-software gnome-software-rpm-ostree 46.3-1.fc40
          LayeredPackages: ddcutil gcc gtk4-devel moby-engine python3-devel tailscale
            LocalPackages: kathara-3.7.6-1.fc38.x86_64

AvailableUpdate:
        Version: 40.20240729.0 (2024-07-29T01:50:19Z)
         Commit: 9252e311174c1a52908de9b5661f1ab22632a1a45223099eb0309017ea03d6c3
   GPGSignature: Valid signature by 115DF9AEF857853EE8445D0A0727707EA15B79CC
           Diff: 1 upgraded
```

**Comment by travier** [comment]
Is the update applied while the game is running? It might apply memory / disk / cpu pressure on top of the game running and triggering an OOM.

**Comment by BuonHobo** [comment]
No, seems to happen when the next deployment is pending. It's probably unrelated and this is just a fake correlation, but I'd like to rule it out so I can start looking into some other cause. Do you ever experience game instability that goes away after a reboot?

**Comment by travier** [comment]
I've been playing The Witcher 3 recently and I had some freezes, but I haven't been able to pin that to something specific. It's also common as reported in https://github.com/ValveSoftware/Proton/issues/607.

I haven't seen any other game crashes in a while.

**Comment by BuonHobo** [comment]
I haven't been able to reproduce this, I guess it was related to something else. I'll close this issue and sorry for wasting people's time
