### ISSUE TITLE
New Package Request: Zenity

### ISSUE THREAD

**Issue by richiedaze** [fedora-silverblue/issue-tracker#588]
Please try to answer the following questions about the package you are requesting:

1. Is the package installed by default in Fedora Workstation? If it is not, we will ask you to [open an issue in the issue tracker](https://pagure.io/fedora-workstation/issues) for the [Fedora Workstation Working Group](https://docs.fedoraproject.org/en-US/workstation-working-group/).

yes

3. What, if any, are the additional dependencies on the package? What is the output of this command on a system without overrides or locally installed packages:

```bash
rpm-ostree install --dry-run <package>
```

zenity-4.0.2-1.fc40.x86_64

4. What is the size of the package and its dependencies?

```bash
rpm -qi <package>
```

Size : 3.2 M 
No dependencies

5. What problem are you trying to solve with this package? Or what functionality does the package provide?

Simple dialog box for scripts

6. Can the software provided by the package be run from a container? Explain why or why not.

yes, but also needs to install GTK dependencies.

8. Can the tool(s) provided by the package be helpful in debugging container runtime issues?

yes

9. Can the tool(s) provided by the package be helpful in debugging networking issues?

yes

11. Is it possible to layer the package locally via `rpm-ostree install <package>`? Explain why or why not.

Yes, but I would like to minimize overlayering the OS

**Comment by travier** [comment]
> 1. Is the package installed by default in Fedora Workstation? If it is not, we will ask you to [open an issue in the issue tracker](https://pagure.io/fedora-workstation/issues) for the [Fedora Workstation Working Group](https://docs.fedoraproject.org/en-US/workstation-working-group/).
> 
> yes

Are you sure about that? I don't see it listed in the comps. I'll have to do a clean install to confirm.

**Comment by richiedaze** [comment]
dnf repoquery --requires anaconda-live.noarch
```sh
Last metadata expiration check: 0:33:54 ago on Sat 10 Aug 2024 04:12:24 PM CDT.
/usr/bin/bash
anaconda-gui = 40.22.3-1.fc40
usermode
xisxwayland
zenity
```

**Comment by travier** [comment]
So that's an "artifact" of the fact that all Workstation installations includes the Anaconda installer by default even though they don't need it anymore once installed. It's not explicitly included (thus why we don't have it).

**Comment by travier** [comment]
Related discussion in https://pagure.io/fedora-kde/SIG/issue/352
