### ISSUE TITLE
rpm-ostree-2024.7-1.fc40 breaks AppImage support for Silverblue 40 (dropping fuse(2))

### ISSUE THREAD

**Issue by Mershl** [fedora-silverblue/issue-tracker#589]
**Describe the bug**
`rpm-ostree 2024.7-1.fc40` drops the `fuse` dependency leading to a removal of `fuse` in Silverblue 40.
Changelog: `- Require fuse3 as ostree now uses it`
```
Removed:
  fuse-2.9.9-21.fc40.x86_64
```

A sideeffect of the `fuse` removal is that AppImages break respectivly AppImages no longer work out-of-the-box in Silverblue 40.

**Screenshots**
![image](https://github.com/user-attachments/assets/b1da3b38-1d6a-40ee-b769-f8811a5f04d7)

**OS version:**
affected: `40.20240819.0`
unaffected: `40.20240818.0`

**Comment by travier** [comment]
PR for F40: https://pagure.io/workstation-ostree-config/pull-request/553

**Comment by travier** [comment]
rpm-ostree change dropping the dependency: https://src.fedoraproject.org/rpms/rpm-ostree/c/3c602a23787fd2df873c0b18df3133c9fec4b66a?branch=rawhide

**Comment by travier** [comment]
I've filled https://gitlab.com/fedora/ostree/sig/-/issues/50 for the larger discussion.

This should be fixed with tomorrow's build in Fedora 40.

**Comment by zrooda** [comment]
@travier
Silverblue 41 beta includes `fuse-2.9.9-22.fc41.x86_64` but misses `fuse-libs`, breaking AppImage support again.

**Comment by travier** [comment]
So which one do we need? Both?

**Comment by travier** [comment]
https://pagure.io/workstation-ostree-config/pull-request/574

**Comment by zrooda** [comment]
Epic speed, thanks! 🥇

**Comment by travier** [comment]
Note: FUSE2 will be dropped in Fedora 44: https://gitlab.com/fedora/ostree/sig/-/work_items/50
