### ISSUE TITLE
Can't login in GDM after upgrade to Silverblue 32

### ISSUE THREAD

**Issue by MatteoNardi** [fedora-silverblue/issue-tracker#59]
I had a working Silverblue 31 installation. I upgraded to Silverblue 32 using Gnome Software.
On reboot it seems to have an issue mounting the home directory:
`Timed out waiting for device /dev/mapper/fedora-home.file`
It eventually gets to the GDM login screen (with the correct list of users), but touchpad, mouse and keyboard don't work (Keyboard was working during boot, when I pressed ESC in Plymouth).

Rolling back to Silverblue 31 works.
After rollback, I tried to upgrade with terminal using `rpm-ostree rebase`. The result was the same.

The laptop is an Asus F552C with a Nvidia card. The original installation was Silverblue 30. So far rebasing worked fine.

[journalctl_boot_log.txt](https://github.com/fedora-silverblue/issue-tracker/files/4616014/journalctl_boot_log.txt)

```
[matteo@localhost ~]$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/31/x86_64/silverblue
                   Version: 31.20200512.0 (2020-05-12T01:47:10Z)
                BaseCommit: c71abaad192d0a772609ecff41ccc3e954fcfaf2499fbe036de482529d8edec0
              GPGSignature: Valid signature by 7D22D5867F2A4236474BF7B850CB390B3C3359C4
           LayeredPackages: ansible fedora-workstation-repositories net-tools nmap tmux vim

  ostree://fedora:fedora/32/x86_64/silverblue
                   Version: 32.20200512.0 (2020-05-12T01:40:56Z)
                BaseCommit: d02c384afbb00ee59a5ebcce380339329c1371637359d42fb82577065773dba7
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
           LayeredPackages: ansible fedora-workstation-repositories net-tools nmap tmux vim

```
Let me know if there is anything you want me to do before I try a fresh install.

**Comment by tpopela** [comment]
I really have no idea. @cgwalters @dustymabe ?

**Comment by cgwalters** [comment]
What's the output of
```
$ cat /etc/fstab
```
?

The `.file` at the end of `/dev/mapper/fedora-home.file` looks strange...my best guess is something went wrong with your LVM configuration.

**Comment by MatteoNardi** [comment]
Sorry, the `.file` suffix was never there, I made an error while copy&pasting.

```
[matteo@localhost ~]$ cat /etc/fstab 

#
# /etc/fstab
# Created by anaconda on Fri Jun 14 18:03:24 2019
#
# Accessible filesystems, by reference, are maintained under '/dev/disk/'.
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info.
#
# After editing this file, run 'systemctl daemon-reload' to update systemd
# units generated from this file.
#
/dev/mapper/fedora-root /                       ext4    defaults        1 1
UUID=cd37e06a-1b13-4a55-88cd-5c45a5075e05 /boot                   ext4    defaults        1 2
UUID=2F69-3FA8          /boot/efi               vfat    umask=0077,shortname=winnt 0 2
/dev/mapper/fedora-home /home                   ext4    defaults        1 2
/dev/mapper/fedora-swap none                    swap    defaults        0 0
```

I tried booting into text mode with Grub (runlevel 3).
After login, `ls /dev/fedora` only gives me `root` and `swap`.
If I wait for 14 minutes, I get the following journal entry and `home` appears. 
```
22:46:18 localhost.localdomain lvm[1281]:   3 logical volume(s) in volume group "fedora" now active
```
After this, I could login in Gdm with:
```
sudo mount /var/home
sudo systemctl start gdm.service
```
Everything seems to work fine and I'm writing this post from the laptop.
If I reboot, I get the same timeout error.

Journal logs: [journalctl.txt](https://github.com/fedora-silverblue/issue-tracker/files/4624623/journalctl.txt)

I find it really strange that during the 14 minutes, I got new device events even if I didn't touch anything.
When I tried LVM commands (like `lvs` or `lvscan`) it complained about not being able to lock. The `--nolocking` flag worked.

I'll keep you updated on my quest for truth.

**Comment by MatteoNardi** [comment]
It was a bug in systemd/udev:
https://github.com/systemd/systemd/issues/15739

RedHat bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1830896#c6

The issue has already been fixed, I'll just delay my upgrade.
Feel free to close this issue.

**Comment by MatteoNardi** [comment]
I've upgraded from 31 to 33 without any issue.
Keep on the good work.
