### ISSUE TITLE
systemd-tmpfiles: errors when creating files

### ISSUE THREAD

**Issue by A6GibKm** [fedora-silverblue/issue-tracker#594]
Running 
```
sudo systemd-tmpfiles --create
```

Will result in 
```
/usr/lib/tmpfiles.d/var.conf:21: Duplicate line for path "/var/lib", ignoring.
"/home" already exists and is not a directory.
"/srv" already exists and is not a directory.
"/root" already exists and is not a directory.
```

Besides the warning I don't think this really poses an issue, feel free to close if this is a non-issue or OK as-is.

**Comment by travier** [comment]
You should not run `systemd-tmpfiles` commands without specifying a specific config to apply.

What do you actually want to do? I'll close this issue as there is nothing to fix here.

**Comment by A6GibKm** [comment]
Since I use systemd-sysext quite liberally, I have a file

```
$ cat /etc/tmpfiles.d/run-extensions.conf 
d /run/extensions :0755 - :root
```

naturally, you have to run `systemd-tpmfiles` for the tpmdir to be created after creating the config file above. While the warning above are not really a problem for this purpose, I wonder if there is something that could be improved.

**Comment by travier** [comment]
Then you run `systemd-tmpfiles --create run-extensions.conf` instead.
