### ISSUE TITLE
Login screen scaled to 125% (after login it respects the 100% setting) - Silverblue 41

### ISSUE THREAD

**Issue by alvaroburns** [fedora-silverblue/issue-tracker#598]
**Describe the bug**
When I start/restart the laptop, the login screen is scaled to 125%. The system was scaled after the rebase from Silverblue 40 to 41, but after setting it to 100%, only the login screen remains on 125%.

**To Reproduce**
Rebase from Silverblue 40 to 41.

**Expected behavior**
The GDM login screen scales to 100%.

**Screenshots**

**OS version:**
```
$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/41/x86_64/silverblue
                  Version: 41.20240917.n.0 (2024-09-17T08:32:32Z)
               BaseCommit: 8cc8df7239dd18cfad4e22deae794573feb2238cc062be95535d08b811447635
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: firefox firefox-langpacks 130.0-5.fc41 gnome-system-monitor 47~beta-1.fc41
                           gnome-tour 46.0-3.fc41 yelp 2:42.2-6.fc41

```

**Additional context**
This are the details from System Details on Settings:

# System Details Report
---

## Report details
- **Date generated:**                              2024-09-17 18:53:40

## Hardware Information:
- **Hardware Model:**                              Lenovo IdeaPad Flex 5 14IIL05
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-1035G1 × 8
- **Graphics:**                                    Intel® UHD Graphics (ICL GT1)
- **Disk Capacity:**                               256.1 GB

## Software Information:
- **Firmware Version:**                            ECCN36WW
- **OS Name:**                                     Fedora Linux 41.20240917.n.0 (Silverblue Prerelease)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.0-63.fc41.x86_64

**Comment by alvaroburns** [comment]
I installed GDM Settings to resolve this. Looks like a problem on my system only. Closing this issue.

**Comment by alvaroburns** [comment]
I installed GDM Settings to resolve this. Looks like a problem on my system only. Closing this issue.

**Comment by khaerunsituncu** [comment]
Hi I also experienced a 125% sceeren scale login drive, what is the solution ?

**Comment by juhp** [comment]
(Interesting after upgrading to SB41 I noticed my scaling was set to 125% which affected my external monitor - I don't know if I had such a setting lying around. After resetting to 100% my monitor is okay but my laptop display seems smaller than before when mirroring displays. It would seem surprising if this was SB specific though.)
