### ISSUE TITLE
Sound does not work after start/restart (Silverblue 41)

### ISSUE THREAD

**Issue by alvaroburns** [fedora-silverblue/issue-tracker#599]
**Describe the bug**
When I login to the system the sound does not work. After clicking the mute/unmute key, everything comes back to normal.

**To Reproduce**
Rebase from Silverblue 40 to 41.
Login.
Try to play sound from any app.

**Expected behavior**
Sound working normally after login if the system is not muted.

**OS version:**
```
$ rpm-ostree status -b
State: idle
BootedDeployment:
● fedora:fedora/41/x86_64/silverblue
                  Version: 41.20240917.n.0 (2024-09-17T08:32:32Z)
               BaseCommit: 8cc8df7239dd18cfad4e22deae794573feb2238cc062be95535d08b811447635
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: firefox firefox-langpacks 130.0-5.fc41 gnome-system-monitor 47~beta-1.fc41
                           gnome-tour 46.0-3.fc41 yelp 2:42.2-6.fc41

```

**Additional context**
This are the details from System Details on Settings:

# System Details Report
---

## Report details
- **Date generated:**                              2024-09-17 19:06:56

## Hardware Information:
- **Hardware Model:**                              Lenovo IdeaPad Flex 5 14IIL05
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-1035G1 × 8
- **Graphics:**                                    Intel® UHD Graphics (ICL GT1)
- **Disk Capacity:**                               256.1 GB

## Software Information:
- **Firmware Version:**                            ECCN36WW
- **OS Name:**                                     Fedora Linux 41.20240917.n.0 (Silverblue Prerelease)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.0-63.fc41.x86_64

**Comment by travier** [comment]
It could pipewire, the kernel driver, the app you are using, etc. It would be good to try to pin point which part is not working.

**Comment by alvaroburns** [comment]
> It could pipewire, the kernel driver, the app you are using, etc. It would be good to try to pin point which part is not working.

Hi! I don't think it is an app specific problem. How can I check the other options? I'm not exactly a tech person, but if you point me out how to do it...
Thanks!

**Comment by travier** [comment]
I saw you posted in the forum as well: https://discussion.fedoraproject.org/t/silverblue-41-is-great-already-two-small-issues-gdm-and-audio/131351

It's probably where you'll get the most help to investigate more.

**Comment by alvaroburns** [comment]
> I saw you posted in the forum as well: https://discussion.fedoraproject.org/t/silverblue-41-is-great-already-two-small-issues-gdm-and-audio/131351
> 
> It's probably where you'll get the most help to investigate more.

Ok. Thank you!

**Comment by alvaroburns** [comment]
There are more people having the same issue. See: https://discussion.fedoraproject.org/t/fedora-41-sound-working-only-on-external-monitor/131767

**Comment by laxman20** [comment]
This is being tracked in pipewire https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4084

**Comment by alvaroburns** [comment]
> This is being tracked in pipewire https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/4084

Thanks!

**Comment by alvaroburns** [comment]
The latest pipewire update to version 1.2.5 resolved this issue!
