### ISSUE TITLE
Include git package in the base image

### ISSUE THREAD

**Issue by cverna** [fedora-silverblue/issue-tracker#6]
Silverblue provides git by default but some command are not working.
```
[cverna@blue]  [develop] $ git add -p production.ini 
git: 'add--interactive' is not a git command. See 'git --help'.
```

Looking at https://bugzilla.redhat.com/show_bug.cgi?id=1337352 it seems that the installation is missing some files under `/usr/libexec/git-core/`

**Comment by cverna** [comment]
Oh ok the base tree contains git-core and not git, so the perl scripts are not installed. Could we consider install git instead of git-core ?

**Comment by tpopela** [comment]
Adding it would mean to add the following to the base image as well:

git-2.26.0-1.fc32.x86_64
git-core-doc-2.26.0-1.fc32.noarch
perl-Error-0.17029-1.fc32.noarch
perl-Git-2.26.0-1.fc32.noarch
perl-TermReadKey-2.38-6.fc32.x86_64

As we ship git in Workstation by default as well I would be in favor. On the other hand we are trying to move users towards using Toolbox for development, so I'm not sure what to do here. Maybe Colin or Dusty might shade some light on why only the git-core is included.

**Comment by cgwalters** [comment]
It was the last thing depending on Perl last I looked...

But Git upstream is at least slowly solving this by dropping the Perl dependency.

**Comment by cgwalters** [comment]
Originally: https://bugzilla.redhat.com/show_bug.cgi?id=1161251

**Comment by mildred** [comment]
I always had `gitk git-gui git-subtree` overrides, and lastly, I could not update to newer fedora 31 or fedora 32 because of the following error:

```
Forbidden base package replacements:
  git-core 2.25.3-1.fc31 -> 2.25.4-1.fc31 (updates)
```
or
```
Forbidden base package replacements:
  git-core 2.26.0-1.fc32 -> 2.26.2-1.fc32 (updates)
```

(error message is truncated too, see https://github.com/coreos/rpm-ostree/issues/1989#issuecomment-620240298 )

I'm upgrading from Fedora 31.20200413.0

I don't know what happened, but I'd suggest either remove git entirely from base image, and use the wonderful package layering to get it if you need, or include all the git packages and not just git-core.

**Comment by jlebon** [comment]
The issue you're hitting specifically isn't so much about git, it's a higher-level issue (the link it should've printed was https://github.com/coreos/rpm-ostree/issues/415).

Hmm, though are you not seeing a newer tree than `31.20200413.0`? I just pulled down `31.20200428.0`, which has `git-core-2.25.4-1.fc31`.

For f32, now that it's released, that issue should resolve itself in a day or so as pending updates are pushed through.

**Comment by daniel-wtd** [comment]
@cverna @jlebon Fedora 32 and 33 are providing git in the base image, afaik. I think the issue can be closed.

**Comment by tpopela** [comment]
@daniel-wtd I don't think that's true:

running https://gist.github.com/tpopela/7fad3adf53c0432497ce31a076d52c86 :

```
tpopela  ~/.../fedora/workstation-ostree-config  >  10:57 [master=]
0 $ overlayed-packages
ostree diff commit from: 2541055ca51a00cb2b7eba5aa3e3f6e8957015d4492e4cc4f49d40487e9bb88a
ostree diff commit to:   f43af6278ca9e856ab0f7ac439df75de2abdc257f1bf175de54eed817dba4772
Added:
  chromium-87.0.4280.66-1.fc33.x86_64
  chromium-common-87.0.4280.66-1.fc33.x86_64
  gc-8.0.4-4.fc33.x86_64
  git-2.28.0-1.fc33.x86_64
  git-core-doc-2.28.0-1.fc33.noarch
  google-chrome-stable-87.0.4280.66-1.x86_64
  gpm-libs-1.20.7-24.fc33.x86_64
  guile22-2.2.6-5.fc33.x86_64
  htop-3.0.2-1.fc33.x86_64
  http-parser-2.9.4-3.fc33.x86_64
  hunspell-cs-20080822-13.fc33.noarch
  liberation-fonts-1:2.1.0-2.fc33.noarch
  libgit2-1.0.1-3.fc33.x86_64
  libssh2-1.9.0-6.fc33.x86_64
  mc-1:4.8.25-3.fc33.x86_64
  minizip-compat-1.2.11-22.fc33.x86_64
  pass-1.7.3-6.fc33.noarch
  perl-DynaLoader-1.47-464.fc33.x86_64
  perl-Error-1:0.17029-4.fc33.noarch
  perl-File-Find-1.37-464.fc33.noarch
  perl-Git-2.28.0-1.fc33.noarch
  perl-TermReadKey-2.38-8.fc33.x86_64
  perl-lib-0.65-464.fc33.x86_64
  qrencode-4.0.2-6.fc33.x86_64
  ruby-libs-2.7.2-135.fc33.x86_64
  slang-2.3.2-8.fc33.x86_64
  starship-0.42.0-4.fc33.x86_64
  terminus-fonts-4.48-8.fc33.noarch
  tig-2.5.1-2.fc33.x86_64
  tmux-3.1-2.fc33.x86_64
  vim-X11-2:8.2.2018-1.fc33.x86_64
  vim-common-2:8.2.2018-1.fc33.x86_64
  vim-enhanced-2:8.2.2018-1.fc33.x86_64
  vim-filesystem-2:8.2.2018-1.fc33.noarch
  weechat-2.9-2.fc33.x86_64
  xclip-0.13-10.fc33.x86_64
tpopela  ~/.../fedora/workstation-ostree-config  >  10:57 [master=]
0 $ rpm -q --whatrequires git
warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
perl-Git-2.28.0-1.fc33.noarch
tig-2.5.1-2.fc33.x86_64
```

**Comment by daniel-wtd** [comment]
Gnarf, had it installed as a dependency from overlaying git-svn. Sorry for that.

**Comment by travier** [comment]
We have git-core in Silverblue now.
