### ISSUE TITLE
amdgpu and kernel 5.6 video corruption

### ISSUE THREAD

**Issue by BlakeCLewis** [fedora-silverblue/issue-tracker#60]
Fedora 31 and 32
All kernels v5.6 that have been delivered to FC31 and FC32
AMD Ryzen 5 Pro 2400GE w/ Radeon Vega Graphics
The first 3 kernel v5.6 broke graphics in FC31, so I upgraded to FC32
kernel 5.5.17 still worked without video corruption in FC31 and still does in FC32
I have tried every 5.6 kernel up to 5.6.11 in FC32 with same results, blocks of video corruption in web browser on youtube. CS:GO locks up.

I will file bug reports, I just need to know where.

**Comment by tpopela** [comment]
This is not Silverblue specific. Please create a bug report in Red Hat Bugzilla against the kernel package - https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=kernel
