### ISSUE TITLE
Bootupd: thread 'main' panicked at src/bios.rs:116:62

### ISSUE THREAD

**Issue by TheGreatDeadOne** [fedora-silverblue/issue-tracker#602]
**Describe the bug**
After updating bootupd, this bug appeared when trying to check the status of bootupd.

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Update the system
2. Reboot
3. view bootupd status (or update)

**Screenshots**

![Captura de tela de 2024-10-01 04-30-57](https://github.com/user-attachments/assets/ecc7c9d8-c08b-40a0-af98-68fa2bab494b)

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/rawhide/x86_64/silverblue
                  Version: Rawhide.20240930.n.0 (2024-09-30T06:07:39Z)
                   Commit: d44afe119fb862868666a1829781e2a1888497d4c0189186e290289cc35c369d
             GPGSignature: Valid signature by B0F4950458F69E1150C6C5EDC8AC4916105EF944
```

**Additional context**
I ran it with RUST_BACKTRACE=full, but I didn't get any more information.

**Comment by travier** [comment]
Can you file this upstream in [bootupd](https://github.com/coreos/bootupd/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen)? Thanks

I've filed https://github.com/coreos/bootupd/issues/738 with a workaround to let you get a backtrace.

**Comment by travier** [comment]
Can you also include the content of `/boot/bootupd-state.json` in your report? Thanks

**Comment by TheGreatDeadOne** [comment]
Reported https://github.com/coreos/bootupd/issues/739

**Comment by TheGreatDeadOne** [comment]
In the update to version Rawhide.20241012.n.1, there is the version of bootupd-0.2.20-2.fc41.x86_64 that contains the bug fix. I will close the issue as fixed.
