### ISSUE TITLE
No 3D acceleration AND No Shared Clipboard in GNOME Boxes where Fedora Atomic Desktop is the guest

### ISSUE THREAD

**Issue by alexsch01** [fedora-silverblue/issue-tracker#604]
**Describe the bug**
1. Fedora Workstation 41 and Fedora KDE 41 both as guests in GNOME Boxes....
a) has 3D acceleration option
b) has a shared clipboard with the host

2. Fedora Silverblue 41 and Fedora Kinoite 41 both as guests in GNOME Boxes....
a) does not have 3D acceleration option
b) does not have a shared clipboard with the host

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. Install each version in "OS versions" section
2. Notice no 3D acceleration option in GNOME Boxes and the clipboard isn't shared

**Expected behavior**
Fedora Silverblue 41 and Fedora Kinoite 41 both as guests in GNOME Boxes....
a) should have 3D acceleration option
b) should have a shared clipboard with the host

**OS versions:**
```
* Workstation 41: https://download.fedoraproject.org/pub/fedora/linux/releases/test/41_Beta/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-41_Beta-1.2.iso
* KDE 41: https://download.fedoraproject.org/pub/fedora/linux/releases/test/41_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-41_Beta-1.2.iso
* Silverblue 41: https://download.fedoraproject.org/pub/fedora/linux/releases/test/41_Beta/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-41_Beta-1.2.iso
* Kinoite 41: https://download.fedoraproject.org/pub/fedora/linux/releases/test/41_Beta/Kinoite/x86_64/iso/Fedora-Kinoite-ostree-x86_64-41_Beta-1.2.iso
```

**Additional context**
Host is running latest version of SteamOS (Steam Deck) in Desktop Mode. GNOME Boxes is latest version through Flathub

**Comment by travier** [comment]
This is likely a GNOME Boxes issue as this is working for me in a libvirtd machine with Virtual Machine Manager. Maybe it does not recognize Silverblue as an installation that is SPICE capable and does not set it up?

**Comment by alexsch01** [comment]
Ahh I see what happened, Boxes doesn't choose Fedora silverblue OS type by default when installing Kinoite.
3D acceleration is now showing
