### ISSUE TITLE
GNU Units - bad currency definitions

### ISSUE THREAD

**Issue by Colonial-Dev** [fedora-silverblue/issue-tracker#616]
**Describe the bug**
When invoking the GNU `units` command under Silverblue, the user is warned that the definition file for currencies could not be loaded due to the file not existing. Trying to convert between currencies (e.g. USD to GBP) results in an 'unknown unit' error.

This does not occur in a Fedora 41 Toolbox container.

**To Reproduce**
1. Install `units`.
2. Invoke it and observe the warning messages displayed.

**Expected behavior**
The currency file should be present and Units should launch without errors.

**Screenshots**
On Silverblue:
```
[colonial@silverblue ~]$ units
units: Unable to read units file '/usr/share/units/currency.units': No such file or directory
units:   file was included at line 5775 of file '/usr/share/units/definitions.units'
units: Unable to read units file '/usr/share/units/cpi.units': No such file or directory
units:   file was included at line 5860 of file '/usr/share/units/definitions.units'
units: bad definition for 'USCPI' in '/usr/share/units/definitions.units' line 5862, function 'UScpi' not defined
units: bad definition for 'cpi' in '/usr/share/units/definitions.units' line 5865, function 'UScpi' not defined
units: bad definition for 'CPI' in '/usr/share/units/definitions.units' line 5866, function 'UScpi' not defined
units: bad definition for 'dollars_in' in '/usr/share/units/definitions.units' line 5877, function 'USdollars_in' not defined
units: bad definition for 'US$in' in '/usr/share/units/definitions.units' line 5878, function 'USdollars_in' not defined
units: bad definition for '$in' in '/usr/share/units/definitions.units' line 5879, function 'USdollars_in' not defined
units: bad definition for 'inflation_since' in '/usr/share/units/definitions.units' line 5884, function 'USinflation_since' not defined
6867 units, 125 prefixes, 124 nonlinear units

You have: 30 USD
Unknown unit 'USD'
```
In a Workstation toolbox:
```
[colonial@toolbox ~]$ units
Currency exchange rates from FloatRates (USD base) on 2022-09-05 
3753 units, 113 prefixes, 120 nonlinear units

You have: 30 USD
You want: GBP
	* 26.123577
	/ 0.038279597
```

**OS version:**
```
State: idle
BootedDeployment:
● fedora:fedora/41/x86_64/silverblue
                  Version: 41.20241122.0 (2024-11-22T00:40:35Z)
               BaseCommit: af059f3b8b2cfd513fcf076ba177c84442d0e8cabb98ebbb13953d515fb8200c
             GPGSignature: Valid signature by 466CF2D8B60BC3057AA9453ED0622462E99D6AD1
      RemovedBasePackages: firefox firefox-langpacks 132.0.1-2.fc41
          LayeredPackages: code fish micro stow syncthing tlp units wl-clipboard
```

**Additional context**
Apologies if this isn't the place to report an issue like this. Upstream doesn't seem to be at fault, and I couldn't find a "package maintainer specific" bug report location (if that makes sense.)

**Comment by travier** [comment]
It looks like the `units` installs some of the needed files in `/var` when they should be in `/usr` instead: https://koji.fedoraproject.org/koji/rpminfo?rpmID=39454693

This should be filed as a bug for the `units` package or maybe even upstream.

As the recommended way to install packages like that is to do it in a toolbox and there isn't something Silverblue specific to do here, I'll close this one.

**Comment by LorbusChris** [comment]
@Colonial-Dev issues for this RPM can be filed against https://src.fedoraproject.org/rpms/units (the Issues tab link will lead you to bugzilla).
