### ISSUE TITLE
Support for ppc64le

### ISSUE THREAD

**Issue by runlevel5** [fedora-silverblue/issue-tracker#63]
I am unable to find any ISO for the ppc64le so I assume this architecture is not supported. I create this ticket to initiate the conversation on supporting ppc64le.

**Comment by tpopela** [comment]
Hi @runlevel5, the ISO are being produced as part of the compose - https://kojipkgs.fedoraproject.org/compose/32/latest-Fedora-32/compose/Silverblue/ppc64le/iso/, but you are right that I don't see them in the ppc64le section of https://alt.fedoraproject.org/alt/.

**Comment by sharkcz** [comment]
The content on alt.fp.o is managed by the Fedora websites team (https://pagure.io/fedora-websites/), pull requests are welcome :-) I would consider Silverblue for ppc64le (and aarch64) as a technology preview, it's not a supported variant, mainly because the flatpak infra is still x86-only.

**Comment by runlevel5** [comment]
> I would consider Silverblue for ppc64le (and aarch64) as a technology preview, it's not a supported variant, mainly because the flatpak infra is still x86-only

Yeah I don't think flatpak would support this arch yet, I am working on to get `toolbox` support ppc64le

**Comment by runlevel5** [comment]
I've submitted a PR on https://github.com/fedora-silverblue/silverblue-site/pull/83
