### ISSUE TITLE
ipa-client-install is breaking sssd configuration

### ISSUE THREAD

**Issue by zem** [fedora-silverblue/issue-tracker#65]
I recently discovered a bug between the ipa-client package and Silverblue when I try to put Silverblue Workstation (32) into my FreeIPA Domain.

ipa-client-install reconfigures sssd, which means all users and groups except root and my local user are gone after execution. Of course logging into the domain failed, too.

**Comment by tpopela** [comment]
Hi @zem, can you please open a bug report in https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=freeipa&version=32 ?

**Comment by kghorvath** [comment]
I experienced this as well and I think the issue is that SB requires altfiles in /etc/nsswitch.conf and ipa-client-install doesn't add it back in. Manually editing /etc/nsswitch.conf and adding it back in fixed it for me.

**Comment by travier** [comment]
This is the same issue as https://github.com/fedora-silverblue/issue-tracker/issues/62, which has a fix waiting for tester at https://bugzilla.redhat.com/show_bug.cgi?id=1751417#c9. Please give it a try and report success/failure!
