### ISSUE TITLE
rpm-ostree update fails

### ISSUE THREAD

**Issue by ojoeth** [fedora-silverblue/issue-tracker#69]
When I run `rpm-ostree update` , it returns 

``` 
Receiving objects: 14% (8/54) 1.4 MB/s 10.1 MB... done
error: fstatat(92/40c3864881a34072b6e13c787a82e4dc77eb8cd7e022a362fcd8cfc60babf6.file): Bad message
``` 
I am not sure on how to grab more information/logs.

Another thing to add is on every boot it drops me in a systemd shell and I have to manually `mount /dev/mapper/fedora-root /sysroot` . My drive is encrypted with LUKS.

**Comment by jlebon** [comment]
> error: fstatat(92/40c3864881a34072b6e13c787a82e4dc77eb8cd7e022a362fcd8cfc60babf6.file): Bad message

Hmm, weird. Not sure what the source of that one is. Do you see anything else in `journalctl -u rpm-ostreed`?

> Another thing to add is on every boot it drops me in a systemd shell and I have to manually `mount /dev/mapper/fedora-root /sysroot` . My drive is encrypted with LUKS.

Do you have `root=/dev/mapper/fedora-root` on your kernel cmdline? That should normally be automatically set up by Anaconda.

**Comment by tpopela** [comment]
Closing, feel free to reopen if needed.
