### ISSUE TITLE
Design suggestion: Silverblue branding

### ISSUE THREAD

**Issue by ghost** [fedora-silverblue/issue-tracker#7]
I just did an install of Silverblue and couldn't tell if it was Fedora 30 workstation or if it was Silverblue.  I'd like to suggest adding some branding/differentiation to the install screen and perhaps the wallpaper (maybe add the silverblue logo next to Fedora at the bottom right of the desktop?).

**Comment by dan1mal** [comment]
I couldnt find  a repository for the branding stuff.  Maybe it hasn't been created yet?  I could only find the logo on the website - https://silverblue.fedoraproject.org/public/silverblue-logo.svg

It would be useful in the future to have the original design file and the font list somewhere for future designers.  Perhaps this could be added to the website under resources.

**Comment by allanday** [comment]
We have some in-progress design work for this, which you can see here: https://teams.fedoraproject.org/project/silverblue/us/108?kanban-status=37

The goal is to get this fixed for F32.

**Comment by travier** [comment]
Nothing has happened in a while here and I don't think we have any plans. Closing.
