### ISSUE TITLE
dbus-daemon should not be installed

### ISSUE THREAD

**Issue by hferreiro** [fedora-silverblue/issue-tracker#70]
I was surprised by seeing `dbus-daemon` installed in one update. Both `dbus-daemon` and `dbus-broker` are installed at the same time. Only `dbus-broker` is running, and `dbus-daemon` doesn't seem to be required by any packages:
```
$  rpm -q --whatrequires dbus-daemon
no package requires dbus-daemon
```

**Comment by tpopela** [comment]
Looking at the repoquery output:

0 $ dnf repoquery  --repoid=rawhide --enablerepo=rawhide --queryformat="%{name} %{sourcerpm}" --whatrequires dbus-daemon --alldeps                              
anaconda-core anaconda-33.25-1.fc33.src.rpm
dbus-doc dbus-1.12.20-2.fc33.src.rpm
dbus-tests dbus-1.12.20-2.fc33.src.rpm
dbus-x11 dbus-1.12.20-2.fc33.src.rpm
gdm gdm-3.37.3-4.fc33.src.rpm

it's still required by gdm through the "Requires: /usr/bin/dbus-run-session" in https://src.fedoraproject.org/rpms/gdm/blob/c44e295739acccc1db773afc33fbc575652a4d72/f/gdm.spec#_89 . I don't know whether we can do anything about it. I will notify the GDM developer about this.

**Comment by halfline** [comment]
dbus-run-session is currently required for the login screen.  we hope to fix that in the future, but we're not there yet.

**Comment by tpopela** [comment]
Lets close this issue. Once the gdm will drop the dependency, then it will be dropped from the base image as well.
