### ISSUE TITLE
Freezing apps SB 32

### ISSUE THREAD

**Issue by Minter1** [fedora-silverblue/issue-tracker#71]
Hi,

I am running experiencing various apps freezing on me. Examples of apps is as follows:

1. Files/Nautilius
2. Atom
3. Gedit
4. Libre Office

It's not a system freeze as I can get an app to unfreeze by changing apps. 

I have posted the issue on the Fedora forum [here](https://discussion.fedoraproject.org/t/flatpaks-hanging-freezing-on-fedora-silverblue-32/21623/23) so you can see troubleshooting so far and further details. Feedback so far indicates it could be a bug related to Gnome / debus.

From the forum, we also now believe the issue could be related to wayland/mutter. I frequently have my apps open in a minimized state rather than full screen. The issue could be related to this minimised state and could explain why I haven't noticed the issue in Firefox as this is usually full screen for me. 

Thanks for your consideration

**Comment by tpopela** [comment]
Hi @Minter1, is this still an issue? If so, can you please try to boot a Workstation F32 iso (ideally https://dl.fedoraproject.org/pub/alt/live-respins/F32-WORK-x86_64-LIVE-20200804.iso that contains all the updates) and see whether you can observe the same issues? As from your description this doesn't look like it's Silverblue specific.

**Comment by Minter1** [comment]
Hi, as a workaround I have been using windows full screen (rather than un-maximised) and I haven't experienced the issue  but also haven't been using those apps as intensively. I would say it's still an issue. I will need to use the iso (I assume on a live usb is oK)  and run programs in their un-maximised state to replicate how I was using it before and get back to you as soon as I can get some results.

**Comment by Minter1** [comment]
Hi @tpopela 

I have installed the version of Fedora you have linked on Gnome Boxes. I have had the hanging behaviour repeated. 

To carry out the test I did the following:
1) Opened Libre Office Writer (installed as standard)
2) Reduced the window to say 50 or 75 percent of full screen (This seems to be important)
3) Typed up a one page document. I had the document saved to Documents.

**Comment by tpopela** [comment]
@Minter1 thank you for testing! Then, please open an issue ideally in https://gitlab.gnome.org/GNOME/mutter/-/issues (according to what cmurf mentioned in https://discussion.fedoraproject.org/t/flatpaks-hanging-freezing-on-fedora-silverblue-32/21623/37). Please mention your GPU, drivers and so on there as well.

**Comment by Minter1** [comment]
thanks @tpopela 

I have now opened an issue with GNOME as suggested:
[https://gitlab.gnome.org/GNOME/mutter/-/issues/1382](url)

**Comment by tpopela** [comment]
Thanks @Minter1 ! I will close this issue then.
