### ISSUE TITLE
Dropping Firefox from base image

### ISSUE THREAD

**Issue by kuba3351** [fedora-silverblue/issue-tracker#72]
I have an idea to drop Firefox from the base Fedora Silverblue image, because it is already available as Flatpak in Fedora registry and Flathub. I think it should be installed by Anaconda like some other apps (see Fedora Silverblue 32 announcement).

I think it will be good because it enables the users to update Firefox independent from the base image, and users can remove Firefox more easily if they want to use another browser. What about this idea?

**Comment by tpopela** [comment]
This is a long term goal, but we are still not there as Firefox Flatpak still has many pain points that needs to be solved first.

**Comment by ldepandis** [comment]
> I think it should be installed by Anaconda like some other apps (see Fedora Silverblue 32 announcement).

To be honest I'd prefer that Fedora would drop Firefox and adopt GNOME Web in the base image, and then let the user choosing to download the browser they want, IF they want.
IMHO GNOME Web has a lot of advantages as the default browser for the base install:
- It's part of the GNOME experience;
- It's simple and great for people who just want to browse the web without any other extra feature;
- It gives the people the tool they need for going to the web and downloading their favorite browser;
- It frees Fedora from depending from FlatHub or any other third-party and not so-compliant repository like it would happen with the official Firefox Flatpak bundle.

I can see GNOME Web in the base install like Safari in macOS or Edge in Windows.

@tpopela sorry for answering to an already closed ticket, but I think this discussion it's very interesting.

**Comment by tpopela** [comment]
@ldepandis we are following the defaults of Fedora Workstation - if you want to propose a change of the default web browser, then open an issue against https://pagure.io/fedora-workstation/

> * It frees Fedora from depending from FlatHub or any other third-party and not so-compliant repository like it would happen with the official Firefox Flatpak bundle.

We don't depend on Flathub. The Firefox that we are and will be using is build in Fedora and not on Flathub.

**Comment by sinaflan** [comment]
> because it is already available as Flatpak in Fedora registry

without codecs
