### ISSUE TITLE
Installer inst.rescue fails to find linux filesystem yet one exists 

### ISSUE THREAD

**Issue by cmurf** [fedora-silverblue/issue-tracker#77]
1. Install Fedora-Silverblue-ostree-x86_64-33-20200830.n.0.iso using default/autopartition (btrfs) or Custom LVM+xfs.
2. Reboot the same install media.
3. At the bootloader, choose Troubleshooting then Rescue a Fedora system.
4. At the text menu, choose continue

Result: fails to find a linux filesystem

Expected: it should find Fedora, mount and assemble all file systems.

Upstream bug report
https://bugzilla.redhat.com/show_bug.cgi?id=1873886

**Comment by cmurf** [comment]
Looks like there's a dup.
https://bugzilla.redhat.com/show_bug.cgi?id=1268237

**Comment by tpopela** [comment]
Thank you @cmurf for the bug report! I will close this one and we will leave the RHBZ opened as that one is assigned to the right component.
