### ISSUE TITLE
F33: Upgrade from F32 marked the user as system account

### ISSUE THREAD

**Issue by vrutkovs** [fedora-silverblue/issue-tracker#78]
`vrutkovs` user on F32 had `/bin/zsh` shell. Upgraded from F32 (with all layered packages removed due to https://bugzilla.redhat.com/show_bug.cgi?id=1876194) and was greeted by gnome-initial-setup. Turns out the users was marked as system account in `/var/lib/AccountsService/users/vrutkovs`.
Updated `SystemAccount` to false and the user showed up on GDM.

Not sure which package is responsible for that - is it due to ZSH being set as a shell or accountservice has incorrectly migrated to a new version?

**Comment by halfline** [comment]
do you have zsh in /etc/shells?

**Comment by tpopela** [comment]
Could https://bugzilla.redhat.com/show_bug.cgi?id=1876194#c1 be related? Quoting @vrutkovs:

> That however has nuked my shell (zsh), so I had to create a new user to login and run the rebase

**Comment by nahuelwexd** [comment]
Hi! I got here because I had this same issue a couple of days ago... Specifically, the problem was when I reset my overrides, not when I did the rebase. It seems that having a shell set that is not in the base image can cause problems when resetting the overrides, so... maybe it is a good idea to have `rpm-ostree reset` also reset the users shell to `/bin/bash`?

**Comment by tpopela** [comment]
@cgwalters @dustymabe any idea about what @nahuelwexd is suggesting?

**Comment by travier** [comment]
I know this is probably not a satisfying answer but I would suggest not changing the default shell and instead adding logic in .bashrc to switch to your preferred shell.

**Comment by cgwalters** [comment]
Hmm, messy.  Ideally the password database would support multiple shells in priority order, i.e. `/bin/zsh,/bin/bash` and use bash if zsh isn't installed.

**Comment by halfline** [comment]
I guess we could augment the shell field in passwd to be comma separated, like some distros augment gecos to be comma separated.  Seems like it would have quite a bit of compatibility fall out though.  I guess this problem just goes away with homed, though, so maybe we should just come up with a near-term solution (e.g. take the shell check out of accountsservice and blocklist any system accounts that get dragged in)

**Comment by cgwalters** [comment]
It's not just accountsservice though, if an invalid shell is specified then PAM will fail right?

**Comment by jlebon** [comment]
> So it didn't recognize your shell and marked you as a system account, I guess? Not sure what the right answer is, maybe we shouldn't check the users shell, but that has the potential to bring in non-user accounts as user accounts (mysql user maybe?)

Naive question: why doesn't it just cue off of `SYS_UID_MAX`? Isn't that the more correct way to do this?

**Comment by halfline** [comment]
> It's not just accountsservice though, if an invalid shell is specified then PAM will fail right?

ah yea of course.  fixing accountsservice will stop gnome-initial-setup from showing up, but then login will fail.




> Naive question: why doesn't it just cue off of `SYS_UID_MAX`? Isn't that the more correct way to do this?

Nope, relying on `login.defs` has not gone well historically.  There are many system accounts in the `UID_MIN-UID_MAX` range.  And it's not unheard of to have user accounts outside of the `UID_MIN-UID_MAX` range.

**Comment by travier** [comment]
Current workaround for this one is https://github.com/fedora-silverblue/issue-tracker/issues/78#issuecomment-705722829. As there isn't much we can do to fix passwd entries that reference removed shells, I'm going to close this one.
