### ISSUE TITLE
F32 : upgrade to 32.20200905.0 from 32.20200822.0 nvidia troubles

### ISSUE THREAD

**Issue by lynerlok** [fedora-silverblue/issue-tracker#79]
Hello everyone !

I tried to upgrade my system two days ago and I have a strange problem maybe with nvidia driver ?

On the 32.20200905.0, one of my two screens leave blank, OBS says there is a problem with my GPU and Blender doesn't detect CUDA ( the last one is because for some reasons the upgrade remove the xorg-x11-drv-nvidia-cuda-libs, so I reinstall by hand )
On the 32.20200822.0, no of these problem appear.

I suspect a problem with the last nvidia driver version 450.66, but nothing seems wrong in my logs !

There is the same `rpm-ostree kargs`  output ( except ostree as expected ) between the two version : `resume=/dev/mapper/fedora-swap rd.lvm.lv=fedora/root rd.lvm.lv=fedora/swap rhgb quiet root=/dev/mapper/fedora-root ostree=/ostree/boot.1/fedora/f34b26550c169909ad3b35a00282ac8747a97b66095956df211e97062b1caa80/0 rd.driver.blacklist=nouveau nvidia-drm.modeset=1`

Same lsmod, services, unit files and Xorg logs, and no other error in logs...

Gnome detect the two screens because windows pop up in my blank screen.
Nvidia-settings seems ok too, it detect the two screen, etc... But always a blank screen.

My config : 
- CPU : AMD RYZEN 9 3950X
- GPU : NVIDIA 2080 TI ( MSI )
- Memory : 32Go Corsair LPX Vengeance

Packages installed for nvidia : akmod-nvidia, xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda-lib,  xorg-x11-drv-nvidia-libs, xorg-x11-drv-nvidia-libs.i686

I'm an experimented GNU/linux user but now I don't what happened here...

**Comment by tpopela** [comment]
Hi @lynerlok. Sadly I don't have any experience with nVidia and its drivers. I would probably ask in https://discussion.fedoraproject.org/c/desktop/silverblue/6 where the other Silverblue users are as they might know more.

**Comment by lynerlok** [comment]
Ok thx, I report this issue on fedora discussion and close it !
