### ISSUE TITLE
initial setup not start Rawhide-20190808

### ISSUE THREAD

**Issue by FastOSlinux** [fedora-silverblue/issue-tracker#8]
Rawhide-20190808.n.0.iso

after the installation process, the initial setup (user creation, password ..) does not start

get stuck on an empty screen
![Captura de tela de 2019-08-08 21-14-36](https://user-images.githubusercontent.com/17401812/62745516-a10a3a80-ba21-11e9-8a78-6b13dd895591.png)

**Comment by tpopela** [comment]
This is caused by "g-i-s crashes if timedatex.service isn't running" - https://bugzilla.redhat.com/show_bug.cgi?id=1734198
