### ISSUE TITLE
Mouse Acceleration Issues

### ISSUE THREAD

**Issue by tandeshmukh** [fedora-silverblue/issue-tracker#81]
I have a Logitech M705 wireless mouse and a Lenovo Ideapad 5 14" and I am running the latest edition of Fedora Silverblue. I had an issue for a while where switching the mouse acceleration profile in Gnome-Tweaks would cause the mouse to lag horribly. This is an issue that I have never had running Gnome on any other distro. I solved my issue by switching the profile to adaptive, but I thought it was worth mentioning here.

**Comment by tpopela** [comment]
Hi @tandeshmukh. Can you please try whether you can reproduce it on regular Fedora Workstation as well (by booting the live image)? If you will be able to reproduce it there, please open a bug against libinput component in Red Hat Bugzilla by using the following link - https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=libinput

**Comment by tandeshmukh** [comment]
I reproduced it on Fedora Workstation 32. The issue seems specific to my logitech M705 mouse because the issue did not persist with an Anker wireless mouse that I tried. I followed you link, made an account, and filed a report on Red Hat Bugzilla.

**Comment by tpopela** [comment]
@tandeshmukh can you please paste the link to the bug here for the reference?

**Comment by Destruxio** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1877432

**Comment by tandeshmukh** [comment]
Update, the issue was that my laptop did not like my usb ethernet adapter and that was causing my mouse issues.
