### ISSUE TITLE
Add gnome-themes-extra to toolbox image

### ISSUE THREAD

**Issue by A6GibKm** [fedora-silverblue/issue-tracker#83]
There is nothing worse than opening an app only to realize it is not taking into account the adwaita-dark theme. Currently toolbox apps can suffer from this is if `gnome-themes-extra` is not manually installed, the former package is not part of the toolbox image for f32 or f33.

**Comment by tpopela** [comment]
Please open an issue in the Toolbox issue tracker at https://github.com/containers/toolbox/.
