### ISSUE TITLE
[F33] Variable $HOSTNAME is not set on Toolbox

### ISSUE THREAD

**Issue by A6GibKm** [fedora-silverblue/issue-tracker#84]
`echo $HOSTNAME` returns only a newline (`\n`). This variable was set to `toolbox` on previous images for f29-f32.

**Comment by tpopela** [comment]
Is this about host (Silverblue) or a guest (inside a Toolbox container)? If the latter, please open a bug report in Toolbox issue tracker - https://github.com/containers/toolbox/.

**Comment by A6GibKm** [comment]
Both this and #83 are issues not with toolbox per se, but with the Fedora image for toolbox, is that the correct place to report this?

**Comment by tpopela** [comment]
No, it's not. The images are maintained by the Toolbox project.
