### ISSUE TITLE
GNOME Software should automatically update Silverblue

### ISSUE THREAD

**Issue by nahuelwexd** [fedora-silverblue/issue-tracker#87]
Currently the graphical way to update Silverblue is:

- Open GNOME Software
- Hit Update & Reboot
- Wait until the update is downloaded and applied
- Reboot

And if I want to update and shutdown my PC I need to:

- Open GNOME Software
- Hit Update & Reboot
- Wait until the update is downloaded and applied
- Hit cancel on the dialog that ask me to reboot my PC
- Turn off the PC though the system menu

I think this is not really the best way to update Silverblue, it's kinda annoying, and Workstation already has a checkbox on the power off dialog in order to "Update and shutdown" the PC. So I think we can maybe have a toggle on GNOME Software in order to automatically download and apply every single update, and when the PC gets eventually rebooted, just boot on the new commit

**Comment by tpopela** [comment]
@kalev might know whether they are some limitations or it could be implemented (and maybe point us to some upstream bug to follow).

**Comment by kalev** [comment]
I think something like this would make sense. I'm not aware of an upstream bug to follow :)

**Comment by jlebon** [comment]
Yeah, that would really take advantage of the OSTree update model. FWIW, the built-in rpm-ostree `AutomaticUpdatePolicy=stage` config does this: https://github.com/coreos/rpm-ostree/blob/0c3f73b7206b3e9003b80203a4b294f7b5501d67/man/rpm-ostreed.conf.xml#L79-L81.

**Comment by felipehw** [comment]
> Yeah, that would really take advantage of the OSTree update model. FWIW, the built-in rpm-ostree `AutomaticUpdatePolicy=stage` config does this: https://github.com/coreos/rpm-ostree/blob/0c3f73b7206b3e9003b80203a4b294f7b5501d67/man/rpm-ostreed.conf.xml#L79-L81.

But I don't think that feature respects the metered connection of network configuration like Gnome Softaware  ...

**Comment by jlebon** [comment]
>> Yeah, that would really take advantage of the OSTree update model. FWIW, the built-in rpm-ostree AutomaticUpdatePolicy=stage config does this: coreos/rpm-ostree@0c3f73b/man/rpm-ostreed.conf.xml#L79-L81.
>
> But I don't think that feature respects the metered connection of network configuration like Gnome Softaware ...

Oh yeah, I'm not saying "use `AutomaticUpdatePolicy=stage` instead of gnome-software". Just pointing out the semantics requested here makes enough sense that it's built into rpm-ostree. Having it part of g-s would be great!

**Comment by felipehw** [comment]
> > > Yeah, that would really take advantage of the OSTree update model. FWIW, the built-in rpm-ostree AutomaticUpdatePolicy=stage config does this: [coreos/rpm-ostree@0c3f73b](https://github.com/coreos/rpm-ostree/commit/0c3f73b)/man/rpm-ostreed.conf.xml#L79-L81.
> > 
> > 
> > But I don't think that feature respects the metered connection of network configuration like Gnome Softaware ...
> 
> Oh yeah, I'm not saying "use `AutomaticUpdatePolicy=stage` instead of gnome-software". Just pointing out the semantics requested here makes enough sense that it's built into rpm-ostree. Having it part of g-s would be great!

I've installed Silverblue for non tech people and enabled `AutomaticUpdatePolicy=stage` because they never manually update the system.
BUT they screamed "OMG! My mobile network plan got sucked by the OS updates" ... so I've disabled the `AutomaticUpdatePolicy=stage` thing and onyl flatpaks are updated at their machines (thanks to Gnome Software).

We really need the auto-update ostree thing integrated at Gnome Software :)

**Comment by Yajo** [comment]
I'd like this workflow:

1. A pop-up tells you "System updated. Reboot to see changes".

And I'll reboot whenever I want. Period.

**Comment by jmaris** [comment]
> > > > Yeah, that would really take advantage of the OSTree update model. FWIW, the built-in rpm-ostree AutomaticUpdatePolicy=stage config does this: [coreos/rpm-ostree@0c3f73b](https://github.com/coreos/rpm-ostree/commit/0c3f73b)/man/rpm-ostreed.conf.xml#L79-L81.
> > > 
> > > 
> > > But I don't think that feature respects the metered connection of network configuration like Gnome Softaware ...
> > 
> > 
> > Oh yeah, I'm not saying "use `AutomaticUpdatePolicy=stage` instead of gnome-software". Just pointing out the semantics requested here makes enough sense that it's built into rpm-ostree. Having it part of g-s would be great!
> 
> I've installed Silverblue for non tech people and enabled `AutomaticUpdatePolicy=stage` because they never manually update the system. BUT they screamed "OMG! My mobile network plan got sucked by the OS updates" ... so I've disabled the `AutomaticUpdatePolicy=stage` thing and only flatpaks are auto-updated at their machines (thanks to Gnome Software).
> 
> We really need the auto-update ostree thing integrated at Gnome Software :)

I agree that this is a serious issue, I know gnome now provides an option to set certain connections as metered, could we somehow leverage that to prevent this from happening? Maybe it is too platform-specific for ostree though

**Comment by tpopela** [comment]
@jmaris there's https://github.com/coreos/rpm-ostree/issues/2560 and I think that I somewhere saw another issue that was requesting the same, but I can't find it now.

@Yajo @jmaris can anyone of you open an issue in https://gitlab.gnome.org/GNOME/gnome-software/-/issues to not only download the updates, but to also apply them?

**Comment by jlebon** [comment]
> @jmaris there's coreos/rpm-ostree#2560 and I think that I somewhere saw another issue that was requesting the same, but I can't find it now.

I think the idea though is that if this is integrated in GNOME Software then it automatically would gain metered connection awareness so rpm-ostree itself doesn't need to care about that. From the rpm-ostree side, I can say a lot of work is going into having it be driven by higher-level user-facing tools like GNOME Software, [Zincati](https://github.com/coreos/zincati/), [MCO](https://github.com/openshift/machine-config-operator), etc... instead of enhancing policy-like management in rpm-ostree itself.

I don't think we'll rip out `AutomaticUpdatePolicy=stage` anytime soon, but I also don't think we'll ever make it the default, whereas g-s is in a position where the equivalent policy could be the default on FSB.

**Comment by Yajo** [comment]
> can anyone of you open an issue in https://gitlab.gnome.org/GNOME/gnome-software/-/issues to not only download the updates, but to also apply them?

See https://gitlab.gnome.org/GNOME/gnome-software/-/issues/659#note_1326607

**Comment by albertgasset** [comment]
Automatic updates via GNOME Software are working on Fedora Silverblue 38. The upstream bug was fixed, see: https://gitlab.gnome.org/GNOME/gnome-software/-/commit/54da3af60a655e6db79a2b8ea7bfedb520aa3779
