### ISSUE TITLE
Package nm-connection-editor as a flatpak on fedora registry

### ISSUE THREAD

**Issue by monterrr** [fedora-silverblue/issue-tracker#88]
Currently nm-connection-editor isn't packaged as a flatpak on fedora registry or flathub so if one needs to do constant advanced network editing the package would need to be layered or.. installed in a toolbox container.

Will it then be considered to be pre-installed?

**Comment by tpopela** [comment]
> Currently nm-connection-editor isn't packaged as a flatpak on fedora registry or flathub so if one needs to do constant advanced network editing the package would need to be layered or.. installed in a toolbox container.
> 
> Will it then be considered to be pre-installed?

Hi @monterrr, Silverblue shares the same pre-installed applications as Fedora Workstation. So if you want it to be pre-installed in Silverblue, you have to do so for Workstation first. Honestly I think that it used to be pre-installed in Workstation in past, but it was removed.

Also the Flatpak probably doesn't exists as it's not an application, but a utility that's tight to the Network Manager.

**Comment by monterrr** [comment]
Hi @tpopela,

I believe it comes pre-installed with Fedora Workstation 33, I asked on freenode and got this: https://paste.centos.org/view/fa36c4d5

Wasn't it also installed on silverblue 32?

**Comment by tpopela** [comment]
I don't think it was part of SB32. Looking at the comps files for Workstation it's not part of Workstation 32 or 33 either - it's part of xfce-desktop, mate-desktop, cinnamon-desktop, lxde-desktop, lxqt-desktop groups, but it isn't part of gnome-desktop group that is part of Workstation (see https://pagure.io/fedora-comps/blob/master/f/comps-f32.xml.in or https://pagure.io/fedora-comps/blob/master/f/comps-f33.xml.in).

**Comment by monterrr** [comment]
I've just literally installed silverblue 32 on a vm and it includes nm-connection-editor pre-installed.

**Comment by tpopela** [comment]
I can confirm that as well (sorry was testing previously on 33 and looked only into https://pagure.io/workstation-ostree-config/tree/f32). But I think when you rebase to 33, then it will be removed as it was previously being pulled in as a dependency of some package and that package removed that dependency on nm-connection-editor.

**Comment by monterrr** [comment]
I've now also tested fedora 33 workstation beta in a vm and it comes with nm-connection-editor pre-installed.

**Comment by monterrr** [comment]
So if fedora workstation 33 has it I guess this can be considered a bug and needs fixing?

**Comment by tpopela** [comment]
We will see. As @felipeborges found out it's being pulled in into Workstation by Anaconda (the installer), so first we have to figure out why Anaconda is still being installed in Workstation (I will ask about that on the today's Fedora Workstation Working Group meeting) and I will get back to you whether nm-connection-editor should be preinstalled or not.

**Comment by felipeborges** [comment]
> Also the Flatpak probably doesn't exists as it's not an application, but a utility that's tight to the Network Manager.

AFAIK nm-connection-editor uses libnm which should be smart enough to talk to NetworkManager over dbus. Therefore a Flatpak is possible. I put together a prototype of this https://gitlab.gnome.org/felipeborges/network-manager-applet/-/commit/b9d4896e2

I also made the network-manager-applet CI able to produce Flatpak bundles that can be easily tried.

1. Go to https://gitlab.gnome.org/felipeborges/network-manager-applet/-/jobs/937490/artifacts/browse
2. Download the artifact
3. Run `flatpak install nm-connection-editor.flatpak`. 

https://gitlab.gnome.org/GNOME/network-manager-applet/-/merge_requests/87
I proposed that this gets merged in network-manager-applet. If its maintainers decide to accept it, I could propose it for Flathub too, so everybody can easily get it from their software centre of choice. :smile_cat:

**Comment by cmurf** [comment]
Downstream bug, and workaround proposal.
https://bugzilla.redhat.com/show_bug.cgi?id=1887891

**Comment by tpopela** [comment]
The bug was accepted to F33, lets wait for the next Silverblue compose to see whether nm-connection-editor is really there.

**Comment by allanday** [comment]
gnome-control-center shouldn't really be calling nm-connection-editor. I've filed this to see if we can sever the link: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1157

**Comment by monterrr** [comment]
It's now live, I've noticed that rpm-ostree status didn't show nm-connection-editor as layered anymore on the newest deployment for me so I loaded the deployment and I did a rpm-ostree upgrade and it gave some message about the package nm-connection-editor so I think the package was still layered somehow so I did rpm-ostree remove nm-connection-editor and it indeed processed my request, I restarted and nm-connection-editor was still there as expected, is this how it is suppose to be?

**Comment by tpopela** [comment]
> It's now live, I've noticed that rpm-ostree status didn't show nm-connection-editor as layered anymore on the newest deployment for me so I loaded the deployment and I did a rpm-ostree upgrade and it gave some message about the package nm-connection-editor

What was the message? I would expect that it would notify you, that nm-connection-editor became part of the base image.

 so I think the package was still layered somehow so I did rpm-ostree remove nm-connection-editor and it indeed processed my request, I restarted and nm-connection-editor was still there as expected, is this how it is suppose to work?

For this I would ask @cgwalters @miabbott or @dustymabe.

**Comment by monterrr** [comment]
> What was the message? I would expect that it would notify you, that nm-connection-editor became part of the base image.

I don't remember but I think it was indeed informing me of that.

@felipeborges Thanks! I didn't though someone would do a flatpak so fast!

**Comment by monterrr** [comment]
What is stopping silverblue from having the remaining system applications gnome system monitor, Color Profile Viewer, Disks, Tour, help, files, settings and terminal as flatpaks?
For example, there is gnome system monitor and various terminals as snaps on snapcraft.io

**Comment by tpopela** [comment]
> What is stopping silverblue from having the remaining system applications gnome system monitor, Color Profile Viewer, Disks, Tour, help, files, settings and terminal as flatpaks?

a. technical difficulties (ie. Files, GNOME System Monitor, Terminal)
b. a line between where it does make a sense to have a Flatpak and where not. What you mentioned are core system applications and for those it doesn't really make sense (at least for now) to have them as Flatpaks.

//note Disks does have a Flatpak (it's name is org.gnome.baobab).

> For example, there is gnome system monitor and various terminals as snaps on snapcraft.io

Snap is not relevant at all in this discussion.

**Comment by monterrr** [comment]
I just mentioned snap because if they can make a terminal and gnome system monitor inside a restricted environment then why flathub doesn't..

**Comment by monterrr** [comment]
For the past few days when I've run rpm-ostree upgrade it upgardes the system but it isn't revealing which packages have been upgraded.. why?
