### ISSUE TITLE
Mozc not available as an input method after installing ibus-mozc

### ISSUE THREAD

**Issue by encrypted-sushi** [fedora-silverblue/issue-tracker#9]
Attempting to use Mozc as my Japanese input method, I installed ibus-mozc using rpm-ostree.
`rpm-ostree install ibus-mozc`

After a reboot, I expected "Japanese (Mozc)" to be listed as an Japanese input method configurable in Gnome's "Region & Language" settings--which was not there.

I've checked to make sure the ibus-mozc package is indeed installed.
```
$ rpm -q ibus-mozc
ibus-mozc-2.23.2815.102-5.fc30.x86_64
```

Even though the package appear to be installed, it seems like ibus does not see this as an engine.

```
$ ibus list-engine Japanese | grep -A3 -B3 "language: Japanese"
  m17n:kn:inscript2 - inscript2 (m17n)
  m17n:kn:typewriter - typewriter (m17n)
  m17n:kn:inscript - inscript (m17n)
language: Japanese
  kkc - Kana Kanji
  xkb:jp::jpn - Japanese
language: Vietnamese
```

**Comment by tagoh** [comment]
Does this issue still persist even if you reboot or run `ibus restart` at the terminal?

**Comment by encrypted-sushi** [comment]
Yes, the issue persist after both rebooting, and issuing `ibus restart`.

```
$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
● ostree://fedora:fedora/30/x86_64/silverblue
                   Version: 30.20190821.0 (2019-08-21T00:39:39Z)
                BaseCommit: 72959f4b14900e0d39978e36d601937d063af4332c469395adb91a8c5c063047
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
           LayeredPackages: evemu fedora-workstation-repositories htop ibus-mozc tlp tlp-rdw

  ostree://fedora:fedora/30/x86_64/silverblue
                   Version: 30.20190821.0 (2019-08-21T00:39:39Z)
                BaseCommit: 72959f4b14900e0d39978e36d601937d063af4332c469395adb91a8c5c063047
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
           LayeredPackages: fedora-workstation-repositories htop ibus-mozc tlp tlp-rdw

  ostree://fedora:fedora/30/x86_64/silverblue
                   Version: 30.20190821.0 (2019-08-21T00:39:39Z)
                    Commit: 72959f4b14900e0d39978e36d601937d063af4332c469395adb91a8c5c063047
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
                    Pinned: yes
$ 
$ 
$ ibus restart
$ 
$ 
$ ibus list-engine | grep -A3 -B3 "language: Japanese" 
  m17n:kn:inscript2 - inscript2 (m17n)
  m17n:kn:typewriter - typewriter (m17n)
  m17n:kn:inscript - inscript (m17n)
language: Japanese
  kkc - Kana Kanji
  xkb:jp::jpn - Japanese
language: Vietnamese
$ 
```

**Comment by tagoh** [comment]
Sure. does `ibus write-cache --system` and then `ibus restart` help?

There should be some updates in /var/cache/ibus/bus/registry with the above command. but maybe good to try first `strings /var/cache/ibus/bus/registry | grep mozc` and see if it has something for mozc before trying the above. if not, it is worth trying.

**Comment by encrypted-sushi** [comment]
Thank you very much for your help!
`sudo ibus write-cache --system` and `ibus restart` seemed to have done the job.
```
$ ibus list-engine | grep -A3 "language: Japanese"
language: Japanese
  kkc - Kana Kanji
  mozc-jp - Mozc
  xkb:jp::jpn - Japanese
$ 
```

It seems a little strange since the ibus-mozc rpm package seem to be configured to run this exact command.  
```
$ rpm -q --scripts ibus-mozc
postinstall scriptlet (using /bin/sh):
[ -x /usr/bin/ibus ] && /usr/bin/ibus write-cache --system >& /dev/null || :
postuninstall scriptlet (using /bin/sh):
[ -x /usr/bin/ibus ] && /usr/bin/ibus write-cache --system >& /dev/null || :
$ 
```

I do have one question...  according to the ibus man page, the `ibus write-cache`:

> By default, it reads the component XML files from the standard component directory (/usr/share/ibus/component)

Assuming that `ibus write-cache` command is ran immediately after the RPM package files are extracted, is the `/usr/share/ibus/component/mozc.xml` file, installed by the ibus-mozc rpm, available prior to rebooting in Fedora Silverblue; i.e., when the `/usr/bin/ibus write-cache --system` command is issued, is it able to read this file in the absolute path  `/usr/share/ibus/component/mozc.xml`?

Being somewhat of a newbie, I wouldn't know what else I can do to help identify potential packaging issues.  Is there anything you'd like me to do in my environment to further investigate?

**Comment by fujiwarat** [comment]
ibus-daemon creates the user cache under $HOME/.cache/ibus whenever engines are installed in /usr/share/ibus/component and you restart ibus-daemon but unfortunately /usr/share/ibus/component/*.xml have old timestamps than the timestamp of the user cache in Silverblue and ibus-daemon doesn't update the cache.
And you have to run `ibus write-cache --system` by manual in Silverblue.

**Comment by tagoh** [comment]
Well, this is actually ostree/Silverblue specific issue in ibus. ibus can't update the cache properly  in %post because packages in ostree aren't usually installed in current tree. as a result, the installed engine wasn't available at that time. IMHO this is the same issue can be happened with ld.so.cache, and they addressed this by running ldconfig as a systemd service. I think ibus may also needs to take a similar approach for this solution.

**Comment by encrypted-sushi** [comment]
> Well, this is actually ostree/Silverblue specific issue in ibus. ibus can't update the cache properly in %post because packages in ostree aren't usually installed in current tree. as a result, the installed engine wasn't available at that time. IMHO this is the same issue can be happened with ld.so.cache, and they addressed this by running ldconfig as a systemd service. I think ibus may also needs to take a similar approach for this solution.

Thank you for the explanation.  This was indeed what I was suspecting.  Happy to finally understand why this was happening.

Thanks again!

**Comment by juhp** [comment]
Should this be reopened?
How and where do we fix it?

**Comment by juhp** [comment]
This should work now in current Fedora SB.
