### ISSUE TITLE
Initial setup: allow setting up VPN and hostname for Enterprise Login

### ISSUE THREAD

**Issue by djasa** [fedora-silverblue/issue-tracker#93]
Version: installed from `Fedora-Silverblue-ostree-x86_64-33-1.2.iso`

Enterprise logins are usually only accessible via VPNs when on public networks. It would be nice to have a button to configure VPN either at network configuration stage or at Enterprise logins screen of `initial-setup`.

**Comment by tpopela** [comment]
Hi @djasa, as we are following the Fedora Workstation, can you please open an issue in https://pagure.io/fedora-workstation/issues? Once you open it, please add the link to the issue here.

**Comment by djasa** [comment]
Hi @tpopela, the issue is here. I added there also setting hostname, that is also necessary for joining domains correctly: https://pagure.io/fedora-workstation/issue/200

**Comment by HarryMichal** [comment]
Should this issue remain open since it is not exactly connected to Silverblue but rather Workstation?

**Comment by travier** [comment]
We're tracking enterprise login issues in https://github.com/fedora-silverblue/issue-tracker/issues/320
