### ISSUE TITLE
rpm database uses bdb not sqlite

### ISSUE THREAD

**Issue by jmou** [fedora-silverblue/issue-tracker#95]
On F33 running rpm gives a warning that is otherwise innocuous.

```
$ rpm -q rpm
warning: Found bdb Packages database while attempting sqlite backend: using bdb backend.
rpm-4.16.0-1.fc33.x86_64
```

I assume this is related to https://fedoraproject.org/wiki/Changes/Sqlite_Rpmdb , but for some reason my rpm database is still using bdb. Not sure if it matters but I upgraded from F32.

Of course the manual workaround does not work on Silverblue:
```
# rpmdb --rebuilddb
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Read-only file system)
```

**Comment by LorbusChris** [comment]
Related:
https://github.com/coreos/fedora-coreos-tracker/issues/623
https://github.com/coreos/rpm-ostree/issues/1964
https://github.com/coreos/rpm-ostree/pull/2221/

**Comment by travier** [comment]
As I wrote for Fedora CoreOS, I think the plan is to switch the rpmdb backend during the F33 cycle, just not on the first release.

**Comment by tpopela** [comment]
Let me close this in favor of https://github.com/coreos/fedora-coreos-tracker/issues/623
