### ISSUE TITLE
grub-mkconfig fails and aborts installation of Fedora 33

### ISSUE THREAD

**Issue by hferreiro** [fedora-silverblue/issue-tracker#96]
I tried to install Fedora 33 Silverblue. The installer failed when running `ostree admin --sysroot=/mnt/sysimage deploy --os=fedora fedora:fedora/33/x86_64/silverblue`

Checking the logs, the specific error is:
```
OT: Using grub2-mkconfig chroot: /mnt/sysimage/ostree/deploy/fedora/deploy/7e1aaaca7dae8d066c139ca2627e470c285e625c30c924774b8d98698fa6b8b7.0
OT: Free lock: state=unlocked, depth=0
OT: Closing repo lock file
OT: Free lock table
error: Bootloader write config: grub2-mkconfig: Child process exited with code 1
```

I'm attaching the contents of /tmp as suggested by anaconda.
[tmp.zip](https://github.com/fedora-silverblue/issue-tracker/files/5505404/tmp.zip)

**Comment by travier** [comment]
I don't know if this is related but it looks like you had a mount point set up for `/home` which is unsupported on Silverblue: https://docs.fedoraproject.org/en-US/fedora-silverblue/installation/#manual-partition

**Comment by hferreiro** [comment]
I used automatic partitioning.

**Comment by hferreiro** [comment]
running ostree deploy manually with `OSTREE_DEBUG_GRUB2` env var gives me this additional error message:
```
/usr/sbin/grub2-probe: error: cannot find a device for / (is /dev mounted?).
```

**Comment by hferreiro** [comment]
Duplicate of https://bugzilla.redhat.com/show_bug.cgi?id=1483818.
