### ISSUE TITLE
Other desktop environments spins

### ISSUE THREAD

**Issue by kuba3351** [fedora-silverblue/issue-tracker#97]
I have an idea to make another desktop environments spins like Plasma, Xfce, i3wm etc. as branches in ostree.

I think it will be good for Silverblue because if user wants to switch from GNOME to another desktop environment, he can rebase into it and get rid of all GNOME stuff after reboot. All apps will be preserved because it is installed in flatpaks, toolboxes and via package layering, so after reboot, user can just start working with the new desktop. User can do as many switches as he wants and can keep  some desktop environments as pinned deployments. I think it will be good to offer these spins also in Silverblue download page.

For now, there is a Kinoite project that does similar thing but it is not official, and I don't know if it gets security updates as fast as official version, and it is a big issue while I am using Silverblue in my work.

I created a thread in the Silverblue forum with this idea, but Kinoite maintainer said that this is the goal for him, but he needs help. What about this idea?

**Comment by tpopela** [comment]
Hi @kuba3351 ! Thank you for contacting us. Currently we are not interested in this mainly due to capacity and priority reasons. I would suggest you to cooperate with the Kinoite maintainer.

**Comment by stbischof** [comment]
here is a very good base for swaywm https://github.com/martinpitt/ostree-pitti-workstation

**Comment by travier** [comment]
Kinoite is now official. Feel free to reach out on the discussion board if you're interested in maintaining other desktop environments. I'll close this one as this tracker is for Silverblue.
