### ISSUE TITLE
Issue: Nautilus (Gnome Files 3.38.1) - pdf thumbnails not visible

### ISSUE THREAD

**Issue by lalincedeldeserto** [fedora-silverblue/issue-tracker#98]
Using Nautilus I discovered that pdf thumbanils are not visible on Fedora Silverblue. This happens both on Xorg and Wayland sessions.
![immagine](https://user-images.githubusercontent.com/33136381/98649022-561f5700-2337-11eb-8a6d-e34c908f126f.png)
Here's a file reporting my Nautilus settings:
[nautilus-state.txt](https://github.com/fedora-silverblue/issue-tracker/files/5515908/nautilus-state.txt)

**Comment by kalev** [comment]
I guess this is fallout from not shipping evince rpm that includes evince thumbnailer. I don't know if thumbnailers are supposed to work through flatpak (we preinstall evince flatpak on silverblue so it should be there but sounds like it's not working).

**Comment by felipeborges** [comment]
We could split the Evince thumbnailers into its own package. It seems to be what Debian does.

**Comment by kalev** [comment]
That sounds like a good plan to get things working for now.

**Comment by hadess** [comment]
That's probably the best plan.

See also:
https://gitlab.gnome.org/GNOME/nautilus/-/issues/399

**Comment by felipeborges** [comment]
For now we went with splitting evince-thumbnailer into its own package https://src.fedoraproject.org/rpms/evince/c/bca6820f136b06c48c7fed99023f6f1dec902b1c?branch=master

**Comment by tpopela** [comment]
Made https://pagure.io/workstation-ostree-config/c/80951707331b9a14649fe2f6005a1ce32e787d74?branch=master and https://pagure.io/workstation-ostree-config/c/80951707331b9a14649fe2f6005a1ce32e787d74?branch=f33 for rawhide and F33. Should be part of today's compose.

**Comment by lalincedeldeserto** [comment]
It's working! Thanks!! :smiley:
